### ISSUE TITLE
Add a 'Get the Images' option to the Explorer page

### ISSUE THREAD

**Issue by s-paquette** [ImagingDataCommons/IDC-WebApp#1003]
@fedorov Need some details on how this should work - did we want this to be a button that opens a dialog, and that dialog has a link to the documentation? or something else?

**Comment by s-paquette** [comment]
Per ImagingDataCommons/IDC-ProjectManagement#1251:

- Button, 'Download Images' next to 'Get BQ String'
- Opens a dialog with two options: a) to your desktop b) to a VM

**Comment by fedorov** [comment]
Replicating the plan from #1251:

For v10, let's do this:

* add gcs_url column to the query that returns "View BQ String"
* add a button "Download" side by side with "View BQ String"
* in the popup, point to the document accompanied by text "Instructions on how to download the files corresponding to the selection in the portal to either Google Colab VM, compute engine VM, or your computer are here: https://learn.canceridc.dev/data/downloading-data"

**Comment by Gibbsdavidl** [comment]
Suggested text in the popup box.

Downloading Images

To download images you will first need to create a file manifest. This can be done interactively using the portal or directly through IDC BigQuery tables.

The manifest contains a list of files, each with a Google Storage URL (i.e. gs://... ). With the manifest, you can download files to your computer or to a cloud VM using either gsutil or s5cmd.

Detailed instructions can be found here: https://learn.canceridc.dev/data/downloading-data

**Comment by fedorov** [comment]
I'd say that the text we currently have in the test tier is ok. We should have all the details in the docs at the URL, this way we can also update the instructions without having to touch the webapp.

**Comment by pgundluru** [comment]
To test this : 

Go to https://testing-portal.canceridc.dev/explore/ 
Test as user logged in - able to view the download images and clicking on the button takes you to the text 
![image](https://user-images.githubusercontent.com/85526819/180243283-75009635-e61a-4661-a3dd-4359b9577bca.png)

**Comment by pgundluru** [comment]
Test passed 
![image](https://user-images.githubusercontent.com/85526819/180243558-11d4b226-ce23-444d-8851-9336412a58b2.png)
