### ISSUE TITLE
OHIF Viewer should not be triggered for HTAN studies

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#1008]
Currently, we only have PR for HTAN collections, and currently it opens OHIF viewer. PR should not be opened from the series list, similar to SR and other modalities we discussed earlier.

I think this can wait post-v10.

**Comment by s-paquette** [comment]
@G-White-ISB Pretty much need to do the same thing we do with SR; if the modality is PR, no eyeball option.

**Comment by fedorov** [comment]
I realized this issue is more sever than I thought.

OHIF Viewer opens not just when PR series is selected, but when study view is toggled from the "Selected Studies" table. I think this should be fixed for this release. This is very very confusing.

**Comment by s-paquette** [comment]
We can do that, I think. @G-White-ISB As soon as you have this ready let me know and we can get it onto dev and test.

**Comment by G-White-ISB** [comment]
@fedorov, just to confirm:
1. SM modality series are viewable by the Slim Viewer
2. PR, RTSTRUCT, RTPLAN,RWV modality series (any others) are not viewable
3.  Series with other modalities are viewable by the OHIF viewer
4. All studies will have series with SM modality OR series with modalities viewable by the OHIF. No study has some series with SM modality and some with CT,MR, PET etc. modalities. So there is one view to associate with the study without ambiguity.

**Comment by fedorov** [comment]
> SM modality series are viewable by the Slim Viewer

Yes

> PR, RTSTRUCT, RTPLAN,RWV modality series (any others) are not viewable

PR depends on the context. PR on its own is not viewable by any viewer. PR with SM is only viewable in Slim. PR with non-SM would only make sense in OHIF.

> Series with other modalities are viewable by the OHIF viewer

Here's a take on the simplified logic: 1) SM is only in Slim; 2) SR, SEG, PR, PR, RTSTRUCT, RTPLAN, RWV not viewable on their own (this list may not be complete, we can review it later, no urgency); 3) everything else should be openable in OHIF as a single series.

> No study has some series with SM modality and some with CT,MR, PET etc. modalities. 

yes

**Comment by s-paquette** [comment]
Confirming @G-White-ISB that for now, we only have studies with either SM/SM+PR (SliM viewer) or an OHIF-compatible modality.

**Comment by fedorov** [comment]
FYI we missed a unique opportunity to highlight IDC portal capabilities to the HTAN community due to this bug.

**Comment by fedorov** [comment]
For the demo today, I will manually replace "viewer" with "slim/studies" in the URL to work around this. 

We will highlight the capabilities and importance of our testing procedures that identified this bug in the test tier :-D

**Comment by s-paquette** [comment]
Ugh, GitHub is now closing tickets if you link them to a PR, so best not to link them anymore.
