### ISSUE TITLE
Tooltip for Analysis Results 'None'

### ISSUE THREAD

**Issue by s-paquette** [ImagingDataCommons/IDC-WebApp#1014]
Since 'None' under the Analysis Results attribute values is a specific case--'only show studies which have series NOT in an analysis result--we should give it a tooltip to this effect.

**Comment by s-paquette** [comment]
@pgundluru  If you have an explorer window open on test already, you may want to close it and re-open before you test this.

**Comment by pgundluru** [comment]
This is tested by going to the explorer page and hovering over the NONE in analysis results 

![image](https://user-images.githubusercontent.com/85526819/180483696-3eef5d87-0322-4ff5-a548-29fdb46c7121.png)
