### ISSUE TITLE
Some collections are not assigned the program

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#1015]
![image](https://user-images.githubusercontent.com/313942/180477008-dc008cd1-8748-4df5-9d05-a55127e88edc.png)

This appears to be the case both for the production tier and v10.

Collections in question are assigned program in the [program tracking spreadsheet](https://docs.google.com/spreadsheets/d/1-sk8CMTDDj-deKv7sXglLvHUhDSNS1cRqUg5Oy5UpRY/edit#gid=0).

**Comment by s-paquette** [comment]
Looks like we have some new programs I didn't know about--for future reference, there's no easy way for me to tell these are coming in. We should come up with a way for me to see that; checking the spreadsheet doesn't help since 'new' Programs aren't called out.

**Comment by s-paquette** [comment]
Ah, right, I remember now.  We decided some time ago if a collection is the only member of a Program, the program is not displayed with a fold out, just the single collection. @fedorov We can change this behavior if we want, but it was requested early on.

**Comment by fedorov** [comment]
Ok, that's fine. About synchronizing of program names with the spreadsheet, that's something that should be done as part of ETL probably. I leave it to @bcli4d.

**Comment by bcli4d** [comment]
The idc_vX_dev.program table indexes by tcia_wiki_collection_id. So, yes, there is at least a casing issue here. Will change to or add an idc_webapp_collection_id column in V11.
