### ISSUE TITLE
Improve wording for URL/query buttons

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#1016]
![image](https://user-images.githubusercontent.com/313942/180486951-2e059a7f-c7b0-441c-8219-8b96cc617d8e.png)

**Comment by s-paquette** [comment]
I'd prefer to keep 'display' in the button due to the functionality. So 'Display Filter URL' should work.

I can go with View BigQuery String but it does make the button very long and unwieldy looking (for a button). If no one minds that, though, we can do it.

**Comment by fedorov** [comment]
> I'd prefer to keep 'display' in the button due to the functionality. So 'Display Filter URL' should work.

This is fine.

> I can go with View BigQuery String but it does make the button very long and unwieldy looking (for a button). If no one minds that, though, we can do it.

How about "View SQL query"? And then in the tooltip for that button explain that "Put this query to the BigQuery Console <url> to select files corresponding to the current cohort selection".

**Comment by s-paquette** [comment]
@fedorov That works--though, rather than have that as a tooltip, since this opens a dialog we can put that in the dialog itself.

**Comment by fedorov** [comment]
You are right, agreed!

**Comment by pgundluru** [comment]
![image](https://user-images.githubusercontent.com/85526819/180668657-2e347ec7-622d-4d14-ae3e-c77d45b7d755.png)
