### ISSUE TITLE
Test tier error loading HTAN OHIF image 

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#1020]
Seen in W10 Firefox browser and Safari Browser 

https://testing-viewer.canceridc.dev/viewer/2.25.93749216439228361118017742627453453196?SeriesInstanceUID=1.2.826.0.1.3680043.10.511.3.91342853824883143715411628225851002 

![image](https://user-images.githubusercontent.com/85526819/180816998-622bafc2-0e63-4fe3-8328-3a963aba146a.png)

**Comment by pgundluru** [comment]
https://testing-viewer.canceridc.dev/viewer/2.25.38649134330414220812979591492650088495

![image](https://user-images.githubusercontent.com/85526819/180826421-55e69d25-4fed-4294-8a96-b263132a0560.png)

**Comment by fedorov** [comment]
Both of those are SM studies that are not expected to load in OHIF. If you are clicking on the PR series, it is a known issue that OHIF viewer should not be invoked: https://github.com/ImagingDataCommons/IDC-WebApp/issues/1008.

**Comment by pgundluru** [comment]
Closing as this is a duplicate.
