### ISSUE TITLE
Manifest export menu column names should match BQ table column names

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#1023]
![image](https://user-images.githubusercontent.com/313942/181057791-7c5b3edb-ed81-4c52-a642-afb53cfcfec0.png)

Instead of the above:

* gcs_url (Google Cloud Storage URL)
* source_DOI (Source DOI)
* ...

**Comment by pgundluru** [comment]
To test this issue on test tier, I created a cohort wit one filter eg body part bile duct and exported the cohort to csv file and the column names are as below in image 1. If I select the same cohort and export to BQ and the column names are in image 2 

![image](https://user-images.githubusercontent.com/85526819/196989588-bf7edf74-7c08-4a35-9a6d-052ae96ec1d0.png)

![image](https://user-images.githubusercontent.com/85526819/196990119-c61d6f48-8142-45aa-bcd0-45a6bc7f432d.png)

**Comment by s-paquette** [comment]
@pgundluru  This one isn't ready for testing and hasn't been done--no need to check it just now.

**Comment by pgundluru** [comment]
@s-paquette My apologies, You are correct, I have deleted my comment.

**Comment by pgundluru** [comment]
This has been tested in test tier using a new cohort and i am able to see the new names except for a missing " ) " like the image below 

![image](https://user-images.githubusercontent.com/85526819/203366567-c2df19a2-4acc-44ef-a09e-b83093e80337.png)

**Comment by s-paquette** [comment]
@pgundluru Fix for this is now up.
