### ISSUE TITLE
zoom in 110% on laptop will cause sign-in button to dissapear

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#103]
If an end-user has their browser set to 100% on a laptop the sign-in button will no longer be visible on the page.

![Screen Shot 2020-05-28 at 12 20 31 PM](https://user-images.githubusercontent.com/16824894/83167095-cca7ff80-a0dd-11ea-9ba4-df2c05ee4089.png)

**Comment by s-paquette** [comment]
@madelyngreyes Found the problem--deploying to dev now, check in ~30m if you have a second.

**Comment by madelyngreyes** [comment]
The zoom issue is resolved on the dev tier for the sign-in link. 

Image below was taken at 200% zoom on a laptop. 
![Screen Shot 2020-07-07 at 2 07 27 PM](https://user-images.githubusercontent.com/16824894/86823825-5347e900-c05b-11ea-83e8-146a11cdd66a.png)
