### ISSUE TITLE
In prod tier, Viewers open up with errors in dev console in Firefox Browser 

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#1030]
This is noted after v10 release in production tier and will be reported to OHIF viewer team 

1. https://viewer.imaging.datacommons.cancer.gov/viewer/1.3.6.1.4.1.14519.5.2.1.5168.1900.259520120774497994844579066293 is slower to load than previously and has this error in the dev console
![image](https://user-images.githubusercontent.com/85526819/182710818-79e3fe1c-7d9b-49c4-a726-2830205b3cbb.png)

2.https://viewer.imaging.datacommons.cancer.gov/viewer/1.3.6.1.4.1.14519.5.2.1.234334146518395432696557278026155271217
![image](https://user-images.githubusercontent.com/85526819/182711036-d71df8a5-5774-46ae-9796-950605f282fb.png)

**Comment by s-paquette** [comment]
@pgundluru Can you include FF version and OS? I'm not seeing this on Firefox 103 for Windows 10.

**Comment by pgundluru** [comment]
@s-paquette My machine is same - FF browser - 103.0 (64-bit) for W10.

**Comment by pgundluru** [comment]
prod ohif viewer version - 4.12.30

**Comment by Gibbsdavidl** [comment]
I get this same error. Win10 FireFox (v103.0.1)

**Comment by s-paquette** [comment]
@wlongabaugh Can this be closed?
