### ISSUE TITLE
Cohorts that contain content (metadata or files) no longer available should be flagged in the cohorts list

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#1033]
The situations that might lead to this is retraction of PHI data, limiting access due to potential face reconstruction.

**Comment by s-paquette** [comment]
Items involved:
* add an attribute to cohorts which is 'contains_limited' or similar
* write a script to fill this out for all extent cohorts - this would need to make a simple faceted count call for just 'access' and check for limited > 0
* adjust _save_cohort to set this attribute based on filters at creation time (as above)
* Add a * or similar icon to any cohort with contains_limited=True, on hover it explains

**Comment by s-paquette** [comment]
Since we're now completely removing Limited access data I'd suggest we close this ticket in favor of addressing the re-addition of Limited access data when we re-add it to the site. @fedorov Do you agree?
