### ISSUE TITLE
Add ability to disable attributes and relevant fallout

### ISSUE THREAD

**Issue by s-paquette** [ImagingDataCommons/IDC-WebApp#1034]
If an attribute is disabled (due to absence in the current data version) then the following must be addressed:

* When a prior-version cohort is brought forward, if it contains filters with those attributes, they need to be detected and flagged to the user/reported
* When a user is viewing a cohort with disabled attributes those should be hilighted in the cohort display
* When a user views the cohort SQL query there should be a comment indicating those attributes are not present in later data versions, so swapping the dataset and table may not work

**Comment by s-paquette** [comment]
ETL scripts updated. Main change was to add an exclusion config parameter to prevent attributes from moving forward into a new version.

**Comment by pgundluru** [comment]
Testing this with previously created cohorts (containing disabled attributes)

1. In the UI, if a cohort from a prior version contains one or more attributes which have been removed, the user will be warned when doing version comparison and on their list of cohorts. I have limited collections cohort which includes attributes that have been removed head n neck) and when I try to do a version control i see the following warning message 
![image](https://user-images.githubusercontent.com/85526819/197030906-fa6d0c2b-53c5-4748-960a-c7ee07e93e68.png)

2.

**Comment by pgundluru** [comment]
2. When a user is viewing a cohort with disabled attributes those should be highlighted in the cohort display
![image](https://user-images.githubusercontent.com/85526819/197059299-8b385591-30d0-41f6-8790-e4c99a6ebfe3.png)

**Comment by pgundluru** [comment]
"When a user views the cohort SQL query there should be a comment indicating those attributes are not present in later data versions, so swapping the dataset and table may not work" @s-paquette What is the best way to test this scenario?

**Comment by s-paquette** [comment]
I think this one got missed. I'll add it on once I'm back--to test it, you would click on the query display icon and see the warning and an alert icon it at the top of the dialog. (Right now you won't see anything.)

**Comment by pgundluru** [comment]
@s-paquette Thank You!

**Comment by s-paquette** [comment]
@pgundluru Ready for testing.

**Comment by pgundluru** [comment]
![image](https://user-images.githubusercontent.com/85526819/199083087-8f07369b-3a2e-4f8f-b2ff-5a038f83b69e.png)
