### ISSUE TITLE
In Test tier Safari, Exporting cohort manifest to BQ issue 

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#1040]
Please note this is isolated to Safari browser, 

Chrome and FF on Windows with same size cohorts load fine. 

![image](https://user-images.githubusercontent.com/85526819/186974038-eacdb177-f032-467a-afc8-cba4ae76a39e.png)

**Comment by fedorov** [comment]
It works for me - I have Version 15.6 (17613.3.9.1.5)

**Comment by pgundluru** [comment]
As verified by Andrey, This issue is isolated to Safari - 14.x. I think we can disregard this issue and close this ticket.

**Comment by s-paquette** [comment]
One final thing to check. @pgundluru did you make sure you weren't trying to export a query with a BMI filter? There's a known problem with those and they'll always fail.

**Comment by pgundluru** [comment]
Thank You Suzanne, I have tried it with no BMI filters and same issue with only my version.
