### ISSUE TITLE
Analysis type collections do not contain the description and links to match the original collections in Prod Tier UI 

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#1043]
![image](https://user-images.githubusercontent.com/85526819/187489141-11fcaeb1-db60-4911-8186-0797695ade79.png)

**Comment by s-paquette** [comment]
These will now display if present in the fold of the Collections table, along with the list of the collections from which the analysis takes its series.

**Comment by pgundluru** [comment]
Able to view the description and links are clickable as expected.

**Comment by pgundluru** [comment]
Closed as completed and tested
