### ISSUE TITLE
Rename "Discourse" to "User forum" on the front page

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#1045]
@ulrikew made that suggestion, and I agree with it.

**Comment by s-paquette** [comment]
@fedorov Since this will widen the menu options, can I make dropping the icons part of this change? That way we don't need to increase the mandatory menu fold even further.

**Comment by fedorov** [comment]
Maybe we should just use "Forum" instead of "User forum" in place of "Discourse"?

@ulrikew what do you think?

**Comment by ulrikew** [comment]
@fedorov @s-paquette I prefer User forum but I am fine with anything that indicates that the users might find answers and discussions there.

**Comment by fedorov** [comment]
Ok, let's keep the icons ditched, and use "User forum".

**Comment by s-paquette** [comment]
Got it--now, another question to consider: do we want to keep Title Casing for our menu bar font, or did we want to swap to Small Caps or all-caps?

Small caps:
![image](https://user-images.githubusercontent.com/8442808/195737130-9c13eff3-4bf6-44be-9c6c-61c1b691cc07.png)

All Caps:
![image](https://user-images.githubusercontent.com/8442808/195737307-dc8f8ec0-b5d0-4e17-a6dc-48b14bf3f19a.png)

Main difference is the Small Caps has the rest of the non-title letters in uppercase, just smaller. This gives the readability of sentence casing but the bolder look of upper case (in theory).

**Comment by ulrikew** [comment]
@s-paquette How would it look if we just "un-bold" the current labels? Upper case / lower case is easier to read than all CAPS.

**Comment by ulrikew** [comment]
@fedorov @s-paquette Can we rename Docs to Help? Docs to me means Documents and not Documentation. If we rename it to Help we could add the link to the help email to the documentation home page and give users a way to contact the team. They wouldn't have to find the link in the footer of the page.

**Comment by fedorov** [comment]
Sure, that's fine by me.

**Comment by pgundluru** [comment]
![image](https://user-images.githubusercontent.com/85526819/196288890-a4e80e0a-1a47-4014-90a4-0e2a0d42da8e.png)

**Comment by pgundluru** [comment]
![image](https://user-images.githubusercontent.com/85526819/196288998-75b3b894-11e3-4e75-b849-a318630a440c.png)

**Comment by pgundluru** [comment]
Closed as completed
