### ISSUE TITLE
Test and Prod tiers show search scope temp instead of search scope 

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#1046]
Identified by Bill L while discussing UX designs 

![image](https://user-images.githubusercontent.com/85526819/188693189-5d2db556-0e2c-4b08-9ade-a3f95c37b0a8.png)

**Comment by s-paquette** [comment]
@pgundluru Ready for testing

**Comment by pgundluru** [comment]
![image](https://user-images.githubusercontent.com/85526819/188967181-2e5334cc-9e60-46c5-94e9-04110107afbf.png)

**Comment by pgundluru** [comment]
This is tested in v12 test tier
