### ISSUE TITLE
Remove Limited Access data from the Web Portal

### ISSUE THREAD

**Issue by s-paquette** [ImagingDataCommons/IDC-WebApp#1051]
We need to do the following:

* Remove 'Access' from the Search Scope
* Disable the access attribute in the WebUI - this involves removing autochecking and autoapplication of 'Public'

Once ETL is done:

* Disable any attributes which only had values in Limited collections (related to #1034)

**Comment by s-paquette** [comment]
@G-White-ISB I did some cursory parts of this--I dropped 'Access' from the Search Scope section of the template, and removed the auto-application of the filter from the back-end, but image_search.js may have other things it does which you might want to look into.

**Comment by s-paquette** [comment]
ETL finished, removed Access attribute from availability in the portal but it still exists on the backend for use in determining Collections for display. Notably the involved the removal of QIN-HEADNECK, which was a source of many attributes in the Derived Quantitative data. @pgundluru This is a good testing case, along with the APOLLO collections, which were also removed.

**Comment by pgundluru** [comment]
In test tier, 

1.  Access is no longer visible in the search scope area. 2.  Autochecking and autoapplication of 'Public' is removed.
