### ISSUE TITLE
Reset/Clear buttons for exploration page to be on the left corner next to filter definition 

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#1052]
Suggested by Andrey- Currently reset button is in the opposite corner from where the filter definition is located in IDC but it would be more intuitive to copy how GDC and PDC have their clear button close to the definition. 

![image](https://user-images.githubusercontent.com/85526819/189385167-d1695e05-fc3c-4e56-80af-2dcc64ce667e.png)

![image](https://user-images.githubusercontent.com/85526819/189385212-d62f217b-d90c-40e7-94ed-16d0c6d4dffd.png)

**Comment by s-paquette** [comment]
Moved Reset to the left and added an icon, same for Return to Data Explorer (in place of Reset when a cohort is being viewed).

**Comment by pgundluru** [comment]
Testing this feature in FF and Safari 

Observation 1 - 

When I am in the explore images page and select search scope (Eg HTAN), Then IF I select reset the reset button there is no change in the filter definition (The checkbox for HTAN is removed though) This is the same behavior for all of the search scope collections

Observation 2 - 

When I am in the explore images page and select Analysis results (eg RIDER), Then IF I select reset the reset button then filter definition is reset and checkbox for analysis results is removed BUT the filter definition still shows like below

ANALYSIS RESULTS IN ( )  (The display filter URL still has all analysis results so its not actually being completely reset)

This is the same behavior for all of the search scope collections

Observation 3 - 


When I am in the explore images page and select any of the filters in search configuration (eg Modality is CT), Then IF I select reset the reset button then filter definition is reset and checkbox for analysis results is removed BUT the filter definition still shows like below

MODALITY IN ( )  (The display filter URL still has all analysis results and i am able to still see the modality cases number in the filter def so its not actually being completely reset)

This is the same behavior for all of the search configuration filters including original derived and related

**Comment by s-paquette** [comment]
@pgundluru Ready for testing again.

**Comment by pgundluru** [comment]
1 - Testing Passed 

When I am in the explore images page and select search scope (Eg HTAN), Then IF I select reset the filter def is cleared including URL 

 2 - Testing passed

When I am in the explore images page and select Analysis results (eg RIDER), Then IF I select reset the filter def is cleared as well as URL and checkboxes 

 3 - Testing Passed

When I am in the explore images page and select any of the filters in search configuration (eg Modality is CT), Then IF I select reset I am able to reset URL, Definition and checkboxes

**Comment by pgundluru** [comment]
Closed as completed
