### ISSUE TITLE
Update the ABOUT page

### ISSUE THREAD

**Issue by ulrikew** [ImagingDataCommons/IDC-WebApp#1066]
The information about IDC on the ABOUT page is slightly outdated. Keyvan and Andrey worked on the attached document with the intent for it to be used on the CRDC page. I propose to use the Overview and possibly the Data Types sections to replace the "About IDC" section.

[IDC Overview_CRDC.docx](https://github.com/ImagingDataCommons/IDC-WebApp/files/9789354/IDC.Overview_CRDC.docx)

**Comment by fedorov** [comment]
We should also update the email to be `support+submissions@canceridc.dev` in place of `support@canceridc.dev` for submissions in this sentence: "If you are interested in making your data available within IDC, please contact us by sending email to support@canceridc.dev."

**Comment by fedorov** [comment]
And we should also update the wording, based on the feedback from Keyvan today.

Let's add this sentence as the first sentence under the "Data submission to IDC" heading:

“Currently IDC takes from NCI-funded driving projects and data from special selected projects.”
