### ISSUE TITLE
In test tier, selecting filters which result in no cases causes never ending spinner 

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#1068]
When you select a filter and reset and select another filter there seems to be a loading issue with no error in console 

Seen in FF w10 

Steps to reproduce:

In test tier, Select body part Abdomen and select reset (The filter URL will still have abd in the URL)
Next try to select another filter eg bile duct 
Then you are stuck on the below page (please note the highlighted parts)

![image](https://user-images.githubusercontent.com/85526819/196986761-601a2c81-70b5-42cd-ab20-7fd4b611c6b0.png)

**Comment by pgundluru** [comment]
Just noticed this same spinner issue while selecting filters where there are no cases for that set of filters 

To reproduce:

G to explore images and select primary site - Marrow/blood. analysis results - none and sample per pixel - 3 and slice thickness to see the never ending spinner 

![image](https://user-images.githubusercontent.com/85526819/197270380-0498131c-8761-456d-88bf-01f5e386dc1d.png)

**Comment by pgundluru** [comment]
Example 3 to see the spinner issue 

Select modality - RT struct and Fusion 

![image](https://user-images.githubusercontent.com/85526819/197274240-c0c48bf4-3a7a-4dc8-94ac-96f86b2e41ad.png)

**Comment by s-paquette** [comment]
@pgundluru This was related to the reset bug which has just been fixed--please give this a shot again and see if it's still happening.

**Comment by pgundluru** [comment]
Spinner is no longer an issue on test tier
