### ISSUE TITLE
In test and prod tier, There is a warning message for BMI when a cohorts with BMI filters is saved. 

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#1069]
Note - I was unable to determine if this issue is actually a bug (We discussed this in our weekly meeting and i was suggested to open a ticket). Please feel free to delete the ticket if its not a bug.

Summary - On the IDC webapp, When I select TCGA collection and BMI filter to create a cohort, I see the message that says Invalid operator seen for attribute 'bmi'; default of OR used instead. (Like in the image below) But I am unable to find where the OR is being used. It still shows AND in the filter definition and also in the filter URL, 

![image](https://user-images.githubusercontent.com/85526819/197254272-1059c2e1-6cda-4cae-9010-42337d216fb1.png)

To reproduce this issue in test, 
 Select TCGA collections and related filter BMI (eg overweight)
Save the cohort to see the warning on top of the page.

**Comment by G-White-ISB** [comment]
This is related to BMI being both a numeric and categorical attribute. Within the context of the front end it functions as a categorical attribute. From my testing the cohort is being filtered and saved correctly - the only issue is this warning. For now I'm hard coding suppression of this warning for the bmi attribute

**Comment by pgundluru** [comment]
This has been tested successfully

Please note we noticed BQ export fail issue which is already documented here https://github.com/ImagingDataCommons/IDC-WebApp/issues/1022
