### ISSUE TITLE
In test tier, In derived filters, the checkall/uncheckall is not functional 

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#1070]
Observed in FF W10 

Summary : Many derived filters have a unselectable checkall/uncheckall feature on test tier currently 

Lobular pattern
Malignancy
Margin
sphericity
spiculation
sub score
texture

To reproduce:
In explore images select all collections, Browse to derived filters - lobular pattern 
The check all / uncheck all is not clickable 

![image](https://user-images.githubusercontent.com/85526819/197278351-75b09176-8fac-44cb-969d-6e60c273b0ba.png)

**Comment by G-White-ISB** [comment]
@pgundluru what do you mean by 'select all collections'? Did you hit 'Check All' at the collections level? I am not able to reproduce.

**Comment by s-paquette** [comment]
@G-White-ISB You can ignore the part about selecting collections; it's that derived filter select-all/unselect-all aren't working.

**Comment by s-paquette** [comment]
@pgundluru Can you check this one in the portal?

**Comment by pgundluru** [comment]
I am able to reproduce the issue wit unselect able checkall/uncheckall functions on test tier as follows: 

In test tier I select explore images 
Then I select collections - CMB,TCGA AND COMMUNITY 
Then I browse to the derived filters and in Segmentation
Anatomic region  - I am able to select individual items but the checkall/uncheckall is unclickable 
Segmentation category - I am able to select individual items and checkall/uncheckall so no issues here 
Segmentation type - I am able to select individual items but the checkall/uncheckall is unclickable 

![image](https://user-images.githubusercontent.com/85526819/206771396-00c433a5-61d5-420a-a829-2decc2f69353.png)

**Comment by pgundluru** [comment]
Note - all the functions in derived filters are working as expected in production tier.

**Comment by G-White-ISB** [comment]
If the 'show more' span is not displayed (for instance when there are 0 or more attributes to display) the height of the encapsulating paragraph, which contains the 'check-all', 'uncheck-all' span becomes 0. This makes those options unselectable. 

This can be reproduced in the production tier too.  Setting a min-height on the paragraph to fix this

**Comment by pgundluru** [comment]
This has been tested in test tier 

Anatomic region -  success 
Segmentation category - success 
Segmentation type - success
