### ISSUE TITLE
Filter URL too long error problem

### ISSUE THREAD

**Issue by wlongabaugh** [ImagingDataCommons/IDC-WebApp#1079]
Don't show the "filter URL is too long" at the top, but only when clicking the "Display filter URL" button. Also, after message is dismissed, need page load to bring it back.

**Comment by s-paquette** [comment]
The dismissible part of the warnings in IDC needs to be changed from 'delete from DOM' to 'hide' like in CGC.

**Comment by s-paquette** [comment]
Turns out we had this, just this specific error message had the wrong attribute (data-dismiss instead of data-hide).

**Comment by s-paquette** [comment]
@wlongabaugh 
> Don't show the "filter URL is too long" at the top, but only when clicking the "Display filter URL" button.
I don't quite understand what this means. The error only shows when the button is clicked--do you mean, move the error to display near the button?

**Comment by VenkatPrema** [comment]
@s-paquette When I clicked Display Filter URL, I don't see any error. I can scroll the bar left and right and can see the entire url.


![image](https://user-images.githubusercontent.com/106698935/219812722-28644d48-17cd-48bf-a7c4-6e24becdc94f.png)
