### ISSUE TITLE
Issues identified in v12

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#1091]
* "search" and "settings" buttons disappeared from "Primary site locations", "Body part examined", .... - I am pretty sure we had those in all places, and we still have them in sections starting from "Manufacturer". So now it is impossible to sort by count.
* "minus inside circle" in the "Collections" tab should be removed - it is irrelevant now that those collections have been removed
* values listed under "Derived > Segmentation" do not match the values we have in BQ (e.g., I do not see anywhere "Body structure (body structure)" in the return list from the query below):

```sql
SELECT
  DISTINCT(SegmentedPropertyType.CodeMeaning)
FROM
  `bigquery-public-data.idc_v12.segmentations`
```

I am guessing this is related to https://github.com/ImagingDataCommons/IDC-ProjectManagement/issues/735, but I do not understand why the portal UI would be showing what it is showing right now. It is very confusing.

**Comment by fedorov** [comment]
> Human readable code meanings (current)

Can you let us know what is the source of the mapping to those code meanings shown in the portal? I do not see this documented in the aforementioned issue. I believe what was discussed is to show the result of mapping into the SCT codes (see https://github.com/ImagingDataCommons/IDC-ProjectManagement/issues/735#issuecomment-1257075484). What is shown in the UI right now appears to be neither SRT nor SCT code meanings we have in the data.

**Comment by s-paquette** [comment]
@fedorov Yes, that is the table that was used, and the values seem to correspond, that I can tell--can you indicate a few that don't so I can compare them?

**Comment by fedorov** [comment]
I see, I think the issue is that in my understanding, that linked table would only be used to map SRT to SCT codes, but we would not pick up the meaning from that table, since it is not the same as in our content. I believe this is because the table contains a different "flavor" of meaning - fully qualified. Picking up meanings from that table is IMO misleading, since those meaning values are not present in our DICOM data!

**Comment by s-paquette** [comment]
@fedorov We can definitely use the meanings in the DICOM data, but the question is, will those meanings be consistent across values, and if they're not, how do we choose to resolve them for use in the portal?

(Worth noting that since the convert to SCT, this is the value saved in any cohorts and supplied for filtering in queries, which means it won't work against the segmentations or dicom_all table but will work against dicom_derived_all and the pivot.)

**Comment by s-paquette** [comment]
@fedorov We have now moved to using the meaning from the DICOM data, but the codes from a code determination. This is available in test.

**Comment by VenkatPrema** [comment]
@s-paquette Search and setting buttons are appearing next to Primary Site Location and Body Part Examined.
![image](https://user-images.githubusercontent.com/106698935/219818287-33aef140-8868-4556-b633-e80f405c42a0.png)
