### ISSUE TITLE
Filter icon should be expanded when the filter is expanded

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#1098]
It's a nitpick, but when Explore page is opened, first three filter categories are expanded, but the triangle icon next to the group name points to the right, not to the bottom.

![image](https://user-images.githubusercontent.com/313942/203167831-7cab233a-5579-41cb-a240-27bccee53861.png)

**Comment by G-White-ISB** [comment]
I got to this while working on other bugs. Please check the dev-portal.

**Comment by s-paquette** [comment]
Confirmed.
![image](https://user-images.githubusercontent.com/8442808/206542778-07fbb5b7-0aad-467e-94d1-b40218be66fd.png)
