### ISSUE TITLE
In prod, When a user selects explore images and clicks on SQL string then there is a loading error 

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#1104]
Summary - When a user selects view SQL string when not logged in in explore images then there is a loading message that doesn't do anything else 

![image](https://user-images.githubusercontent.com/85526819/205976977-6c57f25c-736b-4ca9-b3ed-d016ecc9afc2.png)

**Comment by s-paquette** [comment]
This button shouldn't enable until after you've selected a filter, so we'll have a look at why it's live.

**Comment by s-paquette** [comment]
The 'disabled' default on this button was removed for some reason. Put it back.

**Comment by VenkatPrema** [comment]
@s-paquette View SQL String is disabled before select any filter, once selected a filter View SQL string is  enabled.

![image](https://user-images.githubusercontent.com/106698935/219803559-f74167a4-275a-44bf-ba4c-e54d0cb28055.png)

![image](https://user-images.githubusercontent.com/106698935/219803452-3310cfdb-c998-41d2-b2de-9f61912ba1d6.png)
![image](https://user-images.githubusercontent.com/106698935/219804230-5b9277d2-280a-46a7-9e6e-57bbb7ff7f3a.png)

**Comment by VenkatPrema** [comment]
This issue is working fine in test tier and not tested in Prod tier.

**Comment by VenkatPrema** [comment]
@s-paquette It is working as expected in Prod too.
![image](https://user-images.githubusercontent.com/106698935/224175103-ae93bba4-f9c6-409f-b571-d1ae83567dfc.png)
