### ISSUE TITLE
Discuss feasibility of using curated BodyPartExamined values in the portal

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#1115]
See details in https://github.com/ImagingDataCommons/IDC-ProjectManagement/issues/1271

**Comment by s-paquette** [comment]
Main questions to consider:

- How do we manage currently existing cohorts which use the old values
- Is this to be done at the ETL level (i.e. in dicom_metadata) or via the curated data table (eg. as we did with SliceThickness)

**Comment by fedorov** [comment]
TODO: We should add the query to the etl repo, and include documentation of how this field was derived in the schema field description.

**Comment by fedorov** [comment]
> We should add the query to the etl repo, and include documentation of how this field was derived in the schema field description.

Done in https://github.com/ImagingDataCommons/etl_flow/pull/73

**Comment by fedorov** [comment]
@s-paquette I believe that's what we are doing already?

**Comment by s-paquette** [comment]
Yes this is now being done via the curation table.
