### ISSUE TITLE
Test Tier - Inconsistent case numbers from Home page to Filter definition page for multiple Primary Site Location

### ISSUE THREAD

**Issue by VenkatPrema** [ImagingDataCommons/IDC-WebApp#1117]
Test Links:https://testing-portal.canceridc.dev/
https://testing-portal.canceridc.dev/explore/filters/?tcia_tumorLocation=Bladder

**Steps to Reproduce:**

1. Open IDC test tier 
2. Hover the mouse on Bladder. Cases showing **412**
3. Click Bladder 
4. In the Filter definition page, **431** cases are showing

![image](https://user-images.githubusercontent.com/106698935/212370975-421df5f5-5697-445d-87d6-f0374cd917ae.png)
![image](https://user-images.githubusercontent.com/106698935/212371224-f0978b8d-ec5d-4592-809d-ebfe52dd0dee.png)

**For Brain** 
Home page - Brain Cases - **1945**
Filter Definition - Brain Cases - **1942**

![image](https://user-images.githubusercontent.com/106698935/212388113-22444086-c5a0-481d-9474-22f3874b457a.png)

![image](https://user-images.githubusercontent.com/106698935/212388036-35c9f758-a8e8-4a26-8d4e-f8bc47c903b7.png)

**For Colorectal**

Home Page - Cases **1650**
Filter Definition - Cases **1674** 
![image](https://user-images.githubusercontent.com/106698935/212388673-1a8f7773-2ae7-4dd7-a9a6-d008a79710bf.png)

![image](https://user-images.githubusercontent.com/106698935/212389284-f1abd386-0680-4631-b138-70fcb2e12956.png)

**For Lung:**
Home Page: Cases **4744**
Filter Definition: Cases **4750** 

![image](https://user-images.githubusercontent.com/106698935/212391296-66c73cf4-091d-49ff-aaef-c27690277685.png)

![image](https://user-images.githubusercontent.com/106698935/212391254-fd2e6a89-7538-4c48-be8f-6d606bf63a4f.png)

**Comment by s-paquette** [comment]
This has been reported a few times previously, and is due to the homepage numbers being calculated differently than the actual explorer page.
