### ISSUE TITLE
Test Tier - OHIF image is not loading for Abdomen/Pelvis  and getting 404 not found console error

### ISSUE THREAD

**Issue by VenkatPrema** [ImagingDataCommons/IDC-WebApp#1119]
Test Links: https://testing-portal.canceridc.dev/explore/ 
https://testing-viewer.canceridc.dev/viewer/1.3.6.1.4.1.14519.5.2.1.1600.1201.196671099928195977885582724163

**Steps to reproduce:** 

1. Select CMB-CRC from collections
2. select Abdomen/Pelvis from Selected Studies
3.  Abdomen/Pelvis image is not loading and getting 404 not found console error

Image from Chrome:

![image](https://user-images.githubusercontent.com/106698935/212938032-35ab0d60-9127-4b94-9341-d4e68f879479.png)

![image](https://user-images.githubusercontent.com/106698935/212938124-b76cb7e5-01cb-4753-91b9-197c90ca69da.png)

![image](https://user-images.githubusercontent.com/106698935/212938260-2de21ff7-a645-42da-93cc-c5cadf2d4272.png)

![image](https://user-images.githubusercontent.com/106698935/212938402-7eddf5c0-c5a0-4895-ad51-7cf1429b275a.png)

**Image from Firefox**
![image](https://user-images.githubusercontent.com/106698935/212939280-b31ef42e-efbe-47a6-96a9-9921ba9a9d34.png)

**Comment by s-paquette** [comment]
No longer seems to be happening. (Note you have to scroll with the scrollwheel to view the image series.)
