### ISSUE TITLE
Issues observed prior to the initial demo

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#112]
1. It is not possible to click at the study level to load into the viewer.
2. Selection of the study does not seem to properly select the series included - the content of the series list does not appear to depend on the study selected:

Series for the subject 10 selected:
![image](https://user-images.githubusercontent.com/313942/84313881-2aeccd80-ab35-11ea-98db-3bd54fe9123e.png)
Series for the subject 11 selected:
![image](https://user-images.githubusercontent.com/313942/84313897-33450880-ab35-11ea-9c01-d27baff9299f.png)

3. If I click on a SEG series, I get a CT series loaded. It looks like SeriesInstanceUID is not populated properly, and does not point to a SEG series:
![2020-06-10_16-14-00 (1)](https://user-images.githubusercontent.com/313942/84314217-ae0e2380-ab35-11ea-919b-be2c0a5f0ace.gif)

**Comment by fedorov** [comment]
As of today, 22:05 Eastern time, I see that idc-testing allows loading at the study level. Things are still broken though.

One problem is that the viewer is referring to the Google collections, not IDC-hosted collections. See URL:

https://idc-testing.appspot.com/projects/chc-tcia/locations/us-central1/datasets/qin-headneck/dicomStores/qin-headneck/study/1.3.6.1.4.1.14519.5.2.1.2744.7002.271803936741289691489150315969

@G-White-ISB ?

**Comment by fedorov** [comment]
Also, it would be good to update OHIF to the latest - it has improved debugging capabilities to help trace issues.

**Comment by s-paquette** [comment]
I don't know why this would be working on test, since I haven't merged it in there, just on idc-dev. Unless you meant idc-dev?

**Comment by s-paquette** [comment]
I don't know that we have the locations for the IDC-hosted collections yet; do we @bcli4d ?

**Comment by fedorov** [comment]
When I created the sample testing dataset, I populated BQ and DICOM stores with the content. The DICOM store that contains pre-MVP collections content is here: https://console.cloud.google.com/healthcare/browser/locations/us/datasets/pre-mvp-temp/datastores?project=idc-dev-etl (this was also mentioned in the document I shared earlier and in the issue, wherever it was).

**Comment by fedorov** [comment]
> I don't know why this would be working on test, since I haven't merged it in there, just on idc-dev. Unless you meant idc-dev?

all I know is that I can click to load study in idc-testing, but not in idc-dev

**Comment by fedorov** [comment]
> all I know is that I can click to load study in idc-testing, but not in idc-dev

After "empty cache and hard reload" idc-dev had the study load.

**Comment by s-paquette** [comment]
Okay, looks like the last thing remaining is #3. @G-White-ISB let me know if something needs to come back different from the queries.

**Comment by fedorov** [comment]
And issue 4 is the app is using incorrect DICOM store.

**Comment by fedorov** [comment]
issue 5: considering all collections are searched by default, should all the checkboxes be selected in this panel?

![image](https://user-images.githubusercontent.com/313942/84393438-8ec0d600-abc9-11ea-9398-9d1b80a47310.png)

Also, "Check all/uncheck all" logic is broken - it only checks/unchecks TCGA.

**Comment by fedorov** [comment]
also, this has to be revised:

![image](https://user-images.githubusercontent.com/313942/84394737-57ebbf80-abcb-11ea-85a0-61857f956368.png)

probably we do not want to show CodeValue in the filter, and the long name does not look good, need to come up with something about this

**Comment by fedorov** [comment]
Another issue: for the collections listing, we should provide collection summary on mouseover, and also have an easy way for the user to get to a page describing the collection in detail. Perhaps same goes about each of the items in the facets.

**Comment by G-White-ISB** [comment]
Issue #5. Check All /Uncheck All options are under the TCGA tab and is meant to apply to those collections. Notice the options are hidden if you close the tab.

**Comment by G-White-ISB** [comment]
Collection description issue. This is a good idea but where are we getting these descriptions.

**Comment by G-White-ISB** [comment]
Agreed on needing a nicer way to print the filter definition.

**Comment by fedorov** [comment]
> All options are under the TCGA tab and is meant to apply to those collections.

is there a good reason why in other facet groups check/uncheck applies to all items, and here it applies only to TCGA?

How about a separate section listing projects (e.g., TCGA, CPTAC, PDMR, QIN, ...)? Right now TCGA is a sibling of "Collection", while it is children of TCGA that are collections.

**Comment by fedorov** [comment]
@George White (ISB) can you please comment on https://github.com/ImagingDataCommons/IDC-WebApp/issues/112#issuecomment-642361928

**Comment by s-paquette** [comment]
Re: descriptions, if we can be provided with them, they can definitely be stored for display. If there's a place to get them from let us know.

**Comment by G-White-ISB** [comment]
Re: DICOM store. I will switch to this URL (https://console.cloud.google.com/healthcare/browser/locations/us/datasets/pre-mvp-temp/datastores?project=idc-dev-etl) and test locally.

**Comment by G-White-ISB** [comment]
Re: Checkbox option in TCGA Collection. Other facet groups have a 'Check All option' if the have more that 6 items in the group. The new collection tab is the first time we have dealt with 'nested' checkboxes. We can add a 'Check All' to the 'top layer' of the checkboxes. There will be a little ambiguity as to whether  checking it would then check all the boxes in the nested layer.

**Comment by fedorov** [comment]
I will start splitting off individual issues from this one to make it easier to trace.

**Comment by G-White-ISB** [comment]
Re: Dicom store. Actually I think this is something Bill L. needs to change in the proxy server, not a change in my OHIF configuration. I will confirm.

**Comment by fedorov** [comment]
Closing this issue. All individual issues identified now have corresponding specific focused issues.
