### ISSUE TITLE
Test Tier - Modality not supported error for Abdomen Raw Data

### ISSUE THREAD

**Issue by VenkatPrema** [ImagingDataCommons/IDC-WebApp#1120]
Test Link: https://testing-viewer.canceridc.dev/viewer/2.25.10404001905468495441217502713666726991

**Steps to reproduce:**

1. Click Abdomen in the IDC home page
2. Select PDMR-292921-168-R collection name
3. Select PDMR-292921-168-R case
4. Select 292921-168-R-1404 studies 
5. Click eye symbol under view
6. OHIF image - click Raw data
7. Getting Modality not supported error

![image](https://user-images.githubusercontent.com/106698935/212960660-8da331db-3436-479c-a5c7-2c988b330150.png)
![image](https://user-images.githubusercontent.com/106698935/212960911-e0361a2d-5b39-471c-ad8a-51ad025384b9.png)
![image](https://user-images.githubusercontent.com/106698935/212961061-6e1e2775-fdd1-4999-95a7-cb77f372604a.png)
![image](https://user-images.githubusercontent.com/106698935/212960767-f48c6a3c-5beb-44c8-8384-680cb5953bc4.png)

**From Firefox:**
![image](https://user-images.githubusercontent.com/106698935/212962079-0b6ab223-c0ef-470a-b504-bc094207883b.png)

[Modality not supported console error.log](https://github.com/ImagingDataCommons/IDC-WebApp/files/10437521/Modality.not.supported.console.error.log)

**Comment by VenkatPrema** [comment]
Network - Response:

<!DOCTYPE html>
<html lang="en">

<head>

  
  <script>
    if (window.location.host == 'viewer.imaging.datacommons.cancer.gov') {
      (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
          (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date(); a = s.createElement(o),
          m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
      })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

      ga('create', 'UA-151885665-6', 'auto');
      ga('send', 'pageview');
    }
  </script>
  

  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta name="theme-color" content="#000000" />
  <meta name="mobile-web-app-capable" content="yes">
  <meta name="application-name" content="IDC Viewer">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="apple-mobile-web-app-title" content="@ohif/viewer">
  <meta name="msapplication-TileColor" content="#fff">
  <meta name="msapplication-TileImage" content="/assets/mstile-144x144.png">
  <meta name="msapplication-config" content="/assets/browserconfig.xml">
  <link rel="manifest" href="/manifest.json">

  <link rel="shortcut icon" href="/assets/favicon.ico">
  <link rel="icon" type="image/png" sizes="16x16" href="/assets/favicon-16x16.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/assets/favicon-32x32.png">
  <link rel="apple-touch-icon" sizes="57x57" href="/assets/apple-touch-icon-57x57.png">
  <link rel="apple-touch-icon" sizes="60x60" href="/assets/apple-touch-icon-60x60.png">
  <link rel="apple-touch-icon" sizes="72x72" href="/assets/apple-touch-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="76x76" href="/assets/apple-touch-icon-76x76.png">
  <link rel="apple-touch-icon" sizes="114x114" href="/assets/apple-touch-icon-114x114.png">
  <link rel="apple-touch-icon" sizes="120x120" href="/assets/apple-touch-icon-120x120.png">
  <link rel="apple-touch-icon" sizes="144x144" href="/assets/apple-touch-icon-144x144.png">
  <link rel="apple-touch-icon" sizes="152x152" href="/assets/apple-touch-icon-152x152.png">
  <link rel="apple-touch-icon" sizes="167x167" href="/assets/apple-touch-icon-167x167.png">
  <link rel="apple-touch-icon" sizes="180x180" href="/assets/apple-touch-icon-180x180.png">
  <link rel="apple-touch-icon" sizes="1024x1024" href="/assets/apple-touch-icon-1024x1024.png">
  <link rel="apple-touch-startup-image"
    media="(device-width: 320px) and (device-height: 480px) and (-webkit-device-pixel-ratio: 1)"
    href="/assets/apple-touch-startup-image-320x460.png">
  <link rel="apple-touch-startup-image"
    media="(device-width: 320px) and (device-height: 480px) and (-webkit-device-pixel-ratio: 2)"
    href="/assets/apple-touch-startup-image-640x920.png">
  <link rel="apple-touch-startup-image"
    media="(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)"
    href="/assets/apple-touch-startup-image-640x1096.png">
  <link rel="apple-touch-startup-image"
    media="(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2)"
    href="/assets/apple-touch-startup-image-750x1294.png">
  <link rel="apple-touch-startup-image"
    media="(device-width: 414px) and (device-height: 736px) and (orientation: landscape) and (-webkit-device-pixel-ratio: 3)"
    href="/assets/apple-touch-startup-image-1182x2208.png">
  <link rel="apple-touch-startup-image"
    media="(device-width: 414px) and (device-height: 736px) and (orientation: portrait) and (-webkit-device-pixel-ratio: 3)"
    href="/assets/apple-touch-startup-image-1242x2148.png">
  <link rel="apple-touch-startup-image"
    media="(device-width: 768px) and (device-height: 1024px) and (orientation: landscape) and (-webkit-device-pixel-ratio: 1)"
    href="/assets/apple-touch-startup-image-748x1024.png">
  <link rel="apple-touch-startup-image"
    media="(device-width: 768px) and (device-height: 1024px) and (orientation: portrait) and (-webkit-device-pixel-ratio: 1)"
    href="/assets/apple-touch-startup-image-768x1004.png">
  <link rel="apple-touch-startup-image"
    media="(device-width: 768px) and (device-height: 1024px) and (orientation: landscape) and (-webkit-device-pixel-ratio: 2)"
    href="/assets/apple-touch-startup-image-1496x2048.png">
  <link rel="apple-touch-startup-image"
    media="(device-width: 768px) and (device-height: 1024px) and (orientation: portrait) and (-webkit-device-pixel-ratio: 2)"
    href="/assets/apple-touch-startup-image-1536x2008.png">
  <link rel="icon" type="image/png" sizes="228x228" href="/assets/coast-228x228.png">
  <link rel="yandex-tableau-widget" href="/assets/yandex-browser-manifest.json">

  
  
  <script
    src="https://polyfill.io/v3/polyfill.min.js?flags=gated&features=default%2CObject.values%2CArray.prototype.flat%2CObject.entries%2CSymbol%2CArray.prototype.includes%2CString.prototype.repeat%2CArray.prototype.find"></script>
  <script type="text/javascript">
    window.PUBLIC_URL = '/';
  </script>
  <script type="text/javascript" src="/app-config.js"></script>
  <script type="module" src="/init-service-worker.js"></script>

  <title>OHIF Viewer</title>

  
  <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700&display=swap" rel="stylesheet" />

  
  
<link href="/10.c31cfb871d2567df67a0.css" rel="stylesheet"><link href="/app.c31cfb871d2567df67a0.css" rel="stylesheet"></head>

<body>
  <noscript> You need to enable JavaScript to run this app. </noscript>

  <div id="root"></div>
<script type="text/javascript" src="/vendors~app.bundle.2d9cc79312e464449c0a.js"></script><script type="text/javascript" src="/app.bundle.e9c32155e63d1abbf284.js"></script></body>

</html>

**Comment by s-paquette** [comment]
@pieper @bcli4d @wlongabaugh Does this seem like a problem with the image files or OHIF?

**Comment by s-paquette** [comment]
Just realized this is the original ticket for the same problem in #1137. Closing that in favor of this.

**Comment by bcli4d** [comment]
There are a couple of responses in #1137, one from @pieper  and one from you @s-paquette, that are important. 

@pieper wrote:
"Yes, we should handle this a bit more gracefully, but generally speaking this behavior is what I would expect for a modality we don't (and maybe can't) support. I believe RawData indicates something very application specific that the viewer is not expected to understand.

We can discuss any changes to improve this behavior of the viewer."

 @s-paquette wrote: "Just realized, the real issue is this shouldn't link to opening the viewer. @G-White-ISB This will be another modality to flag with a can't open icon."

...but the study also includes a displayable series so we can't disable viewing the study, only the individual series.

**Comment by s-paquette** [comment]
We have a separate ticket to disable Raw Data at the series level, #1273. Closing this one as addressing availability of 'Raw Data' in OHIF is not a WebApp issue, but an OHIF one, and a ticket should be opened with that team if this still needs addressing.
