### ISSUE TITLE
Test Tier - Eyeball symbol is missing  for Anterior fibromuscular stroma of prostate Segmentation

### ISSUE THREAD

**Issue by VenkatPrema** [ImagingDataCommons/IDC-WebApp#1122]
Test Link: https://testing-viewer.canceridc.dev/viewer/1.3.6.1.4.1.14519.5.2.1.7311.5101.170561193612723093192571245493?seriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.7311.5101.206828891270520544417996275680,1.2.276.0.7230010.3.1.3.1070885483.15960.1599120307.701 

**Steps to reproduce:**

1.  Open Test IDC site
2. Click  Magnetic Resonance from home page carousel image
3. OHIF image will open
4. Click SEG on the left to open Segmentation
5. eyeball missing for Anterior fibromuscular stroma of prostate

![image](https://user-images.githubusercontent.com/106698935/213519432-2c25cf45-2b52-48a8-8f3a-db9a3706dbbb.png)

![image](https://user-images.githubusercontent.com/106698935/213521091-3324a7e4-b377-4e87-8909-06b7769e533c.png)

**Comment by s-paquette** [comment]
This is an OHIF issue and should be added to the OHIF repo.
