### ISSUE TITLE
Determine Appropriate Bins for new Attributes

### ISSUE THREAD

**Issue by G-White-ISB** [ImagingDataCommons/IDC-WebApp#1129]
Determine appropriate, non uniform bins for creating facets for the min_PixelSpacing, max_TotalPixelMatrixColumns, and max_TotalMatrixRows that reflects the unique distributions of these attributes

**Comment by s-paquette** [comment]
@fedorov These are now available on test.

**Comment by VenkatPrema** [comment]
@s-paquette   I am seeing  min_PixelSpacing, max_TotalPixelMatrixColumns, and max_TotalMatrixRows lists are listed uniformly. 
I am going to mark this as a passed. If I need to perform any additional testing please let me know. 

![image](https://user-images.githubusercontent.com/106698935/220173596-d1c7661c-f9d1-4147-89f0-c69f0c980498.png)
