### ISSUE TITLE
Test Tier - Send bug report button is not working

### ISSUE THREAD

**Issue by VenkatPrema** [ImagingDataCommons/IDC-WebApp#1131]
Test Link: https://testing-viewer.canceridc.dev/viewer/1.3.6.1.4.1.14519.5.2.1.7009.2406.804219134722061461357666417697?SeriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.7009.2406.184707591584734218013706434651

**Steps to reproduce:**

1. Open any OHIF image
2. Click Debug info 
3. Click send bug report email icon
4. nothing happening when I click send bug report button

![image](https://user-images.githubusercontent.com/106698935/216366282-dcfb13f4-0647-44f4-b91b-cffa07c3c065.png)

![image](https://user-images.githubusercontent.com/106698935/216366185-7155dc2f-6ea4-4aea-ab50-89a5cb31c098.png)

**Comment by s-paquette** [comment]
@VenkatPrema This is an OHIF issue so should be ticketed in that repo.
