### ISSUE TITLE
Test Tier - Chrome browser opening to click Contact Us link in the Firefox & Nothing happened When I click Contact us in Chrome browser

### ISSUE THREAD

**Issue by VenkatPrema** [ImagingDataCommons/IDC-WebApp#1133]
When I click Contact Us, I expected to open Email link. But it is opening the Chrome browser 

![image](https://user-images.githubusercontent.com/106698935/217310543-5bbb5c6f-5678-4f95-9b4f-f28e2d052562.png)
![image](https://user-images.githubusercontent.com/106698935/217329281-f1a23187-df06-40da-8573-64adfdecd413.png)

**Comment by pieper** [comment]
I believe that's a client side issue with the way the browser thinks your email is handled when a `mailto` link is clicked.

**Comment by s-paquette** [comment]
As Steve said, this is a client side issue; mailto only works if a user's client is set up to use it properly.
