### ISSUE TITLE
Test Tier - Duplicate name appearing under Manufacturer - "GE Healthcare" 

### ISSUE THREAD

**Issue by VenkatPrema** [ImagingDataCommons/IDC-WebApp#1135]
Test Link: https://testing-portal.canceridc.dev/explore/

**Steps to reproduce:**

1. Click Uterus from home page image
2.  There are 2 GE Healthcare item listed  under Manufacturer. 

![image](https://user-images.githubusercontent.com/106698935/217598609-054a477c-f51c-4429-a20b-41d4d75e2f39.png)

**Comment by s-paquette** [comment]
We use the data as it's supplied in DICOM, and do not curate it at this time. Might be worth discussion in the future, but this isn't really a bug.
