### ISSUE TITLE
Test Tier - Skin -  CINE option is not working for chest OHIF images 

### ISSUE THREAD

**Issue by VenkatPrema** [ImagingDataCommons/IDC-WebApp#1139]
Test Link: https://testing-viewer.canceridc.dev/viewer/1.3.6.1.4.1.14519.5.2.1.2857.3159.118675318760849257334780851611?SeriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.2857.3159.221719396190336582395156248269

https://testing-viewer.canceridc.dev/viewer/1.3.6.1.4.1.14519.5.2.1.2857.3159.250377344180398556213643916377?SeriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.2857.3159.283695705914536763818701966621

**Steps to reproduce:** 

1. Click Skin under Cases by Major Primary Site list
2. Select Collection Name: CPTAC-CM
3. Select CaseID:C3L-00275
4. Click eyeball icon under selected series

![image](https://user-images.githubusercontent.com/106698935/219093913-864cab2c-fb1f-4272-8ba8-604256288f4f.png)
![image](https://user-images.githubusercontent.com/106698935/219094014-3f5cba3b-db80-4d8d-a7d9-380760c501e4.png)

**Comment by s-paquette** [comment]
This is an OHIF issue and should be added to the OHIF repo.
