### ISSUE TITLE
Update front page image URL for PET/CT

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#1140]
Let's use this URL:

https://viewer.imaging.datacommons.cancer.gov/viewer/1.3.6.1.4.1.14519.5.2.1.5168.1900.259520120774497994844579066293?seriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.5168.1900.379274847602196071565482395253,1.3.6.1.4.1.14519.5.2.1.5168.1900.924189791316990444955278117416,1.3.6.1.4.1.14519.5.2.1.5168.1900.308784784152451259100701859682,1.3.6.1.4.1.14519.5.2.1.5168.1900.924189791316990444955278117416,1.3.6.1.4.1.14519.5.2.1.5168.1900.379274847602196071565482395253,1.3.6.1.4.1.14519.5.2.1.5168.1900.308784784152451259100701859682

![image](https://user-images.githubusercontent.com/313942/219171721-810ef04e-086e-451e-9533-eeb1ee606e42.png)

It does not quite work exactly as I expected, but we can debug later, and I think it is better than what we have right now (since it currently shows blank screen).

**Comment by VenkatPrema** [comment]
@s-paquette I don't see any blank slide now, so I am going to mark as passed for this ticket. If I need to do any other testing please let me know.

![image](https://user-images.githubusercontent.com/106698935/220170439-042b4505-0a67-4e6c-8eaa-f159bc1f9de6.png)
