### ISSUE TITLE
Add new attributes to the portal for v13

### ISSUE THREAD

**Issue by s-paquette** [ImagingDataCommons/IDC-WebApp#1144]
For addition:

**Derived, Quantification**
Sphericity
Volume of Mesh

**Original**
Max Total Pixel Matrix Columns
Max Total Pixel Matrix Rows
Min Pixel Spacing

These should be tested in cohort creation and export to manifest and BQ.

**Comment by VenkatPrema** [comment]
**Max Total Pixel Matrix Columns**

@s-paquette I selected 500 to 600 and 800 to 1000 attributes under Max Total Pixel Matrix Columns. I try to add to Cohorts  and getting this "Invalid operator seen for attribute 'max_TotalPixelMatrixColumns'; default of OR used instead." message. 


![image](https://user-images.githubusercontent.com/106698935/220154552-a014521f-e8a6-45e7-be17-10146f80ca77.png)
![image](https://user-images.githubusercontent.com/106698935/220155456-085196d5-33d2-4553-8552-b31c2a9546df.png)
![image](https://user-images.githubusercontent.com/106698935/220155543-b3fb4088-b77e-4c1d-9698-7ba3a17d885d.png)

**Comment by VenkatPrema** [comment]
**max_TotalPixelMatrixRows**

@s-paquette I selected 2 attributes and I try to add it in the Cohorts and getting below message. But Cohorts is created successfully and I was able to download the CSV, TSV and JSON files. When I click get BQ table, BQ table link is not generating.

**Error Message:**
Invalid operator seen for attribute 'max_TotalPixelMatrixRows'; default of OR used instead.

![image](https://user-images.githubusercontent.com/106698935/220158400-2d6efc09-0b48-447c-83d2-bf6e92eba2ed.png)
![image](https://user-images.githubusercontent.com/106698935/220158532-ab0a9fab-fbdd-42f1-b175-81a76020fbd9.png)
![image](https://user-images.githubusercontent.com/106698935/220158684-82c97f3f-47ea-4f84-9bed-cf544f771863.png)
![image](https://user-images.githubusercontent.com/106698935/220158857-d3aec79d-9d03-4f7e-b532-e608d1917127.png)

**Comment by VenkatPrema** [comment]
**Min Pixel Spacing**

@s-paquette I selected 2 attributes and I try to add it in the Cohorts and getting this "Invalid operator seen for attribute 'min_PixelSpacing'; default of OR used instead." message. 

![image](https://user-images.githubusercontent.com/106698935/220161493-082693a3-f455-4d33-8cb6-59f9a0456753.png)

When I try to download the CSV,TSV and JSON files and get BQ table, getting this below message 

**Error Message:** 
 "There was an error while attempting to download your cohort manifest(s)--please contact the administrator."
![image](https://user-images.githubusercontent.com/106698935/220162127-b47b9672-ae60-48f7-ae4c-47bb482a1eb7.png)

**Comment by VenkatPrema** [comment]
**Sphericity & Volume of Mesh**

@s-paquette I selected attributes from Sphericity & Volume of Mesh and tried to add it to the Cohorts. I am getting this "Cannot read properties of undefined" console error and page is loading infinitely. 

![image](https://user-images.githubusercontent.com/106698935/220164764-72ad32d2-e5e7-412f-a994-336378224841.png)
![image](https://user-images.githubusercontent.com/106698935/220165299-c829c637-028b-4010-8d80-5a4e8c274319.png)
![image](https://user-images.githubusercontent.com/106698935/220166271-2ba9b32d-5b58-4afd-ae3d-79a290dd689d.png)

[Sphericity & Volume of Mesh console error.log](https://github.com/ImagingDataCommons/IDC-WebApp/files/10786478/Sphericity.Volume.of.Mesh.console.error.log)

**Comment by VenkatPrema** [comment]
created new ticket for this default of OR used instead error #1147

**Comment by VenkatPrema** [comment]
@s-paquette New attributes are added. It is working fine. I am closing this ticket.


![image](https://user-images.githubusercontent.com/106698935/224174521-8a87b496-aaf4-4a0c-a794-2acaea22f702.png)
![image](https://user-images.githubusercontent.com/106698935/224174625-d004cfac-80d9-432e-89cd-1f505a0e07be.png)
