### ISSUE TITLE
Add version 13 data to the portal

### ISSUE THREAD

**Issue by s-paquette** [ImagingDataCommons/IDC-WebApp#1145]
This will involve the addition of a new Analysis Result. **nnU-Net-BPR-annotations**. Standard checks for a new data version apply:

- Attempt to create a cohort with the new collection(s) and/or analysis results as the attribute
- Attempt to export cohorts made with this attribute
- Check for the presence of the new collections and/or analysis results in the collections table

**Comment by VenkatPrema** [comment]
@s-paquette I am not sure what do I need to test for this ticket.

I created new Cohort and I can see the new data version updated under Data Version. 
I don't know how to check this --> nnU-Net-BPR-annotations. Please let me know how to test this ticket.
![image](https://user-images.githubusercontent.com/106698935/219819137-41a8e478-2165-4cc7-9a50-ae271f549041.png)

**Comment by s-paquette** [comment]
For `nnU-Net-BPR-annotations` you'll want to select it as a filter un Search Scope -> Analysis Results, then make a cohort, and confirm the cohort can be made and a manifest exported. You'll also want to go to the `Collections` list (accessed via the menu bar on the top of the page) and sort by Type to get to Analysis. This should cause those to come to the top of the list, and you can confirm it's there and that you can click on the DOI link for it.

**Comment by VenkatPrema** [comment]
@s-paquette I selected this nnU-Net-BPR-annotations filter and created Cohorts. I was able to download CSV,TSV and JSON files and was able to get BQ table. 
I was able to access this nnU-Net-BPR-annotations from collections list. 

![image](https://user-images.githubusercontent.com/106698935/220167307-1e0ea24d-696a-4b46-84d0-91b0eb87f467.png)
![image](https://user-images.githubusercontent.com/106698935/220167446-b12acc7c-15a0-48cb-93b1-0838d3c62c17.png)
![image](https://user-images.githubusercontent.com/106698935/220167540-8983ebd5-77e3-4595-8553-d9db5e4f3c6e.png)
![image](https://user-images.githubusercontent.com/106698935/220167803-3caf53f1-3a62-49fb-802e-b4ba66b65398.png)
![image](https://user-images.githubusercontent.com/106698935/220167955-2ce54be1-6b74-4dba-9e40-4319410cc8cf.png)
