### ISSUE TITLE
Test Tier - Unable to see the Volume of mesh lower number

### ISSUE THREAD

**Issue by VenkatPrema** [ImagingDataCommons/IDC-WebApp#1146]
Unable to see the Volume of mesh &Sphericity lower number. Slider overlapped this number.

![image](https://user-images.githubusercontent.com/106698935/220185578-3ee26f1e-863f-4eec-a46b-1f26fb395162.png)
![image](https://user-images.githubusercontent.com/106698935/220185833-7a3f7c38-f892-40cc-ba29-93151cd227ce.png)

**Comment by VenkatPrema** [comment]
when Volume of mesh & Sphericity is in 0 position

![image](https://user-images.githubusercontent.com/106698935/220671442-014553e5-4cf2-417d-9f17-951cc31ce12d.png)

**Comment by s-paquette** [comment]
@VenkatPrema Can you confirm if this is still happening?

**Comment by s-paquette** [comment]
@VenkatPrema Can you show what filters you're using to get to this state? (Or is this just how it always looks?)

**Comment by VenkatPrema** [comment]
@s-paquette I used this filter.
![image](https://user-images.githubusercontent.com/106698935/223199244-6ac00d0c-8aff-42a9-b394-ea3107798d89.png)

**Comment by s-paquette** [comment]
@VenkatPrema I think I may be confused; the first one looks fine, so are you saying you swap the Primary Site Location to another value and then you see those?

**Comment by VenkatPrema** [comment]
@s-paquette yes, I did two different test(Primary Site Location) . one is when Volume of mesh & Sphericity is in 0. one more testing is when Volume of mesh & Sphericity has  a numbers.
