### ISSUE TITLE
Test Tier - Getting "default of OR used instead" error for Max Total Pixel Matrix Columns / Max_TotalPixelMatrixRows

### ISSUE THREAD

**Issue by VenkatPrema** [ImagingDataCommons/IDC-WebApp#1147]
Select the attributes under Max Total Pixel Matrix Columns / max_TotalPixelMatrixRows and  try to add it in the Cohorts I got below  error message. But Cohorts is created successfully and I was able to download the CSV, TSV and JSON files. 

**Error Message:**
Invalid operator seen for attribute 'max_TotalPixelMatrixRows'; default of OR used instead.
Invalid operator seen for attribute 'max_TotalPixelMatrixColumns'; default of OR used instead.

![image](https://user-images.githubusercontent.com/106698935/220444504-20c674a6-af23-40b4-8e74-64be0730f0de.png)
![image](https://user-images.githubusercontent.com/106698935/220444554-9d9ce115-c251-4ef0-ac05-794660d33017.png)
![image](https://user-images.githubusercontent.com/106698935/220444826-672a3140-6863-4169-911f-313b7e707de2.png)

**Comment by G-White-ISB** [comment]
Currently fix in the dev-port but not testing-portal

**Comment by VenkatPrema** [comment]
I am able to create a Cohort without any issue for Max Total Pixel Matrix Columns / Max Total Pixel Matrix Rows

![image](https://user-images.githubusercontent.com/106698935/224174013-f6726d90-a47a-4503-ac39-a45ec7226581.png)
