### ISSUE TITLE
Test Tier - "Cannot read properties of undefined" console error for Sphericity & Volume of Mesh

### ISSUE THREAD

**Issue by VenkatPrema** [ImagingDataCommons/IDC-WebApp#1148]
Test Link - https://testing-portal.canceridc.dev/cohorts/415/

**Steps to reproduce:**

1.Click Chest from home page
2. Adjust the Sphericity & Volume of Mesh slider
3. Select NLST and try to add to Cohort
4. Getting Cannot read properties of undefined" console error

![image](https://user-images.githubusercontent.com/106698935/220463657-8c33ffc2-4a4b-4d16-b3bb-1ae87c3f1871.png)

![image](https://user-images.githubusercontent.com/106698935/220463673-18cf007d-a6f0-424d-8e8e-af9fee80ff4f.png)

![image](https://user-images.githubusercontent.com/106698935/220463711-81e78d47-4aa6-480f-b590-789ee0328c4c.png)

[Sphericity & Volume of Mesh console error1.log](https://github.com/ImagingDataCommons/IDC-WebApp/files/10797933/Sphericity.Volume.of.Mesh.console.error1.log)

**Comment by G-White-ISB** [comment]
Still seeing an issue in testing-portal but not dev-portal. From my Slack comment:
_"related to #1148 I can define a cohort with sphericity in the dev-portal but not in the testing-portal. In testing portal it seems the sphericity range is set to 0-0 for any cohort defined with this attribute. Volume of mesh works as a filter attribute in either"_

**Comment by VenkatPrema** [comment]
I don't see this issue now. It is working as expected.
![image](https://user-images.githubusercontent.com/106698935/224173185-65f731bd-0c77-490f-b684-baf68919fdfa.png)
