### ISSUE TITLE
Prod - intermittent issue - Blank page appearing when I click Cases under Cases by Major Primary Site

### ISSUE THREAD

**Issue by VenkatPrema** [ImagingDataCommons/IDC-WebApp#1153]
Test Link - https://portal.imaging.datacommons.cancer.gov/explore/filters/?collection_id=acrin_contralateral_breast_mr
I am seeing the blank page some times when I click the Cases under Cases by Major Primary Site. But It is an intermittent issue.
Once refresh the page, it is working fine again. 

![image](https://user-images.githubusercontent.com/106698935/224352011-84c82822-4cca-43dd-9dab-5a3833a489f0.png)
![image](https://user-images.githubusercontent.com/106698935/224352043-3f99600c-ee0b-4b2e-8e94-402b3e3c80f7.png)
![image](https://user-images.githubusercontent.com/106698935/224355015-438d22c4-0db2-4816-9593-83e62a4e6cbf.png)

**Comment by s-paquette** [comment]
@VenkatPrema Your test link there isn't one you'd get to from Cases by Major Primary Site, but from the Collections table. Is this bug happening there as well? 

Next time this happens if you could open the dev console (F12 on a windows machine) and check for errors to screenshot that might help us track this down.

**Comment by VenkatPrema** [comment]
@s-paquette here is console log for this issue.

[IDC prod blank page console.log](https://github.com/ImagingDataCommons/IDC-WebApp/files/10945939/IDC.prod.blank.page.console.log)

**Comment by s-paquette** [comment]
@VenkatPrema Sorry, I meant a screen shot of the dev console as opposed to a log. Eg.:

![image](https://user-images.githubusercontent.com/8442808/224440415-72ddbd5a-87f2-49e5-a9c4-ffb5719e3345.png)

Sadly I'm not seeing any actual error (maps not loading is normal, we don't provide those in production.

If you could keep your dev console open and see if an error pops up next time, maybe we can sort out what's happening.

**Comment by s-paquette** [comment]
@VenkatPrema Just to double-check, that first URL doesn't look like it came from Cases by Primary Site. Did it come from a link on the Collections page?

**Comment by VenkatPrema** [comment]
@s-paquette First image- I did not logged in and I clicked login to save a Cohort button. After logged in, this blank page appeared.

**Comment by s-paquette** [comment]
@pgundluru I'm unclear on what 'select collections, cases, and series' means. Can you explicitly indicate what you're clicking on?

**Comment by s-paquette** [comment]
Note, as this ticket is very old, we can probably close it as the referenced bug may have been fixed some time ago.
