### ISSUE TITLE
Prod - In cohort export page, the tool tip for older versions shows up on bottom of the page 

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#1156]
This was observed by Andrey in W10 with chrome browser. Version 111.0.5563.64 (Official Build) (x86_64)

![image](https://user-images.githubusercontent.com/85526819/227307113-b12f6e6c-4264-4b50-ae60-8489d82341d4.png)

**Comment by s-paquette** [comment]
I think I may know what's causing this, merging in an attempt to fix it now.

**Comment by s-paquette** [comment]
@pgundluru Ready for testing.

**Comment by s-paquette** [comment]
Hm, this is one I can't really test because I don't have a Mac or Safari, so I'm really not sure how to go about working on it. I can't replicate it at all in Windows, on FF or in Chrome. I assume it's some kind of Safari incompatibility. I'll see if I can dig up something research wise.

**Comment by pgundluru** [comment]
This issue with the tooltip still persists. I am able to hover and view a tool tip in the cohorts page only in W10 Chrome browser, Not able to view in MacOS (Safari and FF and Chrome) Researching if this is an issue only with with Mac machines 

Update - Only working on Windows Chrome browser not in Edge

**Comment by s-paquette** [comment]
@pgundluru Can you have a look at this again and let me know if it's still happening?

**Comment by pgundluru** [comment]
I am no longer able to replicate this issue in test tier or prod.
