### ISSUE TITLE
Change manifest exporting to a tabbed interface

### ISSUE THREAD

**Issue by s-paquette** [ImagingDataCommons/IDC-WebApp#1165]
As we're adding another export option, manifest exports should now be a tabbed series of options in the dialog. This makes them scaleable going forward.

**Comment by pgundluru** [comment]
The export manifest is now tabbed like below 

![image](https://user-images.githubusercontent.com/85526819/234912302-d7c711bd-7333-44fa-97a2-e20e69d830ef.png)
