### ISSUE TITLE
Add aws_url to manifest exports

### ISSUE THREAD

**Issue by s-paquette** [ImagingDataCommons/IDC-WebApp#1166]
The new aws_url column should be added to all BQ exports.

**Comment by pgundluru** [comment]
Able to se the AWS_URLS column in BQ and exports 

![image](https://user-images.githubusercontent.com/85526819/234913293-bece95c2-a56c-4eca-af4a-cbc0826aaacc.png)

**Comment by pgundluru** [comment]
![image](https://user-images.githubusercontent.com/85526819/234913538-f8df6e47-4dd1-4eeb-a58b-b0d973360ab0.png)
