### ISSUE TITLE
In test tier, incorrect cohort manifest export using s5cmd and GCP  

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#1169]
Summary - Identified by Andrey that cohorts created and exported using s5cmd via GCP are incorrect as they need to start with gs://  instead of s3://" 

https://user-images.githubusercontent.com/85526819/234377430-b86de86c-47f6-4929-8b28-6ea90e729823.mp4

**Comment by s-paquette** [comment]
@fedorov @pgundluru I am confused--in Slack, Andrey said they need to start with `s3://` and not `gs://`, but this ticket says it should be `gs://` and not `s3://`.

Which one should it be?
