### ISSUE TITLE
Feature request - Remove TSV/CSV/JSON AND BQ for import manifest for older versions in IDC portal 

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#1171]
This was requested by Andrey - To completely remove/disable access to select the CSV/TSV/JSON and BQ tabs for older versions of cohorts where it is  currently greyed out.

**Comment by pgundluru** [comment]
![image](https://user-images.githubusercontent.com/85526819/234955847-47893532-cb65-4ab4-9378-ae546ab7a3e4.png)

**Comment by s-paquette** [comment]
@fedorov Is this not a duplicate of #1178?
