### ISSUE TITLE
Communicate to the users the external URL that is about to be opened

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#1180]
Right now, it is impossible to know what external URL is being opened until it is opened. Can just add the URL to the text of the popup.

![image](https://user-images.githubusercontent.com/313942/236282139-c89f9bff-8be3-4efa-990f-8f2eb1a1cb51.png)

**Comment by pgundluru** [comment]
Currently able to view the link to the external website in the window 

![Screen Shot 2023-06-23 at 10 59 41 AM](https://github.com/ImagingDataCommons/IDC-WebApp/assets/85526819/a4107aae-8143-4bba-a086-cf2e14ce5aff)

**Comment by pgundluru** [comment]
The update shows up in "getting started" "user forum" and "help"
