### ISSUE TITLE
Add "cancer type" to the portal search panel

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#1183]
It is already in `dicom_all` in the `collection_cancerType` column. In the panel, it should probably be high on the list

<img width="310" alt="image" src="https://github.com/ImagingDataCommons/IDC-WebApp/assets/313942/d9243bb7-34d1-47f8-862a-628c2c7d60b4">

Per discussion, let's add it as the second item under cancer site, keep it expanded by default, and have 4 items expanded by default: cancer location, cancer type, body part and modality.

<img width="350" alt="image" src="https://github.com/ImagingDataCommons/IDC-WebApp/assets/313942/713b5b42-081d-4fcc-bd31-a26d6cef5cb2">

**Comment by pgundluru** [comment]
In test tier, I am able to open up explore images (after logging in) and when i scroll to the search configuration the following fields are automatically oped up (primary site, body part, cancer type and modality)

**Comment by pgundluru** [comment]
![Screen Shot 2023-06-23 at 11 02 44 AM](https://github.com/ImagingDataCommons/IDC-WebApp/assets/85526819/46eb9b00-bb53-4a32-ab50-074df3671ccf)
