### ISSUE TITLE
Segmentations or RTSTRUCT do not show - extensions not registered?

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#119]
It should instead point to IDC DICOM store.

Re https://github.com/ImagingDataCommons/IDC-WebApp/issues/112#issuecomment-642842854

**Comment by fedorov** [comment]
As of Jun 12 East coast morning, it is still pointing to the `chc-tcia` collections.

**Comment by fedorov** [comment]
Quoting @G-White-ISB from https://github.com/ImagingDataCommons/IDC-WebApp/issues/112#issuecomment-643493036:

> Re: Dicom store. Actually I think this is something Bill L. needs to change in the proxy server, not a change in my OHIF configuration. I will confirm.

Adding @wlongabaugh.

As of today, idc-dev and idc-testing are still pointing to the google-hosted content.

**Comment by fedorov** [comment]
The DICOM store and BQ to be used for pre-MVP have been documented in https://docs.google.com/document/d/14Wfu-q3hbRxlOSDGIWC0kkSI3CsYoKyB5EhmgY52TgM/edit#, and the destination DICOM store should be https://console.cloud.google.com/healthcare/browser/locations/us/datasets/pre-mvp-temp/datastores?project=idc-dev-etl.

**Comment by wlongabaugh** [comment]
It is now switched over. In fact, the piece of the URL that specifies the project, location, dataset, and DICOM store are configured in the WebApp. The proxy just specifies the host (https://healthcare.googleapis.com). Worth noting that maybe the proxy should be configured to *only* pull from our collections, to keep somebody from getting stuff from some random DICOM store thru our proxy.

**Comment by JamesAPetts** [comment]
We discovered that this issue was because you guys switched to using the UMD bundle, instead of the PWA, which requires manual addition of extensions.

@pieper will help you switch back to the PWA version, which will allow the app to run correctly again.

**Comment by pieper** [comment]
This is what I do to build and deploy the idc-sandbox:

```
(cd viewers; \
  git checkout master && \
  git pull && \
  yarn install && \
  yarn run build) \
&& \
rsync -avP viewers/platform/viewer/dist/ public/ \
&& \
cp backup-app-config.js public/app-config.js \
&& \
cp idc-black.svg public \
&& \
firebase deploy
```

**Comment by fedorov** [comment]
Here's a study that contains SEG: https://idc-dev.appspot.com/projects/idc-dev-etl/locations/us/datasets/pre-mvp-temp/dicomStores/cross-collection-temp/study/1.3.6.1.4.1.14519.5.2.1.6279.6001.191425307197546732281885591780

When SEG extension is not working, SEGs will show on the left as in the screenshot below.

If it is working properly, you should NOT see SEG in the left panel.

![image](https://user-images.githubusercontent.com/313942/85152049-88aea300-b222-11ea-9529-5bee92252959.png)

**Comment by G-White-ISB** [comment]
<img width="1792" alt="Screen Shot 2020-06-19 at 10 38 02 AM" src="https://user-images.githubusercontent.com/58443591/85164422-31580500-b219-11ea-831e-3d8f85067329.png">
I have not figured out how to deploy the PWA version in our environment so that all the resources are located and loaded correctly. I've reached out to Steve P and Suzanne P for help

**Comment by fedorov** [comment]
@G-White-ISB @pieper let's make sure the solution to this is documented here whenever you figure it out.

**Comment by pieper** [comment]
We've been discussing.  The current plan is either to run an independent web server instance for OHIF or to get Danny's help with the config/environment settings to make the deployment work as @G-White-ISB originally tried.  My vote would be for the independent server, but I'm happy either way.

**Comment by fedorov** [comment]
Per discussion with @G-White-ISB, the plan is to seek help from @dannyrb when he is back in the office on Tue, June 23.

**Comment by fedorov** [comment]
@pieper @dannyrb @G-White-ISB were you able to connect to come up with the path forward on this problem?

**Comment by G-White-ISB** [comment]
Suzanne, Steve and I just met with Erik Ziegler. He believes its a simple build configuration to get the PWA version working in our environment. We hope to have it sorted today or tomorrow

**Comment by s-paquette** [comment]
@fedorov Is this one working now? If so we can close this out.

**Comment by madelyngreyes** [comment]
The correct URL seems to be present. 

![Screen Shot 2020-07-08 at 10 57 23 AM](https://user-images.githubusercontent.com/16824894/86934553-d58ee680-c109-11ea-9e7c-015efe416fd0.png)
