### ISSUE TITLE
Add gcs/aws_bucket as top-level attributes to the WebApp

### ISSUE THREAD

**Issue by s-paquette** [ImagingDataCommons/IDC-WebApp#1196]

**Comment by fedorov** [comment]
What is this issue about?

**Comment by s-paquette** [comment]
@fedorov This is a request from @bcli4d to add these columns to the pivot.

**Comment by fedorov** [comment]
Those attributes are already available in IDC API using a workaround in the API implementation.

**Comment by s-paquette** [comment]
@bcli4d This is ready for testing.
