### ISSUE TITLE
TCIA collection descriptions

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#120]
We need to add collection descriptions for the collections list. The way TCIA is doing this is very nice: 

![image](https://user-images.githubusercontent.com/313942/84515506-8c7a7c80-ac9a-11ea-97c7-aba963d02343.png)

We could initially link to the TCIA collection pages using DOIs, but going forward we should probably have our own collections pages to make sure the description matches the version we have in IDC. Or we should make sure we keep them in sync.

Re: https://github.com/ImagingDataCommons/IDC-WebApp/issues/112#issuecomment-642680643

**Comment by fedorov** [comment]
Relevant communication from Ulli on how to get this information:

---

Hi Andrey,

NBIA has an API called “Collection Description API” and it is  listed in the API Guide https://wiki.nci.nih.gov/display/NBIA/NBIA+REST+API+User+Guide

The API requires a token.

 

Here is an example of getting a token:

 

C:\curl>curl -d  "username=nbia_guest&password=&client_id=nbiaRestAPIClient&client_secret=ItsBetweenUAndMe&grant_type=password" -X POST -k "https://public.cancerimagingarchive.net/nbia-api/oauth/token"

{"access_token":"c57af37b-f0d0-44d5-8f55-42a69e4c56df","token_type":"bearer","refresh_token":"c9f20bf4-acf3-4a2a-b5c8-3cbdf8c7a2e8","expires_in":6028}

 

  The base URL is:

https://public.cancerimagingarchive.net/

 

  Using the token provided this get all the collection descriptions:

curl -H "Authorization:Bearer c57af37b-f0d0-44d5-8f55-42a69e4c56df" -k https://public.cancerimagingarchive.net/nbia-api/services/getCollectionDescriptions

 

Ulli

 

Ulrike (Ulli) Wagner, PMP (Contractor)

Technical Project Manager

Biomedical Informatics and Data Science (BIDS) at the FNLCR

Phone: (240) 344-6828

Email: ulli.wagner@fnlcr.nih.gov

**Comment by fedorov** [comment]
@bcli4d to redo the table with the conventions followed by @s-paquette

**Comment by madelyngreyes** [comment]
Looking on the dev tier for other reasons, I noticed this seems to be implemented for the most part in the Search Scope panel. 

But, there is some text box cut-off in the top-left for the collection LIDC_IDRI at 100%+ zoom on a laptop using Google Chrome. 
<img width="960" alt="text-box- cutoff for LIDC_IRDI descriptions in search scopr panel" src="https://user-images.githubusercontent.com/16824894/90162849-42c61500-dd63-11ea-8213-e578932c6b8b.png">

Also, for the collection TCGA itself there is no description, only for the detailed collection name e.g., tcga_gbm. 
<img width="960" alt="no information for collection tcga presented" src="https://user-images.githubusercontent.com/16824894/90163184-c2ec7a80-dd63-11ea-89fa-c0cb2e612e23.png">


One more item I noticed is if you look at the collection tcga_gbm, the text "Cancer Imaging Program (CIP)" and "TCGA-GBM", appear as underlined. Should the underlined text go to a link? Currently, when selected nothing happens.
<img width="960" alt="TCGA_GBM filter detailed information panel" src="https://user-images.githubusercontent.com/16824894/90163566-43ab7680-dd64-11ea-8ee1-96a3c24a5d49.png">

This is how it is displayed for the collect option tcga_esca, with no text displayed as underlined. 
<img width="960" alt="TCGA_ESCA filter detailed information panel" src="https://user-images.githubusercontent.com/16824894/90163665-62aa0880-dd64-11ea-8f44-8d97cfdb643b.png">

**Comment by s-paquette** [comment]
Are you working with a zoom level? This is a tooltip library, so we can't really adjust where it opens, but more importantly, browser zoom information isn't available, so we can't adjust it anyways.

**Comment by s-paquette** [comment]
...this goes for System Zoom as well; if the system is set to eg. 125%, we have no way to check that, nor can we really alter libraries to account for it.

**Comment by madelyngreyes** [comment]
Test system zoom settings below.

<img width="573" alt="display resolution" src="https://user-images.githubusercontent.com/16824894/90177514-a870cc00-dd78-11ea-8b0e-2186b18fce17.png">

**Comment by fedorov** [comment]
@s-paquette can you confirm - can we have links in the tooltips? If not, can we think of an alternative way to allow users to link to the collections wiki pages?

**Comment by s-paquette** [comment]
There are links in the tooltips, though they may be hard to see; I'll adjust the CSS.
