### ISSUE TITLE
In test tier, when a user tries to download manifest by selecting include header fields there is an error 

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#1200]
Happening in windows and Mac machines 

To reproduce this issue:

Select cohort and click on download images 
Select include header fields and click download 
Then there is an error like below 

![image](https://github.com/ImagingDataCommons/IDC-WebApp/assets/85526819/54c7fd47-8ed8-459a-8861-e3f5830b1866)

**Comment by s-paquette** [comment]
@pgundluru Is this still happening?

**Comment by pgundluru** [comment]
This issue is now resolved and able to download with header files included
