### ISSUE TITLE
Test tier has never-ending spinner while trying to export manifest using bQ 

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#1205]
Summary - Currenty selecting any collection, configuration in explore images page and exporting the manifest takes me to a ongoing spinner with error in dev console as below. 

Seen in W10 - Edge, FF, chrome and Mac OS safari 

https://github.com/ImagingDataCommons/IDC-WebApp/assets/85526819/6fa31794-24af-4d04-b1a1-16f39d83bf3c

**Comment by s-paquette** [comment]
This is due to a complex problem involving refactoring BQ exports to not require a cohort. Rather than delay the release we're going to disable BQ exports if there's no cohort for now, and re-enable via ticket #1208 .
