### ISSUE TITLE
Error while downloading files using s5cmd (AWS)

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#1206]
Summary - Followed the steps listed in this [DOC](https://learn.canceridc.dev/data/downloading-data)  define a cohort and download using s5cmd via AWS file and running into errors. 

History of commands - 
pwd
  475  cd Desktop/work/
  476  gcloud init
  477  s5cmd --no-sign-request --endpoint-url https://storage.googleapis.com cp s3://public-datasets-idc/cdac3f73-4fc9-4e0d-913b-b64aa3100977/902b4588-6f10-4342-9c80-f1054e67ee83.dcm .
  478  pwd
  479  ls
526  s5cmd --no-sign-request --endpoint-url https://s3.amazonaws.com run file_manifest_aws.s5cmd
  527  cp s3://idc-open-data/56f8119f-5940-48c1-96ee-8d445dc0b5fd/* .
  528  cp s3://idc-open-data/9a5382ad-338a-451f-aa6a-080122dd2f00/* .
  529  cp s3://idc-open-data/4ddb390d-03e7-4f41-8bda-6c8e1685393c/* .
  530  cp s3://idc-open-data/95a776b1-8b86-48a4-8052-604f5999f1dc/* .
  531  cp s3://idc-open-data/effbff9b-ade5-4dbb-94cc-c4cdbcf3b4ec/* .
  532  cp s3://idc-open-data/d4066bb5-662c-43bd-b535-3852e681f7e4/* .
  533  cp s3://idc-open-data/108de45b-c75b-4333-8e08-74a175990de7/* .
  534  cp s3://idc-open-data/30cdc243-6fc5-4896-b1db-1849a7d8e538/* .
  535  cp s3://idc-open-data/822b015d-361b-492a-851d-4db38517f471/* .
  536  cp s3://idc-open-data/a116340f-35c2-4bc4-9de9-5a74bb5cf83f/* .
  537  cp s3://idc-open-data/a149f373-d72b-42a9-80fe-569801e1ce49/* .
  538  cp s3://idc-open-data/5f302398-fbde-469e-ac8d-75c92f35323e/* .
  539  cp s3://idc-open-data/cc984c73-c55e-47ec-8ad1-235d22633eb9/* .
  540  cp s3://idc-open-data/11748500-4189-4598-85a9-a401ee6af8ad/* .
  541  cp s3://idc-open-data/b9cf8e7a-2505-4137-9ae3-f8d0cf756c13/* .
  542  cp s3://idc-open-data/af18f5e4-f010-4b23-9be7-7c9f1aaa21a5/* .
  543  cp s3://idc-open-data/4aaf9181-fb6a-4a4c-bf49-d1eb9ed4a385/* .
  544  cp s3://idc-open-data/237eaf33-4162-4a9e-8212-7f16d697cbf6/* .
  545  cp s3://idc-open-data/779e7a2a-9769-49b3-a7e9-203a405009e5/* .
  546  cp s3://idc-open-data/2f67b46d-3719-4038-971c-eb483fc415c4/* .
  547  cp s3://idc-open-data/752cae1f-9bc5-494e-9859-4bbbb6b9f85d/* .
  548  cp s3://idc-open-data/57fc9942-e85c-4986-a262-a7ddfcd704aa/* .
  549  cp s3://idc-open-data/088360b3-44f6-4c27-b3c7-7ac82527aeb6/* .
  550  cp s3://idc-open-data/ad792585-87c3-4594-80f5-65f5d0192f7e/* .
  551  cp s3://idc-open-data/56313377-5bb4-45da-9a76-89953d9ea450/* .
  552  cp s3://idc-open-data/c7760a15-586b-4480-960a-288a839d2251/* .
  553  cp s3://idc-open-data/17b07f6f-debe-4be7-b30a-4abef35b3cd8/* .
  554  cp s3://idc-open-data/514bd5b7-274a-4d07-ac82-827412bc616f/* .
  555  cp s3://idc-open-data/58881853-b8e9-454f-bfbd-4f27eb5a261d/* .
  556  cp s3://idc-open-data/16580855-88a2-4be3-8566-9b6008ea103c/* .
  557  cp s3://idc-open-data/2ac05b90-0921-401b-b665-0f9c711ef22c/* .
  558  cp s3://idc-open-data/3726e1de-4bb5-4af7-abe5-ee1d5aca227f/* .
  559  cp s3://idc-open-data/5d409385-d3e7-48a9-ae50-150b39e834da/* .
  560  cp s3://idc-open-data/145c2668-7d2f-4d7e-b1c7-2cf2462bef60/* .
  561  cp s3://idc-open-data/94755b62-0f88-4aa8-82ec-2d6d5cb8dbc7/* .
  562  cp s3://idc-open-data/a32dc650-7d9f-455b-b388-e7263faea36c/* .
  563  cp s3://idc-open-data/7bdba0aa-4581-4118-aa40-63afeee4b11f/* .
  564  cp s3://idc-open-data/ccf0beee-3d04-4ce3-8a3a-c000192d7fcd/* .
  565  cp s3://idc-open-data/7641ccd9-fb84-42f2-8597-d3b3fd26dbad/* .
  566  history

**Your System**
 - OS: Mac OS terminal with S5cmd installed 

Output error :

gundulurus-Air:work gundlurupoojitha$ s5cmd --no-sign-request --endpoint-url https://s3.amazonaws.com run file_manifest_aws.s5cmd
cp s3://idc-open-data/56f8119f-5940-48c1-96ee-8d445dc0b5fd/* .
cp s3://idc-open-data/9a5382ad-338a-451f-aa6a-080122dd2f00/* .
cp s3://idc-open-data/4ddb390d-03e7-4f41-8bda-6c8e1685393c/* .
cp s3://idc-open-data/95a776b1-8b86-48a4-8052-604f5999f1dc/* .
cp s3://idc-open-data/effbff9b-ade5-4dbb-94cc-c4cdbcf3b4ec/* .
cp s3://idc-open-data/d4066bb5-662c-43bd-b535-3852e681f7e4/* .
cp s3://idc-open-data/108de45b-c75b-4333-8e08-74a175990de7/* .
cp s3://idc-open-data/30cdc243-6fc5-4896-b1db-1849a7d8e538/* .
cp s3://idc-open-data/822b015d-361b-492a-851d-4db38517f471/* .
cp s3://idc-open-data/a116340f-35c2-4bc4-9de9-5a74bb5cf83f/* .
cp s3://idc-open-data/a149f373-d72b-42a9-80fe-569801e1ce49/* .
cp s3://idc-open-data/5f302398-fbde-469e-ac8d-75c92f35323e/* .
cp s3://idc-open-data/cc984c73-c55e-47ec-8ad1-235d22633eb9/* .
cp s3://idc-open-data/11748500-4189-4598-85a9-a401ee6af8ad/* .
cp s3://idc-open-data/b9cf8e7a-2505-4137-9ae3-f8d0cf756c13/* .
cp s3://idc-open-data/af18f5e4-f010-4b23-9be7-7c9f1aaa21a5/* .
ERROR "cp s3://idc-open-data/9a5382ad-338a-451f-aa6a-080122dd2f00/* .": no object found
ERROR "cp s3://idc-open-data/effbff9b-ade5-4dbb-94cc-c4cdbcf3b4ec/* .": no object found
ERROR "cp s3://idc-open-data/4ddb390d-03e7-4f41-8bda-6c8e1685393c/* .": no object found
ERROR "cp s3://idc-open-data/56f8119f-5940-48c1-96ee-8d445dc0b5fd/* .": no object found
ERROR "cp s3://idc-open-data/95a776b1-8b86-48a4-8052-604f5999f1dc/* .": no object found
ERROR "cp s3://idc-open-data/30cdc243-6fc5-4896-b1db-1849a7d8e538/* .": no object found
ERROR "cp s3://idc-open-data/7641ccd9-fb84-42f2-8597-d3b3fd26dbad/* .": no object found
ERROR "cp s3://idc-open-data/108de45b-c75b-4333-8e08-74a175990de7/* .": no object found
ERROR "cp s3://idc-open-data/16580855-88a2-4be3-8566-9b6008ea103c/* .": no object found
ERROR "cp s3://idc-open-data/3726e1de-4bb5-4af7-abe5-ee1d5aca227f/* .": no object found
ERROR "cp s3://idc-open-data/145c2668-7d2f-4d7e-b1c7-2cf2462bef60/* .": no object found
ERROR "cp s3://idc-open-data/56313377-5bb4-45da-9a76-89953d9ea450/* .": no object found
ERROR "cp s3://idc-open-data/cc984c73-c55e-47ec-8ad1-235d22633eb9/* .": no object found
ERROR "cp s3://idc-open-data/237eaf33-4162-4a9e-8212-7f16d697cbf6/* .": no object found
ERROR "cp s3://idc-open-data/2f67b46d-3719-4038-971c-eb483fc415c4/* .": no object found
ERROR "cp s3://idc-open-data/7bdba0aa-4581-4118-aa40-63afeee4b11f/* .": no object found
ERROR "cp s3://idc-open-data/779e7a2a-9769-49b3-a7e9-203a405009e5/* .": no object found
ERROR "cp s3://idc-open-data/822b015d-361b-492a-851d-4db38517f471/* .": no object found
ERROR "cp s3://idc-open-data/ad792585-87c3-4594-80f5-65f5d0192f7e/* .": no object found
ERROR "cp s3://idc-open-data/d4066bb5-662c-43bd-b535-3852e681f7e4/* .": no object found
ERROR "cp s3://idc-open-data/a32dc650-7d9f-455b-b388-e7263faea36c/* .": no object found
ERROR "cp s3://idc-open-data/94755b62-0f88-4aa8-82ec-2d6d5cb8dbc7/* .": no object found
ERROR "cp s3://idc-open-data/17b07f6f-debe-4be7-b30a-4abef35b3cd8/* .": no object found
ERROR "cp s3://idc-open-data/58881853-b8e9-454f-bfbd-4f27eb5a261d/* .": no object found
ERROR "cp s3://idc-open-data/a116340f-35c2-4bc4-9de9-5a74bb5cf83f/* .": no object found
ERROR "cp s3://idc-open-data/c7760a15-586b-4480-960a-288a839d2251/* .": no object found
ERROR "cp s3://idc-open-data/a149f373-d72b-42a9-80fe-569801e1ce49/* .": no object found
ERROR "cp s3://idc-open-data/2ac05b90-0921-401b-b665-0f9c711ef22c/* .": no object found
ERROR "cp s3://idc-open-data/5d409385-d3e7-48a9-ae50-150b39e834da/* .": no object found
ERROR "cp s3://idc-open-data/088360b3-44f6-4c27-b3c7-7ac82527aeb6/* .": no object found
ERROR "cp s3://idc-open-data/514bd5b7-274a-4d07-ac82-827412bc616f/* .": no object found
ERROR "cp s3://idc-open-data/af18f5e4-f010-4b23-9be7-7c9f1aaa21a5/* .": no object found
ERROR "cp s3://idc-open-data/11748500-4189-4598-85a9-a401ee6af8ad/* .": no object found
ERROR "cp s3://idc-open-data/ccf0beee-3d04-4ce3-8a3a-c000192d7fcd/* .": no object found
ERROR "cp s3://idc-open-data/57fc9942-e85c-4986-a262-a7ddfcd704aa/* .": no object found
ERROR "cp s3://idc-open-data/4aaf9181-fb6a-4a4c-bf49-d1eb9ed4a385/* .": no object found
ERROR "cp s3://idc-open-data/b9cf8e7a-2505-4137-9ae3-f8d0cf756c13/* .": no object found
ERROR "cp s3://idc-open-data/752cae1f-9bc5-494e-9859-4bbbb6b9f85d/* .": no object found
ERROR "cp s3://idc-open-data/5f302398-fbde-469e-ac8d-75c92f35323e/* .": no object found
gundulurus-Air:work gundlurupoojitha$ cp s3://idc-open-data/56f8119f-5940-48c1-96ee-8d445dc0b5fd/* .
cp: s3://idc-open-data/56f8119f-5940-48c1-96ee-8d445dc0b5fd/*: No such file or directory
gundulurus-Air:work gundlurupoojitha$ cp s3://idc-open-data/9a5382ad-338a-451f-aa6a-080122dd2f00/* .
cp: s3://idc-open-data/9a5382ad-338a-451f-aa6a-080122dd2f00/*: No such file or directory
gundulurus-Air:work gundlurupoojitha$ cp s3://idc-open-data/4ddb390d-03e7-4f41-8bda-6c8e1685393c/* .
cp: s3://idc-open-data/4ddb390d-03e7-4f41-8bda-6c8e1685393c/*: No such file or directory
gundulurus-Air:work gundlurupoojitha$ cp s3://idc-open-data/95a776b1-8b86-48a4-8052-604f5999f1dc/* .
cp: s3://idc-open-data/95a776b1-8b86-48a4-8052-604f5999f1dc/*: No such file or directory
gundulurus-Air:work gundlurupoojitha$ cp s3://idc-open-data/effbff9b-ade5-4dbb-94cc-c4cdbcf3b4ec/* .
cp: s3://idc-open-data/effbff9b-ade5-4dbb-94cc-c4cdbcf3b4ec/*: No such file or directory
gundulurus-Air:work gundlurupoojitha$ cp s3://idc-open-data/d4066bb5-662c-43bd-b535-3852e681f7e4/* .
cp: s3://idc-open-data/d4066bb5-662c-43bd-b535-3852e681f7e4/*: No such file or directory
gundulurus-Air:work gundlurupoojitha$ cp s3://idc-open-data/108de45b-c75b-4333-8e08-74a175990de7/* .
cp: s3://idc-open-data/108de45b-c75b-4333-8e08-74a175990de7/*: No such file or directory
gundulurus-Air:work gundlurupoojitha$ cp s3://idc-open-data/30cdc243-6fc5-4896-b1db-1849a7d8e538/* .
cp: s3://idc-open-data/30cdc243-6fc5-4896-b1db-1849a7d8e538/*: No such file or directory
gundulurus-Air:work gundlurupoojitha$ cp s3://idc-open-data/822b015d-361b-492a-851d-4db38517f471/* .
cp: s3://idc-open-data/822b015d-361b-492a-851d-4db38517f471/*: No such file or directory
gundulurus-Air:work gundlurupoojitha$ cp s3://idc-open-data/a116340f-35c2-4bc4-9de9-5a74bb5cf83f/* .
cp: s3://idc-open-data/a116340f-35c2-4bc4-9de9-5a74bb5cf83f/*: No such file or directory
gundulurus-Air:work gundlurupoojitha$ cp s3://idc-open-data/a149f373-d72b-42a9-80fe-569801e1ce49/* .
cp: s3://idc-open-data/a149f373-d72b-42a9-80fe-569801e1ce49/*: No such file or directory
gundulurus-Air:work gundlurupoojitha$ cp s3://idc-open-data/5f302398-fbde-469e-ac8d-75c92f35323e/* .
cp: s3://idc-open-data/5f302398-fbde-469e-ac8d-75c92f35323e/*: No such file or directory
gundulurus-Air:work gundlurupoojitha$ cp s3://idc-open-data/cc984c73-c55e-47ec-8ad1-235d22633eb9/* .
cp: s3://idc-open-data/cc984c73-c55e-47ec-8ad1-235d22633eb9/*: No such file or directory
gundulurus-Air:work gundlurupoojitha$ cp s3://idc-open-data/11748500-4189-4598-85a9-a401ee6af8ad/* .
cp: s3://idc-open-data/11748500-4189-4598-85a9-a401ee6af8ad/*: No such file or directory
gundulurus-Air:work gundlurupoojitha$ cp s3://idc-open-data/b9cf8e7a-2505-4137-9ae3-f8d0cf756c13/* .
cp: s3://idc-open-data/b9cf8e7a-2505-4137-9ae3-f8d0cf756c13/*: No such file or directory
gundulurus-Air:work gundlurupoojitha$ cp s3://idc-open-data/af18f5e4-f010-4b23-9be7-7c9f1aaa21a5/* .
cp s3://idc-open-data/4aaf9181-fb6a-4a4c-bf49-d1eb9ed4a385/* .
cp s3://idc-open-data/237eaf33-4162-4a9e-8212-7f16d697cbf6/* .
cp s3://idc-open-data/779e7a2a-9769-49b3-a7e9-203a405009e5/* .
cp s3://idc-open-data/2f67b46d-3719-4038-971c-eb483fc415c4/* .
cp s3://idc-open-data/752cae1f-9bc5-494e-9859-4bbbb6b9f85d/* .
cp s3://idc-open-data/57fc9942-e85c-4986-a262-a7ddfcd704aa/* .
cp s3://idc-open-data/088360b3-44f6-4c27-b3c7-7ac82527aeb6/* .
cp s3://idc-open-data/ad792585-87c3-4594-80f5-65f5d0192f7e/* .
cp s3://idc-open-data/56313377-5bb4-45da-9a76-89953d9ea450/* .
cp s3://idc-open-data/c7760a15-586b-4480-960a-288a839d2251/* .
cp s3://idc-open-data/17b07f6f-debe-4be7-b30a-4abef35b3cd8/* .
cp s3://idc-open-data/514bd5b7-274a-4d07-ac82-827412bc616f/* .
cp s3://idc-open-data/58881853-b8e9-454f-bfbd-4f27eb5a261d/* .
cp s3://idc-open-data/16580855-88a2-4be3-8566-9b6008ea103c/* .
cp s3://idc-open-data/2ac05b90-0921-401b-b665-0f9c711ef22c/* .
cp s3://idc-open-data/3726e1de-4bb5-4af7-abe5-ee1d5aca227f/* .
cp: s3://idc-open-data/af18f5e4-f010-4b23-9be7-7c9f1aaa21a5/*: No such file or directory
gundulurus-Air:work gundlurupoojitha$ cp s3://idc-open-data/4aaf9181-fb6a-4a4c-bf49-d1eb9ed4a385/* .
cp: s3://idc-open-data/4aaf9181-fb6a-4a4c-bf49-d1eb9ed4a385/*: No such file or directory
gundulurus-Air:work gundlurupoojitha$ cp s3://idc-open-data/237eaf33-4162-4a9e-8212-7f16d697cbf6/* .
cp: s3://idc-open-data/237eaf33-4162-4a9e-8212-7f16d697cbf6/*: No such file or directory
gundulurus-Air:work gundlurupoojitha$ cp s3://idc-open-data/779e7a2a-9769-49b3-a7e9-203a405009e5/* .
cp: s3://idc-open-data/779e7a2a-9769-49b3-a7e9-203a405009e5/*: No such file or directory
gundulurus-Air:work gundlurupoojitha$ cp s3://idc-open-data/2f67b46d-3719-4038-971c-eb483fc415c4/* .
cp: s3://idc-open-data/2f67b46d-3719-4038-971c-eb483fc415c4/*: No such file or directory
gundulurus-Air:work gundlurupoojitha$ cp s3://idc-open-data/752cae1f-9bc5-494e-9859-4bbbb6b9f85d/* .
cp: s3://idc-open-data/752cae1f-9bc5-494e-9859-4bbbb6b9f85d/*: No such file or directory
gundulurus-Air:work gundlurupoojitha$ cp s3://idc-open-data/57fc9942-e85c-4986-a262-a7ddfcd704aa/* .
cp: s3://idc-open-data/57fc9942-e85c-4986-a262-a7ddfcd704aa/*: No such file or directory
gundulurus-Air:work gundlurupoojitha$ cp s3://idc-open-data/088360b3-44f6-4c27-b3c7-7ac82527aeb6/* .
cp: s3://idc-open-data/088360b3-44f6-4c27-b3c7-7ac82527aeb6/*: No such file or directory
gundulurus-Air:work gundlurupoojitha$ cp s3://idc-open-data/ad792585-87c3-4594-80f5-65f5d0192f7e/* .
cp: s3://idc-open-data/ad792585-87c3-4594-80f5-65f5d0192f7e/*: No such file or directory
gundulurus-Air:work gundlurupoojitha$ cp s3://idc-open-data/56313377-5bb4-45da-9a76-89953d9ea450/* .
cp: s3://idc-open-data/56313377-5bb4-45da-9a76-89953d9ea450/*: No such file or directory
gundulurus-Air:work gundlurupoojitha$ cp s3://idc-open-data/c7760a15-586b-4480-960a-288a839d2251/* .
cp: s3://idc-open-data/c7760a15-586b-4480-960a-288a839d2251/*: No such file or directory
gundulurus-Air:work gundlurupoojitha$ cp s3://idc-open-data/17b07f6f-debe-4be7-b30a-4abef35b3cd8/* .
cp: s3://idc-open-data/17b07f6f-debe-4be7-b30a-4abef35b3cd8/*: No such file or directory
gundulurus-Air:work gundlurupoojitha$ cp s3://idc-open-data/514bd5b7-274a-4d07-ac82-827412bc616f/* .
cp: s3://idc-open-data/514bd5b7-274a-4d07-ac82-827412bc616f/*: No such file or directory
gundulurus-Air:work gundlurupoojitha$ cp s3://idc-open-data/58881853-b8e9-454f-bfbd-4f27eb5a261d/* .
cp: s3://idc-open-data/58881853-b8e9-454f-bfbd-4f27eb5a261d/*: No such file or directory
gundulurus-Air:work gundlurupoojitha$ cp s3://idc-open-data/16580855-88a2-4be3-8566-9b6008ea103c/* .
cp: s3://idc-open-data/16580855-88a2-4be3-8566-9b6008ea103c/*: No such file or directory
gundulurus-Air:work gundlurupoojitha$ cp s3://idc-open-data/2ac05b90-0921-401b-b665-0f9c711ef22c/* .
cp s3://idc-open-data/3726e1de-4bb5-4af7-abe5-ee1d5aca227f/* .
cp s3://idc-open-data/5d409385-d3e7-48a9-ae50-150b39e834da/* .
cp s3://idc-open-data/145c2668-7d2f-4d7e-b1c7-2cf2462bef60/* .
cp s3://idc-open-data/94755b62-0f88-4aa8-82ec-2d6d5cb8dbc7/* .
cp s3://idc-open-data/a32dc650-7d9f-455b-b388-e7263faea36c/* .
cp s3://idc-open-data/7bdba0aa-4581-4118-aa40-63afeee4b11f/* .
cp s3://idc-open-data/ccf0beee-3d04-4ce3-8a3a-c000192d7fcd/* .
cp s3://idc-open-data/7641ccd9-fb84-42f2-8597-d3b3fd26dbad/* .
cp: s3://idc-open-data/2ac05b90-0921-401b-b665-0f9c711ef22c/*: No such file or directory
gundulurus-Air:work gundlurupoojitha$ cp s3://idc-open-data/3726e1de-4bb5-4af7-abe5-ee1d5aca227f/* .
cp: s3://idc-open-data/3726e1de-4bb5-4af7-abe5-ee1d5aca227f/*: No such file or directory
gundulurus-Air:work gundlurupoojitha$ cp s3://idc-open-data/5d409385-d3e7-48a9-ae50-150b39e834da/* .
cp: s3://idc-open-data/5d409385-d3e7-48a9-ae50-150b39e834da/*: No such file or directory
gundulurus-Air:work gundlurupoojitha$ cp s3://idc-open-data/145c2668-7d2f-4d7e-b1c7-2cf2462bef60/* .
cp: s3://idc-open-data/145c2668-7d2f-4d7e-b1c7-2cf2462bef60/*: No such file or directory
gundulurus-Air:work gundlurupoojitha$ cp s3://idc-open-data/94755b62-0f88-4aa8-82ec-2d6d5cb8dbc7/* .
cp: s3://idc-open-data/94755b62-0f88-4aa8-82ec-2d6d5cb8dbc7/*: No such file or directory
gundulurus-Air:work gundlurupoojitha$ cp s3://idc-open-data/a32dc650-7d9f-455b-b388-e7263faea36c/* .
cp: s3://idc-open-data/a32dc650-7d9f-455b-b388-e7263faea36c/*: No such file or directory
gundulurus-Air:work gundlurupoojitha$ cp s3://idc-open-data/7bdba0aa-4581-4118-aa40-63afeee4b11f/* .
cp: s3://idc-open-data/7bdba0aa-4581-4118-aa40-63afeee4b11f/*: No such file or directory
gundulurus-Air:work gundlurupoojitha$ cp s3://idc-open-data/ccf0beee-3d04-4ce3-8a3a-c000192d7fcd/* .
cp: s3://idc-open-data/ccf0beee-3d04-4ce3-8a3a-c000192d7fcd/*: No such file or directory
gundulurus-Air:work gundlurupoojitha$ cp s3://idc-open-data/7641ccd9-fb84-42f2-8597-d3b3fd26dbad/* .
cp: s3://idc-open-data/7641ccd9-fb84-42f2-8597-d3b3fd26dbad/*: No such file or directory
gundulurus-Air:work gundlurupoojitha$

**Comment by G-White-ISB** [comment]
How was this cohort defined? I haven't added the new (v15) collections to AWS yet? I'll add them over the next couple of days.

**Comment by s-paquette** [comment]
@pgundluru This is not a WebApp issue so I am going to close the ticket; items related to Amazon should be made in the IDC-Project-Management ticket set.

**Comment by pgundluru** [comment]
This issue is resolved and able to download files using s5cmd
