### ISSUE TITLE
Revise project/collection selection filters

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#121]
Currently, we have a number of collections under TCGA, and "check/uncheck all" applies only to the items under TCGA.

![image](https://user-images.githubusercontent.com/313942/84516107-51c51400-ac9b-11ea-8cfa-dcc04d58a74e.png)

Suggestion for the revised design:

1. Add separate section listing all projects (e.g., TCGA, CPTAC, )
2. Add separate section listing all collections (as in TCIA)

![image](https://user-images.githubusercontent.com/313942/84516693-268ef480-ac9c-11ea-9165-c5919c1d0f4f.png)

Re: https://github.com/ImagingDataCommons/IDC-WebApp/issues/112#issuecomment-642670718

**Comment by fedorov** [comment]
I think there is an existing issue with the three-state checkbox - I will look for it.

**Comment by G-White-ISB** [comment]
three-state box added in next commit
