### ISSUE TITLE
Cohort ID is not sorting properly on the Cohort list page

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#1210]
**General description**
When a user saves a cohort the assumption is that they will be arranged in the order created or latest version in the cohorts page but currently there is an UI bug that places them randomly. 

**Steps to reproduce the behavior**

https://github.com/ImagingDataCommons/IDC-WebApp/assets/85526819/2e14cc3c-b803-428b-93ad-da62a17667ae

**Your System**
W10 - Chrome browser and Mac Safari

**Comment by s-paquette** [comment]
@pgundluru Did you have any console errors? I can't seem to reproduce this. Also can you try an empty-cache-hard-reload and double-check?

**Comment by s-paquette** [comment]
Okay with some fiddling around it looks like the actual bug is data version isn't sorting right. (@pgundluru I'm not sure what you meant in Slack by 'not showing them all', I do see all my cohorts, just data version is no longer sorting properly, so that I need to look at).

**Comment by pgundluru** [comment]
This issue has been fixed by @s-paquette and is now working as expected

![image](https://github.com/ImagingDataCommons/IDC-WebApp/assets/85526819/fcf31034-0437-43ac-a59a-ed9d48983035)
