### ISSUE TITLE
In prod and test tier, When head and neck are selected in the home page, The filter definition is not selected in the explore page 

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#1218]
This issue/bug was noticed in the prod tier when a user selects head and neck in the body part in the home page then the assumption is that they should populate in the filter definition. Currently the filter definition is empty with no errors in the console 

Same issue in test tier but with the below error 

![image](https://github.com/ImagingDataCommons/IDC-WebApp/assets/85526819/84dcae99-e487-4cd3-b44c-b0cbaaf70f2a)

**Comment by s-paquette** [comment]
Problem is the 'head-and-neck' value is now gone from the tcia_tumorLocation set. As a result there was no UI element to auto-check on the Explorer page. Fix going in shortly.
