### ISSUE TITLE
Add attributes to the pivot table

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#1219]
This is needed since only items in the pivot are accessible via IDC API, and this attribute would be needed to populate DICOM browser interface in Slicer IDC extension. Specifically, it makes sense to add the following:
* PatientSex
* SeriesDate

**Comment by bcli4d** [comment]
@s-paquette, Andrey asked that the pivot also include collection_species and collection_tumorLocation. These are duplicate columns in dicom_all of tcia_species and tcia_tumorLocation.

**Comment by s-paquette** [comment]
@bcli4d @fedorov I'm confused, do we want to rename tcia_tumorLocation and tcia_species to collection_ ? Or is this request for something else?

**Comment by bcli4d** [comment]
I think the question is whether to replace tcia_species and tcia_tumorLocation with collection_species and collection_tumorLocation in the pivot, or just add them as duplicates, as they are in dicom_all. Guessing the former, but it's Andrey's call.

**Comment by s-paquette** [comment]
Add collection_, inactivate tcia_

**Comment by fedorov** [comment]
Considering the situation below, let's add PatientSex and SeriesDate to pivot/webapp, but not add it to the UI of the webapp. Let's also add PatientAge.

<img width="276" alt="image" src="https://github.com/ImagingDataCommons/IDC-WebApp/assets/313942/b3093db8-c03b-4aac-9be2-7297309c0fa7">

**Comment by s-paquette** [comment]
@fedorov @bcli4d this ticket appears to have morphed into 2 different requests. I am now seeing something about adding PatientSex, SeriesDate, and PatientAge, but also something about renaming some of the columns.

I'd prefer we separate these, because the ones we want to rename are WebApp UI level attributes. Those have a special process. Adding things to the pivot without putting them into the WebApp is a simple one-off process. If we want to rename the tcia_ columns, I'd request that a new ticket be made explicitly for handling the retirement of tcia_ and replacement with collection_

**Comment by s-paquette** [comment]
@fedorov Note that PatientAge is already in the pivot as of v15.

**Comment by s-paquette** [comment]
@fedorov @pgundluru This is now available to be tested in `idc-pdp-staging.idc_v16`

**Comment by pgundluru** [comment]
@fedorov Can you please let me know if my test is correct ? 

Below is what i did to verify if below are available in Pivot table in V16 public data  - patientAge, PatientSex, SeriesDate

![image](https://github.com/ImagingDataCommons/IDC-WebApp/assets/85526819/3c2ecd01-7fef-4a34-9ee0-74d7b73af1ed)

**Comment by fedorov** [comment]
Looks fine to me.

**Comment by bcli4d** [comment]
Reopening this. Though patientAge, patientSex, patientSize and patientWeight are in dicom_pivot, collex_metadata_utils/get_bq_metadata() does not recognize them as fields or filters. Can we please address that? Thanks.

**Comment by s-paquette** [comment]
@bcli4d As stated above adding these to the WebApp as attributes is a second issue which I'm not sure if it was ever made or opened. If we could make a separate ticket I'd prefer that (since this was already placed in a release and closed).
