### ISSUE TITLE
AWS Export Manifest Command has incorrect syntax

### ISSUE THREAD

**Issue by G-White-ISB** [ImagingDataCommons/IDC-WebApp#1222]
In the test portal the download command from aws is currently :

s5cmd --no-sign-request --endpoint-url https://storage.googleapis.com run cohort_name_aws.s5cmd

The --endpoint-url argument is wrong. I think it should just be left off for aws downloads

**Comment by s-paquette** [comment]
@G-White-ISB This is actually a bug with it putting in the wrong --endpoint-url; for AWS it should be https://s3.amazonaws.com. Will that be okay or should I just drop endpoint-url?

**Comment by G-White-ISB** [comment]
Actually it probably is safer to  explicitly putting in the correct --endpoint-url.

**Comment by s-paquette** [comment]
Got it, fixing now.

**Comment by pgundluru** [comment]
Tested in prod after V15 release.
