### ISSUE TITLE
Notify users about leaving .gov when clicking URLs in the collection tooltips

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#1225]

**Comment by s-paquette** [comment]
The current format for URLs opening in another tab/window and giving the warning is:
- No `href` value in the anchor tag
- What would be the destination URL in `href` is under the `url` attribute of the anchor tag
- The anchor tag will need to have the following class on it: `class="external-link"`

If we also want to add the external link icon, the following needs to be added at the end of the anchor tag text: 
```
<i class="fa-solid fa-external-link external-link-icon" aria-hidden="true"></i>
```

**Comment by bcli4d** [comment]
@s-paquette 
I'm not following. Given this link:
`<a href="https://doi.org/10.7937/K9/TCIA.2015.ISOQTHKO" target="_blank">NaF PROSTATE</a> ` 
how should it be changed?
Thanks.

**Comment by s-paquette** [comment]
@bcli4d 

`<a href="https://doi.org/10.7937/K9/TCIA.2015.ISOQTHKO" target="_blank">NaF PROSTATE</a> `
would become
`<a class="external-link" href="" url="https://doi.org/10.7937/K9/TCIA.2015.ISOQTHKO" data-toggle="modal" data-target="#external-web-warning">NaF PROSTATE <i class="fa-solid fa-external-link external-link-icon" aria-hidden="true"></i></a> `

**Comment by bcli4d** [comment]
Do we need to apply this to all links in each description?

**Comment by s-paquette** [comment]
@bcli4d Anything not ending in .gov--.gov links don't need this treatment.

**Comment by pieper** [comment]
Are we allowed to have a "dont' ask me again" checkbox on this dialog?  I, and probably others, would appreciate it : )

**Comment by s-paquette** [comment]
@pieper Unfortunately no, .gov requirement.

**Comment by bcli4d** [comment]
@s-paquette In your example:
`<a class="external-link" href="" url="https://doi.org/10.7937/K9/TCIA.2015.ISOQTHKO" data-toggle="modal" data-target="#external-web-warning">NaF PROSTATE <i class="fa-solid fa-external-link external-link-icon" aria-hidden="true"></i></a> `
should that "<i" be "<i>"?

**Comment by s-paquette** [comment]
@bcli4d No, the <i></i> tag is used by Font Awesome to drop in an external link icon and should remain as you see there.

**Comment by bcli4d** [comment]
I think you misunderstood. Your example has "<i" ...no closing ">". I was trying to verify that it should be "<i>"

**Comment by s-paquette** [comment]
@bcli4d ...I see a closing `>` on my screen? I'm not sure what you mean.
 
![image](https://github.com/ImagingDataCommons/IDC-WebApp/assets/8442808/73734692-1116-4348-b7ab-9505d72b4e73)

**Comment by s-paquette** [comment]
@pgundluru this is ready for testing

**Comment by pgundluru** [comment]
Able to see the external link for all collections tooltips
