### ISSUE TITLE
Feature request to add data version and disk size to GCP file manifests similar to AWS file manifest when a cohort is selected 

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#1226]
This was discussed in the weekly meeting on 07/06/2023 and decided that since AWS file manifest currently has the data version and disk size and the GCP file manifest should have the same as well. This is for file manifests and not the saved cohorts.

**Comment by s-paquette** [comment]
Just to note this is really a bug, as the feature is already supported, it's just not functioning right atm. Investigating for Release 38.

**Comment by s-paquette** [comment]
@pgundluru I can't seem to replicate this now. If I click the include header fields checkbox for GCS, I see the total disk size. Can you double-check that this is still a bug for you?

**Comment by s-paquette** [comment]
@pgundluru Is this still happening?

**Comment by pgundluru** [comment]
@s-paquette I am able to verify on test tier that once a user selects AWS or GCP manifest and selects the header files checkbox then the disk size and data version show up in the downloaded file in the format like example below. 

Same behavior in production as well 

# IDC Data Version(s): IDC Data Release Version 16.0 2023-09-05
# Total manifest size on disk: 3.06 TB

**Comment by pgundluru** [comment]
Closing this ticket as testing passed in V16
