### ISSUE TITLE
Improve OHIF Viewer deployment branding with IDC logo

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#123]
As requested by Keyvan during the initial MVP demo.

Probably should wait to hear about https://github.com/OHIF/Viewers/issues/1789 before trying to fork and customize OHIF Viewer ourselves.

**Comment by dannyrb** [comment]
@fedorov, you can use a custom SVG for your logo, configured via the app's config. There is some information in a recent PR that improved/fixed how this is done:

https://github.com/OHIF/Viewers/pull/1659

**Comment by pieper** [comment]
I remember the whitelisting discussion now, but didn't realize it was a simple config issue.  Thanks @dannyrb !

So I made a new version of the svg with a black background and less blank space around it and added that to the idc logo folder on google drive.  (I'll note that the svg files are a bit of a pain to work with for various reasons to do with transforms, but if somebody wants to they could adjust the size of the logo further).

https://drive.google.com/drive/folders/1OZeUZbHyYSQUcg1XM201fDc4j0I0Q1ur

Also updated https://idc-sandbox-000.firebaseapp.com/

If we all like it @s-paquette or @G-White-ISB can update the web app to match.

Add `idc-black.svg` to the toplevel and this to the app-config.js
```
  whiteLabeling: {
  /* Optional: Should return a React component to be rendered in the "Logo" section of the application's Top Navigation bar */
    createLogoComponentFn: function(React) {
      return React.createElement('a', {
        target: '_self',
        rel: 'noopener noreferrer',
        className: 'header-brand',
        href: '/',
        style: {
          display: 'block',
          textIndent: '-9999px',
          background: 'url(/idc-black.svg)',
          backgroundSize: 'contain',
          backgroundRepeat: 'no-repeat',
          width: '200px',
        },
      });
    },
  },
```



![image](https://user-images.githubusercontent.com/126077/84575886-95447e80-ad7e-11ea-8747-abf875b0e6c7.png)

**Comment by G-White-ISB** [comment]
Thanks Steve - will add it with my next code commit

**Comment by fedorov** [comment]
It's not super critical to do the update now - most important we can do it. For the MVP we will most likely need to use NCI branding, but for the sandbox IDC consortium logo is most appropriate. 

We also probably should test that official NCI logo works well (see those here: https://drive.google.com/drive/folders/1KnH0sfGX4odmHYKyG2uKCvYyrSfn3-K5). But please do not add it yet to the MVP, we need to check with NCI when we can start actually using it.

**Comment by madelyngreyes** [comment]
The logo is present but, there is still a formatting issue. 

new logo
![Screen Shot 2020-07-08 at 11 01 02 AM](https://user-images.githubusercontent.com/16824894/86934976-55b54c00-c10a-11ea-9edd-c23f7cf3c3a0.png)
 
old logo 
![Screen Shot 2020-07-08 at 11 00 54 AM](https://user-images.githubusercontent.com/16824894/86935024-61087780-c10a-11ea-9ab2-dbdb9485c1d4.png)

**Comment by pieper** [comment]
Yes, it was hard to resize the logo, so maybe we can get a designer to make some more variants that preserve the aspect ratio.

**Comment by G-White-ISB** [comment]
Closing for now. Maybe address after MVP
