### ISSUE TITLE
Remove CRDC bar on top of the portal

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#1230]
I assume we control this, so we can remove this and save space for more interesting content.

<img width="692" alt="image" src="https://github.com/ImagingDataCommons/IDC-WebApp/assets/313942/ede9fc46-7cfe-4e7c-a71c-a4267e342c50">

**Comment by s-paquette** [comment]
We control the code and I can easily remove it.

**Comment by pgundluru** [comment]
NCRDC Bar + Link is no longer visible at the top of the front page of the Webapp 

![image](https://github.com/ImagingDataCommons/IDC-WebApp/assets/85526819/fbef5870-1a59-4b8b-b77b-7b254883d418)
