### ISSUE TITLE
"Did not Connect" error (SSL cert issue) on FireFox browser when going to IDC Prod website 

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#1231]
This issue was initially identified by Andrey on FF. The summary of the issue is that there is an SSL cert error when a user goes to portal (via both portal.imaging or imaging. URL) on FF 

This was hard to reproduce on existing FF browsers (I had to download a new version of FF on a machine to reproduce this error) 

![screen_shot_2023-07-14_at_1 19 18_pm_720](https://github.com/ImagingDataCommons/IDC-WebApp/assets/85526819/2f67622d-9677-4122-b61a-c0531e490153)
https://files.slack.com/files-pri/TER7HBP44-F05H4KDV6AE/download/certificate_for_.imaging.datacommons.cancer.gov.html?origin_team=TER7HBP44

**Comment by wlongabaugh** [comment]
Clearing site data from Chrome makes the problem crop up. It appears to be a cached permanent redirect that is a problem?
