### ISSUE TITLE
Expand the list of analysis results by defaul

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#1234]
so that it looks like below

<img width="442" alt="image" src="https://github.com/ImagingDataCommons/IDC-WebApp/assets/313942/6115b514-bc31-480e-ad1d-1a590126d357">

**Comment by pgundluru** [comment]
Analysis results are now showing up as expanded by default in test tier, This has been tested in W10 chrome, Edge and MacOS Safari and FF

![image](https://github.com/ImagingDataCommons/IDC-WebApp/assets/85526819/a4fe59e9-0cb8-4865-8b71-7776ab3a6dfa)
