### ISSUE TITLE
Augment tooltip with the UIDs for study/series table with a clipboard copy "button"

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#1235]
We should probably make the text in the tooltip smaller text size (same as in the portal table?), and also add a button next to the UID in the table (both for the study and series UIDs) to copy the text.

<img width="854" alt="image" src="https://github.com/ImagingDataCommons/IDC-WebApp/assets/313942/39b91221-c023-4475-876e-9b205623bfd8">

**Comment by s-paquette** [comment]
Main take away in messing with this: if a tooltip is part of a table it will fail to function correctly in event delegation unless it's set to `interactive: true`. Unclear on the reason for this but it's not a big deal to do so.

**Comment by s-paquette** [comment]
@fedorov This is now available on dev if you want to see how it looks/behaves

**Comment by fedorov** [comment]
I would remove the parentheses around the clipboard icon.

<img width="372" alt="image" src="https://github.com/ImagingDataCommons/IDC-WebApp/assets/313942/fe8113f4-50f5-4c15-8e7e-4aeff923059c">

**Comment by pgundluru** [comment]
![image](https://github.com/ImagingDataCommons/IDC-WebApp/assets/85526819/568f4982-9432-43f4-ae08-5b9ff79c65f1)
