### ISSUE TITLE
Provide  'mini-manifest' in Series and Study Tables

### ISSUE THREAD

**Issue by G-White-ISB** [ImagingDataCommons/IDC-WebApp#1239]
Provide a buttons in the series  and study tables that generate the s5cmd command to download the respective image files. This is in response to the issue https://github.com/ImagingDataCommons/IDC-WebApp/issues/1186.

**Comment by fedorov** [comment]
Can we please replace "Download series" with the download button symbol, as in GCS browser interface?

<img width="268" alt="image" src="https://github.com/ImagingDataCommons/IDC-WebApp/assets/313942/289d8da1-7cb5-4218-bdf5-7c5d16d14756">

**Comment by fedorov** [comment]
Same for the "Download" in the table column title. We have neither need nor space to spell it out.

**Comment by G-White-ISB** [comment]
Yes we can. I'm tempted to leave the header blank, and not create an impression that one could download everything by clicking the header

**Comment by fedorov** [comment]
> I'm tempted to leave the header blank

No objections on this one!

**Comment by s-paquette** [comment]
@G-White-ISB @fedorov The issue with the text and an icon is it begins to make the table very wide and that makes for display and spacing issues on smaller monitors. It would be better if we simply had an image icon with a tooltip or title text.

**Comment by fedorov** [comment]
> The issue with the text and an icon is it begins to make the table very wide and that makes for display and spacing issues on smaller monitors. It would be better if we simply had an image icon with a tooltip or title text.

As I mentioned above, I also think we should replace "Download" text with an icon, so we all seem to be in agreement here.

**Comment by bcli4d** [comment]
Looking at the new mini-manifest button in the dev portal...

- In both the study and series popups, clicking on the icon to copy the command does not give you a 'Copied!' feedback.

- The series mini-manifest pop-up says:
 'To download the images in this series, install s5cmd , then run the following command: ...'.
The study pop-up says the same thing. I think this could be confusing. I think it should say something like:
'To download the images in this series, install s5cmd , click on the Download s5cmd Button, then run the following command:...'

**Comment by pgundluru** [comment]
To add to Bills questions on the mini manifest - 

Study export and series export feature looks slightly different, there is only an option for the series to copy and run in s5cmd while study has the option to include header fields and download – is this intentional?

**Comment by fedorov** [comment]
TODO:
* adjust the text to say "download manifest and then run the command"
* when downloading manifest, message should be the same for study manifest as for the overall manifest ("To download images defined by this manifest, install s5cmd, download the manifest file and run the command below")
* remove the last line pointing to the instructions
<img width="654" alt="image" src="https://github.com/ImagingDataCommons/IDC-WebApp/assets/313942/5f6ba215-2b50-48e6-a810-acf64ebb1f0a">

**Comment by s-paquette** [comment]
@fedorov @pgundluru Ready for testing.

**Comment by pgundluru** [comment]
I am able to see the changes in test tier for the following 

1. Adjust the text to say "download manifest and then run the command" - updated in study level as intended 
2. When downloading manifest, message should be the same for study manifest as for the overall manifest ("To download images defined by this manifest, install s5cmd, download the manifest file and run the command below") - Able to view the message 
3. remove the last line pointing to the instructions - Removed
