### ISSUE TITLE
Clinical data selection should auto-select TCGA?

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#125]
Or maybe clinical data should be empty unless TCGA is selected?

In any case, current behavior is confusing. If I touch the age filter, and even if it set to 0-120, I have all of the collections other than TCGA blanked. I think we need to discuss how filters that apply only to a subset of data are exposed.

Also note that PatientAge and PatientSex, along with some other clinical metadata, is available in DICOM.

**Comment by fedorov** [comment]
Needs more discussion

**Comment by fedorov** [comment]
@wlongabaugh anything that selects "Related" that applies to TCGA only should auto-select TCGA.

@fedorov will need to make a new issue for the clinical data that lives in DICOM - for post-MVP

**Comment by madelyngreyes** [comment]
If you first filter option TCGA, then go to the Collections panel. Then if you select the collection e.g., tcga_brca the Filter Definition panel will still display all collection options. Is this expected behavior?

**Comment by G-White-ISB** [comment]
Hi Madelyn,

I'm not following. Maybe a screen shot would help. The filter definition
should match the checked attributes/collections exactly.
George

**Comment by madelyngreyes** [comment]
Apologies for the confusion, should a selection from the Collections panel reset the filter options in the Filter Definition panel is my question.  

Currently, if I select an option from the collections panel the filter definition panel doesn't seem to update.  If this is expected functionality that works for me.
![collection panel selection doesnt reflect in the filter definition panel](https://user-images.githubusercontent.com/16824894/91583120-bd279500-e91e-11ea-836b-c59e33412d4c.PNG)

**Comment by G-White-ISB** [comment]
You have a collection selected with the checkbox and it doesn't show in the
filter definition? I have not seen that. Highlighting a collection in the
collections table does not filter the collection but adds its studies to
the studies table.
George

**Comment by madelyngreyes** [comment]
No, I don't see that either. If highlighting a collection doesn't affect the Filter Definition panel then it's working as expected. Will close the ticket.

**Comment by G-White-ISB** [comment]
Well it's worth taking note as a possible source of confusion for the user.
George
