### ISSUE TITLE
use sliders to filter Quantitative data

### ISSUE THREAD

**Issue by G-White-ISB** [ImagingDataCommons/IDC-WebApp#126]
Use sliders in place of checkboxes for derived quantitative data

**Comment by G-White-ISB** [comment]
@fedorov is the 'None' attribute relevant for derived quantitative data? Will we want to filter on the 'None Available' value for a quantitative filter?

**Comment by fedorov** [comment]
If we can make it transparent and clear to the user, I do not have any issue with that. But we already have a lot of None's, and in many cases I cannot make sense of the number they show.

Another observation is that with this logic, one can say why don't we add "None Available" to every single facet? I.e., give me cohort that does NOT have MR images. I am not sure how useful that would be, but it will definitely make the UI a lot more complicated.

All in all, I would say for now let's not add features that do not exist in other data nodes, and focus on making sure the facets we already have work as expected, and we understand what is going on. Let's transition to slides, and then pick the next bug from the list we already have.

**Comment by fedorov** [comment]
Sliders have been added.
