### ISSUE TITLE
In Prod tier, counts in explore page are in ascending order 

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#1270]
This issue was identified by Andrey where the counts of analysis results and filters are appearing to be in ascending order. Suzanne has confirmed that this is not intentional and is a bug in test and prod currently.

![image](https://github.com/ImagingDataCommons/IDC-WebApp/assets/85526819/ab2d5677-8776-4bb4-967d-e3f15aae8936)

**Comment by G-White-ISB** [comment]
We just deployed a fix in both the test and production environments. Counts should appear in alpha or numeric order for all attribute as perscribed

**Comment by s-paquette** [comment]
@pgundluru Can you check and see if this is still an issue?
