### ISSUE TITLE
It is impossible to reach the hyperlinks in the collection tooltip

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#1277]
This is how it "works" in IDC:

![2023-09-05_18-00-38](https://github.com/ImagingDataCommons/IDC-WebApp/assets/313942/19ff0e15-a1df-470c-8b53-057211606241)

This is how it *works* in TCIA:

![2023-09-05_18-08-57](https://github.com/ImagingDataCommons/IDC-WebApp/assets/313942/7e1e11ba-1dfd-4bb6-a81c-c66b46b1e472)

We should make it *work* in IDC as well.

**Comment by s-paquette** [comment]
The difference here is TCIA is no longer providing tooltips; they're providing a button to click on to open a dialog which displays the information, which can then be closed.

We can do this, but want to consider a few things:

- Do we want to use a similar (i) icon? We don't use that in a button fashion elsewhere, but as a tooltip/hover, so we might want a different icon, or to change the other uses as well
- Do we want to change the collections table on the right as well?
- Is the X the only way to close it or do we want to provide other methods?

**Comment by fedorov** [comment]
I am open to any options if you would like to propose a design that you prefer for any reason.

The main requirement for me is that the user must be able to reach the hyperlink and click it without having to learn any special tricks.

If you want me to propose the design, let me know.

**Comment by G-White-ISB** [comment]
To be honest the 'trick' was always intuitive to me. I had not appreciated that it would be confusing to others. 

Anyhow lets just change it so the popup exists until they click the 'x' in the corner. For me the outstanding questions is whether we have an 'i' icon by the collection name indicating there is a tooltip, which would make this exactly like TCIA.

**Comment by G-White-ISB** [comment]
The tootlips are replaced by popups which persist until the 'x' is clicked as in TCIA. User must click the info icon by the collection name to open the popup in the first place

**Comment by fedorov** [comment]
Per discussion today, it might be good to show a border around the popup window area, and include collection ID at the top of the window.

**Comment by pgundluru** [comment]
The Tooltips now have a Black box around them and the Collection name is displayed on top of the tooltip description.
![image](https://github.com/ImagingDataCommons/IDC-WebApp/assets/85526819/9b15d1a7-7ec4-4e7d-b72e-942b51f6a0d1)

**Comment by fedorov** [comment]
@G-White-ISB popups for the analysis results collections are missing! 

![image](https://github.com/ImagingDataCommons/IDC-WebApp/assets/313942/8261f08c-1836-46c7-a48f-69cb3887691a)

Also please note the test tier behaves differently - tooltips are gone for the analysis results collection.

**Comment by G-White-ISB** [comment]
Sorry I had forgotten to change the analysis results section

**Comment by fedorov** [comment]
@G-White-ISB @s-paquette is it trivial to add this fix to the prod tier?

**Comment by fedorov** [comment]
The fix looks good in the test tier!

**Comment by fedorov** [comment]
Fixed
