### ISSUE TITLE
Studies table should reset when filter is updated

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#128]
As can be seen below, if I select a new filter settings that invalidate the currently active content of the study table, it still shows that unrelated content.

In this case, I selected collection nsclc-radiomics, but in the study list I have lidc studies.

![image](https://user-images.githubusercontent.com/313942/84967475-015a1600-b0e2-11ea-8c52-b73c93b88ef3.png)

**Comment by G-White-ISB** [comment]
FIxed in current PR
