### ISSUE TITLE
Need Official Quota Exceeded Page

### ISSUE THREAD

**Issue by wlongabaugh** [ImagingDataCommons/IDC-WebApp#130]
Currently, the webapp is configured to have the OHIF viewer send the user to this bare-bones page when the daily quota is exceeded:

https://storage.googleapis.com/idc-sandbox-002-static/quota_exceeded.html

We need to get an official IDC-Django-served page set up to return that message. Or is there one already I don't know about?

**Comment by wlongabaugh** [comment]
Needs to be cleaned up.

**Comment by wlongabaugh** [comment]
Current quota page. On the actual page, the formatting is messed up, the message reads "MB" but should read GB, and there are odd "jkl jkl" strings on the far right.

I understand that the warning message is not going away, though if the user has been recently in the main site and accepted, it might not show up again. It is possible that if I have a static page with the same CSS and styling (not fed from web app), we could serve that up from the Viewer server and avoid the warning. Could that be done by capturing the page source in a browser and just copying it out to a static page?

<img width="1358" alt="QuotaWarning" src="https://user-images.githubusercontent.com/8441547/92010352-8f679500-ecfe-11ea-95f8-f04c1d3d1246.png">
<img width="1372" alt="QuotaPage" src="https://user-images.githubusercontent.com/8441547/92010378-968ea300-ecfe-11ea-9f7e-75c3312e0935.png">

**Comment by wlongabaugh** [comment]
Page URL: https://idc-dev.appspot.com/quota/index.html

**Comment by G-White-ISB** [comment]
Yes, will do.
George

**Comment by G-White-ISB** [comment]
Do you still want the header part (NCI logo, link to Collections,
Exploration etc.)?  I see the footer is in the wrong place. Do we want the
footer at all?

George

**Comment by wlongabaugh** [comment]
Actually, @mitianisb is assigned now. Something to help get up to speed.

**Comment by wlongabaugh** [comment]
Maybe just a page with the NIH IDC logo in the upper left, with the message centered on the screen. Having looked at it, I'm not sure it is best to have it fully integrated with the site? They should already have the portal up in another tab. I think this page replaces the OHIF viewer, and so something that has a visual feel matching the site might work best.

**Comment by mitianisb** [comment]
Thanks for the info! I can mock up something later today and get your feedback. I am not familiar with OHIF viewer, can you share a link or screenshot please? 

It feels to me that if this page is opened in a new tab then maybe no need to keep the navigation header anymore.

**Comment by G-White-ISB** [comment]
Hi Mi,

You don't need the OHIF viewer. You are fixing this page:
https://idc-dev.appspot.com/quota/ .

George

**Comment by wlongabaugh** [comment]
Yeah, and in fact it will be pretty hard to trigger the quota page from the viewer at the moment...the quotas are pretty high. OHIF stands for Open Health Imaging Foundation. Go into the dev webapp, click on filters and collections to get to a study row, and click the icon on the far right.

**Comment by mitianisb** [comment]
I made some changes to the quota.html to make this mock-up. One has background and one without. Please let me know of your feedback, happy to make more changes!
![image](https://user-images.githubusercontent.com/58752821/92084270-01ca8a80-ed7c-11ea-8cd7-23d86395e8ba.png)
![image](https://user-images.githubusercontent.com/58752821/92084320-1149d380-ed7c-11ea-96fa-329044a7cc26.png)

**Comment by wlongabaugh** [comment]
I like the background. Looks great.

**Comment by madelyngreyes** [comment]
Implemented on the testing tier, all looks well. 
URL for reference: https://idc-testing.appspot.com/quota/
