### ISSUE TITLE
OHIF V3 link

### ISSUE THREAD

**Issue by s-paquette** [ImagingDataCommons/IDC-WebApp#1305]
Per BillL:
OK, we are getting close on the V3 viewer in dev. The URLs to launch the V3 viewer are going to have a slightly different format. Where V2 used to do a study like this:
https://dev-viewer.canceridc.dev/viewer/1.3.6.1.4.1.14519.5.2.1.6279.6001.224985459390356936417021464571
the same study in V3 has this format:
https://dev-viewer.canceridc.dev/v3/viewer?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.6279.6001.224985459390356936417021464571
So the study instance UID in V2 was part of the path, there is now the explicit StudyInstanceUIDs argument. Also, that can be a comma-separated list.
To add a specific series, it works the same as before:
https://dev-viewer.canceridc.dev/v3/viewer?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.6279.6001.224985459390356936417021464571&SeriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.6279.6001.273525289046256012743471155680

**Comment by s-paquette** [comment]
* Don't switch homepage, V3 doesn't support Series lists

**Comment by fedorov** [comment]
@pgundluru when testing this ticket, please go over the OHIF viewer test samples, and for each one use drop down next to the eye icon to open "OHIF v3" and summarize any failures you observe in this ticket.

![image](https://github.com/ImagingDataCommons/IDC-WebApp/assets/313942/8df39600-2911-4666-ab07-dd4baf0fdb94)

**Comment by pgundluru** [comment]
Going by the OHIF viewer testing doc https://docs.google.com/document/d/1l0RP3H6D9OCI3J2YubzFidBszu1NvB9lhUcFflnWNLc/edit and testing v3 vs v2 with the same series 
COLLECTIONIN (LIDC-IDRI) ANDSEGMENTATION TYPEIN (Nodule) only shows v3

**Comment by pgundluru** [comment]
For https://testing-viewer.canceridc.dev/v3/viewer/?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.6279.6001.225213110794629789874295007045&SeriesInstanceUID=1.2.276.0.7230010.3.1.3.0.89982.1553284461.956699 I am currently only seeing a blank page with errors in console 
![image](https://github.com/ImagingDataCommons/IDC-WebApp/assets/85526819/66ae6e3a-352c-45cb-bd6c-d8a893d89f19)

**Comment by pgundluru** [comment]
Same behavior as above for https://testing-viewer.canceridc.dev/v3/viewer/?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.6279.6001.225213110794629789874295007045&SeriesInstanceUID=1.2.276.0.7230010.3.1.3.0.89979.1553284456.321777

**Comment by pgundluru** [comment]
CT series in COLLECTIONIN (Colorectal-Liver-Metastases) is showing v3 
![image](https://github.com/ImagingDataCommons/IDC-WebApp/assets/85526819/92098e60-0253-4551-9afb-ab19fe6fd906)

**Comment by s-paquette** [comment]
This is a series problem across the board. Bug found and patched, builds in process.
