### ISSUE TITLE
Need object class name for Multi-frame Grayscale Byte Secondary Capture Image Storage

### ISSUE THREAD

**Issue by pieper** [ImagingDataCommons/IDC-WebApp#1344]
Converted US data from the ReMIND dataset has an object class that doesn't map from UID to String:

<img width="309" alt="image" src="https://github.com/ImagingDataCommons/IDC-WebApp/assets/126077/a6849bab-8b8c-4990-8505-87f82436c681">

**General description**

**Steps to reproduce the behavior**

Look in Object Class section and show all to see the UID string like in the image.

**Your System**
N/A

**Other Comments**

**Comment by fedorov** [comment]
@s-paquette can this mapping be exposed in some table? This can be helpful for IDC users, not just for portal maintenance, and it will also make portal initialization more transparent.

**Comment by s-paquette** [comment]
@fedorov It can be but the question becomes where to do so. BigQuery? The portal itself? I'm fine with linking to the SOP Class UID table, we can add that right there to the filter page if we want.

**Comment by s-paquette** [comment]
Note this will be fixed in v18 when the next round of ETL is done.

**Comment by pgundluru** [comment]
![image](https://github.com/ImagingDataCommons/IDC-WebApp/assets/85526819/71638e3e-35d4-492e-b9f3-eea4c2dbfeaf)

**Comment by pgundluru** [comment]
![image](https://github.com/ImagingDataCommons/IDC-WebApp/assets/85526819/9fa2d16e-25b7-4fc7-8d54-1561d8c11571)

**Comment by pgundluru** [comment]
Object class name now shows up for Multi-frame Grayscale Byte Secondary Capture Image Storage and matches the SOPClassUID
