### ISSUE TITLE
Add more segmentation attributes

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#1347]
Now that we have more and more AI-generated results, we should expose AlgorithmName and AlgorithmType DICOM attributes.

**Comment by fedorov** [comment]
As in 

```sql
SELECT distinct(SegmentAlgorithmType), SegmentAlgorithmName FROM `bigquery-public-data.idc_v17.segmentations` LIMIT 1000
```

**Comment by s-paquette** [comment]
These have been added to the dev and test portals.

**Comment by s-paquette** [comment]
@fedorov Test portal is still updating.

**Comment by s-paquette** [comment]
@fedorov @pgundluru This is ready to be tested.

**Comment by pgundluru** [comment]
Able to view, search and select the AlgorithmName and AlgorithmType DICOM attributes both in webapp and BQ
