### ISSUE TITLE
WebApp seems to be ignoring related data filters for the right-hand tables

### ISSUE THREAD

**Issue by bcli4d** [ImagingDataCommons/IDC-WebApp#1349]
In the WebApp, configure this filter:
COLLECTION IN (TCGA-LUAD) AND TCGA>AGE AT DIAGNOSIS in (85-90)
I.E., select TCGA-LUAD, then set the age_at_diagnosis slider to 85-90 (probably anything that is not the default)
The right hand side shows that the collection has 560 cases, with 7 in the cohort.
If I click on the TCGA-LUAD selection box in the Collections panel on the right hand side, then the  Selected Cases panel shoes all 560 cases rather that the 7 in the cohort.

**Comment by G-White-ISB** [comment]
I have a local fix. I will test further and then put in a PR.

**Comment by s-paquette** [comment]
@pgundluru This appears to be ready for testing

**Comment by pgundluru** [comment]
The cases number to the selections in the filter definition are now matching up. The collections panel in the right hand side now matches to the number f cases selected in the related filter table.
