### ISSUE TITLE
Add clipboard button for PatientID and fix invisible character

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#1350]
Also, it is quite inconvenient that selecting PatientID from the portal copies an invisible tab character

![2024-01-23_18-38-28](https://github.com/ImagingDataCommons/IDC-WebApp/assets/313942/299ebade-c749-4964-9729-2c3fc57d758e)

<img width="422" alt="image" src="https://github.com/ImagingDataCommons/IDC-WebApp/assets/313942/b0b12491-1a29-453f-b457-5f32d5242649">

**Comment by G-White-ISB** [comment]
I can't find an 'invisible' character. You likely copied the tab that is part of the table format. We can add the clipboard copy button next release.

**Comment by fedorov** [comment]
Ok, let's add the clipboard copy button!

**Comment by pgundluru** [comment]
The Clipboard/Copy button is enabled for CASEID and there is no extra characters that are also getting copied.
