### ISSUE TITLE
Enable OHIF v3 URL for Visible Human XC modality

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#1355]
Currently, it is impossible to visualize those.

**Comment by pgundluru** [comment]
V3 is enabled and images are viewable for NLM-Visible-Human-Project

**Comment by fedorov** [comment]
This was either not tested, or got broken after testing. Does not appear to work in v18 as tested today.

![2024-04-28_22-54-05](https://github.com/ImagingDataCommons/IDC-WebApp/assets/313942/29270fea-c7d3-43bb-a204-35bb1a212424)

**Comment by s-paquette** [comment]
@fedorov @pgundluru A fix for this is now available on test and dev.
