### ISSUE TITLE
Selection filter URL includes duplicate parameters

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#1356]
![image](https://github.com/ImagingDataCommons/IDC-WebApp/assets/313942/cdfd2d81-5fbd-41d5-b7cd-9e0281b50f2e)

Removing the redundant item and opening this URL https://portal.imaging.datacommons.cancer.gov/explore/filters/?collection_id=tcga_read selects the collection, but again has the same URL in the filter field.

**Comment by s-paquette** [comment]
@G-White-ISB  To be clear, the bug isn't the presence of a second instance of the attribute, but the presence of the program name as a collection_id value.

**Comment by pgundluru** [comment]
The selection filters are now corresponding to the collections, programs and analysis results with no duplications.
