### ISSUE TITLE
Improve messaging when manifest exceeds the limit

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#1373]
* disable the download button when the limit is exceeded
* provide error message next to the disabled button
* fix the link in the tooltip that points to the invalid "Account settings" page
* add link to the portal documentation that explains how BQ export is done

![image](https://github.com/ImagingDataCommons/IDC-WebApp/assets/313942/8e937726-bbb1-49af-b8c5-333504eefd26)

**Comment by fedorov** [comment]
Yes, I think that is it. Let's reference that section.

**Comment by s-paquette** [comment]
@fedorov @pgundluru This now on the test and dev tiers.

**Comment by pgundluru** [comment]
disable the download button when the limit is exceeded - disabled for S5CMD  and CSV/TSCV/JSON boxes 
provide error message next to the disabled button - can see the message when you hover  
fix the link in the tooltip that points to the invalid "Account settings" page 
add link to the portal documentation that explains how BQ export is done - Done

**Comment by pgundluru** [comment]
@s-paquette @fedorov  If a user selects cases over the limit for download - then saves that cohort - then this cohort download page currently shows up in test tier. 
![image](https://github.com/ImagingDataCommons/IDC-WebApp/assets/85526819/eed39801-2420-41a1-b9a0-85d56e373e89)

Question 1 - Should the s5cmd download here be greyed out as well considering the message?  right now it still is functioning. 
Question 2 - CSV/TSV/JSON still function in parts like below and that is expected ?

![image](https://github.com/ImagingDataCommons/IDC-WebApp/assets/85526819/200297e9-3b65-401c-aea3-5a9a91cb60df)

**Comment by s-paquette** [comment]
@pgundluru For situations like this I'll need to see the counts for the Cohort if only so I can make sure I know what the numbers are at. I'll have a look at this to be sure but first, can you confirm the counts for this cohort?

**Comment by s-paquette** [comment]
Second item: the CSV/JSON limit is 650k total, i,e. 10 file parts, and not 65k like it is for the s5cmd tab. So that is expected; if you total entry count isn't over 650k then you can still do CSV/JSON.

**Comment by s-paquette** [comment]
@pgundluru Okay in trying this out I can't seem to reproduce it, so if you could let me know the exact steps you took to make this happen, from opening Explorer to making the cohort to opening the manifest, that would help. Any time I'm over 65k series I get the button greyed out so there must be something about this cohort causing the issue, though I'm having trouble finding it.

**Comment by s-paquette** [comment]
@pgundluru Ah, I think I found it. Did you do a BQ export and THEN re-open the dialog to do an s5cmd?

**Comment by pgundluru** [comment]
> @pgundluru Ah, I think I found it. Did you do a BQ export and THEN re-open the dialog to do an s5cmd?

Yes you are correct, My apologies for the confusion i was trying too many things at once. I just tried to reproduce this particular issue (CSV/TSV/JSON download button not being greyed out) like below. 

1. In test tier explore page, check all collections, Then save that as a cohort. 
2. Go to the cohort page and export cohort manifest to BQ  
3.  Then it prepares the cohort manifest but you are still on this page like below https://github.com/ImagingDataCommons/IDC-WebApp/issues/1373 
4.  I selected cohort manifest again from the above page and can see the blue box for the CSV like below 
![image](https://github.com/ImagingDataCommons/IDC-WebApp/assets/85526819/60c9f320-0dd7-4cec-9269-cfc2bd7433b4)
5. Clicking the box actually saves and gives me a CSV file like below 
![image](https://github.com/ImagingDataCommons/IDC-WebApp/assets/85526819/a34360ba-75b9-42fb-9bdf-8a76a47deda8)

**Comment by pgundluru** [comment]
To summarize - Once a cohort exceeding the limit has been saved and export cohort manifest is applied to it. If I again select export manifest (on the same page) then the boxes for s5cmd and CSV (which should be greyed out) are still useable.

**Comment by s-paquette** [comment]
Got it. Will have a look.

**Comment by pgundluru** [comment]
This bug was fixed and tested via a hotfix
