### ISSUE TITLE
In prod tier, After saving cohort there are various items failing for all collections.

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#1383]
After the hotfix was pushed for production, Once a cohort is created and saved, then the filter definition is blank and none of the buttons on export manifest page are functional. Tested in windows and Mac browsers. 

https://github.com/ImagingDataCommons/IDC-WebApp/assets/85526819/24669e5d-16cd-4e4a-8bbd-e6f6c00f16d6

**Comment by pgundluru** [comment]
When i select to download the AWS or GCP manifest i am seeing undefined.aws which is incorrect 
![image](https://github.com/ImagingDataCommons/IDC-WebApp/assets/85526819/3010147b-cfc3-4851-b557-a4d539f2b2f5)

**Comment by s-paquette** [comment]
@pgundluru @fedorov Ready for testing
