### ISSUE TITLE
hang when doing query

### ISSUE THREAD

**Issue by pieper** [ImagingDataCommons/IDC-WebApp#1397]
**General description**
Tried to search and got a hang.

```
Uncaught TypeError: Cannot read properties of undefined (reading 'file_parts_count')
    at Object.success (image_search.js:1895:95)
    at c (jquery-3.7.1.min.js:2:25304)
    at Object.fireWith [as resolveWith] (jquery-3.7.1.min.js:2:26053)
    at l (jquery-3.7.1.min.js:2:77782)
    at XMLHttpRequest.<anonymous> (jquery-3.7.1.min.js:2:80265)
```

**Steps to reproduce the behavior**

Repeatable with covid and liver as shown in screenshot

**Screenshots**
![image](https://github.com/ImagingDataCommons/IDC-WebApp/assets/126077/6918a781-4981-44e2-ba8f-e4a7808046db)

**Your System**
 - mac
 - Browser chrome
Version 126.0.6478.116 (Official Build) (x86_64)

**Other Comments**

**Comment by fedorov** [comment]
Might be the duplicate of https://github.com/ImagingDataCommons/IDC-WebApp/issues/1386

**Comment by s-paquette** [comment]
yes, this is a duplicate
