### ISSUE TITLE
Broken link to demo notebooks in documentation 

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#1398]
Reported by Daniela on 07-10, The link leading to the demo notebook is broken - https://github.com/ImagingDataCommons/IDC-Tutorials/blob/master/notebooks/LIDC_exploration.ipynb 
 and https://github.com/ImagingDataCommons/IDC-Tutorials/blob/master/notebooks/Cohort_download.ipynb 

https://colab.research.google.com/github/ImagingDataCommons/IDC-Examples/blob/master/notebooks/collections_demos/lidc_idri-exploration.ipynb 

https://github.com/ImagingDataCommons/IDC-Tutorials/blob/master/notebooks/getting_started/part3_exploring_cohorts.ipynb

**Comment by pgundluru** [comment]
https://github.com/ImagingDataCommons/IDC-Tutorials/blob/master/notebooks/lung_nodules_demo.ipynb

**Comment by fedorov** [comment]
This was resolved (also, it is not a webapp issue - I noticed this by accident!).
