### ISSUE TITLE
In test tier, filter definition doesn't save the collections/filters that are selected while logged out in explore image data page 

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#1408]
**General description**

This bug was identified while testing V19 in test tier. 

**Steps to reproduce the behavior**
You will need to be logged out and select any collection/program/filter 
Then you will click on login to save cohort 
The filter definition is blank as opposed to saving and showing your cohort 

**Your System**

Chrome in windows and Safari in Macos

**Comment by s-paquette** [comment]
Numerous issues underlying this one:
* Sign In header button was an anchor, leading to a race condition in the anon filter save callback
* Sphericity and age_at_diagnosis slider resets had default values which were being misinterpreted as an anonymous filter
* sometimes slider default values are null or NaN which was breaking the anon filter saver

**Comment by s-paquette** [comment]
@pgundluru @fedorov This is now available on the test portal, please be sure to test using both the Sign In link on the header as well as the 'Log in to Save' button below.

**Comment by pgundluru** [comment]
I am able to use both Sign in Link in the home page and log in to save button and see the selected filters persist after a sign in
