### ISSUE TITLE
Segmentations available in BQ are not reflected in the portal

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#1410]
For details see this slack thread: https://nciimagingdat-m8a6349.slack.com/archives/C045VQUAZ0S/p1725051714800109

<img width="443" alt="image" src="https://github.com/user-attachments/assets/835f3c25-aed4-4103-b5e7-cd78843541f1">

**Comment by s-paquette** [comment]
@pgundluru @fedorov Corrected segmentations are now available in test.

**Comment by fedorov** [comment]
Here's the script that will parse the HTML page and output table into CSV. Co-created with [Perplexity.AI](https://www.perplexity.ai/).

```python
import requests
from bs4 import BeautifulSoup
import csv

url = "https://dicom.nema.org/medical/dicom/current/output/chtml/part16/chapter_O.html"

response = requests.get(url)
response.raise_for_status()

soup = BeautifulSoup(response.content, 'html.parser')

# Find the table
table = soup.find('div', class_='table-contents').find('table')

# Initialize lists to store data
headers = []
rows = []

# Extract headers
for th in table.find_all('th'):
    headers.append(th.text.strip())

# Extract rows
for tr in table.find_all('tr'):
    cells = tr.find_all('td')
    if cells:
        row = [cell.text.strip() for cell in cells]
        rows.append(row)

# Write to CSV
csv_filename = 'table_O-1.csv'
with open(csv_filename, mode='w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    writer.writerow(headers)
    writer.writerows(rows)

print(f"Data has been saved to {csv_filename}.")
```

**Comment by s-paquette** [comment]
@fedorov Thank you! The issue which cropped up though wasn't from the Excel pull down and CSV, it was from the BQ import from the CSV; the schema can't be auto-detected because it will treat the SCT code like a number which causes problems; it has to be explicitly labeled a string, and if one column of the schema is defined they all need to be.

**Comment by fedorov** [comment]
Right, but import from CSV into BQ can also be done with a script, and there schema can be explicitly defined. It is very stable and won't change.

All I am saying is that steps of our ETL/portal/etc that are well-defined, deterministic and routine should be as much as possible automated. Otherwise it will be very difficult for us to stay afloat as a project.

**Comment by s-paquette** [comment]
@fedorov I definitely agree, but with other items being higher priority to work on this hasn't been finalized into something smoother and less likely to have an issue. It can be re-prioritized in front of those items if we'd like to do so.

**Comment by fedorov** [comment]
IMHO, we could also do this as part of ETL - @bcli4d already creates a bunch of tables, and this could be just another one on the list. Having this table available publicly would make a lot of sense.

**Comment by pgundluru** [comment]
The segmentation type now has more values added in and they differ from prod based on the new v19 data.

**Comment by pgundluru** [comment]
![image](https://github.com/user-attachments/assets/587addef-5726-4534-95aa-0b4c2aa82180)

**Comment by s-paquette** [comment]
@fedorov @pgundluru Can this be closed?
