### ISSUE TITLE
DOI URLs are broken when more than one DOI is present in the Collections page

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#1417]
![image](https://github.com/user-attachments/assets/fbae81a8-2af2-4abb-be6e-ee9322702588)

**Comment by s-paquette** [comment]
Small change to just using DOIs for now, and properly labeling the URLs as external links; we can go over a more thorough way to manage source_url vs. DOI next release. 

@fedorov @pgundluru This is on test (make sure to clear your cache since it's a JS change).

**Comment by fedorov** [comment]
Looks great, and thank you for propagating this to prod!
