### ISSUE TITLE
Incorrect filtering result

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#144]
The below is the single facet I click. I am trying to understand why Segmentation-related pie charts are all "None". Each of those cases selected comes from the LIDC collection, and I know that each of the cases that has this facet enabled contains a Segmentation object.

![image](https://user-images.githubusercontent.com/313942/86607275-10144a00-bf77-11ea-8aa6-ffcafb73578f.png)

As I try to confirm this, and select LIDC-IDRI collection only, and Segmentation as Modality, as expected I have just a handful of "None"s:

![image](https://user-images.githubusercontent.com/313942/86607762-ad6f7e00-bf77-11ea-83ad-646420547f61.png)

**Comment by fedorov** [comment]
Perhaps filter should not apply to series table

**Comment by fedorov** [comment]
The counts are incorrect right now, let's revisit this once counts are fixed.

**Comment by fedorov** [comment]
I also realized there are "None" options for each of the qualitative measurement options (I missed this earlier, since it was hidden because of "show more"). There should not be "None" in that list. As as user, I would be super confused by this.

![image](https://user-images.githubusercontent.com/313942/86799051-7d8bad80-c03f-11ea-9aaa-37ca8a8c83e5.png)

**Comment by s-paquette** [comment]
Can we say for sure that there will never be a record lacking a value in some of these?

**Comment by s-paquette** [comment]
Oh, also those are older counts--are you looking at test? The newest code is on dev. Can you have a look at dev and let me know if that's working as intended?

**Comment by fedorov** [comment]
Looking at dev, it is better re None, but it is still incorrect - the total number of cases in lidc_idri is 1010 (and the total number of cases that have annotations is less than that), but the below sums up to more than 1010.

![image](https://user-images.githubusercontent.com/313942/86969865-71d1e100-c13c-11ea-9468-4488e949e023.png)

**Comment by fedorov** [comment]
> Can we say for sure that there will never be a record lacking a value in some of these?

Can you clarify what you mean by that? If you mean whether we can have a qualitative measurement concept code, but no value assigned to that concept, then no - I don't think we should have that.

**Comment by s-paquette** [comment]
Got it--in that case, I think it's better to handle that at the UI level. From a faceted counting POV, finding a NULL or missing value is a legitimate thing; if our data won't be doing that in some specific situations, then we should tailor the UI to not show it for those. It's not something we can apply system wide, as there will be records which lack data in some attributes, and we should account for that.

**Comment by s-paquette** [comment]
@fedorov Another filtering question for you. Numerous of the instance IDs linked to the derived data don't have some of the dicom metadata linked to them (eg. BodyPartExamined). So, in a case like that, if you filter on eg. Lung, those records fall out of the counts because they have no BodyPartExamined linked to them (being from the SR modality records, all of which have NULL BodyPartExamined entries). What's the expected behavior here?

**Comment by fedorov** [comment]
That's a good question! I need to think about this ... @dclunie do you have any thoughts to help with the above?

We could assume that BodyPartExamined is the same for everything in a study (and we could easily verify if this is indeed the case for all instances that do have it initialized). I think this is the most practical thing to do.

More complicated approach could be to look at the references from the SR to the images it corresponds to, and take body part from there.

Yet another approach is to take the "Finding site" from the SR tables (which by the way we should add to the facets as well, along with the finding - we should revisit those tables), but while "Finding site" has similar intent, it is not necessarily going to map 1:1 to the body part.

Looking forward, we could do harmonization of BodyPartExamined and coded "Finding site" as part of the multiframe DICOM work, but that's distant future ...

**Comment by wlongabaugh** [comment]
What level does the filter apply to?
