### ISSUE TITLE
Collection groups facets do not work

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#145]
Currently, we have groups of collections organized as below:

![image](https://user-images.githubusercontent.com/313942/86608065-0dfebb00-bf78-11ea-8d02-695a04cf1dff.png)

Selection of the "parent" for the collection puts "parent" into the filter in the UI:

![image](https://user-images.githubusercontent.com/313942/86608142-28389900-bf78-11ea-808d-21f13966d810.png)

However, the behavior is not equivalent to selecting individual collections under the "parent". If I select "LIDC" category, I get nothing under modalities:

![image](https://user-images.githubusercontent.com/313942/86608267-4900ee80-bf78-11ea-8a23-51e1d4d35070.png)

But if I select lidc-idri, I get modalities populated correctly:

![image](https://user-images.githubusercontent.com/313942/86608338-633acc80-bf78-11ea-81f4-60e2137006ca.png)

I suggest that checking of the "parent" results in 

1) auto-checking of all "children" under parent
2) all children are added to the filter definition
3) parent is NOT added to the filter definition

Or/and we could consider adding a new item called "project" which will correspond to the groups of collections, and capture this in another column in the underlying data.

**Comment by fedorov** [comment]
Agreed the desired behavior should be like in DataStudio (the example below is from https://datastudio.google.com/u/0/reporting/9d9a696e-0bb9-405d-a05a-a88983a02717/page/vOhHB):

![image](https://user-images.githubusercontent.com/313942/86615241-2ffd3b00-bf82-11ea-832d-f40f4b63ecc6.png)

**Comment by fedorov** [comment]
Going forward, probably should record assignment to the project as part of ETL.

**Comment by G-White-ISB** [comment]
Fixed in next my next commit

**Comment by G-White-ISB** [comment]
somehow this issue and #121 have ended up at the same place
