### ISSUE TITLE
Differentiate between "has no specific type of derived data" and "has no specific attribute of derived data"

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#146]
Specific example: missing segmentation and missing anatomic region in segmentation.

**Comment by s-paquette** [comment]
I *think* I have this working now in idc-dev, where counts will not involve instances that don't have *any* of a given derived data type. So, if say 200 instances lack segmentation, they won't be part of the segmentation counts (neither will anything without derived data at all). Let me know if that's working as expected.

**Comment by fedorov** [comment]
I don't think it is working properly - if I select lidc_idri that does not have any glycolysis measurements, it gives me below which to me means there are None's assigned as values for glycolysis.

![image](https://user-images.githubusercontent.com/313942/86970128-dee57680-c13c-11ea-8f5a-16dd340e9d08.png)

**Comment by s-paquette** [comment]
Not quite done yet. I'll ping in this and the other issues when it's deployed.

**Comment by s-paquette** [comment]
@fedorov Okay, idc-dev's current deployment has the sliders for quantitative data and all counting issues (that I know of) dealt with, save one: the 'None' entry under Original data resulting from the derived data records which have no values for those attributes. We really can't do anything about those unless as previously discussed in another ticket we want to fill those in from the studies or a similar harmonizing solution.

**Comment by fedorov** [comment]
> the 'None' entry under Original data resulting from the derived data records which have no values for those attributes

That's perfectly fine, and is expected behavior.

But there still are discrepancies: there are only 875 cases in LIDC that have segmentation (which means 875 cases that have any kind of measurements), but the number of measurements across categories of a single measurement sums up to more than that:

![image](https://user-images.githubusercontent.com/313942/87109664-44b42a00-c233-11ea-8c50-15c27de041e6.png)

**Comment by fedorov** [comment]
Thinking about this more, this may make sense, since the same case may have nodules that have different appearance. It is similar situation to what we have with Body Part for LIDC. So I take back the above - we will need to test the numbers are accurate, but at least there is an explanation to what I see.

**Comment by madelyngreyes** [comment]
Working on a notebook that will check the counts found in the BigQuery tables for the Qualitative Analysis filter options with collection lidc_idri. @fedorov

**Comment by madelyngreyes** [comment]
This notebook was created - https://colab.research.google.com/drive/1mwr8qHCftY_sPKNY3T3MiTjLR6Jtm7HP 

All counts match except the None column due to anything without derivied data will not show up on the data portal.
