### ISSUE TITLE
Account information - need to edit panel

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#149]
![image](https://user-images.githubusercontent.com/313942/86822894-30690500-c05a-11ea-98c2-1a19c841178f.png)

**Comment by fedorov** [comment]
Currently, this points to ISB-CGC mailing list. Should replace with a pointer to IDC discourse, add instructions to the documentation about how to apply for the pilot credits

**Comment by s-paquette** [comment]
Do we have a link to those instructions somewhere? Or are we planning to add it somewhere?

**Comment by fedorov** [comment]
You can add the support email: canceridc+support-email@discoursemail.com, this has been set up. I have not yet populated that documentation page mentioned.

**Comment by mitianisb** [comment]
@fedorov Hi Andrey, is the documentation page ready to link from here?

**Comment by fedorov** [comment]
Let's use this link for the instructions: https://learn.canceridc.dev/introduction/requesting-gcp-cloud-credits, and leave it at that. The page has the instructions how to send the request.

**Comment by mitianisb** [comment]
Ok. I only updated "here" to link to: https://learn.canceridc.dev/introduction/requesting-gcp-cloud-credits for now. Let me know anything else I need to change. Thanks!
