### ISSUE TITLE
Empty collections list but non-empty study list

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#155]
I hit a weird issue of collections list being empty, but studies list is not. All I need to do is select "Nodule" under segmentation type in idc-testing:

![image](https://user-images.githubusercontent.com/313942/87049864-772a3c80-c1cb-11ea-9da0-ad516952ac85.png)

**Comment by G-White-ISB** [comment]
I was aware of this bug and it was already fixed in dev.
