### ISSUE TITLE
"Hide values with 0 cases" should be a global setting

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#158]
I do not see the value of toggling that setting for every single section, and also it eats quite some space.

![image](https://user-images.githubusercontent.com/313942/87109772-81802100-c233-11ea-9429-f0101273b116.png)

**Comment by G-White-ISB** [comment]
In Progress

**Comment by G-White-ISB** [comment]
The checkbox option to hide 0 counts is active. But if an attribute is checked it will still be displayed. Also this option does not affect display in the collections panel above. In current PR

**Comment by madelyngreyes** [comment]
It displays a blank filter when zero cases are present. Should it say there is no data available? 

<img width="900" alt="blank filter when zero cases are available" src="https://user-images.githubusercontent.com/16824894/90438746-732eeb80-e0a2-11ea-9edd-e8615404b5fe.PNG">
