### ISSUE TITLE
"SOP Class UID" label should be replaced with "Object class"

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#165]
UIDs are strings of dot and number characters, and SOPClassUID maps to a DICOM object class, which in turn has a human-readable name.

"SOP Class UID" label should be replaced with "Object class" in all occurrences.

![image](https://user-images.githubusercontent.com/313942/87699962-9db81c80-c763-11ea-9176-10ea9281e6db.png)

![image](https://user-images.githubusercontent.com/313942/87699986-a3156700-c763-11ea-80c0-d4a1445b9aa0.png)

I thought I reported this earlier, but maybe I did not, since I do not see the specific open issue about this.

**Comment by s-paquette** [comment]
@fedorov Go ahead and have a look at this one on dev; it's been implemented.

**Comment by fedorov** [comment]
@s-paquette it is actually already appears as "Object class" in idc-testing. Thanks!
