### ISSUE TITLE
Pagination controls move around

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#167]
Pagination controls have a strange behavior, where the buttons move around, and the number of items shown changes.

So if one keeps mouse pointer on Next without moving, after few clicks one would jump to the last page in the list.

This is a bug, right?

![2020-07-16_13-01-57](https://user-images.githubusercontent.com/313942/87700725-cc82c280-c764-11ea-97be-434f978392c5.gif)

**Comment by G-White-ISB** [comment]
If one is currently on a page in the 'middle' then there are buttons displayed to move page 1, page n-2, n-1, n, n, n+1, n+2, and page N. Where n is the current page, N is the last page. Now some of these buttons will not exist if one is at an edge page. If one is at page 1 there is no button to move to page -1. Also buttons with 2 digits are fatter than buttons with one digit.

**Comment by G-White-ISB** [comment]
I'm guessing you wanted to hit 'next' multiple times and it kept moving! I can at least anchor next and previous so they are not moving

**Comment by G-White-ISB** [comment]
'Previous' and 'Left' Buttons anchored at left and right hand  sides of div in new PR

**Comment by fedorov** [comment]
Previous/Next buttons no longer move around
