### ISSUE TITLE
IDC partners

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#169]
We currently have the same as ISB-CGC. I don't think it is correct, is it?

![image](https://user-images.githubusercontent.com/313942/87949659-50de8980-ca74-11ea-8d3e-a21665d2ab1f.png)

**Comment by fedorov** [comment]
Need to decide who will be listed as our partners, and then find icons for each.

**Comment by rkikinis** [comment]
#1: funded by IDC contract
#2: contributed to IDC


> On Aug 3, 2020, at 12:17 PM, Andrey Fedorov <notifications@github.com> wrote:
> 
> 
> Assigned #169 to @rkikinis.
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 



—
Ron Kikinis
ron@kikinis.org
--------
This email is intended for non-work related messages

**Comment by fedorov** [comment]
Here's the link to the MGB logo: https://www.massgeneralbrigham.org/themes/custom/partners_mgb/logo.svg

@pieper @radicalrob @ahomeyer @DavidPotCanuck @pieper @dclunie can you please provide links to the logos of your organizations you would like to see featured on the IDC home page?

**Comment by pieper** [comment]
Here's the Isomics logo:

https://www.dropbox.com/s/93p4va2nkjtmv43/isomics-logo-text-horizontal.png?dl=0

**Comment by DavidPotCanuck** [comment]
GDIT logo is correct

**Comment by ahomeyer** [comment]
Here are the Fraunhofer MEVIS logos:

* [fraunhofer_mevis_logo.pdf](https://github.com/ImagingDataCommons/IDC-WebApp/files/5116668/fraunhofer_mevis_logo.pdf)
* [fraunhofer_mevis_logo.png](https://user-images.githubusercontent.com/53333973/91022335-52f8b280-e5f5-11ea-8e1c-f3e71e433de4.png)

**Comment by dclunie** [comment]
Hi Andrey

PixelMed logo attached in various different forms and rendered at various resolutions (with transparency).

David

**Comment by radicalrob** [comment]
Here is the Radical logo.

**Comment by fedorov** [comment]
all logos have been collected
