### ISSUE TITLE
Unexpected scrolling on the right side of the app

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#170]
This looks like a bug:

![2020-07-20_11-29-47](https://user-images.githubusercontent.com/313942/87956000-796a8180-ca7c-11ea-96bb-6039b9d4137f.gif)

**Comment by G-White-ISB** [comment]
I added a scrollbar for the RHS, but on review I realize you asked for one for the LHS. Still I actually think content scrolling is more of an issue on the RHS with the tables placed below the charts.

'I received feedback from Keyvan that it takes a lot of scrolling to navigate the left panel.

I then thought that maybe we could look into adding independent scrolling for the left panel so the right part could stay in place while navigating facets.'

**Comment by fedorov** [comment]
Sorry for being unclear. My concern is that it is not clear why the height of he vertical scroll area on RHS was selected the way it was. The way it appears to me on idc-dev is that LHS has no scrolling at all, and the vertical size of the scrolling area on RHS is less than the height of the corresponding window area. Looks quite weird, if you ask me.

**Comment by G-White-ISB** [comment]
Fixed in new PR

**Comment by fedorov** [comment]
Fixed in the current idc-dev
