### ISSUE TITLE
Disable annotation tools in OHIF deployment

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#171]
Since new content creation will not be supported in MVP (e.g., annotations), those should be disabled, and the consensus is it will be easiest to just comment those out, since looks like we will need (at least for some time before v2 is out) to fork out OHIF.

See more details in https://github.com/OHIF/Viewers/issues/1866.

**Comment by fedorov** [comment]
@s-paquette and @wlongabaugh will want @pieper or someone else from the OHIF team to make the fork with the disabled annotations.

**Comment by fedorov** [comment]
Adding @JamesAPetts. Can ISB team please provide the details about how OHIF team should go about making these updates in the IDC OHIF deployment?

**Comment by wlongabaugh** [comment]
I have now created a fork https://github.com/ImagingDataCommons/Viewers. @JamesAPetts can make a pull request on that repo to disable annotations and study lists.

**Comment by pieper** [comment]
Sounds good to me.

@fedorov I'm thinking we should also point the idc-sandbox at this fork, do you agree?

**Comment by fedorov** [comment]
Yes, I agree.

**Comment by JamesAPetts** [comment]
PR for #171 and #199 here: https://github.com/ImagingDataCommons/Viewers/pull/1.

**Comment by wlongabaugh** [comment]
Forks created, new code and config handles this issue.
