### ISSUE TITLE
OHIF viewer is broken in idc-dev

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#177]
Seems to be broken with any study I open, but here's the suffix for one of them:

`study/1.3.6.1.4.1.14519.5.2.1.7695.1700.118757564401397374205631727107`

![image](https://user-images.githubusercontent.com/313942/88230601-ae273600-cc40-11ea-9a5a-e5bbcb6a2f28.png)

**Comment by fedorov** [comment]
On a related note, I think we should make it a rule that every time idc-dev is updated, we need to update OHIF Viewer to use the latest version. Can we agree on this? Otherwise we are not really testing what we should be testing!

**Comment by wlongabaugh** [comment]
The errors shown there are 404s related to the viewer's failed attempts to get debug files from the server. I believe the true culprit is what appears to be a bug lurking in the Google Memcache for REDIS implementation that hit the proxy, which is a known issue from late last week: https://github.com/ImagingDataCommons/ThrottleProxy/issues/19#issue-658651884

**Comment by wlongabaugh** [comment]
It is the next thing to fix for the proxy. One question is, what should the behavior of the viewer be if one slice out of hundreds fails to load? My preference would be to omit the slice and flag it somehow. It looks like it treats the whole load as broken.

**Comment by wlongabaugh** [comment]
As for always doing a viewer import on dev deploys, I don't think that is the best strategy. Dev is way too fluid to use that approach. Things are being pushed all the time in dev, and introducing another source of change which we have no control over is just going to cause problems. I can agree that a deploy to test might warrant an integrated new viewer pull, but even then I only think that is wise when OHIF has fixed production branch with formal releases.

**Comment by fedorov** [comment]
> I can agree that a deploy to test might warrant an integrated new viewer pull, but even then I only think that is wise when OHIF has fixed production branch with formal releases.

Ok, so what is your proposal for testing within IDC portal new capabilities added by OHIF to meet the needs of IDC?

**Comment by fedorov** [comment]
Adding @pieper - do you have any comments on the discussion above, Steve?

**Comment by pieper** [comment]
Since the two parts are so loosely coupled maybe we should provide a way for users to configure the version of OHIF to be used from the web app.  Our default could be to use a specifically tagged version, but users could override.

We could even use hooks in github to automatically build and populate a new version for every git commit, with the head of the master branch one being made available as an option.

**Comment by fedorov** [comment]
Adding @swederik

**Comment by wlongabaugh** [comment]
I am investigating with the team the option of selecting a version in the development tier.

**Comment by wlongabaugh** [comment]
The connection reset error in the proxy (https://github.com/ImagingDataCommons/ThrottleProxy/issues/19) is now being handled (the original topic of this issue).

**Comment by wlongabaugh** [comment]
The dev-viewer OHIF Viewer instance is pinned to a specified OHIF GitHub tag and will only updated when there is an official IDC-ready release. But there is now a parallel OHIF Viewer deployed that will be automatically updated nightly. We plan to provide a dev-only Web App dropdown to choose which one to use when launching a link, but until this is done, editing the address bar after the Viewer is launched from the Web App is an option.
