### ISSUE TITLE
"Clear filter" should reset range slides of the quantitative measures

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#183]
Right now, "Clear all" has no effect on the quantitative sliders:

![image](https://user-images.githubusercontent.com/313942/89331993-aadc7300-d660-11ea-8aca-6981a4634dca.png)
![image](https://user-images.githubusercontent.com/313942/89332010-b039bd80-d660-11ea-8b08-65de382e4f50.png)

**Comment by G-White-ISB** [comment]
fixed in current pull request

**Comment by fedorov** [comment]
"Clear all" resets the filter, but the slider range is set to the incorrect values.

![2020-08-17_10-12-12](https://user-images.githubusercontent.com/313942/90405768-3ba84b00-e072-11ea-9bfc-574d8120bb79.gif)

**Comment by fedorov** [comment]
Might be related to #204
