### ISSUE TITLE
Series and Study Tables need to account for 'unfetched data' 

### ISSUE THREAD

**Issue by G-White-ISB** [ImagingDataCommons/IDC-WebApp#186]
The server limits all ajax calls from the browser for series and studies data to 1k record batches. In some cases this means that all matching records are not retrieved at once. In these cases reordering a table or jumping to a new page may require another ajax call to fetch more data. Currently this is not handled correctly. The request for a study or series is assumed to return all records at once.

**Comment by wlongabaugh** [comment]
Referenced in a ZenHub ticket

**Comment by G-White-ISB** [comment]
If its OK with Suzanne I am bumping up the record limit to 2k from 1k to avoid this issue for now. The only relevant collection right now is LIDC which has ~1300 records. The size of the LIDC records fetched is only 800kb.
