### ISSUE TITLE
Need to define format of the cohort manifest

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#194]
What will be the format of the manifest for the portal-defined cohorts?

We never discussed any tools that would facilitate fetching the cohort data to the VM, so I assume this, at least initially, will need to be done by the user, and so we will need to document the manifest format. We probably need to document what users should do next once they have the manifest - right?

**Comment by pieper** [comment]
This is a very important topic.  NHLBI BDC is also going to be interested in this and it would be good to have a common standard.

My suggestion would be something very limited and focused for MVP, and then post-MVP start defining the process for drafting the specific use case and approaches we need to support.

**Comment by fedorov** [comment]
Related user-facing discussion is here: https://discourse.canceridc.dev/t/cohort-manifest-content/37

Once MVP is released, we will also hopefully get feedback from the users about what they would want to see in the manifest.

**Comment by s-paquette** [comment]
Current deployment of dev now allows for saving of Cohorts, and downloading them. 

Format example:

```
Manifest for cohort 'Chest'
User:   spaquett@systemsbiology.org
Filters:   (tcia_tumorLocation = 'Chest')
Date   generated: 09/12/2020 05:39
Total   records found: 15740 
PatientID | collection_id | Program | StudyInstanceUID | SeriesInstanceUID | SOPInstanceUID | source_DOI | gcs_path
LIDC-IDRI-0456 | lidc_idri | LIDC | 1.3.6.1.4.1.14519.5.2.1.6279.6001.225325726732923728196849027710 | 1.3.6.1.4.1.14519.5.2.1.6279.6001.179162671133894061547290922949 | 1.3.6.1.4.1.14519.5.2.1.6279.6001.589287346770887317349091379494 | 10.7937/K9/TCIA.2015.LO9QL9SX | gs://idc-tcia-lidc-idri/dicom/1.3.6.1.4.1.14519.5.2.1.6279.6001.225325726732923728196849027710/1.3.6.1.4.1.14519.5.2.1.6279.6001.179162671133894061547290922949/1.3.6.1.4.1.14519.5.2.1.6279.6001.589287346770887317349091379494.dcm#1592617666797543
```


```

**Comment by fedorov** [comment]
Thanks Suzanne!

What is the meaning of "Program", considering we don't have a filter for that?

**Comment by fedorov** [comment]
When I try to save, I get this error:

![image](https://user-images.githubusercontent.com/313942/93003660-a2ecda00-f50e-11ea-8eca-bc9ca0529438.png)

similar when I try to download:

![image](https://user-images.githubusercontent.com/313942/93003675-bef07b80-f50e-11ea-80f2-90f95394043e.png)

After I open a cohort, the filter is not populated, and no filters are applied.

Errors in the console: 

![image](https://user-images.githubusercontent.com/313942/93003698-e8110c00-f50e-11ea-9a8e-a826691c82d5.png)

**Comment by s-paquette** [comment]
Can you tell me what filters you used for your cohort?

**Comment by s-paquette** [comment]
Found the bug--not manifest related, it's that derived selections were missing a necessary value in the explorer template. That change is now in, so you should be able to save cohorts with derived filters.

**Comment by fedorov** [comment]
Thank you, save and download seem to work now.

What is the meaning of "Program", considering we don't have a filter for that?

**Comment by s-paquette** [comment]
'Program' is a concept we'll need to integrate due to the CRDC and CDA; it groups collections. Eg. all the TCGA collections are part of TCGA, etc. We've postulated programs for others, based on their current collection names, and can put in something more formal once we have it. It needn't show up in the manifest, if you'd rather exclude it.

**Comment by fedorov** [comment]
@s-paquette I am completely in support of integrating the concept of program that would group collections into the portal UI and into the manifest. In fact, I believe I suggested that a while ago. All I am saying is that we should not include into the manifest things that are currently not available in our tables and/or the portal.

**Comment by s-paquette** [comment]
We can definitely include it in the portal as a filter; it's in the index and table as of Bill's last ETL. Do we want to?

**Comment by fedorov** [comment]
I do not see Program column in the collection-level metadata table

https://console.cloud.google.com/bigquery?project=idc-dev-etl&p=canceridc-data&d=idc&t=data_collections_metadata&page=table

**Comment by fedorov** [comment]
Decided to leave for now out of manifest, will add Program post-mvp

**Comment by s-paquette** [comment]
@fedorov This is ready for testing; Program has been removed from the manifest.

**Comment by madelyngreyes** [comment]
Description of cohort is not exported in the manifest.  Suzanne has brought up the point, "We can include the description but as it's freeform text and a freeform size, it's badly suited to the manifest. So I don't feel too strongly about that but it's another thing a user has to delete, and as it's not required (unlike a name) it means the header size becomes variable." 

We can add a note to the documentation the description of the cohort will not be included in the cohort manifest export or add it to the manifest if others feel it would be useful.

**Comment by fedorov** [comment]
@s-paquette can you clarify why is it ill-suited for exporting into manifest? From what I see, corhort name is line of text, and so is description. The manifest already has the header, and I don't see how adding one more line to that existing header can make any difference one way or another.

**Comment by s-paquette** [comment]
@fedorov Cohort descriptions aren't a single line of text; they're a text 'block' in the database, so they can be upwards of several hundred words. (The default length limit of the Text field in MySQL 64kB.) As a result, the description could easily turn into an enormous line and, depending on the user's in-use system, wrap; we're not preventing use of line breaks or other text-wrapping functionality.

That said, I can add it in; due to its freeform nature, though, I assumed it wouldn't be ideal from any kind of pipeline usage as far as a CSV goes.

**Comment by fedorov** [comment]
Re cohort description, if the limit is that high, and we are not preventing line breaks, then we should have a text box instead of text line for description in the UI. If we are not preventing text breaks, and this can result in arbitrary number of header lines, then we should not be exporting it into CSV. When we add the option to export into JSON, we could add it there. Maybe we could add a warning, or a footnote about not saving cohort description into CSV.

On a different note related to the manifest, I've just added the below to Slack.

![image](https://user-images.githubusercontent.com/313942/94300470-10e5c800-ff37-11ea-8d2d-ffff56f966e7.png)

**Comment by fedorov** [comment]
Actually, I see the gs URI has a similar issue, and this just can't be right to have those brackets in the URI, so it appears that it is broken in testing. @madelyngreyes can you test how it works in dev?

`gs://['idc-tcia-qin-headneck']/dicom/1.3.6.1.4.1.14519.5.2.1.2744.7002.193170296045032115043138323703/1.3.6.1.4.1.14519.5.2.1.2744.7002.597826950517150638767826178314/1.3.6.1.4.1.14519.5.2.1.2744.7002.210411744008772526435322302517.dcm#[1592627592017143]`

**Comment by madelyngreyes** [comment]
I had a look at the dev tier and returned this, 

<img width="233" alt="source_doi format" src="https://user-images.githubusercontent.com/16824894/94301682-02001500-ff39-11ea-9ccd-b8b3886ac32c.PNG">
<img width="907" alt="gcs_path in the dev tier" src="https://user-images.githubusercontent.com/16824894/94301687-04fb0580-ff39-11ea-9584-e58d5f2277c8.PNG">

**Comment by s-paquette** [comment]
Okay so it appears to specifically be QIN Headneck has an issue. Note I can't reproduce this with just any random filter set.

**Comment by s-paquette** [comment]
Actually, this might be a MAC issue. Madelyn can you get this to happen on your Windows machine? I can't.

**Comment by fedorov** [comment]
I attach the manifest with those issues. Assuming manifest header is working correctly as expected, it should be sufficient to (try to) reproduce it on your end ;-)

[manifest_cohort_8_20200925_174959.csv.zip](https://github.com/ImagingDataCommons/IDC-WebApp/files/5284621/manifest_cohort_8_20200925_174959.csv.zip)

Indeed, I am using a mac.

**Comment by madelyngreyes** [comment]
I used a windows machine as well.

**Comment by fedorov** [comment]
@s-paquette sorry this issue is growing out of control and definitely beyond the title, but ....

I really think we need to include CodeMeaning in the saved filter definition. It is super confusing that we show code meaning in the portal, but codevalue+codingscheme in the saved manifest! It is not trivial how to reconcile the two!

**Comment by s-paquette** [comment]
Oh, I bet that's for anatomic region, isn't it. That's the only one where we went with the table holding code meanings rather than code values.

I can do a simple fix for the MVP; the larger fix will happen when we redo the data.

**Comment by s-paquette** [comment]
@madelyngreyes The anatomic region fix is ready on dev.

**Comment by madelyngreyes** [comment]
Example of manifest format below, 

![manifest_download-screenshot](https://user-images.githubusercontent.com/16824894/96509672-60fc3580-122a-11eb-868c-31c67a07eaa1.PNG)
