### ISSUE TITLE
Collections page should show only the included collections

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#195]
Currently, it includes a lot more than that.

https://idc-testing.appspot.com/collections/

It would also be good to make sure all URLs are styled such that it is clear they are click-able, and all URLs are hyperlinked (let me know if I should make a separate issue about this).

**Comment by s-paquette** [comment]
This isn't really a bug; it's that BillC hasn't re-performed the ETL on the metadata table to include the analysis collections. Once he does I can pull it in and this will update.

**Comment by wlongabaugh** [comment]
Andrey says it is fixed.
