### ISSUE TITLE
Need to disable measurements panel in OHIF

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#199]
Measurements panel does not apply to the data in IDC, we need to disable it to reduce confusion.

Features were added to do this from config, see https://github.com/OHIF/Viewers/issues/1864.

OHIF Team can take care of this, but needs instructions as to what is the process for updating OHIF IDC deployment.

cc @JamesAPetts

**Comment by JamesAPetts** [comment]
PR for #171 and #199 here: https://github.com/ImagingDataCommons/Viewers/pull/1

**Comment by fedorov** [comment]
idc-dev needs to point to the fork above, @wlongabaugh is working on it this week.

**Comment by wlongabaugh** [comment]
Will point to latest OHIF version this week.

**Comment by madelyngreyes** [comment]
Measurements panel no longer visible on the OHIF viewer when opened from the dev tier.

<img width="960" alt="2020-09-21 (15)" src="https://user-images.githubusercontent.com/16824894/93811443-264cb080-fc1e-11ea-9176-e16ca72dd590.png">
