### ISSUE TITLE
JS error returned on the data portal when certain filters are selected/de-selected

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#201]
Returned an Uncaught RangeError, Invalid String length in the dev console, while selecting and de-selecting filter options on the dev tier. 

<img width="945" alt="invalid string length error found in dev tier also" src="https://user-images.githubusercontent.com/16824894/90279841-eed93000-de37-11ea-9ea2-c3d204df21c9.PNG">

George is aware of the issue and wrote, "The encountered an error message is due to the backend erroring, no doubt in response to receiving a bad request from the failure in the JS (it's an error in JSON.stringify). You can ignore those for the moment, George."

**Comment by madelyngreyes** [comment]
Also, if you do a hard refresh of the IDC data portal while filter options are selected you return the error message, "Encountered an error when attempting to load the page - please contact the administrator."  some of the time. This bug also can only be encountered with extensive testing. 

<img width="939" alt="encountered error while loading the page" src="https://user-images.githubusercontent.com/16824894/90281521-b38c3080-de3a-11ea-8141-8fbc163902ac.PNG">

**Comment by G-White-ISB** [comment]
testing needed. Build: dev.010920201029.e06ce4
