### ISSUE TITLE
Change study_id to series_id in the Selected Series panel in data portal

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#202]
Currently, the study Id is displayed in the Selected Series panel instead of the series Id. 

<img width="647" alt="change study_id to series_id - dev tier" src="https://user-images.githubusercontent.com/16824894/90282347-2fd34380-de3c-11ea-842a-7eef2ccc2907.PNG">

**Comment by madelyngreyes** [comment]
Andrey also mentioned, "It also does not make any sense that to view study one needs to click on the study UID, and to show series it is ok to click anywhere on the row." 

To make it consistent we can set the Selected Series panel to require a click on the Series UID to open the OHIF viewer.

**Comment by G-White-ISB** [comment]
We made the choice to reference each series by the study id plus series number. We used to show the series id and that was removed on request.
