### ISSUE TITLE
"Clear all" does not reset any of the facet selection in dev

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#204]
Still see the below after even repeatedly clicking "Clear all"

![image](https://user-images.githubusercontent.com/313942/90404986-27b01980-e071-11ea-9da1-c51455a05f1c.png)

**Comment by fedorov** [comment]
Correction: none of the facets selected appear to be affected by "Clear all" in idc-dev.

**Comment by G-White-ISB** [comment]
should be fixed in next PR
