### ISSUE TITLE
Allow to load multiple selected series from the single study into OHIF

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#207]
Steve, I thought this is possible to select multiple series from a single study and load into OHIF, no?

**Comment by fedorov** [comment]
Related earlier issue #48

**Comment by pieper** [comment]
You can change the layout and see multiple studies, or you can drag and drop series into viewports.

Did you mean you want to specify multiple series as url parameters?  That is not currently possible so far as I know.

![image](https://user-images.githubusercontent.com/126077/90450465-c8c1c300-e0b7-11ea-8c2d-01a58a9facb7.png)

**Comment by fedorov** [comment]
@pieper what is then the interpretation of this comment from @swederik in https://github.com/ImagingDataCommons/IDC-WebApp/issues/48#issuecomment-600055075:

> The behaviour of the query parameter is controlled by an application configuration value (which is badly named...) called filterQueryParam. If True, the study will be filtered to show only the Series which is in the query string.

**Comment by pieper** [comment]
I take it to mean that the viewer can be configured in terms of how it interprets a series UID parameters.  Either it only shows those series or it shows them at the top of the series list above others in the study.

**Comment by fedorov** [comment]
Steve, would it be difficult to set that filterQueryParam parameter and test it so we can confirm the actual behavior?

**Comment by pieper** [comment]
Sure, the idc-sandbox is being deployed now with `filterQueryParam: false` (was true before).

I'm not sure of the format of the multiple seriesUIDs as URLParameters though.  Did you see it documented anywhere?

**Comment by swederik** [comment]
> I'm not sure of the format of the multiple seriesUIDs as URLParameters though. Did you see it documented anywhere?

I'm not 100% sure we every checked that this works. Let me check

**Comment by swederik** [comment]
It doesn't work. There was an open PR which apparently was closed by our stupid stale bot: https://github.com/OHIF/Viewers/pull/1533/files

I've reopened it.

**Comment by swederik** [comment]
The current PR uses commas to delimit different series. Is that okay? Or should we do it as multiple values separated by an ampersand (see the answer to this one: https://stackoverflow.com/questions/24059773/correct-way-to-pass-multiple-values-for-same-parameter-name-in-get-request)

> http://server/action?id=a&id=b

**Comment by pieper** [comment]
I think either commas or ampersand would work here, but whatever format seems like it would work best in general would be fine as far as I know.

**Comment by fedorov** [comment]
This has been fixed
