### ISSUE TITLE
Provide more space for the SeriesDescription column

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#208]
Currently all cols are spaced equal.

**Comment by fedorov** [comment]
This applies to all tables that have SeriesDescription column

**Comment by madelyngreyes** [comment]
@mitianisb Can we add this to the Study description column in the Selected Studies panel also?

<img width="712" alt="selected-studies sizing of columns" src="https://user-images.githubusercontent.com/16824894/94200426-6747fd80-fe88-11ea-983b-8f9a47b6b92f.PNG">

**Comment by mitianisb** [comment]
> @mitianisb Can we add this to the Study description column in the Selected Studies panel also?
> 
> <img alt="selected-studies sizing of columns" width="712" src="https://user-images.githubusercontent.com/16824894/94200426-6747fd80-fe88-11ea-983b-8f9a47b6b92f.PNG">

No problem! can do.

**Comment by fedorov** [comment]
On a related note, I do not see any reason in having the OHIF image in the right-most column. We could replace that logo that has no purpose with an eye icon and make space for content that is actually important. The header title for 
"Open Viewer" can be replaced with "Open", or "View".

**Comment by mitianisb** [comment]
I made some changes. It looks like this. I also tried folder open icon for camparision. Please let me know your feedback!
![Screen Shot 2020-09-24 at 4 25 24 PM](https://user-images.githubusercontent.com/58752821/94210422-8d1ed380-fe83-11ea-980d-9c46933f3276.png)
![Screen Shot 2020-09-24 at 4 25 46 PM](https://user-images.githubusercontent.com/58752821/94210453-9d36b300-fe83-11ea-99b0-67bce0990d33.png)

**Comment by fedorov** [comment]
IMHO - MUCH better, thank you! 

I like the eye icon better than the folder icon. The folder icon to me means open in file browser or something like that.

**Comment by wlongabaugh** [comment]
Eye is better, yeah.

**Comment by fedorov** [comment]
I am removing merge/testing needed, since I am assuming those do not apply anymore. Let's add those tags when the updates are in for the second half of the discussion.

**Comment by wlongabaugh** [comment]
What shows up for the non-viewable series?

**Comment by mitianisb** [comment]
This is the current look for non-viewable series:
![Screen Shot 2020-09-25 at 10 56 44 AM](https://user-images.githubusercontent.com/58752821/94316111-9f0e7e00-ff38-11ea-9447-57a14b1ee901.png)

I also tried eye slash for non-viewable series and removed the grey out. It looks like this:
<img width="1267" alt="Screen Shot 2020-09-25 at 2 06 32 PM" src="https://user-images.githubusercontent.com/58752821/94316508-52777280-ff39-11ea-94aa-2b17fc046530.png">

**Comment by fedorov** [comment]
> I also tried eye slash for non-viewable series and removed the grey out.

Much better! I would just move the tooltip a bit to the right.

Also, we should probably use more consistent styling for the tooltips throughout.

**Comment by madelyngreyes** [comment]
The current non-viewable series example below. 
<img width="960" alt="2020-10-14 (7)" src="https://user-images.githubusercontent.com/16824894/96016675-040e1300-0e17-11eb-8907-8218e5e044ad.png">

Should the tool-tip open to the right or to the left when using Google Chrome?

**Comment by mitianisb** [comment]
This is what we expect.  We are using a new tooltip system called tippy. It handles resizing window better so if the window width becomes too small to not hold the tooltip on the right, it will move it to the left. But by default if the window size is normal the tooltip is on the right side.
