### ISSUE TITLE
Better flow for the descriptions in the collections table

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#209]
Reduce the height of the descriptions

**Comment by fedorov** [comment]
I don't recall what this is about - has it been fixed? Do you remember, Suzanne?

**Comment by s-paquette** [comment]
This might predate breaking them out into a separate row.

**Comment by madelyngreyes** [comment]
Example of new description format below, 

<img width="958" alt="cohort_list_table-page" src="https://user-images.githubusercontent.com/16824894/96533303-a4bb6300-125b-11eb-99fa-e21d567e17a0.PNG">
