### ISSUE TITLE
Make facets lists sortable by either count or alphabetically

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#221]
Currently facets are sorted alphabetically only. Feature suggested by Ulli.

**Comment by madelyngreyes** [comment]
[Issue 4.7](https://docs.google.com/document/d/1MhsTLdfVa9knEWVhgdjCUKwev5ekXF-jiUAhhfHxAQY/edit#) from Tin's Test Report addressed in this issue.

**Comment by madelyngreyes** [comment]
For the filter option Derived tab Lobular Pattern, the sort by is not working as expected.

https://user-images.githubusercontent.com/16824894/118175049-9605ea80-b3fd-11eb-92d3-5754983af13a.mov

**Comment by s-paquette** [comment]
@G-White-ISB Can you have a look at this and confirm if it's still happening?
