### ISSUE TITLE
Mouse overs on menu wrong/missing

### ISSUE THREAD

**Issue by wlongabaugh** [ImagingDataCommons/IDC-WebApp#224]
Mouse over "documentation", text is copy of Discourse MO. Mouseover cohorts, nothing shows.

**Comment by madelyngreyes** [comment]
There is slight cut off of the border of the mouse over box. 

<img width="960" alt="2020-08-27 (7)" src="https://user-images.githubusercontent.com/16824894/91490405-67041480-e880-11ea-83a6-fdf4d6bde536.png">

**Comment by s-paquette** [comment]
Unrelated issue--would like to request a new ticket.

**Comment by s-paquette** [comment]
...note, this isn't happening to me. I suspect this is related to your monitor's zoom level. That's not really something we can develop to.

**Comment by madelyngreyes** [comment]
Will make a note in the existing zoom ticket and close this issue.
