### ISSUE TITLE
Use accurate stats counts for the front page

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#228]
Current counts at the bottom of the website do not correspond to the actual data offering in the MVP

**Comment by wlongabaugh** [comment]
Need to scan buckets for number.

**Comment by s-paquette** [comment]
@madelyngreyes @fedorov Can you let us know if these are correct.

**Comment by madelyngreyes** [comment]
Total cases count in the collections panel is 4,957 subject count while the homepage lists 3,230 cases. I created a quick spreadsheet that checks the sum of all subject count values. - https://docs.google.com/spreadsheets/d/1o9B2a2hBqq0cXXmpBcCkb3nRhlvO2X2Mjf4erITSk1I/edit#gid=0  


Another question I have is should we use the same verbiage across the platform e.g., to use either subject count or cases throughout the system?

**Comment by s-paquette** [comment]
@madelyngreyes  You need to drop the analysis collections from your totals--that's effectively counting some cases twice. Only count the primary collections.

**Comment by madelyngreyes** [comment]
Yes, I had noticed the some data is supplementary e.g., the first option is related to collection lidc_idri.  I'm able to return the correct count of 3,230 cases.

**Comment by fedorov** [comment]
I don't think we should drop analysis results from the counts. In fact, it will be good to highlight the number of cases/series that have analysis results in the front-page stats post-MVP.

I don't think the counts should be done based on the collections table, but instead directly on the BQ table with the metadata corresponding to the collections we include.

So I think the counts we should be showing should be the following queries:

```
SELECT count(distinct(collection_id)) FROM `canceridc-data.idc_views.dicom_all` 

SELECT count(distinct(PatientID)) FROM `canceridc-data.idc_views.dicom_all` 

SELECT count(distinct(SeriesInstanceUID)) FROM `canceridc-data.idc_views.dicom_all` 
```

All of them match what we have on the front page, with the exception of collections number.

It is debatable if the count for the collections we should have on the front page should be reflecting the number of all collections, or primary collections.

**Comment by fedorov** [comment]
Analysis vs original counts issue is tracked in #292
