### ISSUE TITLE
Add IDC funding acknowledgments at the bottom of the front page

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#229]

**Comment by s-paquette** [comment]
@fedorov Where can I get copy for this?

**Comment by fedorov** [comment]
At the bottom of https://imagingdatacommons.github.io/

**Comment by mitianisb** [comment]
I added acknowledgements at the front page. Please let me know if you have any feedback. Thanks!
![Screen Shot 2020-09-02 at 5 08 08 PM](https://user-images.githubusercontent.com/58752821/92049437-513e9580-ed3f-11ea-96f4-0b3134d9885d.png)

**Comment by madelyngreyes** [comment]
Text matches the current IDC webpage. 

<img width="926" alt="text matches" src="https://user-images.githubusercontent.com/16824894/93103972-465afd80-f67b-11ea-8d0c-9f64576f1235.PNG">
<img width="378" alt="matching text" src="https://user-images.githubusercontent.com/16824894/93103973-46f39400-f67b-11ea-956d-99a58268ba83.PNG">
