### ISSUE TITLE
Resolve duplicate names for Digital Mammo Class names

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#233]
Right now there are 2 duplicate entries under object class with the name "Digital Mammography X-Ray Image".

Most likely, this is because the names are incomplete - see http://dicom.nema.org/medical/dicom/current/output/chtml/part04/sect_B.5.html#sect_B.5.1.2, one should probably be " - for Processing", and the other " - for Presentation".

**Comment by s-paquette** [comment]
It looks like this happened to a LOT of them, actually. I think that's because the original table I was pointed at didn't break them out like this. Do we have a table that does? This page has them broken up, unfortunately.

**Comment by s-paquette** [comment]
Note, this table also has VERY different, and much *longer* text values than the first one I was pointed to. Do we want to go with these? They're going to look awkward on the UI.

**Comment by fedorov** [comment]
Indeed, the tables I earlier suggested in https://github.com/ImagingDataCommons/IDC-WebApp/issues/131#issuecomment-647865078 to use for this purpose do not have this distinction. We do not have an alternative table that has this distinction.

**Comment by G-White-ISB** [comment]
This seems to be resolved for now? We are using the longer Class name values such that the two Digital Mammo Classes have distinct names

**Comment by fedorov** [comment]
yes, this is resolved in test.
