### ISSUE TITLE
Define organization of the revised Solr table

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#236]
This is a follow up on https://github.com/ImagingDataCommons/IDC-WebApp/issues/212

@s-paquette:

> Going forward we'll want to reformat the data we count to be central to the kind of counting we're doing, i.e., if we're counting cases, the records need to be by-case and all duplicated fields combined into either a single text field (for strings) or multi-valued fields with a delimiter (for numerics).

The question is how to structure this table considering that for a given case we can have multiple kinds of measurements, and for individual measurement we can have multiple instances of measurement, and within a given case we can have multiple structures that have multiple instances of those measurements. We need to decide on how to flatten this hierarchy.

**Comment by s-paquette** [comment]
So, before we even do this, we need to define what we want our facets to result in. (This is what Justin and Ulrika were getting at on the call with them the other day.)

- If I select an Original facet like modality, does it:
 - Select all cases which have instances with that modality, and then do faceted counts for *all* instances in those cases?
 - Select all cases which have instances with that modality, and then do faceted counts *only for instances which match the filters* in those cases?

- How does this interact with derived filters for counting?

- How does this interact with related filters for counting?

**Comment by s-paquette** [comment]
Note, this is the flip side of wanting to select, eg., BodyPartExamined=Chest but still see the Modality=SR records. We only get those because we 'subquery' the Study.

That's a way to handle it, maybe; we make the data *study* centric, and count cases. This might get you what you're after.

**Comment by fedorov** [comment]
Related to #144

**Comment by s-paquette** [comment]
This work was completed as part of the v2 data release.
