### ISSUE TITLE
Harmonize icons used in the header of the website

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#237]
This is follow up on https://github.com/ImagingDataCommons/IDC-WebApp/issues/230#issuecomment-682060625.

Suggestion is to pick all icons that show up on the top of the front page from the same icon set.

**Comment by fedorov** [comment]
@s-paquette let me know if you would like me to suggest specific ones from https://fontawesome.com/icons?d=gallery&m=free.

Potentially:
* exploration: https://fontawesome.com/icons/eye?style=regular
* collections: https://fontawesome.com/icons/copy?style=solid or https://fontawesome.com/icons/stream?style=solid

**Comment by s-paquette** [comment]
So I managed to find the GDC icon set. We could in fact just use those. The GDC Portal is using them at the moment, if you want to have a look:

https://portal.gdc.cancer.gov/

**Comment by fedorov** [comment]
With all my admiration of many features of GDC, I have to admit that in this case the icons we have in FontAwesome look much better to me than below - they seem too tiny and pale. But I can live with those too. Your call.

![image](https://user-images.githubusercontent.com/313942/91492702-15f61f80-e884-11ea-8fde-c41da5639404.png)

**Comment by s-paquette** [comment]
The size we can definitely adjust. For some weird reason GDC is using microscopic sizing. It's more than a little baffling.

Here's what it looks like using their icons at a more reasonable size:

![image](https://user-images.githubusercontent.com/8442808/91496772-95c6be80-e871-11ea-8c0b-86d967e291f2.png)

**Comment by mitianisb** [comment]
I found the discourse (fa-comments) and documentation (fa-book) icons are from FontAwesome 4.0.3 we are using. The collections and exploration icons are from gdc-icons. I found two in FontAwesome to replace them (fa-th-list and fa-eye), so they will all be from the same icon set. It look like this:
![image](https://user-images.githubusercontent.com/58752821/91940616-982f7b00-ecac-11ea-84a7-fa97d2cd7ac3.png)
This is the current webpage:
![image](https://user-images.githubusercontent.com/58752821/91940784-dfb60700-ecac-11ea-8d8a-3552147dee46.png)
Please let me know of how you think. Thanks!

**Comment by fedorov** [comment]
FWIW I like the new set of icons better. Thanks for putting together this experiment!
