### ISSUE TITLE
text cut-off from the selected studies panel when working with the collection qin_headneck 

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#239]
When working with the collection qin_headneck, there is text cut-off in the Selected Studies panel.

<img width="960" alt="2020-08-27 (8)" src="https://user-images.githubusercontent.com/16824894/91490979-51431f00-e881-11ea-925a-ae794d2e3bf7.png">

**Comment by G-White-ISB** [comment]
I have also observed the Study table being cut off or shorter than needed
to display all the expected rows. However I have not tracked down
conditions to reproduce and it seems random right now. It seems to fix
itself by selecting a new page or reordering the Study records.
George

**Comment by G-White-ISB** [comment]
Testing needed (dev.090920201505.377d44). No specific action on this but I am not able to reproduce it anymore. If you encounter this problem please try to reproduce and document steps to reproduce.

**Comment by madelyngreyes** [comment]
There is still text cutoff on my laptop when using Google Chrome at 80% zoom unfortunately. This is visible for both the Selected Series and the Selected Studies panel. 

<img width="960" alt="2020-09-14 (2)" src="https://user-images.githubusercontent.com/16824894/93112986-9db29b00-f686-11ea-8feb-871f1c5c525a.png">


<img width="960" alt="2020-09-14 (3)" src="https://user-images.githubusercontent.com/16824894/93112983-9d1a0480-f686-11ea-9112-7c378505f71a.png">

**Comment by fedorov** [comment]
Should try to reproduce at 100% zoom

**Comment by fedorov** [comment]
Comfirmed works fine at 100%
