### ISSUE TITLE
On the homepage the collaborators link points to the privacy policy

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#242]
At the bottom of the page the Collaborators link points to the privacy policy

![collaborators link broken](https://user-images.githubusercontent.com/16824894/91584830-37591900-e921-11ea-8b63-d0147b8ede0d.PNG)

**Comment by wlongabaugh** [comment]
Placeholder till we get collaborators list up.

**Comment by s-paquette** [comment]
@fedorov Do we have text and logos for this yet?

**Comment by fedorov** [comment]
@s-paquette that's been tracked here: https://github.com/ImagingDataCommons/IDC-WebApp/issues/169

I think most responded with the logos

**Comment by s-paquette** [comment]
Thank you! @mitianisb Feel free to use the privacy policy page's core as a template for this.

**Comment by mitianisb** [comment]
![image](https://user-images.githubusercontent.com/58752821/93124942-43620c00-f67f-11ea-945c-180be73a9d88.png)
Hi all, I have implemented the collaborator page, can you give feedback on the following?
- The logos are in alphabetical order, do we want a different order?
- The Isomics logo has a white background, do we want to remove the background?
- I was not able to find the logo of Radical Imaging in the reply above. So I took it from its website. It has a black background, do we want to use a different one?
- Is there any style change we want?

Thanks!

**Comment by fedorov** [comment]
Would it be possible to arrange them such that they are center -aligned, and there is more space around individual logos? It looks way too cramped right now.

**Comment by fedorov** [comment]
See example here https://cloud.google.com/ or here https://mlperf.org/

**Comment by mitianisb** [comment]
No problem, I will give it try and send a new screenshot.

**Comment by mitianisb** [comment]
@fedorov I made the changes and I think it look better now. I changed the order (moved mgb to first row) so that the two rows align better. Please let me know if you have any further suggestion. Thanks!

![image](https://user-images.githubusercontent.com/58752821/93296017-39d1c480-f7a3-11ea-83ed-ba5de0f6426b.png)

**Comment by fedorov** [comment]
Thank you, this is much better.

I think ISB logo is missing from the list. It shoud be added, and also the first line should list MGB, ISB and GDIT in that oder.

**Comment by mitianisb** [comment]
Got it. This is the new look.

![image](https://user-images.githubusercontent.com/58752821/93390366-6ed12c00-f822-11ea-8300-af61770bfc0b.png)

**Comment by madelyngreyes** [comment]
Looks great!

**Comment by s-paquette** [comment]
Is there a reason this is reopened?

**Comment by fedorov** [comment]
My guess is Madelyn wanted me to confirm, and indeed it looks great to me. Thank you @mitianisb!

**Comment by fedorov** [comment]
Sorry, I do have one more nit-pick ... Can we change "Collaborators" to "Team" or something like that?

**Comment by mitianisb** [comment]
Sure, maybe change to "partners" like in ISB-CGC? https://isb-cgc-test.appspot.com/about/

**Comment by madelyngreyes** [comment]
Yes, I just wanted Andrey to confirm mainly.

**Comment by fedorov** [comment]
@mitianisb I emailed few other team members to seek feedback, let's wait to hear back, if it's ok.

**Comment by fedorov** [comment]
How does everyone feel about renaming that section from "Collaborators" to "Development team"?

**Comment by madelyngreyes** [comment]
Development team feels a bit internal. What do you think about the term "Partners"?

**Comment by fedorov** [comment]
Team includes funded members, Collaborators is Google. Top-level title is "Team and Collaborators".

**Comment by mitianisb** [comment]
@fedorov @madelyngreyes Does this look ok?

![image](https://user-images.githubusercontent.com/58752821/93815937-a7e71300-fc0b-11ea-9fe2-9d5e71e541e8.png)

**Comment by madelyngreyes** [comment]
Looks good to me!

**Comment by fedorov** [comment]
I would make the logos larger a bit, but either way is ok with me. Thanks!

**Comment by mitianisb** [comment]
It's easy to change. @fedorov Is this size ok?
![image](https://user-images.githubusercontent.com/58752821/94043453-ccfd9200-fd81-11ea-8e6b-f9a764c6140d.png)

**Comment by fedorov** [comment]
Great, let's have it merged!
