### ISSUE TITLE
IDC local login reset password functionality improvements 

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#246]
When an end user uses the local login to reset the password a ">" appears on the reset confirmation page. 

<img width="960" alt="2020-09-01 (5)" src="https://user-images.githubusercontent.com/16824894/91914040-327bc880-ec85-11ea-9272-add90c6b1997.png">

**Comment by s-paquette** [comment]
@madelyngreyes Can you check this again?

**Comment by madelyngreyes** [comment]
The arrow is still visible on the dev tier. 

<img width="960" alt="password reset arrow still present on the dev tier" src="https://user-images.githubusercontent.com/16824894/92752122-a3db0b80-f356-11ea-9e82-f12261c32a71.PNG">

**Comment by madelyngreyes** [comment]
<img width="960" alt="password reset" src="https://user-images.githubusercontent.com/16824894/93493199-a4851c00-f8d9-11ea-8189-6e6fdc3b9168.PNG">

The Password reset box looks much better! But, the footer of the web page is in the middle of the page. If that is expected we can close the ticket. @s-paquette

**Comment by s-paquette** [comment]
Okay, try now. Stray > should? be gone.

The footer is up there due to page-height being a difficult thing to force. Post MVP fix.
