### ISSUE TITLE
Sign-in link from Change Password confirmation page unresponsive 

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#247]
After an end-user finalizes the password has been changed, they are sent to a Change Password confirmation page. If an end-user selects the Sign In link in the top right, nothing happens. Unfortunately, no errors in the DEV console appeared during this test run. 

<img width="960" alt="2020-09-01 (8)" src="https://user-images.githubusercontent.com/16824894/91914405-f7c66000-ec85-11ea-9d71-891463957cd8.png">

**Comment by s-paquette** [comment]
@madelyngreyes  Can you give this another shot now on dev?

**Comment by madelyngreyes** [comment]
After going to the reset password email link and entered a new password. I was able to select the login link, then login with my IDC local login credentials. 

But, I was then sent to a Verify your e-mail address page. I verified the email madelyngreyes@gmail.com on Tuesday, Sept 15 in the afternoon ET while testing. The email "should" be in the system as verified. Does this need a new ticket? @s-paquette

**Comment by s-paquette** [comment]
That's because we've wiped the database several times, probably causing that verification to be lost. Check it again with the current database (you may need to re-register, etc.)

And yes if it *is* a bug please make a new ticket; this ticket is specifically for lack of sign-in drop-down functionality on pages other than the landing page.

**Comment by s-paquette** [comment]
@madelyngreyes Okay fix for this should be in. Please note Google is being very sluggish to update CSS and JS from the static folder; empty cache and hard reload may be needed.

**Comment by madelyngreyes** [comment]
I just tried to login after I reset the password, and verified my email address. When I went to login I then returned the error message, "Only members of the idc_team group may access the development server."

<img width="960" alt="2020-09-21 (1)" src="https://user-images.githubusercontent.com/16824894/93792937-293aa780-fc04-11ea-9d7c-f02d4b2dc17d.png">
