### ISSUE TITLE
Email verification page slight text modification for local login functionality 

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#248]
On the email verification page, currently the first sentence uses email with a hyphen e.g., e-mail. Current text example below,

"We have sent an e-mail to you for verification. Follow the link provided to finalize the signup process.
If you do not receive the email within a few minutes, check your spam folder. Registration confirmation emails are often flagged as potential spam.
If the email hasn't arrived and isn't in your spam folder, please contact us for assistance."

We should decide on if we would like to use e-mail or email for this page in order to keep consistency if time permits pre-MVP. 

<img width="960" alt="2020-09-01 (10)" src="https://user-images.githubusercontent.com/16824894/91915609-03ffec80-ec89-11ea-9a40-b3422475c851.png">

**Comment by s-paquette** [comment]
Templates location: https://github.com/ImagingDataCommons/IDC-WebApp/tree/master/templates/accounts

**Comment by mitianisb** [comment]
I noticed we have been using "e-mail" in most places, and only here we had "email". I have changed them to be "e-mail" to be consistent.

**Comment by madelyngreyes** [comment]
Text has been updated. - https://idc-dev.appspot.com/accounts/confirm-email/
