### ISSUE TITLE
TCGA filters not applied to Studies Table

### ISSUE THREAD

**Issue by G-White-ISB** [ImagingDataCommons/IDC-WebApp#251]
As an example the filter

COLLECTION IN (tcga_brca) AND MODALITY IN (Mammography)

shows 5 cases. The filter

COLLECTION IN (tcga_brca) AND MODALITY IN (Mammography) ANDTCGA.HISTOLOGICAL TYPE IN (Infiltrating Lobular Carcinoma)
shows 2 cases. However opening the studies for these cases yields 5 cases. The URL called to fetch the studies is below. It seems to be correct:

 http://localhost:8085/explore/?counts_only=False&is_json=True&with_clinical=False&collapse_on=StudyInstanceUID&filters=%7B%22Modality%22:%5B%22MG%22%5D,%22histological_type%22:%5B%22Infiltrating%20Lobular%20Carcinoma%22%5D,%22collection_id%22:%5B%22tcga_brca%22%5D%7D&fields=%5B%22collection_id%22,%22PatientID%22,%22StudyInstanceUID%22,%22StudyDescription%22,%22StudyDate%22%5D&order_docs=%5B%22collection_id%22,%22PatientID%22,%22StudyInstanceUID%22%5D

**Comment by s-paquette** [comment]
...maybe I'm confused but I thought filters weren't being applied to study and series tables?

**Comment by s-paquette** [comment]
Found the issue, though, if we DO want to filter those. You're passing in `with_clinical=False` which implicitly indicates you don't want to use those filters.

**Comment by G-White-ISB** [comment]
I thought with_clinical=False means we don't return clinical data in the
records, not that we disable clinical filters.
George

**Comment by s-paquette** [comment]
We never return clinical records, not being a clinical data node. ONLY Original set data is ever returned as records; `with_clinical` and `with_derived` provide toggles for leaving those data types (and any sources related to them) out of all filters and counting.

**Comment by s-paquette** [comment]
Sorry, wrong button!

**Comment by s-paquette** [comment]
(I can, if you want, adjust them to leave the data types out of counting but not filters, though a) I'm not sure of a case where you'd want that and b) it would have to be post MVP.)

**Comment by G-White-ISB** [comment]
I would not worry about it. I'll adjust the front end call.
George

**Comment by G-White-ISB** [comment]
Testing needed Application Version: dev.090920201037.46fd5a

**Comment by madelyngreyes** [comment]
Waiting for collections panel fix to test filter set originally mentioned in first comment. https://github.com/ImagingDataCommons/IDC-WebApp/issues/287

**Comment by s-paquette** [comment]
@madelyngreyes Is there a reason the Search scope filter needs to work to test this? They're not related issues. You can check by using any of the derived filters (which won't apply to TCGA).

**Comment by madelyngreyes** [comment]
I mainly just wanted to test the filter options George mentioned in the first comment as well.

**Comment by madelyngreyes** [comment]
To follow the original test case reported by George, the studies should now return five or seven entries?  I'm currently reporting seven entries in the studies panel. 
<img width="940" alt="seven entries on selected studies panel" src="https://user-images.githubusercontent.com/16824894/93398733-1f065b00-f84a-11ea-9926-4ff44a56c436.PNG">

@G-White-ISB Is this expected?
