### ISSUE TITLE
Edit sapien raw svg to exclude extra body parts

### ISSUE THREAD

**Issue by s-paquette** [ImagingDataCommons/IDC-WebApp#253]
Location: https://github.com/ImagingDataCommons/IDC-WebApp/tree/master/static/js/sapien

Can comment out the unneeded sections, or delete? (Various options go here.)

**Comment by madelyngreyes** [comment]
Screenshot of all options listed on the landing page. 

<img width="340" alt="All primary sites available in the landing page" src="https://user-images.githubusercontent.com/16824894/93110635-96d65900-f683-11ea-8783-2014938e5705.png">
