### ISSUE TITLE
Add 'chest' SVG entry to sapien raw svg

### ISSUE THREAD

**Issue by s-paquette** [ImagingDataCommons/IDC-WebApp#254]
Might be able to draw with Adobe Illustrator?

**Comment by madelyngreyes** [comment]
On the landing page the count for Chest filter is 2,120 cases but, when you go to the data portal the primary site location has 1,079 cases present for the Chest filter option.

<img width="960" alt="2020-09-14 (1)" src="https://user-images.githubusercontent.com/16824894/93110971-00566780-f684-11ea-859f-c337a151e871.png">

<img width="949" alt="1079 cases in the data portal" src="https://user-images.githubusercontent.com/16824894/93110985-03515800-f684-11ea-8ad8-5e24c241df22.PNG">

**Comment by mitianisb** [comment]
I have integrated a new chest image from Allison and it looks like this now, also with a new color.
![image](https://user-images.githubusercontent.com/58752821/93294422-4d7b2c00-f79f-11ea-8d3c-43bf9a754033.png)

@madelyngreyes Are the count in other body parts correct? I am not familiar with how the count are calculated (maybe @s-paquette knows more). It also is different in my explore page (chest is 1185). Maybe we should create a separate ticket to look into the count numbers?

**Comment by s-paquette** [comment]
@madelyngreyes Counts on the homepage are in another ticket, though those have been fixed as well.

**Comment by madelyngreyes** [comment]
Thank you, do you have the ticket number handy I should be looking at?
