### ISSUE TITLE
Click on Landing Page Bar Goes to Explorer With That Filter

### ISSUE THREAD

**Issue by wlongabaugh** [ImagingDataCommons/IDC-WebApp#255]
E.g. click on Brain on the Landing page takes you to brain in the Explorer. Need to be able to launch the Explorer with a specified filter set.

**Comment by fedorov** [comment]
Landing page summarizes cancer location (as in "Location" in this table https://www.cancerimagingarchive.net/collections/), which is available in the BQ tables but is not currently exposed in the portal UI. BodyPart shown in the portal UI and extracted from DICOM metadata is not the same as the cancer Location, which is a collection-level attribute not stored in DICOM metadata.

**Comment by G-White-ISB** [comment]
Also, where do any of the numbers in the 'Cases by Major Primary Site
Chart' come from?
George

**Comment by fedorov** [comment]
One place where those can be found is `canceridc-data:idc.data_collections_metadata`, but I will let @s-paquette comment where she is getting them from for the front page.

**Comment by s-paquette** [comment]
The numbers in the chart are coming from the collections metadata table, and not from a specific counting query done against the dicom_all dataset.

**Comment by s-paquette** [comment]
The `tcia_tumorLocation` filter can be used for this.

**Comment by s-paquette** [comment]
Note, tcia_tumorLocation is now available for filtering under the Original tab as 'Primary Site Location' on dev.

**Comment by mitianisb** [comment]
@madelyngreyes I have completed and merged the code change. Clicking the bar, label, or body part will go to explore page automatically with the body site pre-selected. But to test this now you need to log in first. Later when we remove login requirement on Explore page this can be tested directly without log in, similar to #276 .

**Comment by madelyngreyes** [comment]
There is a bug with the selection of the value Head and Neck, ticket related to issue https://github.com/ImagingDataCommons/IDC-WebApp/issues/392.

**Comment by mitianisb** [comment]
@madelyngreyes The fix is on the dev tier now. Thanks for finding this out!

**Comment by madelyngreyes** [comment]
Anytime I also just noticed the selection of Head and Neck from the sapien figure itself it is not working as expected. I have attached a video.  - https://screencast-o-matic.com/watch/cY6DqV7t9f

**Comment by fedorov** [comment]
Clicking on head-neck in the sapien figure works for me the same way as clicking on the chart, and as expected. Seems to be resolved to me on the dev tier. Let's get it into prod.
