### ISSUE TITLE
cursor blocks text in the Search Results panel for filter options on the Exploration page

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#266]
On the Search Results panel it seems the cursor blocks the first letter in the filter option being hovered over. I have attached the URL to a video for reference. 

https://screencast-o-matic.com/watch/cYQQ3MH8YV

**Comment by G-White-ISB** [comment]
I have not seen that. What is your OS and browser?

**Comment by madelyngreyes** [comment]
The system is Windows 10 Pro version 1909, the browser I was using in the case above is Google Chrome.

**Comment by s-paquette** [comment]
This is likely due to your zoom level--can you set your monitor to 100% and see if it's still hapenning?

**Comment by s-paquette** [comment]
(I'll note, in checking my laptop--1920x1080, 100% and 125%, Windows 10, Chrome 85--I can't replicate this behavior.)

**Comment by madelyngreyes** [comment]
At 100% zoom seems to be working as expected. 
<img width="960" alt="2020-09-15 (2)" src="https://user-images.githubusercontent.com/16824894/93235802-0a439d80-f74c-11ea-91d8-3b28e0ab89eb.png">

**Comment by fedorov** [comment]
fixed
