### ISSUE TITLE
Do not use same/similar colors for adjacent segments of the piechart

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#267]
This is what I get with the following configuration:

![image](https://user-images.githubusercontent.com/313942/92737417-1ba23980-f349-11ea-9e9a-94af1a8542fa.png)

**Comment by G-White-ISB** [comment]
I have not been able to replicate. What is your filter definition here?

**Comment by G-White-ISB** [comment]
Sorry I was looking under Body Part Examined. I have replicated this.

**Comment by G-White-ISB** [comment]
Testing needed (dev.120920201915.f0fa04)

**Comment by madelyngreyes** [comment]
New color scheme.
<img width="960" alt="2020-09-14 (26)" src="https://user-images.githubusercontent.com/16824894/93135871-fdba3900-f6a8-11ea-9ac9-be11955ba32c.png">

**Comment by fedorov** [comment]
This is still a problem as of today in prod:

![image](https://user-images.githubusercontent.com/313942/95391239-be0bf900-08c4-11eb-8141-ae48a6fa6116.png)

**Comment by madelyngreyes** [comment]
Anatomic region attribute selection, body part examined color schema example below: 
![body part examined color schema](https://user-images.githubusercontent.com/16824894/96508645-ec74c700-1228-11eb-80d7-23ca30ae1877.PNG)

Diameter(millimeter) color schema on the production tier example below: 
![diameter pie chart](https://user-images.githubusercontent.com/16824894/96508754-14fcc100-1229-11eb-9452-2aeb44219c6b.PNG)
