### ISSUE TITLE
Collection counts are not updated

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#269]
Reproducible with the configuration below. The only counts that are updated are collections under TCGA

![image](https://user-images.githubusercontent.com/313942/92739942-59a05d00-f34b-11ea-9299-52dfb030ed52.png)

**Comment by madelyngreyes** [comment]
Seems to be working as expected now. 
<img width="938" alt="selection of body part examined breast working as expected" src="https://user-images.githubusercontent.com/16824894/93103642-e3696680-f67a-11ea-8b12-a2c8f2f67974.PNG">
