### ISSUE TITLE
Piecharts appear disorganized on smaller page width

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#270]
Maybe the size should scale down, or they should be aligned better when changing page width?

![image](https://user-images.githubusercontent.com/313942/92751447-f831bb80-f355-11ea-9eda-b9f00b92912e.png)

**Comment by G-White-ISB** [comment]
I'm trying a different layout (dev.120920201915.f0fa04).

**Comment by madelyngreyes** [comment]
Formatting has greatly improved, screenshot below is from when using Google Chrome at 110% zoom. 

<img width="960" alt="2020-09-14 (23)" src="https://user-images.githubusercontent.com/16824894/93135075-bd0df000-f6a7-11ea-92f9-79d0272cde85.png">
