### ISSUE TITLE
Add TCIA data usage terms

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#272]
We should add a link to the TCIA usage terms at the bottom of the front page.

"Data hosted by IDC is subject to the [TCIA Data Usage License and Citation Requirements](https://wiki.cancerimagingarchive.net/x/c4hF)"

Once we have data from sources other than TCIA we will need to update this.

p.s. This was agreed upon with @wlongabaugh and our stakeholders.

**Comment by madelyngreyes** [comment]
<img width="960" alt="2020-09-14 (20)" src="https://user-images.githubusercontent.com/16824894/93128424-74513980-f69d-11ea-92cc-ffb667d79b28.png">

**Comment by fedorov** [comment]
@madelyngreyes it is not clear from the screenshot - can you confirm if that is a link, or just a text?

**Comment by fedorov** [comment]
never mind, I see it is a link
