### ISSUE TITLE
Google Analytics setup

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#273]
Would it be possible to set up google analytics tokens for the portal?

The Analytics account for IDC has been setup, and @s-paquette should have admin rights to create a property.

**Comment by fedorov** [comment]
I will add the token

**Comment by fedorov** [comment]
@s-paquette here's the property ID for the portal: UA-151885665-5

**Comment by wlongabaugh** [comment]
Production only; waiting until production is released.

**Comment by fedorov** [comment]
we are getting analytics for the tracking ID above
