### ISSUE TITLE
Save filters when user logs in after selecting them and re-apply to explorer

### ISSUE THREAD

**Issue by s-paquette** [ImagingDataCommons/IDC-WebApp#276]
As is done in ISB-CGC, when a user is not logged in and selects filters, the 'Save as Cohort' button should be a 'Log in To Save' button. If the user goes to log in, their filters should be saved in localStorage and then applied after login is successful and they're re-directed to the explorer page.

This can be done the same way as ISB-CGC, so re-use of that code (with adjustments for our layout) should work. I have some tweaks to make to the explorer page JS to provide a simple hook for detecting re-applied filters on load, and then we'll be good to go.

**Comment by mitianisb** [comment]
Hi @s-paquette, I tried to apply my code from CGC to here and noticed the checkboxes do not have ID available to save and load back like in CGC (in CGC it has format like FEATURENAME_VALUENAME_PROGRAMNAME). Is this something you are working on? I can try add them but not sure if it would conflict with your change. Thanks!

**Comment by s-paquette** [comment]
@mitianisb Ah ha, yes I just merged in a fix for this, you'll need to grab Common master *and* IDC-WebApp.

**Comment by s-paquette** [comment]
Note, this can't be tested until we remove the login requirement from the explorer page.

**Comment by fedorov** [comment]
This does not work in production. If I form a filter, and then log in to save the cohort, the filter is reset. Is it expected to work in production?

**Comment by mitianisb** [comment]
Thanks for the report @fedorov. When the change was initially merged, my local test showed it working as expected. I just tried and it does not work anymore. I will debug this today and hope can have a fix soon. Thanks!
