### ISSUE TITLE
Slider updates are all broken

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#282]
On the dev tier, if you select the filter option GLYCOLYSIS WITHIN FIRST QUARTER OF INTENSITY RANGE (GRAM)  80 - * doesn't update the pie chart to the filter option selection. I have attached a video for reference. 

https://screencast-o-matic.com/watch/cYQ2DpJY7B

**Comment by madelyngreyes** [comment]
Also, the filter option is displayed as 80-279 in the Filter Definition panel but, is displayed as 80-* in the pie chart. 

<img width="960" alt="2020-09-14 (5)" src="https://user-images.githubusercontent.com/16824894/93113989-01899380-f688-11ea-89fa-400c42aed39b.png">

**Comment by G-White-ISB** [comment]
This is since the latest deployment. Investigating this morning.

**Comment by G-White-ISB** [comment]
Yeah the '_btw' or sliders are not working with the new backend. 
Request:
http://localhost:8085/explore/?counts_only=True&is_json=true&is_dicofdic=True&data_source_type=S&filters=%7B%22Diameter_btw%22:%5B16,50%5D%7D

Stack Trace:

Traceback (most recent call last):
  File "/home/vagrant/www/IDC-Common/idc_collections/collex_metadata_utils.py", line 332, in get_collex_metadata
    results = get_metadata_solr(filters, fields, sources, counts_only, collapse_on, record_limit, facets, records_only)
  File "/home/vagrant/www/IDC-Common/idc_collections/collex_metadata_utils.py", line 380, in get_metadata_solr
    ) if filters else None
  File "/home/vagrant/www/IDC-Common/solr_helpers/__init__.py", line 458, in build_solr_query
    elif len(values) >= 1 and re.match(r'\d+ [tT][oO] \d+', values[0]):
  File "/usr/lib/python3.5/re.py", line 163, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object
[ERROR] @2020-09-14 11:04:46,332 in collex_metadata_utils/2717/140159914448640 - [ERROR] While attempting to load the search page:
[ERROR] @2020-09-14 11:04:46,332 in collex_metadata_utils/2717/140159914448640 - local variable 'results' referenced before assignment
Traceback (most recent call last):
  File "/home/vagrant/www/IDC-Common/idc_collections/collex_metadata_utils.py", line 123, in build_explorer_context
    collapse_on=collapse_on, order_docs=order_docs, sources=sources, versions=versions
  File "/home/vagrant/www/IDC-Common/idc_collections/collex_metadata_utils.py", line 355, in get_collex_metadata
    return results
UnboundLocalError: local variable 'results' referenced before assignment
Internal Server Error: /explore/

**Comment by s-paquette** [comment]
Sorry, thought I'd merged this in. It's now on master Common if you want to try it out locally.

**Comment by G-White-ISB** [comment]
Where would I pull from? The last commit to IDC-Common master was 3 days
ago and I am up to date, also up to date on IDC-WebApp.
George

**Comment by s-paquette** [comment]
Yes, apparently my PR didn't go through. Try now-- a pull from Common master.

**Comment by madelyngreyes** [comment]
The Search configuration panel matches the filter definition selection when an option is selected from the pie chart.  

There is slight text overlap in the left with certain filter selection options, e.g., GLYCOLYSIS WITHIN FIRST QUARTER OF INTENSITY RANGE (GRAM) range 30-40. 
<img width="960" alt="2020-09-17 (1)" src="https://user-images.githubusercontent.com/16824894/93521406-05bee680-f8fe-11ea-94f1-429a6051824e.png">

The pie chart displays all options available as expected for this release.

**Comment by G-White-ISB** [comment]
testing needed (Application Version: dev.180920201050.e8edab)

**Comment by madelyngreyes** [comment]
There still seems to be text overlap with the selection of the filter option, "GLYCOLYSIS WITHIN FIRST QUARTER OF INTENSITY RANGE (GRAM)" in 20-30. 

<img width="960" alt="2020-09-18 (18)" src="https://user-images.githubusercontent.com/16824894/93636478-03be5b80-f9c2-11ea-9b3f-130854e4ad5a.png">

**Comment by madelyngreyes** [comment]
Also, now when I selected the option 80-*, the count was 80-279 in the Filter Definition panel. Then in the Search Configuration panel the count was represented as 0-300. 

<img width="960" alt="2020-09-18 (17)" src="https://user-images.githubusercontent.com/16824894/93636708-61eb3e80-f9c2-11ea-99d9-71457eea3cff.png">

Also, is there a range that can be set for the pie chart filters that are displayed as e.g., 80-* and *-10 instead of "*" as a value?
