### ISSUE TITLE
Selection of filter option from the Search Results pie chart panel doesn't enable the Save As New Cohort button

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#283]
When you select a filter option from the Search Results pie chart panel doesn't enable the save cohort button.

<img width="960" alt="2020-09-14 (7)" src="https://user-images.githubusercontent.com/16824894/93119097-35b48280-f68f-11ea-99aa-4cb161136147.png">

**Comment by G-White-ISB** [comment]
And the selection does not check the appropriate checkbox. Will fix ASAP
