### ISSUE TITLE
cohort doesn't apply filter selection on the cohort details page

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#284]
After you save a cohort the filters do not seem to be applied on the cohort details page. 

<img width="960" alt="2020-09-14 (11)" src="https://user-images.githubusercontent.com/16824894/93119945-a27c4c80-f690-11ea-8766-5ee97fc08976.png">

**Comment by s-paquette** [comment]
Can you let me know what filters this is happening for? Also please check the dev console--this is definitely implemented functionality, so I need to be able to sort out the actual bug.

**Comment by madelyngreyes** [comment]
I was able to reproduce this issue with body part examined Abdomen and Brain with Modality: Magnetic resonance filters.

The filter was added after I saved the cohort for a test run I just made this morning. Which wasn't being added yesterday.  

But, now I went to the cohort table list page, then selected the cohort I just created and the filters are no longer present in the Filter Definition panel. 

There is no error in the dev console unfortunately. 

<img width="960" alt="2020-09-15" src="https://user-images.githubusercontent.com/16824894/93235300-58a46c80-f74b-11ea-85a9-2f6f6cbbed45.png">

**Comment by s-paquette** [comment]
Got it--thank you! I'll see if I can get to the bottom of this.

**Comment by madelyngreyes** [comment]
I was also able to reproduce this by first the selection of a Modality: SR document from the Search Results panel pie chart. Then from the left Search configuration panel, I selected body part examined: Abdomen. Then going to save a cohort doesn't save the filters once you are sent to the cohort details page.

**Comment by s-paquette** [comment]
@bcli4d @mitianisb @G-White-ISB @wlongabaugh We could use some help with this one. I can't reproduce this bug no matter how hard I try. The bug is:

- Make a cohort (doesn't seem to matter what filters you use, though for sake of testing make sure to apply 2 or more)
- See if the cohort details page loads correctly (i.e. loads the filter set, disables all filter widgets)
- Click on 'Cohorts' in the top menu
- Attempt to reload that same cohort from this list page

On the load of the cohort details page *from the list page*, Madelyn's page load is halting, and we can't figure out why, particularly since mine isn't.

**Comment by s-paquette** [comment]
Okay. I think I've figured it out; it's a network lag issue surrounding the call to get the cohort-filtered counts (which is run after the page loads). Going to try a fix using jQuery deferred.

**Comment by s-paquette** [comment]
@madelyngreyes Ready for testing, please note Google is being very sluggish to update CSS and JS from the static folder; empty cache and hard reload may be needed.

**Comment by madelyngreyes** [comment]
I cleared my cookies and my cache through the settings and the filter selection again wasn't added to the save cohort details page. I created a video of the functionality I saw. 

https://screencast-o-matic.com/watch/cYQropdnVN

**Comment by s-paquette** [comment]
@madelyngreyes Can you try to reproduce this again?

**Comment by madelyngreyes** [comment]
I just tried with two cohorts and the filter selection I used didn't get applied to the cohort details page unfortunately. The cohort filters used were selected from the pie chart panel and listed in the cohort name, and in the cohort description section. 

<img width="960" alt="2020-09-25 (11)" src="https://user-images.githubusercontent.com/16824894/94301879-52777280-ff39-11ea-97bd-e1a040d6fd6e.png">
<img width="960" alt="2020-09-25 (10)" src="https://user-images.githubusercontent.com/16824894/94301881-53100900-ff39-11ea-974a-4e80daef12cb.png">
