### ISSUE TITLE
# of cases and # of samples not displayed on the cohort list table

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#285]
<img width="960" alt="2020-09-14 (12)" src="https://user-images.githubusercontent.com/16824894/93120142-e8391500-f690-11ea-993e-363c5c7cbdb4.png">

**Comment by madelyngreyes** [comment]
Also, there is text cut off when the cohort name is too long.

**Comment by madelyngreyes** [comment]
Another issue is also N/A being displayed for the Last Modified column when it should be a date and/or time.

**Comment by s-paquette** [comment]
This is not a bug; case and sample count won't be displayed. The columns *do* need to be removed, however.

**Comment by s-paquette** [comment]
@madelyngreyes Removed these, also re-ordered the cohorts table columns somewhat and added in description

**Comment by madelyngreyes** [comment]
There still seems to be some text cut-off in the cohort name panel. I have highlighted it in red below. 

<img width="960" alt="2020-09-17 (8)" src="https://user-images.githubusercontent.com/16824894/93539774-b5f11700-f91f-11ea-9213-c9ce7f5e95fb.png">

**Comment by s-paquette** [comment]
Different issue--new ticket, please. How we wrap the text for description and name is it's own thing

**Comment by madelyngreyes** [comment]
Should the column headers be in wrapped text format? At 67% zoom the header of the table is visible as one line but, at 90% zoom it's displayed as wrap text. In the original screen shot you will notice the header column displayed as one line. 

<img width="960" alt="2020-09-18 (3)" src="https://user-images.githubusercontent.com/16824894/93607146-f0e26180-f996-11ea-8529-ff7ce9ce9ce3.png">

**Comment by s-paquette** [comment]
Would prefer a different ticket for that as well, as it's a separate thing to look into.
