### ISSUE TITLE
Adjust the bucket ranges for quantitative filters

### ISSUE THREAD

**Issue by G-White-ISB** [ImagingDataCommons/IDC-WebApp#286]
Right now every bucket is 10 units 'wide' and the last bucket is '80 to *' regardless of the facet data. An example is Glycolysis in 2 Qrtr Range. The min value is 1.38, the max is 252, but the buckets are

* to 10
10 to 20 
...
70 to 80
80 to *
None

**Comment by s-paquette** [comment]
I need to know what we want the buckets to be. The by-10 and 80-max are simply defaults. @fedorov What would you like the bucket values to be for the pie-charts on the numeric attributes?

**Comment by G-White-ISB** [comment]
Maybe just decide on 10 even buckets between min and max?

**Comment by fedorov** [comment]
10 even buckets between min and max is fine with me.

I've just noticed that clicking of quantitative pie charts updates the filter definition but does not update the corresponding piechart content.

I do not know if this is expected or not.

![image](https://user-images.githubusercontent.com/313942/93142689-868aa200-f6b4-11ea-9182-9eb6a75a6426.png)

![image](https://user-images.githubusercontent.com/313942/93142707-91453700-f6b4-11ea-955f-583c97ff87ae.png)

**Comment by s-paquette** [comment]
Filters don't count against themselves, is the reason for this. Or, they shouldn't; not for counting purposes.

**Comment by fedorov** [comment]
I don't understand this, but we can review this tomorrow.

**Comment by fedorov** [comment]
Agreed that the behavior shown above for diameter is what we actually want to have for all filters. Agreed to investigate how much effort it will take to implement this. @s-paquette will follow up.

**Comment by fedorov** [comment]
Also agreed to put a tooltip with this explanation over an "i" icon: https://discourse.canceridc.dev/t/understanding-idc-portal-cohort-plots/81/7?u=fedorov

**Comment by G-White-ISB** [comment]
Further thoughts: probably the lowest bucket should start at 0 for all quant filters regardless of the actual lowest value? The 'Glycolysis within ... Quarter of Intensity..' filters should have the same buckets. In future iterations I might combine these onto one chart. Also the 'Percent with ...' filters should run from 0 to 100.

**Comment by s-paquette** [comment]
@fedorov @G-White-ISB Can you have a look at the quantitative batches now and tell me what you think? I did all of them as 0-max with 10 buckets, with two exceptions: I slightly customized Volume and Surface Area of Mesh due to how uneven those distributions were.

**Comment by madelyngreyes** [comment]
Is this what is expected for the pie chart values e.g., 151.213800000000002?

<img width="960" alt="2020-09-25 (1)" src="https://user-images.githubusercontent.com/16824894/94281564-c6efe880-ff1c-11ea-9dc5-05243a913f44.png">

**Comment by s-paquette** [comment]
That's happening because these are floats. It occurs to me that could make an issue with bucket inconsistency in terms of the slices (as they're calculated on the fly), so I'll swap these to integers for a fixed range.

**Comment by wlongabaugh** [comment]
Problem area: Standardized Metabolic Activity

**Comment by fedorov** [comment]
Sorry, I do not understand - why we cannot round those up for the presentation purposes?

If we swap for integers, it will not make sense for values with small ranges.
