### ISSUE TITLE
Search Scope Collection filter not working on the dev tier

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#287]
<img width="960" alt="2020-09-14 (18)" src="https://user-images.githubusercontent.com/16824894/93126132-ffc8cb80-f699-11ea-8ff5-e0b4272e95ef.png">

**Comment by G-White-ISB** [comment]
... and that is also a break from a recent commit. Will try and patch today.

**Comment by madelyngreyes** [comment]
Also, if we can remove the blue arrow from the ISPY1 collection since nothing is displayed after it's selected. 

<img width="238" alt="remove arrow from ispy1" src="https://user-images.githubusercontent.com/16824894/93127574-25ef6b00-f69c-11ea-8d49-88033352343c.PNG">

**Comment by madelyngreyes** [comment]
The selection of a collection that is not TCGA will cause the cases count to be zero in the Search Scope for TCGA. Then when you de-select the collection option select the collection TCGA still reflects zero cases. 

**Steps to reproduce** 
1. select collection ISPY1
2. count for TCGA cases count is zero 
3. de-select the ISPY collection selection
4. The count for TCGA will still reflect zero

<img width="944" alt="search scope panel TCGA collection count zero" src="https://user-images.githubusercontent.com/16824894/93529898-b59a5100-f90a-11ea-9297-749ec9bc55ac.PNG">

**Comment by s-paquette** [comment]
@madelyngreyes That's a different issue with its own ticket, which I would like to confine to that issue. Is the Search Scope filter otherwise working, even if the count display is off?

**Comment by madelyngreyes** [comment]
Yes, the only check box that is not a reflection of a case count after selection is the main "all" TCGA collection filter. Will close this ticket.
