### ISSUE TITLE
Disable Save As New Cohort when no data is available

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#288]
The filter options I have selected don't have any data available but, I was still able to select the Save As New Cohort button. 

<img width="960" alt="2020-09-14 (19)" src="https://user-images.githubusercontent.com/16824894/93127276-98ac1680-f69b-11ea-8f44-92b5dd7ea2e0.png">

**Comment by s-paquette** [comment]
So, this isn't strictly a bug. The reason is, unlike in ISB-CGC, where we save samples and cases, we don't save those here. We only save filters. The reasoning being, these filters might not match records now--but they could, in the future, with a more recent data version. So, do we want to still prevent saving of cohorts which don't *currently* have any available cases/studies/series/instances? @fedorov This is really a use case question for you.

**Comment by fedorov** [comment]
I think for the user what is important is the actual cases included in the cohort, and that the cases included in the cohort remain the same. I believe it was mentioned in the past that the cohort defined by filter is presumably going to be persistent and with the versioning of the data the actual composition of the cohort will remain the same. If that remains a requirement, there would be no use from an empty cohort - it would remain empty if the subsequent versions of data are updated.

All in all, if I understood the earlier discussions correctly, we should not be saving cohorts that are empty.

**Comment by fedorov** [comment]
Decided to disable creation of empty cohorts.

**Comment by madelyngreyes** [comment]
I was able to save the cohort with the filters 
- BODY PART EXAMINED IN (Brain) AND
- SEGMENTATION CATEGORY IN (Morphological Abnormal Structure
 with zero cases present in the cohort. 

<img width="960" alt="2020-09-21 (8)" src="https://user-images.githubusercontent.com/16824894/93804424-48413580-fc14-11ea-9510-afd76458aebe.png">

**Comment by s-paquette** [comment]
Should be available to test in both dev and test now.

**Comment by madelyngreyes** [comment]
I just tried to select the filter options BODY PART EXAMINED IN (Brain) AND
SEGMENTATION CATEGORY IN (Morphological Abnormal Structure) and returned a, 

"Uncaught TypeError: Cannot read property 'attributes' of undefined
    at Object.success (image_search.js:1468)
    at fire (jquery-3.5.1.js:3496)
    at Object.fireWith [as resolveWith] (jquery-3.5.1.js:3626)
    at done (jquery-3.5.1.js:9786)
    at XMLHttpRequest.<anonymous> (jquery-3.5.1.js:10047)" error message in the dev console. 

![zero cases returned](https://user-images.githubusercontent.com/16824894/96305029-33fe1780-0fcb-11eb-821d-6a312a123f3f.PNG)

**Comment by s-paquette** [comment]
This bug is separate from the actual saving of the cohort. I'll make a ticket for it, but if you could make a zero-size cohort without using a derived filter (that's the error), that'll let you test this.

An example of a filter set you can use is Country: Brazil and Body Part Examined: Abdomen.

**Comment by madelyngreyes** [comment]
You are unable to save a cohort when using non-derived attributes. 

<img width="960" alt="2020-10-18 (2)" src="https://user-images.githubusercontent.com/16824894/96372126-80fcfd80-1133-11eb-9f95-9e7d3ac2bfc8.png">
