### ISSUE TITLE
Cohort view panel styling/appearance issues

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#290]
1) currently, name of the cohort appears in largest font size anywhere on the page - is there a good reason for this? I would decrease the font, and also use background color closer to the existing color scheme (perhaps Allison can comment on that)

2) when resizing the width of the window, cohort panel sometimes completely disappears, see below

![2020-09-15_10-07-35](https://user-images.githubusercontent.com/313942/93221561-eaa47900-f73b-11ea-92e1-54fa10e2fe26.gif)

**Comment by s-paquette** [comment]
The name is that large to ensure the user realizes they're on the cohort page and NOT the Exploration page. I'm concerned about making it too much smaller lest they get confused as to what page they're on.

I can change the color but, similarly, I want to use one that's not the same as the Exploration page, or they won't be clear on what page they're on. Preferences? Light Blue, maybe?

**Comment by s-paquette** [comment]
What you're seeing on the 'disappearance' is the upper menu has to become double-height, covering the name line. I can see about ways to adjust that.

**Comment by s-paquette** [comment]
Okay, figured out a solution for this--any time the top navbar would 'double up', it's going to swap to what's called 'collapse' mode where it becomes a toggle-dropdown. Will mark this for testing as soon as that's deployed.

**Comment by s-paquette** [comment]
@fedorov This is ready for looking at (except the color, still waiting for a suggestion from Allison). Please note Google is being very sluggish to update CSS and JS from the static folder; empty cache and hard reload may be needed.

**Comment by fedorov** [comment]
@madelyngreyes can you test this?
