### ISSUE TITLE
Add an option to download cohort manifest in a BQ-compatible JSON format

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#291]
At the moment, with CSV format, one needs to manually remove the header, or specify rows to skip, and then manually edit the column names, which is quite awkward.

**Comment by s-paquette** [comment]
We can also do this for CSV, but the request was explicitly made to have all of this header information. JSON files will inherently have fewer records owing to the overhead in the format causing the 32M limit to come in much earlier. So a headerless CSV might be a good option as well.

**Comment by mitianisb** [comment]
@s-paquette  I might have implemented this as part of this ticket[#291](https://github.com/ImagingDataCommons/IDC-WebApp/issues/421) Can you let me know if there is something else that is still missing?

**Comment by s-paquette** [comment]
@mitianisb  I'll take a look at make sure the JSON format is Avro-compatible; as long as it is, this should be fine.

**Comment by mitianisb** [comment]
@s-paquette Sounds good! I tried to upload JSON file to Google Cloud. It can convert to BQ table. but I am not sure about Avro-compatible.

**Comment by fedorov** [comment]
We have JSON download now, and BQ export is preferred, so this issue is effectively resolved.
