### ISSUE TITLE
Text cut-off on the cohort list table

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#303]
On the cohort list details there is text cut-off for the name column. 

<img width="960" alt="2020-09-17 (8)" src="https://user-images.githubusercontent.com/16824894/93604941-1cb01800-f994-11ea-82ae-aad6d24e39d5.png">

Suzanne is aware of the issue.

**Comment by fedorov** [comment]
Need to confirm zoom 100%

**Comment by fedorov** [comment]
Confirmed full text in tooltip

**Comment by madelyngreyes** [comment]
<img width="960" alt="2020-09-21 (4)" src="https://user-images.githubusercontent.com/16824894/93799129-b97cea80-fc0c-11ea-9f7c-53dfbbcecdb8.png">

**Comment by madelyngreyes** [comment]
The tooltip that displays the entire text for the description column seems to be disabled. It should be working as well. Does this need a new ticket? @s-paquette 

description column text hover-over
<img width="960" alt="2020-09-25 (8)" src="https://user-images.githubusercontent.com/16824894/94300539-28bd4c00-ff37-11ea-9230-0376d2a420be.png">

name column text hover over
<img width="960" alt="2020-09-25 (9)" src="https://user-images.githubusercontent.com/16824894/94300638-48547480-ff37-11ea-855c-c51c28a850b7.png">

**Comment by s-paquette** [comment]
It's not disabled so much as not implemented. If we want that, it should be an enhancement, but note that since descriptions can be long, it's not a good idea.

**Comment by madelyngreyes** [comment]
Should we implement a text limit for the description as well? Then the tooltip can be implemented.

**Comment by s-paquette** [comment]
The description is meant to be a larger area for a user to save something like a paper abstract or similar. It's not really meant to be 'viewed quickly'. As a result the current limit (64k) is fine; it doesn't really need a tooltip. If they want to read it all, they can open the cohort detail page. (Or, we could implement something like with collections, where it's in a fold-out. But that's also post-MVP.)

**Comment by madelyngreyes** [comment]
Okay, I made a new ticket to implement a fold-out for the description.
