### ISSUE TITLE
Study and Series tables are not loading

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#304]
I added the filters 
- body part examined: abdomen
- modality: SR document
- object class: comprehensive SR

I then scrolled down to the collections panel to select collection qin_headneck and the study panel didn't load. I then opened the dev console and there is a 500 error being returned. 

<img width="960" alt="2020-09-18" src="https://user-images.githubusercontent.com/16824894/93605643-06568c00-f995-11ea-99a2-bb4723d079f7.png">

**Comment by G-White-ISB** [comment]
It's more generic than that. Studies and Series tables are not loading at all with the latest release.

**Comment by s-paquette** [comment]
Ultimately, this is an issue with how we're managing the data once it comes off Solr. We really need to rethink how we organize it once we have it; what we're doing right now isn't sustainable. I'll make a specific ticket for that, though.

In the mean time, fix incoming.

**Comment by s-paquette** [comment]
Okay, fix merged into Common master. Next rebuild to dev will include it.
