### ISSUE TITLE
cohort list table page re-alignment of table header needed

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#306]
Column header is in wrapped text format. At 67% zoom the header of the table is visible as one line but, at 90% zoom it's displayed as wrap text. 

<img width="960" alt="2020-09-18 (11)" src="https://user-images.githubusercontent.com/16824894/93629048-99072300-f9b5-11ea-8308-c79709ff0ac7.png">

**Comment by fedorov** [comment]
Unless it is confirmed at 100% zoom not a priority

**Comment by madelyngreyes** [comment]
Issue is also present at 100% zoom at this time.

<img width="960" alt="2020-09-21 (2)" src="https://user-images.githubusercontent.com/16824894/93798915-67d46000-fc0c-11ea-9986-9a9ea0b12f09.png">

**Comment by s-paquette** [comment]
@madelyngreyes Can you confirm if this is still happening?

**Comment by madelyngreyes** [comment]
fixed
