### ISSUE TITLE
Clear all doesn't remove filter selection for any Derived - Quantitative filter analysis on the Search results panel

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#310]
The clear all button in the search results panel doesn't remove the filter selection from a Derived - Quantitative Analysis pie chart in the Search Results panel.

http://somup.com/cYQFqPXJop

**Comment by s-paquette** [comment]
@madelyngreyes This appears to be fixed, can you have a look? (in dev)
