### ISSUE TITLE
Improve slider range appearance for Quantitative analysis

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#317]
Related to ticket, https://github.com/ImagingDataCommons/IDC-WebApp/issues/282
 
Minor fixes
- text overlap for certain range selections
- range selection of 80-* to reflect filter selection in the left panel

**Comment by fedorov** [comment]
- keep one tooltip above, one below
-

**Comment by fedorov** [comment]
It would also make sense to always show the slider range in tooltip. It is kind of useless without knowing what those ranges actually are.

**Comment by fedorov** [comment]
Note that in the cohort view mode tooltips do not show up at all, so this is another reason to have them visible all the time and not on mouseover.

**Comment by fedorov** [comment]
this appears to be fixed in production
