### ISSUE TITLE
cohort confirmation panel invalid character notification enhancement

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#318]
If you use an invalid value when working when trying to save a cohort you are returned the error message, "Your cohort's name contains invalid characters (). Please choose another name." but, doesn't list which are the specific invalid characters you used. 

<img width="960" alt="2020-09-21 (9)" src="https://user-images.githubusercontent.com/16824894/93808937-a4a75380-fc1a-11ea-8968-9539f027c930.png">

**Comment by s-paquette** [comment]
Possible duplicate of #328
