### ISSUE TITLE
mysql idc_collections_collection_data_versions and several other tables are not populated

### ISSUE THREAD

**Issue by bcli4d** [ImagingDataCommons/IDC-WebApp#319]
Several mysql many-to-many tables:

- idc_collections_collection_data_versions
- idc_collections_datasource_programs
- idc_collections_dataversion_programs

are not populated. Some of these are needed, I think, to be able to determine, for example, which collections are in some IDC version.

**Comment by fedorov** [comment]
@bcli4d is this still a valid issue, or should it be closed?

**Comment by fedorov** [comment]
@bcli4d please reopen if this is still an issue.
