### ISSUE TITLE
Fix typo in the collections table

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#320]
Glioblatoma -> Glioblastoma

![image](https://user-images.githubusercontent.com/313942/93821462-93ffd900-fc2c-11ea-8a49-7524fbb98ab0.png)

**Comment by s-paquette** [comment]
This typo is actually in the BQ table itself. I can fix the MySQL ETL as it stands, but we'll need the BQ table fixed in order for it to hold.

**Comment by fedorov** [comment]
I reported to TCIA helpdesk to fix it on their website

**Comment by fedorov** [comment]
This has now been resolved on the TCIA side.

![image](https://user-images.githubusercontent.com/313942/94733718-2d6a7180-0336-11eb-808e-e2074736c674.png)

cc @bcli4d

**Comment by wlongabaugh** [comment]
Since this involves another ETL round with other possible changes we are kicking this to post-MVP.

**Comment by fedorov** [comment]
This is potentially related to the versioning discussion. Will not be touched until that discussion takes place.

**Comment by fedorov** [comment]
"fixed" by excluding the collection in question from the pilot release
