### ISSUE TITLE
"Filter Definition" and "Search Results" sections need more explanation

### ISSUE THREAD

**Issue by wlongabaugh** [ImagingDataCommons/IDC-WebApp#325]
This was discussed last week, I don't see it as a ticket? We need more info in those two sections as to what they mean. A hefty tooltip or info/help icon that explains the nuances of non mutually exclusive attributes and whey we are pulling in non-selected attributes. An expanded section description should also be helpful. E.g. For filter definition, "Select _**all**_ studies where the selected filter has **_at least one series_** where the following is true:" Something similar above the pie charts. Don't make people guess.

**Comment by G-White-ISB** [comment]
Has any user documentation been written yet? Tooltips can be cribbed from that.

**Comment by madelyngreyes** [comment]
It was my understanding the explanation would be pulled from the discourse discussion. - [Understanding IDC portal cohort plots](https://discourse.canceridc.dev/t/understanding-idc-portal-cohort-plots/81/6)

**Comment by fedorov** [comment]
This post, to be specific: https://discourse.canceridc.dev/t/understanding-idc-portal-cohort-plots/81/7

**Comment by G-White-ISB** [comment]
In progress. Here is the current text I have.
Info in Search Configuration panel: "Each facet count is the number of cases within the given facet calculated by applying the defined filter with the facet added to the filter definition (if otherwise absent)."

In Search Results panel: "In the charts below each facet count is the number of cases within the given facet calculated by applying the defined filter. For some facet categories a case may apply to several facets within the category. Hence some facets not included in the filter may have positive case counts."

**Comment by wlongabaugh** [comment]
Thanks. Is this for a mouseover tooltip (as opposed to a very short phrase always in the panel)? Seems long enough to qualify for the former.

I note that facet is a term we use, but is kinda obscure to a user, e.g. "pie slice" or "slice" might be more understandable?

**Comment by fedorov** [comment]
I think this kind of long explanations do not belong to the UI. If users are confused, they should go to the docs. I am having troubles understanding the text above. I think the tooltip can have something brief like "Numbers correspond to the count of cases that meet the selected search criteria. See detailed explanation in <url>".

**Comment by G-White-ISB** [comment]
This text would be put in tooltips.  Remember the counts reported in the
search configuration lists differ from the counts that are plotted in the
search results charts, so I have two tooltips to explain the difference. I
think we should come up with consistent jargon for the documentation, ui,
and our conversations. Is Modaily a category or a filter set? Is CT a
filter or a facet?

I'll push the tooltips and you can see if they make sense in the context of
the ui.

George

**Comment by madelyngreyes** [comment]
I looked around to see what the other nodes use and so far have found this documentation from the GDC. - https://docs.gdc.cancer.gov/API/Users_Guide/Search_and_Retrieval/#facets

**Comment by wlongabaugh** [comment]
OK, after some Slack iterations, I suggested this as an alternative for the left panel: "Counts shown for each attribute (e.g. Modality) are unchanged by the values (e.g. PET) selected (checked) for that attribute. They only change based on the values selected for all other attributes."

**Comment by wlongabaugh** [comment]
I could preface that statement, I suppose we could say "To provide consistent context, counts shown..."

**Comment by G-White-ISB** [comment]
Sounds good to me. I prefer the statement without the preamble.

**Comment by G-White-ISB** [comment]
Below is the current text in my latest PR:

Search Configuration tooltip: 'Counts shown below are the number of cases (or patients) for each attribute value. Counts for each attribute (e.g. Modality) are unchanged by the values (e.g. PET) selected (checked) for that attribute. They only change based on the values selected for all other attributes.'

Search Results tooltip: 'Each chart below reports the number of cases (or patients) for all values within a given attribute. For certain attributes (e.g. Modality) several distinct values may apply to the same case.'

**Comment by wlongabaugh** [comment]
Is it cases/patients, or studies (to be exact in our terminology)?

**Comment by wlongabaugh** [comment]
What about:
"Each chart below reports the number of cases (or patients) for all values within a given attribute, given the currently defined filter set. For certain attributes (e.g. Modality), since other distinct values not explicitly selected can also apply to the same case, those other values will also appear."?

**Comment by G-White-ISB** [comment]
case=patient or person. Counts are pre case right now.

**Comment by wlongabaugh** [comment]
But I thought that it was *actually* per-study, which since number of cases is approximately the number of studies, is roughly the case count. So we *say* cases, but is actually implemented as per-study. @s-paquette ?

**Comment by s-paquette** [comment]
@wlongabaugh *Counts* are per case, but we back-include per study for determining WHAT to count.

**Comment by wlongabaugh** [comment]
OK, so again:

"Each chart below reports the number of cases (or patients) for all values within a given attribute, given the currently defined filter set. For certain attributes (e.g. Modality), since other distinct values not explicitly selected can also apply to the same case, those other values will also appear."

?

**Comment by G-White-ISB** [comment]
Works for me,
George

**Comment by fedorov** [comment]
"Each chart below reports the number of cases (or patients) for all values within a given attribute, given the currently defined filter set. Once a case is selected, both instances that meet and do not meet the search criteria corresponding to this case will affect the charts content. E.g., cases selected based on the presence of CT modality may also contain PET modality, counts of which for that given case will also appear in the chart summary"

I know the above is longer, but I think makes it more clear. Again, I think this explanation belongs to the documentation. I would put the effort into the explanation and example in the documentation, and have the tooltip include a link to that page.

**Comment by wlongabaugh** [comment]
We can certainly include a link to the documentation. And the documentation can include figures, which will really help to clarify the situation. But we need to say _something_ in a tooltip as well as that link.

**Comment by madelyngreyes** [comment]
I added this text into the documentation. 

![count clarification](https://user-images.githubusercontent.com/16824894/96272754-883dd300-0f9c-11eb-8026-f10702a9d8bc.PNG)

**Comment by wlongabaugh** [comment]
@madelyngreyes I really don't understand the second paragraph of the above. Something closer to the new tooltip ('Counts shown below are the number of cases (or patients) for each attribute value. Counts for each attribute (e.g. Modality) are unchanged by the values (e.g. PET) selected (checked) for that attribute. They only change based on the values selected for all other attributes.') seems somewhat clearer.

@fedorov We need to have text to go into the tooltip today. You provided a longer alternative to my suggestion above, but then said it should not be in a tooltip at all, leaving me unsure what you will find acceptable for tooltip text. Your longer version can certainly be in the docs, but what is OK in the tooltip in addition to the pointer to the docs that you want? Can you please clarify? And do we have the URLs now to include in the tooltips?

**Comment by fedorov** [comment]
@wlongabaugh I tried to clarify, since the earlier version was confusing to me. I hope that the text I provided is more clear, but I am open to alternative opinions, and if folks think the earlier version is more clear - I am cool with that.

I am fine with any text you will put into the tooltip, as long as there is a pointer to the documentation. 

I have not yet reviewed in detail the documentation that Madelyn put together, I will refine that as well. We can also allocate a separate meeting working as a group on components of documentation like this one.

Hope this helps.

**Comment by madelyngreyes** [comment]
I pulled that text from the dev tier, I have now changed it to the text provided by Andrey.

**Comment by wlongabaugh** [comment]
OK, how about this iteration then:
"Each chart below reports the number of cases (or patients) for all values within a given attribute, given the currently defined filter set. Once a case is selected, all series for that case, including those that do not meet the search criteria, are included. Thus, cases selected based on the presence of CT modality may also contain PET modality, and thus counts for both values will appear in the chart, and the manifest."

**Comment by fedorov** [comment]
Indeed, series is more appropriate than instance here. I would keep "As an example" in the opening of the last sentence in place of "Thus" though.

**Comment by wlongabaugh** [comment]
Sure, though "For example" is a tiny bit shorter and a bit more colloquial:

"Each chart below reports the number of cases (or patients) for all values within a given attribute, given the currently defined filter set. Once a case is selected, all series for that case, including those that do not meet the search criteria, are included. For example, cases selected based on the presence of CT modality may also contain PET modality, and thus counts for both values will appear in the chart, and the manifest."

@G-White-ISB Let's go with the above.

**Comment by G-White-ISB** [comment]
Ok, I'll put it in a PR now, but Suzanne handles the commit.

**Comment by fedorov** [comment]
"For example" is perfect!

**Comment by madelyngreyes** [comment]
Search Configuration panel more information tooltip text below, 
![2020-10-19 (15)](https://user-images.githubusercontent.com/16824894/96522269-06220880-1241-11eb-854c-0f910efdf124.png)


updated Search Results more information tooltip text below,
![2020-10-19 (14)](https://user-images.githubusercontent.com/16824894/96522124-be9b7c80-1240-11eb-83a6-11bf4ae4b6ce.png)
