### ISSUE TITLE
"Invalid characters" message needs to be improved

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#328]
Not clear in the below which of the characters are invalid.

![image](https://user-images.githubusercontent.com/313942/93900459-687bfd80-fcc3-11ea-9634-82378e052035.png)

**Comment by fedorov** [comment]
removing space does not help

![image](https://user-images.githubusercontent.com/313942/93900730-bdb80f00-fcc3-11ea-8880-84138996167f.png)

**Comment by fedorov** [comment]
hard reload did not help

**Comment by fedorov** [comment]
After further testing, I am not sure the issue with the invalid characters. When I defined a cohort that did not include quantitative filters, I was able to save it. Furthermore, when I after that created a cohort that does include quantitative filters, I again was able to save it, although quantitative filters were discarded when I opened the saved cohort.

**Comment by s-paquette** [comment]
I ran into this last night and then couldn't reproduce it. I'll try using quantitative filters, maybe that's what's causing it.

**Comment by s-paquette** [comment]
So the real issue was to do with handling the description. This is now fixed in dev. An example of an invalid character set would be `<script>` or `<iframe>` (if you want something guaranteed to trigger it. Numeric filters should also be working.

**Comment by fedorov** [comment]
> An example of an invalid character set would be <script> or <iframe>

I don't understand the above. What are the invalid characters in the example below?

![image](https://user-images.githubusercontent.com/313942/93900730-bdb80f00-fcc3-11ea-8880-84138996167f.png)

**Comment by s-paquette** [comment]
What are the filters you're using for that? I can't seem to replicate the behavior on dev or test. (Maybe try clearing the cache and hard reloading?)

**Comment by s-paquette** [comment]
...In fact I don't see the text changes I made to the message so that's definitely old code. You might need to do a hard reload.

**Comment by fedorov** [comment]
Sorry for the confusion - I was asking about the error I had yesterday. I thought you meant there is an explanation for that behavior.

With the current testing, when save cohort, I get "Failed to save" as in the below, but the cohort does show up in the list.

![image](https://user-images.githubusercontent.com/313942/94043383-d9421900-fd9a-11ea-9e04-9b02e8a6de5f.png)

If I then click on that saved cohort, filter definition is blank:

![image](https://user-images.githubusercontent.com/313942/94043442-eced7f80-fd9a-11ea-9a4f-c330fe7d994d.png)

**Comment by s-paquette** [comment]
The behavior from yesterday was a bug related to the bad characters checking; definitely not intentional. Checking on this error, which is likely something different.

**Comment by s-paquette** [comment]
Ah ha, looks like Common wasn't fully merged in. Doing that now--the fix will show up on dev first.

**Comment by fedorov** [comment]
It works for me for the configuration that used to be broken. Thank you!
