### ISSUE TITLE
Disable "Real world mapping" object class to open OHIF in the Selected Series panel

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#332]
The selection of the a series with the object class real world mapping will cause the OHIF viewer to return a 404 error in the dev console. 

<img width="960" alt="2020-09-23 (2)" src="https://user-images.githubusercontent.com/16824894/94043332-c9c2d000-fd9a-11ea-8784-1c05ab6fbe93.png">
<img width="960" alt="2020-09-23 (1)" src="https://user-images.githubusercontent.com/16824894/94043343-cc252a00-fd9a-11ea-9bdf-dfc3a87876bf.png">

**Comment by fedorov** [comment]
RTPLAN might also need to be added to the list of non-displayable

**Comment by fedorov** [comment]
Filter out: RTPLAN and Real World mapping

**Comment by madelyngreyes** [comment]
![RWV series](https://user-images.githubusercontent.com/16824894/101844053-90883980-3b19-11eb-8393-f5094e5f8ca2.PNG)
![RTPLAN series](https://user-images.githubusercontent.com/16824894/101844060-941bc080-3b19-11eb-839d-29ca9311e03c.PNG)
fixed
