### ISSUE TITLE
Zombie pie chart visible with filters that create a null set

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#334]
The selection of collection: qin_headneck and body part examined: brain and modality: computed tomography will display filter options in the pie chart Body Part Examined but, zero cases are returned for the filter selection. 

<img width="960" alt="2020-09-23 (4)" src="https://user-images.githubusercontent.com/16824894/94046630-f37df600-fd9e-11ea-88a5-ddb4ea2b98c9.png">

**Comment by madelyngreyes** [comment]
This bug is visible with the selection of any category. From Andrey," If I select a filter that has 0 entries under any category, it will trigger the corresponding piechart, but only one category can be shown at a time."

**Comment by G-White-ISB** [comment]
I can confirm the data shown is the data that is returned from the filter request. View the response to http://localhost:8085/explore/?counts_only=True&is_json=true&is_dicofdic=True&data_source_type=S&filters=%7B%22Modality%22:%5B%22CT%22%5D,%22BodyPartExamined%22:%5B%22BRAIN%22%5D,%22collection_id%22:%5B%22qin_headneck%22%5D%7D

in a JSON formatter and note the values in the 'filtered_counts' attributes. Also odd is that tcga_gbm and tcga_lgg have 'filtered counts' even though the collection is qin_headneck. Reassigning to Suzanne.

**Comment by s-paquette** [comment]
Okay, bug found for this and generally all of the weird count/zero behaviors. I'll be merging it in and moving it onto test right away; it's a relatively small change.

**Comment by madelyngreyes** [comment]
All pie charts now display the text, "No Data Available".

<img width="960" alt="2020-10-14 (17)" src="https://user-images.githubusercontent.com/16824894/96051542-bced4580-0e49-11eb-858b-b5b341a65656.png">
