### ISSUE TITLE
Portal - use 1000 (,) separators for number of cases and image series

### ISSUE THREAD

**Issue by ulrikew** [ImagingDataCommons/IDC-WebApp#338]
The case and image series numbers are easier to read when 1000 separators are used.
![image](https://user-images.githubusercontent.com/3019001/94194748-1af8bf80-fe80-11ea-9d3f-b12164f8d413.png)

**Comment by madelyngreyes** [comment]
Current data portal summary lists two collections less than before but, the (,) separators are present. 

<img width="949" alt="homepage data portal summary" src="https://user-images.githubusercontent.com/16824894/96008576-b345ec80-0e0d-11eb-883f-776820a5c4eb.PNG">
