### ISSUE TITLE
Modify Application Version Text

### ISSUE THREAD

**Issue by wlongabaugh** [ImagingDataCommons/IDC-WebApp#339]
The version tag shown at the bottom of the landing page (e.g. Application Version: dev.230920201515.d278c8) should be changed to say "Pilot Application Version: ...". This will remain in effect until we have our 2021 production release.

**Comment by fedorov** [comment]
Can we use this opportunity to address this issue as well: https://github.com/ImagingDataCommons/IDC-WebApp/issues/261?

It will be awkward to change version conventions after the public release.

**Comment by mitianisb** [comment]
No problem. I can work on both of them.
