### ISSUE TITLE
Quantitative filters slider range to only show valid range when user clicks 'hide with 0'

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#341]
Volume range remains the same no matter what I choose for the other filters. I don't know if this is a bug or not, but it is definitely confusing.

![image](https://user-images.githubusercontent.com/313942/94303651-2a3d4300-ff3c-11ea-991b-6da3e56e4880.png)

**Comment by fedorov** [comment]
To be clear, it is probably the same for other quantitative filters, I did not do a thorough check.

**Comment by madelyngreyes** [comment]
On the dev tier there is slight improvement but, the numerical values are displayed backwards e.g., 1,940 appears before the 1,360 value.

<img width="960" alt="2020-09-25 (16)" src="https://user-images.githubusercontent.com/16824894/94309785-9d4bb700-ff46-11ea-84c1-4997f4f73863.png">

**Comment by fedorov** [comment]
I do not think the issue I reported above is fixed in dev.

Here's the filter definition:

![image](https://user-images.githubusercontent.com/313942/94311623-92465600-ff49-11ea-8d1f-49d185232d1c.png)

The range of the Volume slider is the same as I had before defining any filters:

![image](https://user-images.githubusercontent.com/313942/94311648-9a05fa80-ff49-11ea-8b62-376ecd387a2d.png)

Which to me implies that this filter configuration has items in this Volume range.

But if I adjust the sliders for Volume within the range, I get an empty cohort:

![image](https://user-images.githubusercontent.com/313942/94311723-bb66e680-ff49-11ea-8cb9-51652357ba1d.png)

![image](https://user-images.githubusercontent.com/313942/94311739-c15cc780-ff49-11ea-8eff-203c6e501de6.png)

**Comment by G-White-ISB** [comment]
The sliders and absolute ranges are set at the time of page load. After
that they are static. I have not reproduced Madelyn's bug with the lower
value slider to the right of the higher value.

George

**Comment by madelyngreyes** [comment]
I will make a new ticket for the issue I have reported above, it is indeed different.

**Comment by fedorov** [comment]
> The sliders and absolute ranges are set at the time of page load. After that they are static. 

I think they definitely should be updated the same way as counts for non-slider filters.

If this is a post-MVP thing, then @madelyngreyes should document the current behavior in the user guide, since to me this is not intuitive at all.

**Comment by G-White-ISB** [comment]
Progress made but following a meeting with others at ISB we decided to table it for now. We would like further discussions to nail down a satisfactory design

**Comment by fedorov** [comment]
Sure - let's discuss it here in this issue. What is the question you have about design?

Madelyn, can you please add a note about this limitation to the docs?

**Comment by fedorov** [comment]
Discussed and agreed that a compromise could be to show only the valid range of the slider when the user toggles "hide attributes with 0 cases". Those agreed included @s-paquette @G-White-ISB, and no one disagreed.

![image](https://user-images.githubusercontent.com/313942/95108248-07afe480-0709-11eb-8902-08e4e8e2f628.png)

**Comment by G-White-ISB** [comment]
Note: if a user has already selected a certain range for a certain attribute, then that range will not be hidden even if a portion of the range has non-zero cases. This is similar behavior to selection of categorical attributes. A selected attribute is still shown even if it has 0 cases.

**Comment by madelyngreyes** [comment]
For the Diameter attribute it seems the Clear Slider doesn't reset properly. 

![diameter clear slider broken](https://user-images.githubusercontent.com/16824894/100946298-0f092980-34d1-11eb-8426-abe2eac2b13f.PNG)

**Comment by madelyngreyes** [comment]
When there are zero cases present the attribute appears as blank, 
![quantitative analysis](https://user-images.githubusercontent.com/16824894/100946736-fb11f780-34d1-11eb-8c08-ee0883467b35.PNG)

**Comment by G-White-ISB** [comment]
Yes the clear slider option was not working. I think I missed it because of a cache issue. Anyhow a new PR is in to address this.

**Comment by G-White-ISB** [comment]
If the quantitative attribute has 0 cases (ie a tcga collection with no segmentation data) then the sliders are not drawn. This is as expected. There is another ticket to handle empty attributes 'gracefully' (https://github.com/ImagingDataCommons/IDC-WebApp/issues/453)

**Comment by G-White-ISB** [comment]
Please test again. New pull request is in to handle the slider clear option

**Comment by madelyngreyes** [comment]
![diameter reset incorrect](https://user-images.githubusercontent.com/16824894/101382751-52bfb280-3886-11eb-96eb-8dfc2028b376.PNG)


I reset my cookies and still seem to be running into this issue on the test tier.

**Comment by s-paquette** [comment]
@madelyngreyes  A build hadn't been done to test yet. One is underway now, should be done in about 30m.

**Comment by madelyngreyes** [comment]
@G-White-ISB  Could you clarify what is the functionality I should expect on the production tier?
