### ISSUE TITLE
Add code meaning to the cohort manifest filters used row

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#342]
Related to comment in ticket, https://github.com/ImagingDataCommons/IDC-WebApp/issues/194#issuecomment-699095543 in the data portal a filter value for segmentation type is displayed as Nodule, but in the manifest the filter value is displayed as M-03010:SRT 

<img width="266" alt="segmented property type" src="https://user-images.githubusercontent.com/16824894/94310525-c7ea3f80-ff47-11ea-9481-4264f1122e47.PNG">
<img width="960" alt="2020-09-25 (17)" src="https://user-images.githubusercontent.com/16824894/94310533-cae53000-ff47-11ea-94aa-9d435685c6d7.png">

**Comment by s-paquette** [comment]
@madelyngreyes Does that happen to all of them or does it only happen for that one?

**Comment by s-paquette** [comment]
Ah, I see what it is--display values. So, this is a conversation to include @fedorov  on.

There's the concept of display values, i.e. we don't show the user the raw value from the system in the UI, we show them the 'display value'. They can't filter using display values, though, so if we provide display values in the manifest, it won't represent a filter they can use in any meaningful way.

Do we want the filters in the manifest to be 'display' filters, or actual raw filters?

**Comment by fedorov** [comment]
@s-paquette how do you envision a user can use the current filter in the example above in a meaningful way?

IMHO, the filter definition in the manifest should serve two purposes:
1) allow the system to reuse the definition to apply the filter to the data
2) allow the user to make sense out of the filter definition

If we need to definitions to do the above, so be it.

**Comment by fedorov** [comment]
Agreed it makes sense to add the display value for those codes in the manifest filter definition.

**Comment by s-paquette** [comment]
Manifest filter display will now be 'display values' style

**Comment by fedorov** [comment]
this is done
