### ISSUE TITLE
Search Configuration Quantitative analysis range filter enhancements

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#344]
While using a Windows 10 pro at 100% zoom certain numerical values are displayed backwards e.g., 1,940 appears before the 1,360 value for the Volume filter.

Steps to reproduce the issue
1. Open the Derived tab in the Search Results panel
2. Open the Quantitative analysis pie charts
3. Select the option 1360-1940 for the Volume (cubic millimeter) filter
4. Open Volume filter the left Search Configuration panel under the Derived tab
5. The 1,940 value is displayed before the 1,360

<img width="960" alt="2020-09-25 (16)" src="https://user-images.githubusercontent.com/16824894/94312825-a2f7cb80-ff4b-11ea-8bbf-bf0729869fd5.png">

**Comment by G-White-ISB** [comment]
I can also reproduce this (Mac/chrome).  I have spot checked other
slider-based filters but I have only seen this come up on the Volume
filter.
George

**Comment by fedorov** [comment]
This is still reproducible in v2 production tier.

![image](https://user-images.githubusercontent.com/313942/122856230-73ac9a00-d2e4-11eb-9530-8a07dada4e36.png)
