### ISSUE TITLE
Implement fold-out for description of cohort on the cohorts list page

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#345]
Related to ticket, https://github.com/ImagingDataCommons/IDC-WebApp/issues/303#issuecomment-699159360 the description for the cohort is not easily readable on the cohorts list page. 

<img width="960" alt="2020-09-25 (8)" src="https://user-images.githubusercontent.com/16824894/94318171-e7886480-ff55-11ea-8577-f03c86d702aa.png">

**Comment by s-paquette** [comment]
The best solution is to use dataTables on the cohort listing (as is done with Collections, see collections_list.js) and then move the description into a foldout similar to what's used there.

**Comment by madelyngreyes** [comment]
Fold-out example below.

<img width="907" alt="2020-10-18" src="https://user-images.githubusercontent.com/16824894/96367062-8fd6b680-1119-11eb-96fc-283ef85f1183.PNG">
