### ISSUE TITLE
Tooltip completely obscures filters area

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#350]
Would it be difficult to move the tooltip to the right from the mouse pointer, so it is possible to see the filters below at least partially?

It is currently very disruptive.

![image](https://user-images.githubusercontent.com/313942/94881941-a7812000-0434-11eb-9fa8-ad8feb703875.png)

TCIA is a good example to follow:

![image](https://user-images.githubusercontent.com/313942/94881991-c5e71b80-0434-11eb-8f0c-04de9f8d80a7.png)

**Comment by s-paquette** [comment]
Please note, these tooltips are mediated by a specific UI plugin, Tippy.
