### ISSUE TITLE
Make tooltip styling consistent throughout the application

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#351]
![image](https://user-images.githubusercontent.com/313942/94882157-368e3800-0435-11eb-988c-0232c3d248b7.png)

![image](https://user-images.githubusercontent.com/313942/94882175-3ee67300-0435-11eb-88e6-4d4e4546499f.png)

What is this one supposed to show?..

![image](https://user-images.githubusercontent.com/313942/94882205-5160ac80-0435-11eb-98bc-f39960bf8083.png)

**Comment by s-paquette** [comment]
The larger, fancier tooltips are handled by a special UI tooltip plugin known as Tippy, which can support complex HTML in tooltips. We can make use of it throughout the site, if we want. See the bottom of explore.js for an example of its use.

**Comment by s-paquette** [comment]
The following tooltips are now converted to Tippy, so they can be consistent in style:

- The two info tooltips
- The 'Can't use None for Derived filters' tooltip
- The Study GUID tooltip

I left the Study GUID tooltip as the dark theme because it seemed easier to read, but we could change that. Study GUID tooltips are loaded dynamically via delegation to save on DOM load time.

**Comment by mitianisb** [comment]
Thanks Suzanne! I converted the eye-slash button tooltip and the study GUID tooltip (using a ppStudyId to studyId hashmap) in my branch. I think your implementation is nicer with the data-study-id.

**Comment by fedorov** [comment]
Thanks! AFAIK, the GUID tooltips are of no use. I would remove them, and add back in the unlikely case someone asks. They look ugly and weird.

**Comment by mitianisb** [comment]
@fedorov By UID do you mean the study GUID tooltip, or something else? Right now the study GUID tooltip allows viewing the full ID in addition to the short version.
![image](https://user-images.githubusercontent.com/58752821/95388376-0caa9a80-08a7-11eb-8203-b8b71420ebe5.png)

**Comment by madelyngreyes** [comment]
Example of UID tooltip below
![2020-10-19 (2)](https://user-images.githubusercontent.com/16824894/96465094-938c3b00-11f6-11eb-877c-662bb3747464.png)

None attribute tooltip example below
![2020-10-19 (3)](https://user-images.githubusercontent.com/16824894/96465144-a0a92a00-11f6-11eb-8bb3-2e1e4ab58d91.png)

Search Configuration panel tooltip example below
![2020-10-19 (4)](https://user-images.githubusercontent.com/16824894/96465183-aacb2880-11f6-11eb-8c3e-d1005d509b0a.png)

Search Results panel tooltip example below
![2020-10-19 (5)](https://user-images.githubusercontent.com/16824894/96465417-f1b91e00-11f6-11eb-8b11-afa1507c8d7b.png)

Collection tooltip example below
![2020-10-19 (7)](https://user-images.githubusercontent.com/16824894/96466037-b0753e00-11f7-11eb-9d83-c7e60eca237a.png)
