### ISSUE TITLE
Need explanation of the behavior for selecting TCGA filters

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#352]
If I select LIDC, and then apply a TCGA-specific filter, I get TCGA collections auto-selected, but non-TCGA remain selected.

The result is confusing to me, since it includes all of LIDC cases, which implies to me that age at diagnosis somehow applies to LIDC, and it does not.

![image](https://user-images.githubusercontent.com/313942/94882314-ab617200-0435-11eb-8e0f-2538ffa251a7.png)

The related data summary is also confusing, since there is nothing that says there that it is specific to TCGA.

![image](https://user-images.githubusercontent.com/313942/94882440-07c49180-0436-11eb-8f35-52ef0690117d.png)

My suggestion is to de-select non-TCGA collections when a TCGA-specific collection filter is selected, or somehow reflect better that TCGA-specific filter does not apply to non-TCGA data.

If nothing else, this should be covered in the documentation - @madelyngreyes

**Comment by fedorov** [comment]
Discussed with @wlongabaugh, and for now should just capture this in the docs. Bill, here's the documentation page about the portal: https://app.gitbook.com/@imagingdatacommons/s/idc-user-guide/portal/getting-started/, or you can do it in the next page.

**Comment by G-White-ISB** [comment]
The filter definition includes the note: TCGA.* collections only apply to
TCGA filters. I thought that was clear enough.


One could put it more explicitly in the filter definition using brackets
conjunctions:

(Collection in lidc) or (Collection in (tcga_blca, tcga_brca...) and
tcga.age_at_diagnosis in (0-71)))

However the definition could become harder to read.

**Comment by fedorov** [comment]
Closing for now, and will revisit if we get similar feedback from other users.
