### ISSUE TITLE
500 error on login change

### ISSUE THREAD

**Issue by wlongabaugh** [ImagingDataCommons/IDC-WebApp#361]
1) Go to landing page
2) Click on exploration
3) Get the login page
4) Instead of logging in using that dialog, click on the upper-left "sign in" link
5) 500 error
6) Click in upper left to go to landing page; turns out I am signed in
7) Click on exploration
8) 500 error 
9) Can only seem to clear things by logging out of the site.

**Comment by s-paquette** [comment]
I think I'm going to need you to show me this.
`Instead of logging in using that dialog, click on the upper-left "sign in" link`
- By dialogue, do you mean page?
- Upper-left -> upper-right?

**Comment by wlongabaugh** [comment]
By dialogue, do you mean page? --> Yes
Upper-left -> upper-right? --> Yeah, I always mix the two up.

**Comment by s-paquette** [comment]
I can't seem to replicate this--can you try again?

**Comment by s-paquette** [comment]
@wlongabaugh Also what tier?

**Comment by wlongabaugh** [comment]
Dev tier...I note that the drop-down login is now gone? So I can't get it to happen either. It required the login dropdown to malfunction.

**Comment by s-paquette** [comment]
Going to go ahead and close this since we don't have the dropdown anymore.
