### ISSUE TITLE
Normalize volume units

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#364]
Right now volume measurements are mixed between milliliters and mm^3. To confirm, use this query:

```sql
WITH
  all_units AS (
  SELECT
    Units.CodeMeaning AS units_meanings
  FROM
    `canceridc-data.idc_views.quantitative_measurements`
  WHERE
    Quantity.CodeMeaning = "Volume")
SELECT
  DISTINCT(units_meanings)
FROM
  all_units
```

**Comment by s-paquette** [comment]
Normalized on cm3

**Comment by fedorov** [comment]
Why is it then saying cubic mm in the UI as of now?

![image](https://user-images.githubusercontent.com/313942/96660976-08579600-1319-11eb-81bd-5e047f2cb4a7.png)

**Comment by s-paquette** [comment]
That was a typo in my comment--should have read mm3 aka mm^3

**Comment by fedorov** [comment]
@s-paquette got it, thanks!

@madelyngreyes in terms of validating it, I would think that you could take the original views that should still have the un-normalized values, and cross check with the views with the normalized values that Suzanne is using for Solr, if you wanted to test this at that level.
