### ISSUE TITLE
"Show more" shows a negative number

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#374]
![image](https://user-images.githubusercontent.com/313942/95389821-5eace980-08c2-11eb-8a4b-65506e6288d3.png)

**Comment by fedorov** [comment]
This issue is still appearing sporadically, and was observed as recently as today. Can developers do some extra testing/debugging?

![image](https://user-images.githubusercontent.com/313942/99279208-f5dc5980-27fd-11eb-9b25-a7ac47bd13f7.png)

**Comment by s-paquette** [comment]
@G-White-ISB

**Comment by G-White-ISB** [comment]
I have not seen or heard of this problem in several sprints
