### ISSUE TITLE
Stretch and add shadow to the left side panel

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#375]
how difficult it would be to match the height of the left-side panel with the overall height of the page view? I.e., stretch as shown by the red arrow, and also show shadow for the lower edge of the left side panel as shown by the yellow arrow

![image](https://user-images.githubusercontent.com/313942/95390273-20fc9080-08c3-11eb-9e3a-4ccf76b9cb27.png)

**Comment by s-paquette** [comment]
@fedorov Has this been addressed per the requirements of the issue?

**Comment by fedorov** [comment]
Yes, this is resolved. So much better IMHO! Thank you!
