### ISSUE TITLE
Collections page not loading on the dev and test tier

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#391]
The collections panel doesn't seem to be loading on the dev tier or the test tier at this time. 

dev tier
<img width="960" alt="2020-10-14 (1)" src="https://user-images.githubusercontent.com/16824894/96008147-40d50c80-0e0d-11eb-8015-4cd2b77a6468.png">

test tier
<img width="960" alt="2020-10-14 (3)" src="https://user-images.githubusercontent.com/16824894/96008185-4b8fa180-0e0d-11eb-8f7f-b9f9cb451274.png">

**Comment by mitianisb** [comment]
@madelyngreyes  I can not reproduce this issue on the dev tier. Can you try this again on dev tier? I merged code this morning that may fix this issue. Thanks!
