### ISSUE TITLE
Add Banner Touting Available Cloud Credits to Explorer Page

### ISSUE THREAD

**Issue by wlongabaugh** [ImagingDataCommons/IDC-WebApp#403]
Title says it all

**Comment by fedorov** [comment]
I would actually make it stick on the portal main page as well, in a similar way as it is done on the main page of ISB-CGC

![image](https://user-images.githubusercontent.com/313942/97057932-6d4dfe80-155a-11eb-8168-11020bcbdc57.png)

**Comment by mitianisb** [comment]
I have applied the same banner style from CGC to the IDC landing page and explore page and they look like this. @fedorov @wlongabaugh Please let me know your thoughts. Thanks!

![image](https://user-images.githubusercontent.com/58752821/98075859-fcdc9280-1e21-11eb-94ff-c1088b932042.png)


![image](https://user-images.githubusercontent.com/58752821/98075896-1087f900-1e22-11eb-92e4-99fba499d752.png)

**Comment by fedorov** [comment]
Can we make the color a bit more prominent so it stands apart from the blue ribbon underneath?

Other than that looks great - thanks!

**Comment by mitianisb** [comment]
@fedorov  np. How about this color? I am not sure if this color looks very good. Maybe we just keep one banner on the landing page?
![Screen Shot 2020-11-04 at 3 37 36 PM](https://user-images.githubusercontent.com/58752821/98179771-65744f80-1eb4-11eb-9c66-5c2ddaf4cd0a.png)


![Screen Shot 2020-11-04 at 3 37 22 PM](https://user-images.githubusercontent.com/58752821/98179779-6e652100-1eb4-11eb-8251-f6bcb357adfb.png)

**Comment by fedorov** [comment]
I think this is better. Definitely let's include it both on the front page and in the portal. Thank you!
