### ISSUE TITLE
Add links on Collections Page that takes user to Explore page with collection selected

### ISSUE THREAD

**Issue by wlongabaugh** [ImagingDataCommons/IDC-WebApp#404]
- User request: Have a link on Collections page that takes you to the Explorer page with collection selected.
- User request: Have a link on Collections page that allows you to download a manifest of the entire collection (clearly needs the BiqQuery and/or multi-click workaround for > 32 MB). Note we could also have permanent manifests for each collection in BQ tables.

**Comment by s-paquette** [comment]
I'd like this to be split into two tickets, as thelater is a very different situation than the former.

**Comment by mitianisb** [comment]
Separate ticket created here:[#429](https://github.com/ImagingDataCommons/IDC-WebApp/issues/429)

**Comment by mitianisb** [comment]
I have implemented this by turning the ID column into buttons as shown in image below. When clicked it will go to Explore page with the collection pre-selected. Most of the collection rows are working now.

@s-paquette @wlongabaugh I have a question about the two rows in the image below. I do not see Lung Phantom, QIN LUNG CT, RIDER Lung CT, BREAST-DIAGNOSIS, and Breast-MRI-NACT-Pilot in our Explore page. Are these collections missing?

![image](https://user-images.githubusercontent.com/58752821/98781450-2a3db900-23ab-11eb-8126-19e60791807f.png)

**Comment by mitianisb** [comment]
Based on discussion in ISB team meeting, I did a mock-up of grey out the collections that we do not support in Explore page. It looks like below. I feel the color difference in the same link may be confusing for users. Maybe we only need to explain it in the description?

![image](https://user-images.githubusercontent.com/58752821/99216776-61d1aa00-278b-11eb-860b-26cc74555e06.png)

**Comment by fedorov** [comment]
Let's discuss this at the next coordination meeting.

**Comment by mitianisb** [comment]
This is the current look.
![Screen Shot 2020-11-30 at 7 39 18 AM](https://user-images.githubusercontent.com/58752821/100630418-6182f400-32df-11eb-9620-1acc8bbff15a.png)
