### ISSUE TITLE
Remove non-Google login option

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#407]
As discussed in https://github.com/ImagingDataCommons/IDC-WebApp/issues/394#issuecomment-710427951

I strongly suggest we consider the option to completely remove the non-google login. I think it only adds confusion, and will make maintenance more challenging going forward (handing off cohorts, handling different workflows for google and non-google users). There is very little one can do if they are not willing to create a google account. I think refinement of our login options is a fair game considering we are in the pilot stage.

As noted by @s-paquette, also "numerous things are no longer needed if only Google handles our logins".

**Comment by fedorov** [comment]
I actually didn't realize the "numerous things are no longer needed if only Google handles our logins" part. I don't know what is the justification for using resources for maintaining those things, if there is no use case, and there is no benefit.

**Comment by s-paquette** [comment]
So, this is something @DavidPotCanuck and @wlongabaugh have to weigh in on because I seem to recall it was a part of the proposal, that a user not be required to use a Google log in.

**Comment by fedorov** [comment]
Good point, I will add to the stakeholder agenda to discuss this. Even if it was part of the proposal, I am pretty sure we can remove it if both we and stakeholders agree on this item.

**Comment by wlongabaugh** [comment]
The idea was to allow users to save cohorts without requiring a Google ID, which is still a desirable situation. Note that with DRS bundling, we should be able to support large manifest downloads in the long run. For comparison, GDC supports logins with NIH/eRA credentials, PDC supports logins with either NIH/eRA or Google credentials, and ICDC does not appear to support logins (but appears to be holding onto a file manifest for me through a persistent cookie).

**Comment by fedorov** [comment]
> The idea was to allow users to save cohorts without requiring a Google ID, which is still a desirable situation.

What is the point of being able to save a cohort without google id, if you cannot download it without a google id?

> For comparison, GDC supports logins with NIH/eRA credentials, PDC supports logins with either NIH/eRA or Google credentials, and ICDC does not appear to support logins (but appears to be holding onto a file manifest for me through a persistent cookie).

I think this makes the case to free the resources from maintaining the resource-specific login to instead add NIH/eRA credentials.

**Comment by fedorov** [comment]
As confirmed by Todd, we do NOT have a contractual obligation to have the non-google node-specific login. It would be good to have NIH login, but that is a separate topic.

All in all, I do not see any benefit in keeping non-google login option.

**Comment by s-paquette** [comment]
@fedorov @wlongabaugh We should discuss this on Monday, but, the issue at hand is we already have users making use of the non-Google logins. The chunked download allows them to get their files, so that issue has a solution in place.

**Comment by fedorov** [comment]
Given the resistance from ISB to remove the non-google login, closing the issue.
