### ISSUE TITLE
collection tcga count on dev tier different from the test tier

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#412]
The counts for the collection TCGA seems to be 1,842 on the dev tier but, 1,841 on the test tier.

dev tier
![dev tier collection tcga count](https://user-images.githubusercontent.com/16824894/96320785-5c910c00-0fe1-11eb-8657-986cc0a34e47.PNG)

test tier
![test tier tcga collection count](https://user-images.githubusercontent.com/16824894/96320791-6155c000-0fe1-11eb-92cf-d510f8d0cbb3.PNG)

**Comment by s-paquette** [comment]
I found the culprit--somehow, case TCGA-J2-8194 is missing from TCGA-LUAD on test. It's a little weird considering it's not missing on production.

I'll re-do the ETL into the index to get it added back into test.

**Comment by s-paquette** [comment]
ETL done and counts seem to match again--confirm when you have a chance.

**Comment by madelyngreyes** [comment]
The Collection counts on the dev tier and the test tier is the same. 

dev tier
<img width="303" alt="dev tier counts" src="https://user-images.githubusercontent.com/16824894/96900754-73f84b00-1460-11eb-9473-65b0adddc55c.PNG">

test tier
<img width="484" alt="test tier counts" src="https://user-images.githubusercontent.com/16824894/96900780-778bd200-1460-11eb-827a-0ebe373ae440.PNG">
