### ISSUE TITLE
Capitalization of collection names should be consistent with TCIA conventions in all places

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#414]
Currently, it is lower-case in the right panel.

![image](https://user-images.githubusercontent.com/313942/96346945-83485480-106c-11eb-8f73-1c817fc4c00d.png)

**Comment by fedorov** [comment]
George says it's just formatting, will be fixed to use upper case, consistent with the TCIA conventions.

**Comment by ulrikew** [comment]
Beware, TCIA uses upper and lower case depending on the collection. 
![image](https://user-images.githubusercontent.com/3019001/96916873-271f6f00-1476-11eb-8d50-23ae0551e628.png)

**Comment by fedorov** [comment]
@ulrikew indeed, so you recommend we use those names? As @bcli4d identified and documented, there are differences in spelling between the various ways those names can be obtained, between TCIA_API_CollectionID, NBIA_CollectionID and TCIA_Webapp_CollectionID.

As a preview, see below, but I can also make a complete list. As you can see, it is not as trivial as using '_' in place of ' '. 

Is it a bug or something that need to be addressed on the TCIA/NBIA side to make sure the names are consistent across the various ways those names can be obtained?

![image](https://user-images.githubusercontent.com/313942/96930477-c1d57900-1489-11eb-8ccd-74df66c43c71.png)

**Comment by fedorov** [comment]
@G-White-ISB @s-paquette can we switch to using `tcia_api_collection_id` from `idc-dev-etl:idc_v2.auxilliary_metadata` for the name of the collection displayed in the webapp?

![image](https://user-images.githubusercontent.com/313942/112380706-18a4e000-8cc0-11eb-8895-68684f530aac.png)

**Comment by G-White-ISB** [comment]
TCIA collection names (https://www.cancerimagingarchive.net/collections/) should now appear consistently in IDC

**Comment by fedorov** [comment]
Great, thanks - I see it on dev.

Did you notice that now there are some rendering issues do to lack of wraparound for top-level names?

![image](https://user-images.githubusercontent.com/313942/115056279-9e2b4280-9eb0-11eb-83a1-d9755ac01364.png)

**Comment by madelyngreyes** [comment]
There is another field that has text cut off. 

<img width="1322" alt="Screen Shot 2021-05-13 at 3 37 26 PM" src="https://user-images.githubusercontent.com/16824894/118177844-3a3d6080-b401-11eb-82f3-90b75392cd82.png">

**Comment by ulrikew** [comment]
We have similar issues in NBIA and have brought this up as a topic in this morning's NBIA/TCIA call. Our plan is to work towards a size limit for the collection short names. Which max length would IDC prefer?

**Comment by fedorov** [comment]
I am not sure it is a good idea to change the collection names for the existing collections, so I think we need to have a way to deal with the current lengths. Did you think about enacting the limit going forward, or also for the existing collections, Ulli?

**Comment by ulrikew** [comment]
@fedorov I do not yet know the answer to your question. I will put it on the IRCoCo agenda for all to discuss.

**Comment by G-White-ISB** [comment]
Old issue but worth checking again? I think we are now consistent

**Comment by s-paquette** [comment]
@fedorov @ulrikew Do we now meet the requirements of this ticket?

**Comment by ulrikew** [comment]
Yes, looks good. Only (very minor) difference I found was the last letter in the MIDRC collection names. Don't fix.
