### ISSUE TITLE
Add "case" level to the search results navigation panel on the right

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#415]
Right now, we have Collection > Study > Series. Skipping the Case level does not make sense, is not consistent with any of the other existing DICOM browser interfaces, and already raised concerns from two very experience users (Ulli Wagner and David Clunie).

For the reference, DICOM Browser interface in Slicer:

![image](https://user-images.githubusercontent.com/313942/96357277-dbf90b00-10c7-11eb-969e-3c60331ca731.png)

**Comment by fedorov** [comment]
Another example of Case/subject level in the TCIA browser:

![image](https://user-images.githubusercontent.com/313942/96456684-d517e880-11ec-11eb-9c06-e5179d1bbb91.png)

**Comment by fedorov** [comment]
Suggestion for what should go into the case table: Collection ID, Case ID, number of studies, number of series

**Comment by fedorov** [comment]
Discussed with the team, and agreed adding a case-level table makes sense.

We should probably not have a column with the "View" option, since we currently cannot open multiple studies in the viewer. There is no clear timeline if/when that would be possible.

**Comment by fedorov** [comment]
George will use collection id + patient id for building the table

**Comment by madelyngreyes** [comment]
![new cases panel](https://user-images.githubusercontent.com/16824894/100013290-9accd880-2da2-11eb-9fdf-c88a3809f44b.PNG)
