### ISSUE TITLE
Age at diagnosis None selection is not listed on the cohort creation confirmation pop-up

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#420]
On the Explore Image Data portal, the selection of the attribute Related, Age at Diagnosis: None doesn't appear on the cohort creation confirmation pop-up on the dev tier and the test tier. 

![2020-10-19 (13)](https://user-images.githubusercontent.com/16824894/96511407-0c0dee80-122d-11eb-9db8-e416021931f0.png)

**Comment by madelyngreyes** [comment]
Also, the attribute is not listed on the cohort details page Filter Definition panel after the cohort is created.

**Comment by G-White-ISB** [comment]
Remains an issue. Will see if I can resolve it.

**Comment by s-paquette** [comment]
@G-White-ISB Move this into Sprint 22?

**Comment by pgundluru** [comment]
![image](https://user-images.githubusercontent.com/85526819/129973437-086e67f1-ab39-47fb-9232-471b3f9f8b17.png)
