### ISSUE TITLE
Implement proper dialog for cohort manifest export

### ISSUE THREAD

**Issue by mitianisb** [ImagingDataCommons/IDC-WebApp#421]
From Zenhub:

This dialog should provide the following options:

- Format output type (CSV, TSV, JSON)
- Disabling of header fields via checkbox (Name, Filters, timestamp, etc)
- Disabling/enabling of various columns
- File name

The file name MUST be checked for potentially unsafe characters (code for cohort name and desc can be re-used).

**Comment by mitianisb** [comment]
@s-paquette @fedorov I started working on this item from zenhub, and have some questions:

1. Does the user must provide a name for the manifest? Or can the user use automatic generated name, and only rename as needed?

2. Is there any header fields or columns that are required and not optional? 
If so, can we change the two titles to "optional header fields", and "optional columns"? The checkboxes can all be selected by default.

3. For the file formats, I saw CSV is implemented in the backend right now. Is TSV and JSON not implemented yet?

This is a mock up I made. If you can help clarify these questions it will help a lot! Thanks!

![image](https://user-images.githubusercontent.com/58752821/96831380-d403d880-13f1-11eb-8c55-63d5f1cfa375.png)

**Comment by ulrikew** [comment]
The column labels in the form should correspond to the column names in the manifest file e.g. Study Instance UID, SOP Instance UID etc. Spell out abbreviations that might not be obvious to novice users.

**Comment by fedorov** [comment]
@mitianisb let's review this at our weekly meeting with the ISB team. I don't think it is urgent to address this, and I don't want to make decisions without making sure @wlongabaugh and @s-paquette are on board.

**Comment by mitianisb** [comment]
Thanks for the feedback! We have discussed this in our team meeting. And we feel it will be better to make the manifest file name as required, and all the columns are optional. There is a warning message to let the user choose at least one column so that the file will not output empty records.

As requested by @fedorov, I have also made the JSON format work with Big Query upload. For this to work the JSON file need to only contain data records, and cannot contain header fields or warning messages (such as "exceeding 65000 rows") like in CSV or TSV files. This is because BigQuery UI does not have the option to skip rows in JSON.

@fedorov Can you help me finalize the Columns checkbox texts we would like to show in the dialog? I have made them match exactly with the column names in the manifest file. Do we want to spell out the abbreviations too? Thanks!

![Screen Shot 2020-11-01 at 9 13 38 PM](https://user-images.githubusercontent.com/58752821/97832271-375df800-1c87-11eb-81e6-9fc778f68323.png)

**Comment by fedorov** [comment]
Thanks, this sounds good. The columns text looks good to me, except I would change "GCS Path" to "GCS URL". I do not think it is necessary to spell out the abbreviations.

Another thing to consider is to perhaps pre-populate the name of the file with the cohort name and identifier, and the date/time of export.

A related question - do we have a concept of a unique identifier for each cohort?

**Comment by mitianisb** [comment]
Thanks for the feedback! I can make the text change and pre-populate the name of the file. According to my understanding, We do have a unique cohort Id for each user, but we do not have a global unique id.

**Comment by s-paquette** [comment]
We have a unique ID for each cohort in the database itself, but it's a simple integer relative to that table. It wouldn't necessarily be especially useful to the user.

**Comment by fedorov** [comment]
IMHO consistently pre-populated filename is better than empty field that needs to be populated by the user.

**Comment by mitianisb** [comment]
@fedorov pre-populated filename has already added. Please let me know if you have any more feedback.
![Screen Shot 2020-11-03 at 10 51 28 PM](https://user-images.githubusercontent.com/58752821/98078677-5dba9980-1e27-11eb-9cc9-1323dee26fbd.png)

**Comment by fedorov** [comment]
Looks good to me - thanks!

**Comment by fedorov** [comment]
When I choose to download JSON, I get this:

![image](https://user-images.githubusercontent.com/313942/99688719-1f8ebe00-2a54-11eb-98be-f8f836d84299.png)

**Comment by mitianisb** [comment]
@Thanks for finding this. I will look into it later today.

**Comment by mitianisb** [comment]
@fedorov This is fixed and merged. Thanks!

**Comment by madelyngreyes** [comment]
I return a failed network error message.

![network error from json download](https://user-images.githubusercontent.com/16824894/100020895-9a3a3f00-2dae-11eb-9aff-0240610b1e76.PNG)

**Comment by madelyngreyes** [comment]
We will also need to update the cohort is too large and is truncated at 65,000 rows notification to reflect the new columns that were added. 
The options now include, 
- Patient ID 
- Collection ID
- Study Instance UID 
- Series Instance UID
- SOP Instance UID 
- Source DOI 
- CRDC Instance UUID 
- GCS URL

![2020-11-23 (3)](https://user-images.githubusercontent.com/16824894/100042210-ff0a8f00-2dd8-11eb-8ac2-6e8a869f4e66.png)

**Comment by mitianisb** [comment]
I have updated the warning message to include all columns. I also tried to test the download JSON network error. I am not sure what is causing the problem. Sometimes I can download a large file (32MB) correctly in my localhost server. But sometimes the file will stop downloading at very small size, show as completed, but file content is broken. I think there may be some server setting need to change. @s-paquette could you help take a look when you come back? Thanks!

**Comment by s-paquette** [comment]
I haven't been able to reproduce the download hiccup option, but part of the issue is how we were triggering the download. I've adjusted how it's done on dev, and will port that to test later today with some upgrades. This should let us track the JS errors better.

**Comment by s-paquette** [comment]
@madelyngreyes Ready for testing when the current test build completes, ~30m
