### ISSUE TITLE
Selected Studies and Series panel enhancements

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#422]
For the Selected Studies panel,

- [ ] change the Case Id to Patient ID
- [ ] change Study Id to Study StudyInstanceUID
- [x] add the ability to be able to copy to StudyInstanceUID to the clipboard, which can be helpful for example to use with BigQuery
- [ ] capitalize ID/UID
- [x] change "Project name" to "Collection name"

![Id in data portal not ID](https://user-images.githubusercontent.com/16824894/97039794-fb19f180-153a-11eb-8e40-3662c8c8a6f1.PNG)

For the Selected Studies panel,

- [ ] change Study Id to Study StudyInstanceUID
- [ ] add the ability to be able to copy to StudyInstanceUID to the clipboard, which can be helpful for example to use with BigQuery
- [ ] capitalize ID/UID

![series panel column header enhancements](https://user-images.githubusercontent.com/16824894/97039889-2a306300-153b-11eb-8fd2-169c1744b81c.PNG)

**Comment by fedorov** [comment]
Capitalization is addressed in https://github.com/ImagingDataCommons/IDC-WebApp/issues/414.

The only controversial one is Case ID -> Patient ID. Although `PatientID` is what we have in DICOM, we should discuss if we should make this switch, or stay with Case ID for the sake of consistency with other nodes.

**Comment by fedorov** [comment]
Also, need to change Project name into Collection name in the below

![image](https://user-images.githubusercontent.com/313942/97058086-dc2b5780-155a-11eb-84ac-fa5c0c5233b2.png)

**Comment by s-paquette** [comment]
@fedorov Is this issue now resolved?

**Comment by fedorov** [comment]
@s-paquette I checked the items that have been resolved in the original issue post. Not all of them are resolved.

**Comment by G-White-ISB** [comment]
@fedorov  what remains to be resolved?

**Comment by fedorov** [comment]
Items that are unchecked from the original list in https://github.com/ImagingDataCommons/IDC-WebApp/issues/422#issue-728425015:

![image](https://user-images.githubusercontent.com/313942/152882823-4530629c-2da1-46b7-9d7b-ac92dce88c52.png)

**Comment by G-White-ISB** [comment]
Got it. But are we changing 'Case ID' to 'Patient ID'? I think that would require changes elsewhere, including the documentation. 'StudyInstanceUID' will be one word?

**Comment by fedorov** [comment]
Yes, it's a difficult decision. But there is no such thing as "Study Id" in our metadata. There is also no such thing as "Case Id" anywhere. So with all the harm this will cause, I don't see how we can justify this inconsistency. Thoughts?

**Comment by fedorov** [comment]
> 'StudyInstanceUID' will be one word?

Can be one word, or "Study Instance UID".

Let's discuss this at the next webapp coordination meeting.

**Comment by G-White-ISB** [comment]
Study Id -> Study Instance UID is trivial. Case Id -> Patient Id is more of an issue.  I know its been debated before

**Comment by s-paquette** [comment]
@G-White-ISB @fedorov What's the status of this issue?

**Comment by fedorov** [comment]
I thought when we discussed this last time, we decided to replace Case ID with Patient ID in the portal, and add the "info" icon with the tooltip explaining Patient ID vs Case ID, but I do not see this in the portal yet.

<img width="405" alt="image" src="https://user-images.githubusercontent.com/313942/157320689-b9fb3a8f-8c6c-4bdc-9efd-346978f84d72.png">

**Comment by G-White-ISB** [comment]
I thought we decided to keep CASE ID and add a tooltip exp. that Case ID = Patient ID in the DICOM files. I did not make that tooltip yet.  But there was a[ merge](https://github.com/ImagingDataCommons/IDC-WebApp/pull/890) related to this issue before the last discussion wrt CASE ID vs Patient ID

**Comment by fedorov** [comment]
It could be I got it the way around. Keeping Case ID and adding tooltip is fine.

**Comment by fedorov** [comment]
@G-White-ISB please also update StudyID in the search box:

<img width="368" alt="image" src="https://user-images.githubusercontent.com/313942/157887279-8e857bae-913d-4054-b2e9-065c09f0630e.png">

**Comment by s-paquette** [comment]
@fedorov @G-White-ISB Are we moving this into Sprint 28, or should I wait for a PR to fix it?

**Comment by fedorov** [comment]
no need to hold the release for this

**Comment by G-White-ISB** [comment]
Fixes were already checked in. This item needs testing to resolve.

**Comment by pgundluru** [comment]
CASE ID and associated tool tip in exploration page for selected cases - success
Search is now Case ID search and works when a full Case ID is given to search
