### ISSUE TITLE
Debug and fix, or explain the behavior of the portal

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#423]
Why do I get empty cohort list if I set the Volume attribute to [27872-31113]? As a user, my naive assumption is that if the upper limit of the range is set to X, then there must be something that hits that max limit. What am I missing?

![image](https://user-images.githubusercontent.com/313942/97212788-3a447e80-1797-11eb-82e2-0025d44ea85a.png)

It's a bug in production, until someone proves otherwise.

**Comment by fedorov** [comment]
![image](https://user-images.githubusercontent.com/313942/97237972-aedee380-17be-11eb-8c35-71a5baff9fd5.png)

**Comment by G-White-ISB** [comment]
In progress

**Comment by G-White-ISB** [comment]
Test ready in  dev.202011190249.1cbc69

**Comment by madelyngreyes** [comment]
While testing the attribute TOTAL LESION GLYCOLYSIS (GRAM) towards the end of the range I ran into occasional 500 error in the console and the cases panel wouldn't load e.g., range (748-776).

![500 error in dev console when using total lesion glycolysis](https://user-images.githubusercontent.com/16824894/100038482-fa8ea800-2dd1-11eb-95e9-85da5f29fa23.PNG)
![total lesion filter has a bug](https://user-images.githubusercontent.com/16824894/100038485-fb273e80-2dd1-11eb-89d6-b4a72e835133.PNG)

**Comment by G-White-ISB** [comment]
As discussed this is really a new issue. But I'm not sure if the idc-test portal is even up to date right now. I thought testing should be done in idc-dev

**Comment by madelyngreyes** [comment]
I will have a look in the dev tier, thank you for the clarification!

**Comment by madelyngreyes** [comment]
![case reflected](https://user-images.githubusercontent.com/16824894/101409410-e0fa5f80-38ab-11eb-8b4b-623a74ecbe1d.PNG)
![case reflected](https://user-images.githubusercontent.com/16824894/101409419-e3f55000-38ab-11eb-8cef-76aa5e0bf82b.PNG)

**Comment by madelyngreyes** [comment]
![ticket423 fix](https://user-images.githubusercontent.com/16824894/101916557-1e553a80-3b95-11eb-8c07-963680ee9446.PNG)
