### ISSUE TITLE
zombie pie chart present in Search Results with selection of multiple Derived attributes

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#425]
Running into the "ghost pie chart" related issue again on the production tier. I selected Segmentation type mass then selected the attribute Volume, values 9485-31113. Then returned 31 cases in the Segmentation Type pie chart but, no Collections are listed in the Collections panel.

![2020-10-28 (7)](https://user-images.githubusercontent.com/16824894/97509583-1335aa80-1959-11eb-9777-ae178d92f0b3.png)

**Comment by madelyngreyes** [comment]
Suzanne's comment in Slack, "This looks like an issue with that chart not using the 'filtered' count-set, or rather, not reacting to it coming back empty (i.e. all zeros)." @G-White-ISB

**Comment by G-White-ISB** [comment]
In progress

**Comment by G-White-ISB** [comment]
Test ready in  dev.202011190249.1cbc69

**Comment by madelyngreyes** [comment]
While testing I returned a 500 error in the dev console for the attribute selection, "Derived Segmentation Type:Heart, Mass, Nodule and Volume:9168 to 31113"  and the selected studies panel wouldn't open. 

![cohort selection doesnot open the selected studies panel](https://user-images.githubusercontent.com/16824894/100040575-8ce47b00-2dd5-11eb-8e76-73f0eb5a8120.PNG)

**Comment by madelyngreyes** [comment]
@s-paquette  Hello, do the 500 errors I ran into last week belong in this ticket or a new ticket?

**Comment by G-White-ISB** [comment]
It belongs in a new ticket. I also with a network error message there is
always the issue of whether this is a code problem or a network (possibly
intermittent) problem. It would make sense to report the URL that
generates the 500 error and to retest.

George

**Comment by madelyngreyes** [comment]
![ticket 425 resolved](https://user-images.githubusercontent.com/16824894/100669139-f65f0f00-332a-11eb-9696-6ebe4fdb91ad.PNG)

**Comment by madelyngreyes** [comment]
![no ghost pie chart object](https://user-images.githubusercontent.com/16824894/101844826-5029bb00-3b1b-11eb-941f-c58fceac2eeb.PNG)
