### ISSUE TITLE
Disable ability to select "None" in piecharts

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#433]
As discussed earlier, we are not supporting filtering on None, and that is why it is disabled in the left panel. It is currently still selectable from the piechart though.

**Comment by madelyngreyes** [comment]
I was able to filter on the attribute None for the Body Part Examined option on the dev tier.

http://somup.com/cYlebj22Bo

**Comment by G-White-ISB** [comment]
This is only applies to quantitative filters in the derived tab

**Comment by madelyngreyes** [comment]
Can we add a notification the option is disabled? Currently, nothing happens when the None option is selected.
