### ISSUE TITLE
Use first 6 characters of commit hash for webapp versioning

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#434]
Last 6 characters used now make it very difficult to identify the actual commit that was used.

**Comment by s-paquette** [comment]
Swapped to first 6.

**Comment by madelyngreyes** [comment]
Where the most recent hash is displayed. 

![image (2)](https://user-images.githubusercontent.com/16824894/100635800-f6491a00-32fe-11eb-941f-17031dccf6c7.png)
