### ISSUE TITLE
Manifests for NSCLC-Radiomics collection is invalid

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#436]
The columns include DCF UUID, but that column is not populated, and does not have empty items, so effectively the exported manifest file has fewer columns than the column header items.

**Comment by s-paquette** [comment]
Any manifest entries with missing values will now have a blank field (,"",) for that missing value. The column header will remain if it was a requested column, as someone could conceivably make a manifest which combines NSCLC and LUAD, the later of which does have CRDC UUIDs and so would have values for that coumn.

**Comment by fedorov** [comment]
I confirm this appears to be working in dev.
