### ISSUE TITLE
Data summary ribbon needs to be updated to account for NSCLC-Radiomics

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#437]
The current summary does not match the actual content, the Collections table, and the list of collections included in the docs.

![image](https://user-images.githubusercontent.com/313942/99279333-1f958080-27fe-11eb-9e73-163afe84852d.png)

**Comment by s-paquette** [comment]
@bcli4d @wlongabaugh Will need new Data Volume and Image Series numbers

**Comment by bcli4d** [comment]
Data volume: 1065825767524
Series: 51247
Cases: 3652
Collections: 28
