### ISSUE TITLE
Selection of a collection attribute on the no login required data exploration page doesn't save the selection after login

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#439]
Steps to reproduce the issue, 

1. Go to the exploration page
2. Select collection NSCLC_RADIOMICS 
3. Select the login to save button
4. Login to the IDC
5. The Filter definition panel will not have the collection NSCLC_RADIOMICS listed

**Comment by mitianisb** [comment]
@s-paquette I have found a fix and tested it works locally. I have sent out a PR. Thanks!
