### ISSUE TITLE
Cohort details page: all TCGA collections display if any one TCGA collection is in the filter

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#440]
Bill C reports, 

On both dev and production webapps, defined a cohort:
<img width="1311" alt="attribute selection" src="https://user-images.githubusercontent.com/16824894/99329057-652c6a80-284b-11eb-9d31-1f009e7c5ef7.png">
On saving it, it became:
<img width="640" alt="saving attribute selection" src="https://user-images.githubusercontent.com/16824894/99329102-855c2980-284b-11eb-85f8-e4e6a17747e1.png">

**Comment by s-paquette** [comment]
Ah ha, I know what this is. The filter *isn't* changing. It's just the display is checking the TCGA box, which is resulting in *all* of the boxes being visually checked. I'll see if I can get it to only check TCGA-READ.
