### ISSUE TITLE
Check all / uncheck all button below collection list does not work

### ISSUE THREAD

**Issue by ulrikew** [ImagingDataCommons/IDC-WebApp#445]
The check all/ uncheck all links at the bottom of the collection list in the portal do not work.

**Comment by madelyngreyes** [comment]
On the dev tier, the select all/uncheck all functionality currently only applies to the collection TCGA.

Should the select all/uncheck all functionality apply to all collections? @G-White-ISB

**Comment by madelyngreyes** [comment]
For this iteration the select all/unselect all only applies for the collection TCGA.
