### ISSUE TITLE
Add Species as search criteria in portal

### ISSUE THREAD

**Issue by ulrikew** [ImagingDataCommons/IDC-WebApp#446]
TCIA has public mouse collections and is in the process of curating a dog collection. Users need to be able to select by species.
Attached are the NBIA team's curation recommendations to the TCIA team. It contains an explanation of what DICOM fields to populate and examples.
[TCIA curation - 2019-09-29 incl canine.docx](https://github.com/ImagingDataCommons/IDC-WebApp/files/5577707/TCIA.curation.-.2019-09-29.incl.canine.docx)

**Comment by s-paquette** [comment]
Note, this would need to be brought into dicom_all, so is in part an ETL adjustment.

**Comment by wlongabaugh** [comment]
@bcli4d Add species into dicom_all (as well as cancer_type?).

**Comment by bcli4d** [comment]
tcia_species and tcia_cancerType are in dicom_all

**Comment by madelyngreyes** [comment]
Species options added to the exploration page, 

<img width="1308" alt="Screen Shot 2021-06-09 at 4 49 57 PM" src="https://user-images.githubusercontent.com/16824894/121427477-c2505080-c942-11eb-902a-bc738494833e.png">
