### ISSUE TITLE
Users should not have to scroll to see all search criteria

### ISSUE THREAD

**Issue by ulrikew** [ImagingDataCommons/IDC-WebApp#451]
The left side search criteria should expand without the users having to scroll. Right now, IDC has only about a fifth of the data that TCIA has in the radiology portal and it is already a problem. I opened up the lists for primary site location and body part examined and had to scroll within the window.
![image](https://user-images.githubusercontent.com/3019001/99879091-57267300-2bd8-11eb-97e6-c48e1c049d09.png)

**Comment by fedorov** [comment]
Related issue https://github.com/ImagingDataCommons/IDC-WebApp/issues/375

**Comment by wlongabaugh** [comment]
@ulrikew We are currently consistent with GDC. Decision so far is to keep the scroll bar but make the left-hand filter panel larger by default (Right now it is smaller than the right side).

**Comment by ulrikew** [comment]
@wlongabaugh Thank you for pointing the similarity to GDC out. Let's take a look at it after the left-hand filter panel has been enlarged.
Please keep in mind that as of now TCIA has 108 public radiology collections, 73 primary sites, 2 species, 23 modalities. These are criteria that IDC has to support and the team may decide that other criteria should be introduced. GDC has fewer attributes to support.

**Comment by G-White-ISB** [comment]
The maximum height of the LH panel has been doubled on the dev tier

**Comment by fedorov** [comment]
Looks better to me!

**Comment by madelyngreyes** [comment]
Should the scroll bar appear at all? @G-White-ISB 

If all options are opened for the Original tab, the scroll bar functionality will appear. 
![scroll bar appears when all options opened for original tab](https://user-images.githubusercontent.com/16824894/103924168-ad496a00-50e3-11eb-9be4-e54e4035c2a0.PNG)

**Comment by fedorov** [comment]
@ulrikew I find the absence of scroll bar on the left side to be very limiting. I think it would be very helpful for improved usability of the portal to be able to scroll through the search options without moving the results of the search out of view. This became a particularly problematic issue looking at the v2 with the extent of the number of collections and options in the portal.

I suggest that we mimic the behavior of the GDC portal as shown below, so that the left panel can be scrolled independently from the right side. What are your thoughts? Do you agree we should revisit this?

![2021-04-20_13-06-04](https://user-images.githubusercontent.com/313942/115436827-6a665a80-a1d9-11eb-8007-b86a88f60b62.gif)

**Comment by ulrikew** [comment]
Yes, let's revisit. I have only access to the test tier and don't see the full list of collections there.

**Comment by fedorov** [comment]
@madelyngreyes I think we were planning to revisit this.

**Comment by fedorov** [comment]
I personally like how on GDC portal the left scroll area height is adjusting to the height of the right side panel when the number of items is changing:

![image](https://user-images.githubusercontent.com/313942/117035170-014f0e80-acd2-11eb-9571-ec5ddcbc7a43.png)

Also note there is a single left-side scrollable area in GDC Portal.

**Comment by fedorov** [comment]
Will revisit once v2 is available to @ulrikew in the test tier.

**Comment by fedorov** [comment]
@ulrikew do you have any comments on the suggestion to mimic the scrolling approach implemented in the GDC portal, now that you have access to v2 in test?

**Comment by ulrikew** [comment]
The implementation of the scroll bar looks ok.

**Comment by pgundluru** [comment]
The scroll on the left has been tested

**Comment by fedorov** [comment]
I discussed this topic with @ulrikew and @rkikinis, and both of them agreed the current behavior where the height of the left area expands uncontrollably disregarding the height of the right panel is not user friendly. Both Ulli and Ron agreed that implementation of the behavior as seen in the GDC portal, where heights of the left and right panels are coordinated, is a lot more appealing and user-friendly.

**Comment by s-paquette** [comment]
@G-White-ISB See the most recent comment on how this should be changed.

**Comment by fedorov** [comment]
Is this something that is really hard to fix?

**Comment by G-White-ISB** [comment]
The LHS now resizes to stay the same length as the RHS when the RHS length changes. This is how the LHS and RHS are coordinated in GDC. This change was already propagated to production. Sorry I'm not sure how this was missed in the issue tracking

**Comment by s-paquette** [comment]
@fedorov @ulrikew Does the new format of the display suit the requirements of this issue?

**Comment by fedorov** [comment]
Related/duplicate to #375 - resolved.
