### ISSUE TITLE
Derived search tab: How difficult would it be to remove the search categories when the user selects "Hide attributes with 0 cases"?

### ISSUE THREAD

**Issue by ulrikew** [ImagingDataCommons/IDC-WebApp#453]
The "Hide attributes with 0 cases" is an excellent feature!
I selected breast as the anatomical region and it removed all the attributes of the search criteria in the qualitative analysis category but I still had to expand every single one of the sub-categories e.g. calcification to see if there were entries/attributes there. Is there a way to indicate to the user that these categories are empty by either removing them or expanding them or any other way that makes it clear to the user that there is nothing more to select from?

**Comment by G-White-ISB** [comment]
Proposed fix  on dev tier

**Comment by madelyngreyes** [comment]
New hidden value format on the test tier,
![Screen Shot 2021-02-17 at 8 05 51 PM](https://user-images.githubusercontent.com/16824894/108288983-93c42500-715b-11eb-957c-902f38fed9e6.png)
@fedorov @ulrikew

**Comment by ulrikew** [comment]
Looks good to me.

**Comment by fedorov** [comment]
Looks good, thanks!
