### ISSUE TITLE
Related Search Tab: Indicate or remove empty search criteria

### ISSUE THREAD

**Issue by ulrikew** [ImagingDataCommons/IDC-WebApp#454]
Same as in the ticket for the "Derived" search tab: Is there a way to indicate which sub-categories still contain search criteria?
![image](https://user-images.githubusercontent.com/3019001/99879498-6529c300-2bdb-11eb-9f50-60b1905fc1b9.png)

**Comment by s-paquette** [comment]
related to #411 and #453

**Comment by madelyngreyes** [comment]
![no data available implementation](https://user-images.githubusercontent.com/16824894/103925849-1f22b300-50e6-11eb-8793-712957826af5.PNG)

Current implementation will display the option as "greyed out" when no data is available. Additional text should be added, "No data available with current attribute filter selection" to make it clear to the end user. 

Also, the "blank" attribute option can still be selected and displays white space. Selection should be disabled no need for white space. 
![whitespace not needed](https://user-images.githubusercontent.com/16824894/103926317-c0aa0480-50e6-11eb-800f-376ba7947703.PNG)

**Comment by fedorov** [comment]
I do not think displaying a gray rectangle over interface elements is a good way to indicate that "no data is available". I also don't understand the meaning of "no data is available". Can someone explain what that actually means?

**Comment by fedorov** [comment]
I believe a lot more intuitive approach to indicating that all items under a category are zero would be to show the cumulative count of categories underneath side by side with the filter group heading.

Also note that those gray boxes show up while viewing cohorts, but not when defining a filter and forming a cohort, even when "no data is available" during that process.

**Comment by fedorov** [comment]
@ulrikew would be great to have your thoughts on this.

**Comment by madelyngreyes** [comment]
Bug reported when using the hide filters with zero cases functionality and the filter selection Body Part Examined: Abdomen in the exploration page. 
![grey rectangle broken for certain filter selections](https://user-images.githubusercontent.com/16824894/105218633-687df400-5b23-11eb-8059-570d1194b1ce.PNG)

**Comment by fedorov** [comment]
Per discussion today, we agreed to indicate in the attribute sub-category if the number of cases underneath is 0. This will be indicated independently of whether "hide attributes" checkbox is selected. When expanded, the sub-category with 0 cases will not have any content IF "hide attributes" checkbox is selected.

@ulrikew does this sound good to you?

**Comment by G-White-ISB** [comment]
Here is a proposed fix. If an attribute has no cases it's heading is struck though and the explanation (No relevant cases) appears.

![Screen Shot 2021-02-02 at 9 57 42 AM](https://user-images.githubusercontent.com/58443591/106642508-4762cd80-653d-11eb-9a9e-ae75baab233d.png)

**Comment by fedorov** [comment]
I would prefer not to have the strikethrough, it looks very strange, and "0 cases" instead of "No relevant cases".

**Comment by s-paquette** [comment]
@fedorov  Maybe graying it out to signal de-activation?

**Comment by ulrikew** [comment]
I like the latest version (grayed out text and 0 cases in parenthesis).  Assuming that you are going to implement this for all selection criteria please verify that it is CASES and not studies or series that return no results.

**Comment by G-White-ISB** [comment]
Currently the filtering applies to the case level, not study or series level. Will implement this version.

**Comment by fedorov** [comment]
I also like the updated design. Thank you!

**Comment by ulrikew** [comment]
> Currently the filtering applies to the case level, not study or series level. Will implement this version.

Ok, sounds good.

**Comment by s-paquette** [comment]
@ulrikew @fedorov @G-White-ISB Filtering is currently done at the *study* level, not the case level. Very few cases have more than one study, so this comes very close to 1:1, but we can expect that to change as we add in more collections. 

There's one instance where this doesn't apply, which is related data. Related data comes from the GDC, PDC, and similar nodes, and will be associated to a case or a sample. So, in effect, related filters are case-level filtering, in that you'll obtain all studies for that case, but that's simply because related data is only found at that level.

**Comment by ulrikew** [comment]
@s-paquette "Filtering is currently done at the study level, not the case level"
Would it then be more accurate to say "0 studies" instead of "0 cases"?

**Comment by G-White-ISB** [comment]
But the counts reported are # of cases matching the filter.

**Comment by s-paquette** [comment]
@ulrikew Right, we show case counts, not study counts. It's best for now if we keep a consistent language of '0 cases found'. We have a ticket and general plan to discuss what to do about 'level of filtering', as this has a significant impact when it comes to derived data, which isn't available for all studies.

**Comment by ulrikew** [comment]
OK, sounds good.
