### ISSUE TITLE
Collections list - cosmetic fix needed

### ISSUE THREAD

**Issue by ulrikew** [ImagingDataCommons/IDC-WebApp#455]
Text runs into text. Add space between "entries" and "Show" or move it to different lines.
![image](https://user-images.githubusercontent.com/3019001/99879563-cea9d180-2bdb-11eb-8ee4-6403651c5cf7.png)

**Comment by fedorov** [comment]
I can reproduce this

![image](https://user-images.githubusercontent.com/313942/101383197-d5e10880-3886-11eb-8edf-869bee71fab4.png)

**Comment by wlongabaugh** [comment]
Might just be on a Mac

**Comment by madelyngreyes** [comment]
![spacing error fixed](https://user-images.githubusercontent.com/16824894/103926694-43cb5a80-50e7-11eb-96e0-757d9e7e4482.PNG)
