### ISSUE TITLE
Collections list: prepare for more data

### ISSUE THREAD

**Issue by ulrikew** [ImagingDataCommons/IDC-WebApp#456]
TCIA currently hosts >100 collections. The IDC collections list needs to be prepared for the large number of collections e.g. by setting the default on the collection list entries shown to 100. 
![image](https://user-images.githubusercontent.com/3019001/99879609-103a7c80-2bdc-11eb-9717-dc784bf8ea2b.png)

**Comment by fedorov** [comment]
I agree with Ulli. I suggest we show the same number of collections by default as in TCIA, which is currently 125.

**Comment by s-paquette** [comment]
Option to use is `pageLength` which defaults to 25, can be set to 100

**Comment by madelyngreyes** [comment]
![100 entries displayed by default](https://user-images.githubusercontent.com/16824894/103932475-dec83280-50ef-11eb-97d1-ecf98f6ea15c.PNG)
fixed
