### ISSUE TITLE
Pointers to Github, YouTube, Twitter from IDC front page

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#458]
I think it would be great to have pointers to IDC spaces below from the front page:
* YouTube channel: https://www.youtube.com/channel/UCQxuVp3_3aTJZBA4zZLMQtQ
* GitHub organization: http://github.com/ImagingDataCommons
* Twitter channel: https://twitter.com/CancerIDC

A conventional way to present those pointers is using icons like below at the footer of the website: 

![image](https://user-images.githubusercontent.com/313942/100015514-17ad8180-2da6-11eb-84dc-dad5fd7aa1ba.png)

Is this something that can be addressed easily?

**Comment by wlongabaugh** [comment]
This would be handled by the new footer.

**Comment by wlongabaugh** [comment]
Should check with @ulrikew about having this in the footer? Any NIH issues?

**Comment by fedorov** [comment]
This is being addressed in #449
