### ISSUE TITLE
Repeated login requested when viewing a study

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#47]
I logged in, configured some filters, and then clicked on the linked study ID.

I was then prompted to give access again, and was also prompted about doing unsafe things, and then was requested to give the following:

![image](https://user-images.githubusercontent.com/313942/75633720-69d5c380-5bd5-11ea-93c3-58f15624f1d7.png)

![image](https://user-images.githubusercontent.com/313942/75633725-70643b00-5bd5-11ea-96a2-25d5cb82a4f7.png)

Not sure if this is expected at this early stage, or is a bug. We should probably not have to log in second time, right?

**Comment by G-White-ISB** [comment]
Was your email address 'whitelisted' to access google healthcare? I needed to fill out this form first: https://services.google.com/fb/forms/cloudhealthcarepublicdatasetaccess/. 
It only took an hour for google to respond in my case.

**Comment by fedorov** [comment]
Yes, it was whitelisted a while ago. I don't think that was the reason.

**Comment by wlongabaugh** [comment]
Once we are going through the proxy, this problem should go away.

**Comment by G-White-ISB** [comment]
We are using the proxy now and I don't think this issue has come up again
