### ISSUE TITLE
export of large cohort to BigQuery with no columns selected will return error on the cohort details page

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#476]
![large cohort - no columns selected error](https://user-images.githubusercontent.com/16824894/101413463-52d5a780-38b2-11eb-8a0f-4cacaea146fd.PNG)

**Comment by madelyngreyes** [comment]
Any columns removed will trigger the notification error to please contact administrator.

**Comment by madelyngreyes** [comment]
non-google identity view of page below,
![IDC identity](https://user-images.githubusercontent.com/16824894/101417597-f9717680-38b9-11eb-87d0-ff8e46778a68.PNG)

**Comment by s-paquette** [comment]
So, no volumns sholdn't be allowe,d, since obviously you can't expect northing. @mitianisb can you have a look at that? It should be refusing to export without at least one selected column.

**Comment by madelyngreyes** [comment]
ticket https://github.com/ImagingDataCommons/IDC-WebApp/issues/479 was created.

**Comment by mitianisb** [comment]
I remember I have added check in the front end to warn and disable when no
column selected. Maybe just need to hook it up with the BQ option. I'll
have a look at this.

**Comment by madelyngreyes** [comment]
![column must be selected](https://user-images.githubusercontent.com/16824894/101529045-0647a600-395e-11eb-89c5-53edb4aeacd5.PNG)
fixed
