### ISSUE TITLE
It should be possible to view a specific series

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#48]
Right now, the whole study is loaded, no matter if it is selected in the study or series list.

**Comment by G-White-ISB** [comment]
Is that currently possible?
Set a series into the viewport programmatically #1006
https://github.com/OHIF/Viewers/issues/1006

**Comment by fedorov** [comment]
I think there are two different issues:
1. populate OHIF Viewer with a specific series, or a subset of series, from a single study
2. initialize viewport with a specific series

What I was asking is 1. @swederik is this possible?

**Comment by fedorov** [comment]
@pieper thinks it is probably not supported right now in OHIF Viewer. If this is the case, let's postpone this. I will bring up with Erik next week.

**Comment by swederik** [comment]
I believe both 1 and 2 are supported now. I will confirm before our meeting.

**Comment by G-White-ISB** [comment]
Any update on this?

**Comment by swederik** [comment]
Sorry for the delay.

If you launch a study normally, it will hang display sets in order of series number (e.g. https://viewer.ohif.org/viewer/1.3.6.1.4.1.25403.345050719074.3824.20170126085406.1 loads the scout first)

Adding a query parameter for SeriesInstanceUID allows you to launch another series. For example, this launches the second series (axial) of the study:

https://viewer.ohif.org/viewer/1.3.6.1.4.1.25403.345050719074.3824.20170126085406.1?SeriesInstanceUID=1.3.6.1.4.1.25403.345050719074.3824.20170126085406.5

The behaviour of the query parameter is controlled by an application configuration value (which is badly named...) called filterQueryParam. If True, the study will be filtered to show only the Series which is in the query string. If False (the default), that Series will be 'promoted', meaning it will be hung first and moved to the top of the thumbnail panel. 

You should be able to use more than one SeriesInstanceUID (if filterQueryParam is True) to filter the Study to a specific list of Series.

This happens at initial load. So we do the first QIDO-RS query to obtain the Series available in the Study, and then we only launch requests for the full metadata for the Series that we want to view.

We will add this to the documentation.

**Comment by G-White-ISB** [comment]
If the google healthcare dicom server is used then it seems it is currently NOT possible to initiate the viewer with a specific series. What happens is that the call is redirected to google for authorization, and after the callback the GET parameter ?SeriesInstanceUID= ... is 'stripped'.

**Comment by pieper** [comment]
Interesting.  What happens if you were already logged in?  (e.g. you go to the link a second time?)

**Comment by swederik** [comment]
Oooh that's interesting. I didn't test that. We can file an issue for that.

**Comment by G-White-ISB** [comment]
If you are already logged in you are not prompted to login again, but any time the viewer is opened in a new tab there is a redirect to google cloud and then a callback to the viewer. Now after you come back to the viewer you can navigate to ?SeriesInstanceUID=... since that will not cause a second redirect.

**Comment by pieper** [comment]
> Now after you come back to the viewer you can navigate to ?SeriesInstanceUID=... since that will not cause a second redirect.Makes sense, thanks.  This should go away once we proxy the dicomweb api so that people don't need to be logged in to view images.

**Comment by swederik** [comment]
Filed as https://github.com/OHIF/Viewers/issues/1663

**Comment by fedorov** [comment]
We are now going through the proxy (right, @wlongabaugh?) but if I click on a specific series, I am still not getting a single series in the viewer.

**Comment by wlongabaugh** [comment]
I think that would be an issue of what was specified to the viewer to show. The proxy is not making any editorial decisions.

**Comment by G-White-ISB** [comment]
Should be enabled when current pull request is accepted.
