### ISSUE TITLE
Allow user to specify the included fields in the BQ export

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#486]
Table will have null values for columns that were removed. 
![de-selection of columns result](https://user-images.githubusercontent.com/16824894/101806123-97935580-3ae1-11eb-8d68-9e3c85448a00.PNG)

Enhancement: To remove column headers with null values.

**Comment by pgundluru** [comment]
To test this I followed the below steps:

1. In test tier, select and create a cohort.
2. Export to BQ and select the header fields and columns to display (In this test I selected one column, many columns and no columns which is not permitted by default)
3. Then in GCP, preview to see only the selected columns.


![image](https://user-images.githubusercontent.com/85526819/144656842-655d26e1-45cb-45f8-a842-893fb4647fc6.png)
