### ISSUE TITLE
OHIF version used

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#49]
It appears that at the moment OHIF 3.4.1 is used, while the latest OHIF version is 3.7.2. We should use the latest one, especially since we are adding features that will be needed specifically by IDC, and should define the process of upgrade.

**Comment by G-White-ISB** [comment]
We will upgrade the viewer soon.

**Comment by G-White-ISB** [comment]
Updating to 3.8.1 when next pull request is processed

**Comment by fedorov** [comment]
I see as of today the version is 3.8.1 - thank you!
