### ISSUE TITLE
-1 as value range error for standardized added metabolic activity filter

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#493]
![-1 value as range](https://user-images.githubusercontent.com/16824894/102141335-aa35c380-3e2e-11eb-88f0-4c5fcbeed53e.PNG)

**Comment by G-White-ISB** [comment]
So Solr is reporting the minimum value for the standardized_metabolitv_activity to be -0.90883.. which is rounded to -1. This is the same in BQ ( at least in canceridc-data.idc.dicom_derived_all_wave1`).
