### ISSUE TITLE
Improve usability of BQ cohort manifest export information

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#494]
Right now, the URL to the destination table is shown in an obscure blue frame as plain tex:

![image](https://user-images.githubusercontent.com/313942/102278168-54791e00-3ef7-11eb-8e1f-083a2fa6af5e.png)

My understanding from earlier discussions that it is very difficult to add the link to that BQ table to the cohort list. Can we at least make that URL click-able?

**Comment by s-paquette** [comment]
The `showJsMessage` method from base provides a way to do this with HTML instead of plain text.

**Comment by s-paquette** [comment]
...better yet, render an HTML template and just use that.

**Comment by madelyngreyes** [comment]
![clickable links](https://user-images.githubusercontent.com/16824894/104059772-d5a89580-51c3-11eb-96fe-d5a2f9166be4.PNG)

**Comment by s-paquette** [comment]
@madelyngreyes Can this one be considered testing passed?
