### ISSUE TITLE
Icons not loading with abbreviated URL

### ISSUE THREAD

**Issue by wlongabaugh** [ImagingDataCommons/IDC-WebApp#495]
Note that the new abbreviated portal URL works, but icons glyphs are missing from the home page. They are also not loading on the exploration page: 

![PortalIcons](https://user-images.githubusercontent.com/8441547/102555261-481dce00-407b-11eb-934c-cbdc1c6e4b18.png)

**Comment by wlongabaugh** [comment]
Is this perhaps an XSS/CORS issue?

**Comment by s-paquette** [comment]
Yeah, the CORS policy needs the new domain added. (Note, added, NOT replaced.)

**Comment by s-paquette** [comment]
@madelyngreyes Done. Have a look at https://imaging.datacommons.cancer.gov/ when you have a chance and see if it's loading okay.

**Comment by madelyngreyes** [comment]
Chrome fixed for homepage,
![chrome](https://user-images.githubusercontent.com/16824894/102918824-acfb6e80-4455-11eb-8b3d-3649d8ded638.PNG)
Firefox fixed for homepage, 
![firefox-load](https://user-images.githubusercontent.com/16824894/102918842-b7b60380-4455-11eb-802d-4966d5dd82cf.PNG)


Chrome exploration page fixed,
![chrome-exploration](https://user-images.githubusercontent.com/16824894/102918908-dae0b300-4455-11eb-8427-5590f83500df.PNG)
Firefox exploration page fixed, 
![firefox exploration load](https://user-images.githubusercontent.com/16824894/102918921-e2a05780-4455-11eb-8493-db74bac5f522.PNG)
