### ISSUE TITLE
Fix text in several Attribute values

### ISSUE THREAD

**Issue by G-White-ISB** [ImagingDataCommons/IDC-WebApp#503]
As commented by an external reviewer there are several confusing attribute headers and attribute values, and inconsistent capitalization in the headers and values:

_Chestabdpelvis_ in BodyPartExamined
_Thorax_1head_nec_ in BodyPartExamined
_Internal structure_ (as opposed to _Internal Structure_) in Qualitative Analysis ....

The attribute headers and values are stored and sourced directly from the DICOM files. For consistency with these source files we will not be changing them.

**Comment by G-White-ISB** [comment]
![unnamed](https://user-images.githubusercontent.com/58443591/102832707-060aca00-43a4-11eb-901d-f6eac9b274d3.png)

**Comment by madelyngreyes** [comment]
Issue 4.2 in **Test Report** from Tin, attribute text Thorax_1head_nec is stored in this format in the data.
