### ISSUE TITLE
Table Formatting

### ISSUE THREAD

**Issue by G-White-ISB** [ImagingDataCommons/IDC-WebApp#505]
An external reviewer noted that the _Previous_ and _Next_ buttons are spaced far apart from the page number buttons. We will adjust the spacing. Also the option to enter a page number in a text field and press the _GO_ button is redundant with the _Previous_ , _Next_ and page number buttons. We will remove this option.
![unnamed-1](https://user-images.githubusercontent.com/58443591/102833407-d957b200-43a5-11eb-9be7-5bf7c467a46a.png)
![unnamed-2](https://user-images.githubusercontent.com/58443591/102833416-e07ec000-43a5-11eb-9341-663a2250ad48.png)

**Comment by G-White-ISB** [comment]
The 'GO' button and supporting page selection features have been removed. Also the Previous and Next buttons are closer to the page number buttons. This is currently in the dev deployment but not the test deployment

**Comment by madelyngreyes** [comment]
[Issue 4.6](https://docs.google.com/document/d/1MhsTLdfVa9knEWVhgdjCUKwev5ekXF-jiUAhhfHxAQY/edit#) from Tin's Test Report is addressed in this ticket.

**Comment by madelyngreyes** [comment]
Format on a desktop monitor, Mac OS, and using Crome browser, with 100% zoom 
![Screen Shot 2021-02-19 at 9 55 02 AM](https://user-images.githubusercontent.com/16824894/108520439-af811580-7298-11eb-870d-0f8cdec0195f.png)

**Comment by madelyngreyes** [comment]
Chrome browser at 100% zoom on a laptop display the next button still appears to be displayed in another row.

<img width="1440" alt="Screen Shot 2021-05-17 at 7 29 31 PM" src="https://user-images.githubusercontent.com/16824894/118568647-451c2c00-b746-11eb-953b-266dac5f1574.png">

**Comment by G-White-ISB** [comment]
Related to https://github.com/ImagingDataCommons/IDC-WebApp/issues/663
