### ISSUE TITLE
Issues with Correlation Between Search Results Graph with what is selected in Search Configuration Box

### ISSUE THREAD

**Issue by G-White-ISB** [ImagingDataCommons/IDC-WebApp#506]
An external reviewer noted issues with the correlation between the search results graph and the search configuration box. For instance when just the _Abdomen_ _BodyPartExamined_ value is selected, four different values, Abdomen, Headneck, Chest, and None appear in the _Body Part Examined_ pie chart. This behavior is known and expected. The attribute are faceted by CaseIDs, and the same CaseID may match several different values of the same attribute. Hovering over the two information icons in the panels yields some explanatory text. We realize the users could easily miss these icons or not understand they are actionable. We are exploring better ways to explain these issues to the user.

**Comment by G-White-ISB** [comment]
![unnamed-3](https://user-images.githubusercontent.com/58443591/102834124-fb523400-43a7-11eb-9a59-369226cfd123.png)

**Comment by fedorov** [comment]
@G-White-ISB if I recall correctly our today's discussion, we planned to add a text right below the piecharts with the pointer to the documentation, no (cc @wlongabaugh )? 

One idea for the text: "[This documentation section](https://learn.canceridc.dev/portal/data-exploration-and-cohorts#count-clarification-of-categorization) explains why the charts include items other than the attributes selected in the left panel".

**Comment by wlongabaugh** [comment]
My suggestion is something more conversational, with a glyph that catches the eye, e.g.:
<img width="800" alt="PieGuidance" src="https://user-images.githubusercontent.com/8441547/102925356-11173600-4448-11eb-8aba-b72740014fc2.png">

**Comment by G-White-ISB** [comment]
Clicking away for an explanation is annoying. I think we should attempt an explanation in the text so that most people either understand or think they understand without following the link.

"As some attributes have non mutually exclusive values the charts may contain non zero counts these values even when they are not selected in the left hand panel.  See [here](https://learn.canceridc.dev/portal/data-exploration-and-cohorts#count-clarification-of-categorization) for a detailed explanation."

**Comment by wlongabaugh** [comment]
OK, how about a mouse over with more text then, plus the link? I am trying to capture attention here with something short and pithy. In my experience, verbose text gets ignored...the "fine print"

**Comment by G-White-ISB** [comment]
True text is usually ignored, but our use case here is someone who is confused by the chart results and is looking for an explanation. If we had text that reveals more text in a mouseover, well it would have to be crystal clear that you could mouseover the initial text.

I'm not crazy about the conversational style but that might just be me. Somehow it reminds me of [clippy](https://en.wikipedia.org/wiki/Office_Assistant). I'll make a couple of prototypes for a web app meeting in the new year and we can spend 15 minutes reviewing them.

**Comment by wlongabaugh** [comment]
At least I'm not suggesting eyeballs on a wiggly paperclip 8^D. Might run ideas past the original reviewer? Note I'm not trying to _explain_ the situation in the visible text (too complex), but provide a more noticeable and compelling "hook" to provide the explanation besides a tiny (i) glyph. Thanks.

**Comment by G-White-ISB** [comment]
Proposed solution is a glyph at the bottom of the pie charts that looks like this:
![Screen Shot 2021-02-01 at 11 47 02 AM](https://user-images.githubusercontent.com/58443591/106510096-584f0880-6483-11eb-8cdb-3edea0563d6d.png)
On hover a tootip pops up:

![Screen Shot 2021-02-01 at 11 48 42 AM](https://user-images.githubusercontent.com/58443591/106510209-7caae500-6483-11eb-8daf-eab2bb4e8419.png)
[@fedorov](https://github.com/fedorov) and [@ulrikew](https://github.com/ulrikew) comments welcome

**Comment by madelyngreyes** [comment]
[Issue 4.4](https://docs.google.com/document/d/1MhsTLdfVa9knEWVhgdjCUKwev5ekXF-jiUAhhfHxAQY/edit#) in Tin's test report addressed in this ticket.

**Comment by madelyngreyes** [comment]
Also, issue 4.5

**Comment by madelyngreyes** [comment]
New clarification section for filters returned, 
![Screen Shot 2021-02-25 at 12 53 05 PM](https://user-images.githubusercontent.com/16824894/109195422-7cdb8f00-7768-11eb-8859-95e098339c81.png)

**Comment by wlongabaugh** [comment]
@G-White-ISB I'm wondering if the pie chart shown in the glyph (corresponding to nothing selected) should correspond the the attributes selection (Abdomen selected). I found that somewhat perplexing when trying to understand what was being conveyed.

**Comment by s-paquette** [comment]
@wlongabaugh @fedorov Is this considered testing passed? (That glyph is simply a fixed image, it's not a realtime drawing.)

**Comment by wlongabaugh** [comment]
My preference would be to swap in this image instead and then consider it testing passed:
![results_glyp2](https://user-images.githubusercontent.com/8441547/109234059-d602ed00-777f-11eb-8c70-8c82b50f4e52.png)

**Comment by G-White-ISB** [comment]
Concur with change proposed in image. Actually I had meant the filter selection to correspond with the pie chart.

**Comment by s-paquette** [comment]
@G-White-ISB Are we going to get to this adjustment this Sprint, or should I push this into Sprint 19?

**Comment by wlongabaugh** [comment]
@G-White-ISB  Should be able to take the above image and drop it in place. Original file just edited.

**Comment by G-White-ISB** [comment]
I can put this in now.
George

**Comment by G-White-ISB** [comment]
In a PR. Nothing else is changed.

**Comment by fedorov** [comment]
I am not a 508 compliance expert, but dark blue on dark grey for the link color does not strike me as good contrast.

**Comment by s-paquette** [comment]
@fedorov We can I think make a separate ticket for addressing 508 items such as contrast, so as to minimize scope creep. The new proposed image is now live on idc-testing; does it address the ticket's original concerns?

**Comment by fedorov** [comment]
I thought this belongs to this ticket, since we are introducing a new feature, and my comment was specifically about testing of that new feature. Again, I am not in a position to comment on 508. All I am saying is that the choice of colors in the tooltip for this specific feature implemented in this ticket is suboptimal.

**Comment by s-paquette** [comment]
@fedorov We generally try to keep 508 compliance in its own ticket or tickets, because those changes are often small tweaks which are best done en masse rather than issue by issue. (Also because we run the test as a separate pass.)
