### ISSUE TITLE
Disable entire page scroll when using the cohort manifest export popup

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#514]
On the test tier, if the user scrolls anywhere outside of the popup panel, the explorer page under the popup is moved.  But, it appears to the end user as popup box is cut off while trying to scroll down to confirm the manifest export. 

Steps to reproduce the issue below,

1. create cohort
2.  select the export manifest button 
3. open the header fields drop down 
4. open the column field drop down
5. the popup box download buttons have moved passed the visible space of the browser (scroll down needed)
6. move mouse cursor outside of the popup box
7. scroll down the page
7. the pop-up box doesn't scroll down 
8. the entire page scrolls down
9. popup box appears as cut off 

![page cut off for popup box](https://user-images.githubusercontent.com/16824894/103572501-af6cb800-4e9a-11eb-9341-131e3989f22a.PNG)

**Comment by G-White-ISB** [comment]
confirm fixed in dev

**Comment by madelyngreyes** [comment]
Scroll down on cohort manifest export confirmation page is working as expected,
![Screen Shot 2021-02-25 at 12 51 27 PM](https://user-images.githubusercontent.com/16824894/109195221-40a82e80-7768-11eb-8e79-08cb5468185e.png)
