### ISSUE TITLE
Question re. check / uncheck all

### ISSUE THREAD

**Issue by ulrikew** [ImagingDataCommons/IDC-WebApp#520]
Is check/ uncheck all only shown when there are more than 5 items in the list?
![image](https://user-images.githubusercontent.com/3019001/104491412-3529eb00-55a0-11eb-83c4-76eb698cf22c.png)

**Comment by G-White-ISB** [comment]
Yes that's correct.

**Comment by G-White-ISB** [comment]
Per discussion today we are planning to add this option to all lists regardless of the # of items.

**Comment by madelyngreyes** [comment]
When hide 0 cases is selected, some filters will display "show more 0"
![Screen Shot 2021-02-17 at 8 05 34 PM](https://user-images.githubusercontent.com/16824894/108289100-c53cf080-715b-11eb-9ae3-4f167259a6c1.png)

A Check All/ Uncheck All appears for only two options as expected.

**Comment by G-White-ISB** [comment]
Will hide 'show more' when there are 0 more to show

**Comment by madelyngreyes** [comment]
Thank you George! Also It seems after you save a cohort with all collections added in the search scope panel a show more/show less, Check All/Uncheck All options appear per collection filter,
![Screen Shot 2021-02-18 at 11 36 56 AM](https://user-images.githubusercontent.com/16824894/108389604-d3cbec00-71dd-11eb-8c07-b9eb1c7665df.png)
