### ISSUE TITLE
Windows OS - selection of cases/studies/series is not obvious 

### ISSUE THREAD

**Issue by ulrikew** [ImagingDataCommons/IDC-WebApp#522]
It is difficult to select multiple items in a Window environment.  Holding the Shift key highlights other rows or highlights the header. A selection can only be done one item at the time.
![image](https://user-images.githubusercontent.com/3019001/104492797-293f2880-55a2-11eb-8b4f-1180bf4e0d22.png)

**Comment by s-paquette** [comment]
Shift and Control select are reversed; preventDefault() needed to stop the normal drag behavior

**Comment by G-White-ISB** [comment]
Proposed behavior is that holding CNTRL or COMMAND(MAC) toggles a row without changing the selection of other rows. Without holding CNTRL, selecting one row will deselect all other rows. Holding the shift key will allow multiple sequential rows to be selected at one time.

**Comment by madelyngreyes** [comment]
Issue 4.13 in Tin's Test Report is addressed in this ticket.

**Comment by fedorov** [comment]
> Issue 4.13 in Tin's Test Report is addressed in this ticket.

To be precise, specific issue identified by Tin is the following:

> Improvement: Awkward selection of Cases for a selected Collection.  If I wanted to select every other case under a Collection, I would have to hold down the Shift key.  In TCIA portal for each Case I would click on the Cart Icon.  I think this is also a 508 violation having to hold the shift key to perform random selection.  Also, it would be tedious for a Collection having over a thousand cases.  This same behavior is also exhibited for Studies and Series box.

I would strongly prefer not too have selection using alt-keys, and instead have checkboxes, buttons etc. I can't comment on 508, but I agree with Tin's suggestion overall.

**Comment by madelyngreyes** [comment]
I shift+selected two studies, the total count for the series should be 20 entries but, only 15 entries appear. I need to re-select the first option to get the total count of 20 entries to appear in the selected series panel. 

![Screen Shot 2021-02-19 at 9 58 21 AM](https://user-images.githubusercontent.com/16824894/108521862-2a96fb80-729a-11eb-87de-59755437e73a.png)

**Comment by fedorov** [comment]
> Issue 4.13 in Tin's Test Report is addressed in this ticket.

@madelyngreyes the issue above is not addressed in this issue. Can you please create a new issue for not using an alt-key for selection:

> Improvement: Awkward selection of Cases for a selected Collection. If I wanted to select every other case under a Collection, I would have to hold down the Shift key. In TCIA portal for each Case I would click on the Cart Icon. I think this is also a 508 violation having to hold the shift key to perform random selection. Also, it would be tedious for a Collection having over a thousand cases. This same behavior is also exhibited for Studies and Series box.

**Comment by s-paquette** [comment]
There doesn't seem to be any violation:
https://www.w3.org/TR/WCAG20/#keyboard-operation-keyboard-operable

There's an explicit exception for timing based on movement. That said, we can definitely add in a checkbox.

**Comment by s-paquette** [comment]
@fedorov @ulrikew @madelyngreyes This is now available on test.

**Comment by fedorov** [comment]
I am not a 508 compliance expert. @ulrikew is there any chance Tin can be included in this discussion?

**Comment by s-paquette** [comment]
@ulrikew @fedorov It'd be preferable for any 508 concerns to be addressed in their own ticket, as that wasn't the specified issue in this ticket. (Trying to avoid scope creep in specific task items.) We have a 508 ticket in #555, which would be where we should focus that discussion.

**Comment by ulrikew** [comment]
Has the decision been made to have checkboxes as mentioned in  #555?

**Comment by s-paquette** [comment]
@ulrikew Yes, that'll be done in hopefully Sprint 19 (depends on our workload otherwise).

**Comment by madelyngreyes** [comment]
Number of entries selected in the series panel matches the number of series' selected in the selected studies panel in the screenshot below,
<img width="1067" alt="Screen Shot 2021-03-01 at 9 13 53 AM" src="https://user-images.githubusercontent.com/16824894/109509313-c1b83c00-7a6e-11eb-9ade-0c41e88a3657.png">

**Comment by G-White-ISB** [comment]
@urlikew and @fedorov, are clicking the checkboxes going to be the only way to select a row or can one still highlight the row itself?

**Comment by fedorov** [comment]
I am fine either way.

**Comment by fedorov** [comment]
Am I the only one finding it not particularly intuitive or usable that the only way to un-select individual rows is to do control-click for those already selected?

**Comment by G-White-ISB** [comment]
?? That's not how its supposed to work, nor how its working in my experience (Mac, Safari or Chrome). If you click a row that's already selected, the corresponding rows in the following table will be removed. You should not need to do control click, just click.

**Comment by fedorov** [comment]
Ok, I really don't know how it is supposed to work. My (apparently, incorrect) expectation was that the behavior would be the same as when selecting multiple files on desktop - click+ctrl adds a new file to selection, but click without control resets the selection to just the single file clicked.

I tested it just now on the production tier, and apparently all tables multi-select without the need to use any alt key. In clicking around in the video below, I did not use any alt keys. I do not know if this is expected behavior or a bug. Either way is fine with me - I will let the @ulrikew as the original reporter comment on usability of this solution.

![2021-03-02_10-33-40](https://user-images.githubusercontent.com/313942/109672574-280e8e80-7b43-11eb-9831-f2d84c7046c6.gif)

**Comment by G-White-ISB** [comment]
@fedorov I am seeing the same behavior you recorded above. In my last comment I expect my browser may have used a cached version of some javascript sources. 
We are close to implementing selection with checkboxes only, which is the same as in https://portal.gdc.cancer.gov/, and  the same as in https://public.cancerimagingarchive.net/nbia-search/ (if you replace the shopping cart with a checkbox)

**Comment by fedorov** [comment]
@G-White-ISB what effect, if any, will this selection have on the definition of the cohort?

**Comment by G-White-ISB** [comment]
@fedorov - no effect.  The cohort is defined by the filter definition and the data version number, which are not changed by what you select to view in these tables.The table selections allow one to view information pertaining to the cohort as it is already defined.

**Comment by madelyngreyes** [comment]
Can this ticket be closed by chance?

**Comment by G-White-ISB** [comment]
Superseded by #555, so lets close
