### ISSUE TITLE
Lack of results for a given filter set needs to be clearer in the Collection/Case/Study/Series tables

### ISSUE THREAD

**Issue by ulrikew** [ImagingDataCommons/IDC-WebApp#523]
![image](https://user-images.githubusercontent.com/3019001/104493796-91dad500-55a3-11eb-9129-09deca17be61.png)
![image](https://user-images.githubusercontent.com/3019001/104493827-9b643d00-55a3-11eb-9cb4-77e654b516de.png)

**Comment by s-paquette** [comment]
@ulrikew Those are expected debug lines related to minified JS files, you'll see them on probably all page loads. (We don't provide source maps to our users.) Were their some additional error messages in the console?

**Comment by ulrikew** [comment]
Hi Suzanne, please try to recreate the query. My description of the issue was insufficient. When I apply the first slider I still see results when I apply the second slider the page is empty. Does it mean that it is broken or that no results exist for this particular query? If the latter is the case why don't I see the collection anymore? 
The test was conducted on prod.

![image](https://user-images.githubusercontent.com/3019001/104635983-ad5fe180-5670-11eb-9127-a6664e39576d.png)
![image](https://user-images.githubusercontent.com/3019001/104636014-b6e94980-5670-11eb-8abe-942bfd69f300.png)

**Comment by s-paquette** [comment]
@ulrikew In this case, it means there's no data found for those two filters combined; as a result, nothing will list in any of the tables. Only collections (and cases, studies, series) which contain records that meet the filter criteria will be listed in the selection tables.

Would it help if, like the Pie Charts, the tables showed a single row of 'No Data Available for this set of filters' or a similar message?

**Comment by ulrikew** [comment]
Yes, that would help. I like your idea of including in the message that it is "for this set of filters" or we can use "No matching results
Try changing your search." ( I borrowed this wording from Zillow) or "No matching results for this set of filters".

**Comment by G-White-ISB** [comment]
How about we add an alert when the search comes back empty with text given above.

**Comment by madelyngreyes** [comment]
![Screen Shot 2021-02-19 at 9 51 22 AM](https://user-images.githubusercontent.com/16824894/108519891-1651ff00-7298-11eb-8200-1f003a7b967c.png)

New format example for alert of no results present for given set of filters. @ulrikew @fedorov

**Comment by ulrikew** [comment]
The notification looks ok. Do we need to include the first sentence (URL says)?

**Comment by fedorov** [comment]
I do not like the idea of popup at all. Instead, I suggest somewhere under the filter definition, there should be a summary of the defined cohort (number of cases, and perhaps also studies and series).

**Comment by s-paquette** [comment]
@ulrikew The 'x says' is due to the manner of implementation and can't be removed; we would need to use a different method.

**Comment by s-paquette** [comment]
@G-White-ISB Has this been changed away from an alert and to a simple text message in the table, etc.?

**Comment by G-White-ISB** [comment]
No, its not been on my radar for a while.

**Comment by s-paquette** [comment]
Got it--gonna bump it into Sprint 19

**Comment by G-White-ISB** [comment]
We now generate stats to report as per @fedorov's comment above

**Comment by s-paquette** [comment]
@G-White-ISB Did you want to move this into 22, or is it on dev/test now?

**Comment by G-White-ISB** [comment]
Move to 22

**Comment by fedorov** [comment]
@G-White-ISB looks like you closed this by mistake.
