### ISSUE TITLE
Question: By what principle is the object class list sorted?

### ISSUE THREAD

**Issue by ulrikew** [ImagingDataCommons/IDC-WebApp#527]
What determines the sorting order of the object class list? It is not alphabetical and it is not numerical.
![image](https://user-images.githubusercontent.com/3019001/104638713-8acfc780-5674-11eb-9662-3644d46d8377.png)

**Comment by G-White-ISB** [comment]
It's sorted by an internal key. Will change to sort alphabetically by default

**Comment by ulrikew** [comment]
Alphabetic 👍  Looks good
