### ISSUE TITLE
Minor issue - exploration vs. collection

### ISSUE THREAD

**Issue by ulrikew** [ImagingDataCommons/IDC-WebApp#528]
Carolyn Klinger, who has a very good eye for details, noticed that the order of Exploration and Collection is reversed on the page vs. the menu.
![image](https://user-images.githubusercontent.com/3019001/104639263-34af5400-5675-11eb-8d0d-4b57a65e5445.png)

**Comment by G-White-ISB** [comment]
How about we consistently put Collections first.

**Comment by ulrikew** [comment]
Another option is to delete the Exploration and Collection buttons because there are links in the top menu bar.

**Comment by G-White-ISB** [comment]
I have left them in but order is now consistent at https://idc-testing.appspot.com/

**Comment by ulrikew** [comment]
Looks good.

**Comment by s-paquette** [comment]
@ulrikew A quick note, the reason they're present is we were told to make the page look similar to GDC, which has both the buttons and the same links in the header.

**Comment by ulrikew** [comment]
@s-paquette Thank you, Suzanne. Bill L. mentioned it in one of the stakeholder meetings.

**Comment by madelyngreyes** [comment]
<img width="618" alt="Screen Shot 2021-03-03 at 9 27 49 AM" src="https://user-images.githubusercontent.com/16824894/109820221-cd3c6c00-7c02-11eb-979f-1b932bdcc000.png">

**Comment by ulrikew** [comment]
👍
