### ISSUE TITLE
Indicate or remove empty search criteria enhancments

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#529]
**Is your feature request related to a problem? If so, let us know**

Related to ticket, https://github.com/ImagingDataCommons/IDC-WebApp/issues/454

**Enhancement description**

- When using the exploration page certain filter selections will be grey-ed out to display no entries available. Should have additional text stating no data is available.  
- Selection of empty field will display white space, therefore selection of empty field should be disabled.  

**Screenshots**

![103925849-1f22b300-50e6-11eb-8793-712957826af5](https://user-images.githubusercontent.com/16824894/104940261-78f56980-597f-11eb-9be0-cd57510ead97.PNG)
![103926317-c0aa0480-50e6-11eb-800f-376ba7947703](https://user-images.githubusercontent.com/16824894/104940262-798e0000-597f-11eb-8df6-9dee0a3adc51.PNG)

**Other comments**

**Comment by G-White-ISB** [comment]
Please see related ticket, [#454 ](https://github.com/ImagingDataCommons/IDC-WebApp/issues/454)

**Comment by madelyngreyes** [comment]
This ticket can be closed.
