### ISSUE TITLE
500 error returned from the user details page

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#534]
**General description**

A 500 error is returned after you login and go to the user details page

**Steps to reproduce the behavior**

1. login to the IDC
2. select the account details option in the top right hand side of the page
3. you are sent to a 500 error page

**Screenshots**
![500 error on the production tier](https://user-images.githubusercontent.com/16824894/106020982-4ee42b80-6092-11eb-8f51-3d6b8c1e1424.PNG)

**Your System**
 - OS: Windows
 - Browser: Chrome
 - Version: canceridc.202101111506.0a8af57

**Other Comments**

**Comment by s-paquette** [comment]
Bug involving failure to import the right template tags.

**Comment by madelyngreyes** [comment]
Tins reports issue 4.20 addressed in this ticket.

**Comment by madelyngreyes** [comment]
user details page example below,
![Screen Shot 2021-03-01 at 7 06 21 PM](https://user-images.githubusercontent.com/16824894/109576157-403dc980-7ac1-11eb-84b9-41fce5b6c885.png)
