### ISSUE TITLE
Local account confirmation email does not arrive

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#535]
I created a non-google account on IDC, with an acceptable 16-character password, and was shown confirmation. I then waited for an hour, but did not receive confirmation email. I checked my Spam folder, and did not find the confirmation email there.

**Comment by fedorov** [comment]
Also checked the corporate spam quarantine portal, and did not find that email there.

![image](https://user-images.githubusercontent.com/313942/106055055-de9dd000-60ba-11eb-8dea-128f2172ff8f.png)

**Comment by s-paquette** [comment]
The 'verification email sent' page will now clarify how to trigger a re-send of the verification email. This is done by attempting to log into the account.

**Comment by s-paquette** [comment]
@fedorov @madelyngreyes Is this working now?

**Comment by fedorov** [comment]
it worked for me when I tried second time, I didn't do any further testing

**Comment by madelyngreyes** [comment]
I received this email when registering with a brand new email, I then was able to verify my email but, got a notification only members of idc_group can access the server. Can do further testing on production to run workflow as end user perspective. 

<img width="982" alt="Screen Shot 2021-03-01 at 9 04 05 AM" src="https://user-images.githubusercontent.com/16824894/109508226-a0a31b80-7a6d-11eb-8dbf-f1fcd23c3e96.png">

**Comment by madelyngreyes** [comment]
<img width="989" alt="Screen Shot 2021-03-04 at 3 47 50 PM" src="https://user-images.githubusercontent.com/16824894/110028265-078c3300-7d01-11eb-95a0-d740b1d1d9e9.png">
