### ISSUE TITLE
Webapp usage statistics metrics

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#536]
Internally within the team we need to have access to the following information to track usage of the platform over time:
* how many registered users we have
* how many of those use local login
* how many cohorts (ideally, per user) have been created
* how many times they logged in, and what was the last time they logged in

**Comment by s-paquette** [comment]
@fedorov 

- how many registered users we have
63 (excludes all devs and the primary IDC team)

- how many of those use local login
34

- how many cohorts (ideally, per user) have been created
Total, from non-dev and non-IDC team sources: 56
Per user is a huge list, how did you want me to provide that? As an average?

- how many times they logged in, and what was the last time they logged in
How many times isn't stored. Last time is also a huge list, are you looking for a specific sort of value here?

**Comment by fedorov** [comment]
Is there an easy way to collect this from some BQ table whenever this is needed?

**Comment by s-paquette** [comment]
We have undergone a few revisions of how this data is collected, so this ticket is no longer relevant.
