### ISSUE TITLE
Fix Social Account connections template

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#538]
ticket from Suzanne

**Comment by s-paquette** [comment]
Fixed numerous issues with the 'connect your account' page for connecting a Google account to a local IDC account.

**Comment by madelyngreyes** [comment]
Having signed in with a Google account, if you go to unlink your Google ID you are asked to set your password. After you set your password you are then sent to the reset password page, when it's not needed. You should be sent to a password set confirmation page instead. 
![Screen Shot 2021-02-19 at 9 42 10 AM](https://user-images.githubusercontent.com/16824894/108518842-0980db80-7297-11eb-9ab3-0bad5fd4f592.png)

**Comment by s-paquette** [comment]
@madelyngreyes So, this is a bug in Django-allauth. I can make a work-around, but as it's a separate concern, I'd like to make a different ticket for it to address this item in particular (that setting a password takes you to the change page). So, aside from this, for which we'll make a ticket, is the testing passed?

**Comment by s-paquette** [comment]
Ticket made for this: #553

**Comment by madelyngreyes** [comment]
I was able to unlink my google ID and link again. But, could we also list the email that is linked? I was able to link my @csra.com email with my @gdit.com email address but, the gdit email is not listed anywhere. 

![Screen Shot 2021-02-19 at 3 02 36 PM](https://user-images.githubusercontent.com/16824894/108555673-c8eb8700-72c3-11eb-9cb2-459bd41e3ee3.png)

**Comment by s-paquette** [comment]
Let's make that a separate ticket for that as well, if only to get the sprint out.
