### ISSUE TITLE
"Copy to clipboard" button for the BQ manifest table location

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#542]
When a manifest is exported to BQ, it is very often the case for the next step is that the target table name needs to be reused in other places. Right now, I need to select the table name, making sure I don't accidentally include a space and don't click on the hyperlink.

I think it would be very convenient to have a button next to the table location to copy to clipboard (similar to how it is done, for example, in the Storage bucket path in GCP console).

**Comment by s-paquette** [comment]
So, one thing I just realized, this is already supported in any browser--if you right-click on a link (or command click) you get a context menu with 'copy link text' and 'copy link address' etc. We can definitely add this, but it might be a confounding addition. (Copying the Table name, on the other hand, makes perfect sense.)

**Comment by fedorov** [comment]
I was indeed talking about the table name.

**Comment by madelyngreyes** [comment]
Able to copy the table name as expected, 

https://user-images.githubusercontent.com/16824894/119075152-53747d00-b9be-11eb-9403-74d51e2ef8b0.mov

**Comment by fedorov** [comment]
Unfortunately, I just now noticed that what is copied to the clipboard is only the table name. Not being fully qualified by the dataset, name of the table is rather useless. We need to have the full location in the clipboard, i.e., `canceridc-user-data:user_manifests.manifest_cohort_245_20210913_204805` instead of `manifest_cohort_245_20210913_204805`.

**Comment by s-paquette** [comment]
Bug found and fixed; will flag for testing once it's on test. Please note this is an intermittent bug and was reliant on exporting a LARGE cohort, because it wouldn't happen if the cohort was small and the query could execute quickly.

**Comment by fedorov** [comment]
This appears to be resolved in test, but I will let @pgundluru confirm and close.

**Comment by pgundluru** [comment]
Tested successfully.
