### ISSUE TITLE
Error populating filter content in a specific situation

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#544]
1. select attribute in Derived (e.g., 
![image](https://user-images.githubusercontent.com/313942/107406073-025b1000-6ad6-11eb-847f-15331b3a95e1.png))

2. select a collection for which that selection does not apply (e.g., LIDC)

Collection is not captured in the filter, error in the console

![image](https://user-images.githubusercontent.com/313942/107406135-19016700-6ad6-11eb-817f-02c9c6176aa4.png)

![image](https://user-images.githubusercontent.com/313942/107406020-f2dbc700-6ad5-11eb-96c7-e7fc394e1b41.png)

**Comment by madelyngreyes** [comment]
New notification, when there are zero cases present for the filter selection. @fedorov 
<img width="1321" alt="Screen Shot 2021-05-17 at 9 13 30 PM" src="https://user-images.githubusercontent.com/16824894/118575571-ca0e4200-b754-11eb-83d8-5f84e17808c9.png">

**Comment by fedorov** [comment]
Why is it needed? Is it not possible to just show empty list?

**Comment by G-White-ISB** [comment]
We do show the empty list.
 Please see this issue which is specifically about what else to report when filter returns no cases.
https://github.com/ImagingDataCommons/IDC-WebApp/issues/523.
