### ISSUE TITLE
Define best practice mechanism for fetching large IDC cohorts

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#549]
It appears we do not have a robust mechanism to download a cohort of reasonable size (I am not entirely sure what is the limit when things start to break).

Currently, we can export manifest either as a multi-part file, or as a BQ table. Multi-part file approach falls apart very quickly (manifest for just NSCLC + QIN-HEADNECK collection exceeds the limit), so we can safely ignore it from this discussion as irrelevant.

Export of the manifest to BQ works, but to download the files corresponding to the manifest, the most logical approach I could think of is the following (as illustrated in our notebook here: https://colab.research.google.com/github/ImagingDataCommons/IDC-Examples/blob/master/notebooks/Cohort_download.ipynb)

1) query the manifest table to get the list of gs:// URLs
2) run gsutil to fetch the list

In the above, Step 1 takes very long time and may not load at all (based on @madelyngreyes experiments). If it works, I am not sure about the performance of gsutil being fed a very large file with the list of URLs.

This is a very high priority issue, since without a robust mechanism to fetch the files corresponding to a cohort to a VM, there is no meaningful way to analyze the IDC cohorts.

I think we need all hands on deck to figure this out ASAP!

**Comment by fedorov** [comment]
Some ideas to brainstorm:

* we could investigate if the process becomes manageable if we fetch at the level of series. @madelyngreyes can you please investigate how practical are the BQ query and bucket download, if instead of instance-level manifest you fetch one row per series, and then download recursively series-level folders?
* how feasible would it be to allow user export the files corresponding to the manifest into a new short-lived (read-only?) shared disk, which they could then attach to a VM and copy files to where they want?

@bcli4d I wonder if this issue has implications on our decisions for bucket layout in the data versioning approach.

**Comment by s-paquette** [comment]
To sum up some items from Slack:
- The current feeling is that using the BQ table manifests is much too complex, and the chunked download is too small. The later is done to prevent egress charges from becoming significant; even Google prevents large downloads of BQ tables.
- A preference has been stated for putting the manifest as a file (or files if over 1G total--this is a Google limitation and we can't get around it) into a GCS bucket which is locked to the exporting user, set to requester pays. A Cron job would then delete the bucket after 7 days.

This outstanding issues with the GCS proposal are:

- We need to create a Cron task to sweep and delete the export buckets. While GCS does offer the option of Lifecycle management, this is bucket level. We would need a bucket per user manifest exported due to the difficulties in managing user access on a per-object basis (fine grained control is very difficult to manage).
- Since a manifest can be over 1G in total size, a user can wind up with more than one file, in which case a bucket is preferred over a series of objects (buckets are flat and have no actual hierarchy structure; folder names are really just extensions of the file name). 
- Significant back-end word will be needed to produce the system which will export the manifest to the bucket, apply the security limitations to that bucket, and set it to requestor pays.

This will be several tickets worth of work, so we have to consider where it can be placed into the timelines.

**Comment by G-White-ISB** [comment]
Suggest we get firm numbers first before heading off in a new direction. What examples break the process? Also could there be issues with the collab environment? What if one provisions their own VM or works locally?

My understanding is that ISB-CGC has seen good performance from BigQuery.

**Comment by fedorov** [comment]
@madelyngreyes can you please summarize results of your experiments?

**Comment by fedorov** [comment]
Excerpt from @madelyngreyes experiment notebook: below is export of compressed table to GCS.

```python
from google.cloud import bigquery
try:
  project_id = 'PROJECT' # Update your_project_number with your project number
  client = bigquery.Client(project=project_id)
  print('BigQuery client successfully initialized')
except:
  print('Failed')

project = "canceridc-user-data"
dataset_id = "user_manifests"
table_id = "manifest_cohort_70_20210218_153425" # small subset
table_id = "manifest_cohort_82_20210218_153918" # all of IDC
bucket_name = "gs://BUCKET/PATH"

destination_uri = "{}/{}".format(bucket_name, table_id+".csv_*.gz")
dataset_ref = bigquery.DatasetReference(project, dataset_id)
table_ref = dataset_ref.table(table_id)
job_config = bigquery.job.ExtractJobConfig()
job_config.compression = bigquery.Compression.GZIP

extract_job = client.extract_table(
    table_ref,
    destination_uri,
    # Location must match that of the source table.
    location="US",
    job_config=job_config,
)  # API request
extract_job.result()  # Waits for job to complete.
```

**Comment by wlongabaugh** [comment]
@fedorov @madelyngreyes Can we get some performance numbers? How long is a "very long time" and what is a specific case that does "not load at all"?

**Comment by wlongabaugh** [comment]
And what are the numbers on a dedicated VM? I would not expect particularly high performance on a Colab notebook...the service is free, after all, right?

**Comment by G-White-ISB** [comment]
I created a cohort from all TCGA - over 2 million files. I queried the cohort in a collab notebook with the following:

client = bigquery.Client(project="idc-dev")
rng=[5000, 50000, 500000, 5000000]
for i in range(len(rng)):
  query= "SELECT * FROM `canceridc-user-data.user_manifests.manifest_cohort_128_20210218_163614` limit "+ str(rng[i]);
  
  %time cohort_df = client.query(query).to_dataframe()
  print('cohort_df: '+str(len(cohort_df)))

Results shown below

CPU times: user 322 ms, sys: 11.1 ms, total: 334 ms
Wall time: 1.58 s
cohort_df: 5000
CPU times: user 1.29 s, sys: 23.1 ms, total: 1.31 s
Wall time: 5.31 s
cohort_df: 50000
CPU times: user 12.7 s, sys: 351 ms, total: 13.1 s
Wall time: 47.5 s
cohort_df: 500000
CPU times: user 51.7 s, sys: 1.44 s, total: 53.1 s
Wall time: 3min 24s
cohort_df: 2022892

'Wall time' agrees with my experience waiting for the query to finish. These times are faster(maybe ~10X??) in the BQ GUI.

**Comment by fedorov** [comment]
@madelyngreyes thank you! Can you also add stats for the gsutil download for those cohorts of varying sizes, both to a Colab VM and a non-colab VM, feeding the list of GCS URLs to gsutil as in our example notebook?

```cat gcs_paths.txt | gsutil -u $myProjectID -m cp -I ./downloaded_cohort```

**Comment by wlongabaugh** [comment]
@fedorov Above stats ^^^ are from @G-White-ISB. To test this properly, the job should break the manifest into multiple separate "gsutil -m" jobs and see if that adds any benefit over a single job running with the -m option. Plus do that on e.g. 8 or 16 CPU machines. As this link shows: https://cloud.google.com/compute/docs/machine-types#n2d_machine_types multiple processor machines have more egress bandwidth (they do not list ingress bandwidth, but I am assuming they are correlated).

**Comment by wlongabaugh** [comment]
We can also test throughput by using cat instead of cp and routing the output to /dev/null.

**Comment by fedorov** [comment]
@wlongabaugh @G-White-ISB thanks! Sorry for my tunnel vision!

I understand the time to pull the files is unavoidable, and can be reduced by parallel download, but is the BQ time acceptable?  If we export into GCS, which is very quick, we can save the user quite some time and effort.

I still think that ideally we would provide a disk with all the files available, but I understand this would be expensive and difficult.

**Comment by fedorov** [comment]
But indeed, @wlongabaugh reality check is correct - the query time is buried in file download time. We might as well accept it. I will check again my colab notebook, since in it I used `%%bigquery` magic, @G-White-ISB used BQ client and `to_dataframe`, and @wlongabaugh used batch query and iterated over rows. I don't know if those approaches are equivalent. Need to do more experiments.

**Comment by fedorov** [comment]
Since it was confirmed by @G-White-ISB that query of even very large manifests using the BQ approach works from colab notebook, this is not an emergency I thought it was. We do need to revisit the current approach and develop the best practice to recommend to the users.

**Comment by fedorov** [comment]
Alternative approach to download is documented in https://learn.canceridc.dev/cookbook/virtual-machines/using-a-bq-manifest-to-load-dicom-files-onto-a-vm. Will revisit if that should be the recommended approach as we get user feedback. No concerns from the users so far following the recommended gsutil-based download approach.
