### ISSUE TITLE
Revise attributes shown for cohorts in cohort list

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#550]
We should revise what is shown in the cohort list table. Currently, we have a lot of stuff that is not of much use, but some critical characteristics of the cohort are missing:

* what is the use of "Cohort ID"?
* what is the use of "Ownership" and "Shared with"?
* we probably can shorten the data version column to just show the date and version number
* we don't have any numbers to get an idea of cohort size (number of cases, number of instances, ...)

![image](https://user-images.githubusercontent.com/313942/108380037-7b442100-71d4-11eb-861d-3ba7a3085974.png)

**Comment by s-paquette** [comment]
@fedorov Shared With and Ownership are related to cohort sharing, which isn't enabled at this time. Cohort ID is used to fetch a Cohort in the API. Shorting the version column is easy enough to do. The 'size' is something we're working on; we have the columns in (on test) but I need to write a script to populate them.

**Comment by fedorov** [comment]
I understand. I am saying we show a lot of stuff which is irrelevant, and don't show things that are of interest. This ticket is to revise what we show to the user.

**Comment by s-paquette** [comment]
@fedorov This has been overhauled and is now on test.

**Comment by madelyngreyes** [comment]
The field order by name in descending order is not working as expected. 

<img width="1307" alt="Screen Shot 2021-05-17 at 9 39 53 PM" src="https://user-images.githubusercontent.com/16824894/118577509-874e6900-b758-11eb-9b36-c4d4d95a2f49.png">

**Comment by s-paquette** [comment]
@madelyngreyes That 404 isn't related to the ticket--it's an icon not being found in the icon set (but not one we need).

The filters can be seen by clicking on the +.

**Comment by s-paquette** [comment]
@fedorov @madelyngreyes This is ready for testing.

**Comment by madelyngreyes** [comment]
There is text off the page for the cohort filter list. Do I give it its own ticket? 
<img width="1306" alt="Screen Shot 2021-06-10 at 12 49 16 PM" src="https://user-images.githubusercontent.com/16824894/121565299-57f2eb00-c9ea-11eb-94eb-1b6aa947bfbe.png">

**Comment by s-paquette** [comment]
Yeah, that should get its own ticket.

**Comment by madelyngreyes** [comment]
okay

**Comment by fedorov** [comment]
Do we really need to spell data version as "Imaging Data Commons Data Release Version 1.0 2020-10-06"?

**Comment by s-paquette** [comment]
@fedorov The wording is controlled by the backend in the database, so it can be set arbitrarily any time we want (i.e. not a code change) unless you would like this longer form elsewhere as well as a shortform, and then that would be a code change.

Alternative: we can make a new ticket for adjusting that specific item (how the data version displays throughout the site), since it has broader implications, if you feel this ticket's issues are otherwise handled.

**Comment by fedorov** [comment]
Sure, we can make a separate ticket for that.
