### ISSUE TITLE
Opening a cohort BQ table needs fixes

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#551]
* clicking on the link should open in a new tab
* links to the tables should have the external site icon
![image](https://user-images.githubusercontent.com/313942/108382234-96179500-71d6-11eb-96d6-aa442525ce98.png)

**Comment by s-paquette** [comment]
@fedorov The opening in a new tab is functional on test for me; are you not seeing that currently?

**Comment by fedorov** [comment]
Yes, it is opening in a new tab in test. So we should just add the external link icon.

**Comment by s-paquette** [comment]
Looks like this is a duplicate of #542, can we close it?

**Comment by s-paquette** [comment]
@fedorov This is now in test.

**Comment by madelyngreyes** [comment]
This is working as expected on the test tier. 


https://user-images.githubusercontent.com/16824894/121053848-c6853e00-c789-11eb-8bbe-b0b18e3c1400.mov
