### ISSUE TITLE
"Show less" shows up when there's not much less to show

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#552]
This is happening for me in the test tier. Hard reload and clear cache did not help.

![image](https://user-images.githubusercontent.com/313942/108547927-20d0c080-72b9-11eb-8216-e635f3da3663.png)

**Comment by G-White-ISB** [comment]
@fedorov can you provide steps to reproduce? Thanks.

**Comment by fedorov** [comment]
Confirmed @G-White-ISB has the steps to reproduce.

**Comment by s-paquette** [comment]
@fedorov @madelyngreyes This is now on test.

**Comment by madelyngreyes** [comment]
<img width="386" alt="Screen Shot 2021-03-04 at 3 38 00 PM" src="https://user-images.githubusercontent.com/16824894/110027161-a3b53a80-7cff-11eb-9494-6640f977f761.png">
