### ISSUE TITLE
Enhancements to selection of cases/studies/series

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#555]
**Is your feature request related to a problem? If so, let us know**

Related to ticket, https://github.com/ImagingDataCommons/IDC-WebApp/issues/522

**Enhancement description**

Add a checkbox to be able to select multiple studies/cases currently you need to select shift or control(mac) then select another row to select multiple options. 

**Screenshots**

![108521862-2a96fb80-729a-11eb-87de-59755437e73a](https://user-images.githubusercontent.com/16824894/108888137-16743680-75d9-11eb-81e0-8b1b443db0e6.png)

**Comment by G-White-ISB** [comment]
Currently on dev-tier:

Each row in the Collections, Cases, and Studies table now has a checkbox. Checking the checkbox opens the relevant rows in the 'child' table. Unchecking the checkbox removes those rows. The checkbox is similar to the shopping cart icon in TCIA. One can no longer select a row by clicking anywhere on it - one must check the box. The Studies/ Series tables also have +/- icons in the header. Clicking on the + icon will check all the rows on the current page and open the relevant rows in the 'child' table. This is how the shopping cart icon in the header of the TCIA tables works. Clicking on the - icon unchecks all rows on the current page and removes relevant rows in the 'child' table. I did not put +/- icons on the header of the Collections page because we have a limit of less than 2000 rows that can be selected at one time and selecting a page's worth of Collections would likely exceed 2000.

**Comment by madelyngreyes** [comment]
Able to select a collection with more than 2,000 entries and trigger a notification. But, after the selection of okay the collection is still appears selected. The cases panel also did not populate with any entries. Video of the test run below,


https://user-images.githubusercontent.com/16824894/118578410-1f991d80-b75a-11eb-8a6e-0d38cdedcfab.mov

**Comment by fedorov** [comment]
I find the new approach to selecting items using checkbox only to be restrictive (user needs to click in a very specific small area). My personal preference would be to mimic the behavior of standard file picker selection (click to select, ctrl+click to toggle selection of a specific row, shift+click to select/unselect group of items, click when selection exists to unselect everything).

Selection/deselection of specific items to be included/excluded in the cohort would need to be addressed separately.

@ulrikew what are your thoughts?

**Comment by ulrikew** [comment]
I like the checkboxes in particular in combination with the plus and minus signs that allow the user to select multiple rows and receive an indication of which items have been selected. 
What still is very strange to me is that I cannot save a cohort based on the selections I made on the search results page.

**Comment by ulrikew** [comment]
What does this message mean? Why is there a limitation on the number of rows that a user can select?
![image](https://user-images.githubusercontent.com/3019001/118684873-97099400-b7d0-11eb-9125-7c39517b9ba7.png)

**Comment by G-White-ISB** [comment]
There is a limit on  the number of rows (currently 2000) the server can return to the web app AT ONE TIME. There is no way around having such a limit on returned rows in a single request. However we are going to handle this more intelligently such that the user can still select any size of rows. The rows will be sent to the web app in batches (sets of pages) as the user traverses the pages of rows in their selection, and this alert will not be shown (https://app.zenhub.com/workspaces/overall-project-workspace-5d39f406a4f118000112b4bb/issues/imagingdatacommons/idc-projectmanagement/632).

**Comment by ulrikew** [comment]
@G-White-ISB Thank you for the explanation, George.

**Comment by fedorov** [comment]
> I like the checkboxes in particular in combination with the plus and minus signs that allow the user to select multiple rows and receive an indication of which items have been selected.

@ulrikew I would agree this would be helpful if it was possible to add the selected items to the cohort, but currently this is only used to define the items that would be included in the table below in the hierarchy.

I have never used/thought of using the plus/minus sign buttons. Now that I tried, I am confused about the behavior. See the recording below, noting the "Selected studies" number of entries. Clearly, clicking on the row has some mysterious behavior.

Also, in the end, I click "+", and get the "2000 rows" error - where are those 2000+ come from? The number of cases being selected is 10, and summing up the number of all studies for those cases is far less than 2000.

![select](https://user-images.githubusercontent.com/313942/118841320-393f7f80-b896-11eb-8e8c-20f5ba341330.gif)

**Comment by G-White-ISB** [comment]
When you select cases in the cases table you are retrieving the associated Study level rows.  So when selecting all cases in the above you are asking to retrieve ~200 studies. But there is a bug such that the  webapp checks the total # number of series associated with the studies instead of the number of studies, which is greater than 2000. 
I did not notice the 'click anywhere on row mystery' until now. It will be corrected in my next code check-in.

**Comment by fedorov** [comment]
> So when selecting all cases in the above you are asking to retrieve ~200 studies

I thought when I click the "+" sign, I am asking to retrieve only the studies on the current page, not on all pages. In fact, you can confirm this is what is happening (rather, appears to be happening) if you select a different collection, such as "AAPM RT-MAC Grand Challenge 2019".

![2021-05-19_17-19-24](https://user-images.githubusercontent.com/313942/118886102-850a1d00-b8c6-11eb-91a1-c11d79f634c2.gif)

**Comment by G-White-ISB** [comment]
Correct, only the studies on the current page are selected.  The 10 4d-lung collections on the shown page in your previous video have about ~200 studies by my estimate

**Comment by fedorov** [comment]
> The 10 4d-lung collections on the shown page in your previous video have about ~200 studies by my estimate

I thought the limit was 2000, not 200. At least that's what the popup was saying.

**Comment by madelyngreyes** [comment]
I'm able to select 5000+ entries in the Selected Cases panel.

<img width="1220" alt="Screen Shot 2021-06-07 at 9 02 39 AM" src="https://user-images.githubusercontent.com/16824894/121021365-4eaa1a00-c76f-11eb-89b0-296ddaf91e22.png">

But, there is also text cut off on the Collections panel for the option prostate in the screenshot above.

**Comment by G-White-ISB** [comment]
Well this is different issue. @madelyngreyes can you reproduce the cutoff issue? If so what are the steps to reproduce?

**Comment by madelyngreyes** [comment]
Yes, just was unsure since the ticket states enhancements in the title.

I'm able to reproduce the issue by selecting all collections then sorting by descending order, then ascending order on the total # of cases column. 

<img width="1033" alt="Screen Shot 2021-06-07 at 11 42 28 AM" src="https://user-images.githubusercontent.com/16824894/121049308-95a30a00-c785-11eb-9d1c-99101caa7d74.png">

**Comment by s-paquette** [comment]
@pgundluru Can you check and see if this is still relevant?

**Comment by pgundluru** [comment]
+/_ Selection enables selection of all the rows in that particular page in selection of cases and studies level
