### ISSUE TITLE
Add datacommons.cancer.gov to homepage

### ISSUE THREAD

**Issue by s-paquette** [ImagingDataCommons/IDC-WebApp#563]
Per IDEA, add a link back to the datacommons.cancer.gov site to the top of the homepage (see PDC).

**Comment by madelyngreyes** [comment]
Link is present at the top of the page,

https://user-images.githubusercontent.com/16824894/119074709-7ce0d900-b9bd-11eb-858a-e3dcc7c9d946.mov
