### ISSUE TITLE
Qualitative analysis filter default settings improvements

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#564]
**General description**

Text cut off for filter selection and, show less was set as default setting for calcification filter. 

**Steps to reproduce the behavior**

1. go to the explore page
2. go to the derived tab
3. open the Calcification tab
4. show less is set as the default
5. open the Internal Structure tab
6. there is text cut off for the check all/ uncheck all option

**Screenshots**
<img width="714" alt="Screen Shot 2021-03-03 at 9 13 31 AM" src="https://user-images.githubusercontent.com/16824894/109818679-3fac4c80-7c01-11eb-8c53-f56736c9d877.png">
<img width="1429" alt="Screen Shot 2021-03-03 at 9 12 52 AM" src="https://user-images.githubusercontent.com/16824894/109818674-3e7b1f80-7c01-11eb-8885-a74744b934b3.png">

**Your System**
 - OS: Mac OS
 - Browser: Chrome
 - Version: canceridc.202103011131.27ce3b3

**Comment by G-White-ISB** [comment]
I saw that earlier. Fix deployed in dev

**Comment by madelyngreyes** [comment]
Format as expected on the test tier, 
<img width="382" alt="Screen Shot 2021-05-20 at 10 46 32 PM" src="https://user-images.githubusercontent.com/16824894/119074570-46a35980-b9bd-11eb-99e6-a58380db2acf.png">
