### ISSUE TITLE
Add manifest export/download to cohort list page

### ISSUE THREAD

**Issue by ulrikew** [ImagingDataCommons/IDC-WebApp#565]
Please investigate if the export cohort manifest button can be shown on the cohort page rather than the search screen.

On the Cohort screen, users have to click the name of the cohort which btw is not marked as a link by underlining it to go to the search results screen where they find the Export Cohort Manifest button.
This is neither user-friendly nor intuitive.

The "Delete cohort" functionality is on the cohort screen. Assembling all cohort-based functionality on the cohort page seems to be the logical choice.

**Comment by s-paquette** [comment]
Definitely can be done!

**Comment by fedorov** [comment]
We will also need this capability in order to support migration of cohorts into new data version. We will need to be able to support export of the cohort using the original version this cohort was created from.

**Comment by s-paquette** [comment]
Partially done - download part isn't functional yet, choosing a large number of cohorts will get a 500 if the request is > 30s

**Comment by s-paquette** [comment]
Exports of several cohorts won't error anymore, it queues them up and only waits 5-10s for all of them, then reports your list and lets you know they're on-going.

Downloads can only be done one at a time, and are always series-level now.

**Comment by madelyngreyes** [comment]
<img width="1321" alt="Screen Shot 2021-06-09 at 4 59 31 PM" src="https://user-images.githubusercontent.com/16824894/121428679-1576d300-c944-11eb-82d4-1fd8d60dc393.png">

Export all cohorts on the cohort list page will return the error, "There was an error exporting your cohort to BigQuery. Please contact the administrator."

**Comment by fedorov** [comment]
Removing the bulk export altogether would be completely acceptable for me. I do not know why we need it at all.

**Comment by s-paquette** [comment]
@fedorov This was done to save space on the page; having an export button on each cohort complicated the layout immensely. The bulk export is definitely not the issue in and of itself.

I'll have a look at the error in question.

**Comment by s-paquette** [comment]
Ah, I just noticed. @madelyngreyes One of your cohorts has derived filters, which per #617 is creating errors. Could you trying re-testing this without any derived cohorts?

**Comment by s-paquette** [comment]
Ah, I see what's going on now. 

Note, for now, this is going to necessitate a change: a user cannot select the BQ columns which will be included. We already have a ticket to allow for this, so that one will cover adding the functionality to do so.

**Comment by fedorov** [comment]
here's what I get trying to export CSV for cohort 111, which corresponds to the APOLLO collection

![image](https://user-images.githubusercontent.com/313942/121435490-fa5c9100-c94c-11eb-9da9-c98c773d147e.png)

**Comment by s-paquette** [comment]
@madelyngreyes @fedorov This feature should now be working per the fixes in 641 and 642. Note this doesn't include derived data cohorts, per 617, which will be fixed in an upcoming sprint.

**Comment by madelyngreyes** [comment]
I was able to export a cohort with derived filters present. 

But, then when I selected all 33 cohorts present for my account I triggered the error message, "There was an error exporting your cohort to BigQuery. Please contact the administrator."

<img width="1325" alt="Screen Shot 2021-06-10 at 2 59 20 PM" src="https://user-images.githubusercontent.com/16824894/121582056-90032980-c9fc-11eb-9256-a56bc87f3093.png">

**Comment by madelyngreyes** [comment]
Both functionality is present on the testing tier. 

<img width="1363" alt="Screen Shot 2021-06-17 at 9 55 01 AM" src="https://user-images.githubusercontent.com/16824894/122410640-1adea980-cf52-11eb-8f75-aa05a1edd6ba.png">
