### ISSUE TITLE
Selected studies panel # of series column asc/desc broken

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#566]
**General description**

Ascending and descending order incorrect for # of series column

**Steps to reproduce the behavior**
1. go to explore page
2. select a collection
3. select multiple cases
4. select the # of series column to sort
5. the numerical count is not in descending order

**Screenshots**
<img width="1440" alt="Screen Shot 2021-03-04 at 3 39 27 PM" src="https://user-images.githubusercontent.com/16824894/110027565-2211dc80-7d00-11eb-80fb-24933d8b631b.png">

**Your System**
 - OS: Mac
 - Browser: Chrome 
 - Version: canceridc.202103011131.27ce3b3

**Other Comments**

**Comment by G-White-ISB** [comment]
It's doing alphabetical sorting "27" >"5" rather than numeric. Will fix
