### ISSUE TITLE
IDC consortium logo should be removed from the login page

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#568]
IDC consortium logo (image right above the user name) should be removed from the login page

![image](https://user-images.githubusercontent.com/313942/110355836-a79ad280-8007-11eb-839d-5b9010338c44.png)

**Comment by fedorov** [comment]
Let's just put text "Sign in with IDC credentials" instead, to keep things simple.

**Comment by fedorov** [comment]
@s-paquette can this be included in the upcoming hotfix please?

**Comment by s-paquette** [comment]
It will roll out when V2 data was; I'd need to, in effect, re-do the change to hotfix it. I can if we want to but it's basically a duplication of the effort.

**Comment by fedorov** [comment]
Let's hold it then, I didn't know how difficult it would be to include it.

**Comment by madelyngreyes** [comment]
<img width="1081" alt="Screen Shot 2021-05-20 at 9 38 29 AM" src="https://user-images.githubusercontent.com/16824894/118988397-276de300-b94f-11eb-8ed8-bb617561625a.png">

Removal of logo from login page above.
