### ISSUE TITLE
"Show more" should show on top of the list, not the bottom

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#586]
When shown at the bottom, it disappears at the bottom of the scroll area.

**Comment by madelyngreyes** [comment]
<img width="379" alt="Screen Shot 2021-05-20 at 9 36 45 AM" src="https://user-images.githubusercontent.com/16824894/118988120-e970bf00-b94e-11eb-9f73-504f3fb77470.png">

Show more at the top of the filter.
