### ISSUE TITLE
DICOM source name hard coded in several places to aid the display

### ISSUE THREAD

**Issue by s-paquette** [ImagingDataCommons/IDC-WebApp#588]
In numerous places, the DICOM source Solr name is hard-coded for purposes of fetching data out of the context and result set for displaying in the UI. This needs to be refactored to make no use of the source name, as this will change from data version to version. 

Eg., in idc/template_tags/custom_tags.py: https://github.com/ImagingDataCommons/IDC-WebApp/blob/a2b3962e9cbdaa848fcffcdcc164d613bdabba16/idc/templatetags/custom_tags.py#L59

This breaks when a new source is made. 

Better would be to alter the keys used in the dict to only name the derived set type, eg. 'quantitative', 'segmentation'. This has to be done in numerous places.

**Comment by G-White-ISB** [comment]
So web app code is refactored to expect the derived sources to have names in the pattern *:quantitative, *:qualitiative, *:segmentation. Note that some of the etl code is still hard coded with the source name

**Comment by s-paquette** [comment]
@madelyngreyes Note there's no formal testing for this, once various exploration filters are working right we can count this as resolved.
