### ISSUE TITLE
Provide user with the selection of the analysis results collections under the Search Scope tab.

### ISSUE THREAD

**Issue by s-paquette** [ImagingDataCommons/IDC-WebApp#593]
Broken out from #590 

A few things we need to consider:

- What is the value we're displaying for selection? The DOI, the name of the results collection, something else...?
- How do we plan to keep this list of values up to date? Right now, all attributes used in filtering are a complete list of values, but this would imply a sub-set of values (analysis results DOIs, as opposed to ALL DOIs)
- Counts on the derived tab only pertain to derived data, but a filter pertains to all of IDC. How does selecting an analysis result set (by selecting a DOI or the name, or however we plan to filter it) impact the overall cohort as it pertains to the original collection this may stem from?

As analysis results are effectively series-level, this will have to be a series-applicable attribute filter, so we'll need to support series level filtering in order for this to proceed.

**Comment by fedorov** [comment]
Here are the short names for the analysis results collections we currently include, as coordinated with TCIA (see this issue https://help.cancerimagingarchive.net/servicedesk/customer/portal/1/TH-47291):
* PROSTATEx Zone Segmentations - PROSTATEx-Seg-Zones
* High Resolution Prostate Segmentations for the ProstateX-Challenge - PROSTATEx-Seg-HiRes
* DICOM SR of clinical data and measurement for breast cancer collections to TCIA - DICOM-SR-Breast-Clinical
* Standardized representation of the TCIA LIDC-IDRI annotations using DICOM - DICOM-LIDC-IDRI-Nodules
* RIDER Lung CT Segmentation Labels from: Decoding tumour phenotype by noninvasive imaging using a quantitative radiomics approach - RIDER-LungCT-Seg
* QIN multi-site collection of Lung CT data with Nodule Segmentations - QIN-LungCT-Seg

**Comment by fedorov** [comment]
Proposed idea: have analysis results listed and selectable under a panel that is sibling to the Collections panel in "Search scope".

**Comment by G-White-ISB** [comment]
So as I understand it you would like to have a separate 'analysis collections' list that is separately selectable and the stats calculated would reflect both the analysis and image collections selected.  @s-paquette would know more about how difficult the stats calculations then become. Right now it seems we have a 1-1 map between image and an analysis collections. If you select an image collection, why would you not want to select the analysis collection if it is present?

**Comment by fedorov** [comment]
Related to #222

**Comment by fedorov** [comment]
Per @s-paquette we will need to have all low caps underscore versions of the IDs for the analysis results. In addition to this:

![image](https://user-images.githubusercontent.com/313942/146053426-cd5e9496-62d5-43eb-ac1a-de010233adf2.png)

we will need something like this:

![image](https://user-images.githubusercontent.com/313942/146053493-073e2c77-e2b9-4957-b769-e1ade7000273.png)

**Comment by fedorov** [comment]
One issue we need to decide is whether we should use DOIs or something else to tag collections.

**Comment by fedorov** [comment]
@bcli4d can you please clarify the process for assigning DOIs to instances?

**Comment by fedorov** [comment]
from @bcli4d:

All the code is in the etl_flow repo:
utilities/get_collections_dois.py: get_internal_series_ids() returns a list of IDs of all series in a collection or a patient in a collection. These are internal (to NBIA I guess) IDs; they are not, e.g. SeriesInstanceUIDs. The third_party param controls whether the series returned are in the original data collection (third_party = False), or in some analysis result (third_party=True).

utilities/get_collections_dois.py:get_data_collection_doi() "drills down" to convert those IDs tp SeriesInstanceUIDs. Similarly get_analysis_collection_dois().

**Comment by bcli4d** [comment]
To clarify a bit more...
At the start of ingesting a collection, I get the original collection DOI, and a list of (third party SeriesInstanceUID,  third party DOI).
Then when I add a series, if it is in the list of third party series, I use the associated third party DOI. If it is not in the third party series list, then it must be from the original collection, and I assign the original collection DOI.
This, of course, assumes that there is a single DOI per original collection, but that is implicit in TCIA/NBIA.

**Comment by fedorov** [comment]
Relevant email communication from TCIA's Kirk Smith re one-to-one correspondence between SOPInstanceUID and DOI from Feb 28, 2022:

---

Hi Andrey,

I’ll be giving more thought to this in the coming week, but wanted to reply as I have been out of office the last week.

> “The key assumption for us right now is that every DICOM instance can correspond to one and only one entry in either original or analysis collection.”

I believe that statement to be true for Data within NBIA as I think there is a one to one relationship of DOI to a DICOM instance.

In practice that is our goal and it should mostly be true, however, I know there is at least one early case that could lead to confusion. The collection is HNSCC. We first received HNSCC data from a submitting site and called it a collection. The data had a corresponding manuscript. Later on another group from the same site used data from the same trial, had some overlapping subjects (no overlapping series) and had its own related manuscript.

At that point we decided we needed a parent collection that contained all data and two separate Analysis Results collections that contained the related data for each manuscript.

So the HNSCC Collection itself has a DOI and a DOI Landing Page with access to download all of the data. Each of the two Analysis Results pages have their own DOI and the download for them has download access to the DICOM for the portion of the parent collection related to the manuscript.

Our current policy on Analysis Results would not have allowed this, instead the original images would have been the parent collection and only related segmentations etc would have been part of the Analysis Results.

For HNSCC the DICOM images stored in NBIA only have the DOI of the Parent Collection and not of the Analysis Results.

I don’t know if there may be other anomalies, but in general your statement is correct and going forward will be correct per our current policy on Analysis Results.

Adding Justin and Scott Gustafson to the thread.

Thanks,

Kirk

**Comment by fedorov** [comment]
Per discussion today, we should proceed with the implementation and not wait for TCIA revisions to the data model.

**Comment by s-paquette** [comment]
Tooltips are now added to the analysis results section. They're not displaying quite right due to the attribute being under Original and not Search Scope; once it moves, they should display properly.

**Comment by G-White-ISB** [comment]
I see that in the dev portal there is a script with an id analysis_results_tooltips, similar to the collections_tooltips script, but it's empty. Running locally I don't see analysis_results_tooltips in the explorer page context

**Comment by fedorov** [comment]
Discussed and decided to add description column for analysis results collections, which will include DOI URL. I will create those and pass to @bcli4d

**Comment by s-paquette** [comment]
@G-White-ISB Sorry there, missed a few steps. You can now download a new database see from idc-dev-files and pull from Common master, then refresh the database. That'll get you the new column plus the current analysis results tooltips.

**Comment by fedorov** [comment]
Analysis collections descriptions passed to @bcli4d here: https://docs.google.com/document/d/1JF1UmvMgvEUutmpXz_UAlpbPdFyEen3lEkBR_-CwXtc/edit?usp=sharing.

TCIA has been informed via this ticket: https://help.cancerimagingarchive.net/servicedesk/customer/portal/1/TH-49649.

**Comment by bcli4d** [comment]
I converted Andrey's doc to [this](https://docs.google.com/spreadsheets/d/1C0ZLeHzx23UbWALtb5j6WfzjmFvRVjd5ieuTcOw7dfE/edit#gid=0) spreadsheet. It is an easier form to load into BQ, PSQL, etc.

**Comment by fedorov** [comment]
Thanks Bill, I agree. I used text document for the sake of editing convenience.

**Comment by pgundluru** [comment]
![image](https://user-images.githubusercontent.com/85526819/167937210-3f4b609b-66f7-4cd3-ad85-b6cb90a71fda.png)

**Comment by pgundluru** [comment]
Tool tips included for each analysis results
