### ISSUE TITLE
Fix link to the page explaining cohort count

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#599]
The correct URL to be used in the tooltip below is https://learn.canceridc.dev/portal/data-exploration-and-cohorts#understanding-counts-in-the-search-results.

**Comment by fedorov** [comment]
![image](https://user-images.githubusercontent.com/313942/115261312-826aab00-a101-11eb-867f-44140d29c2db.png)

**Comment by fedorov** [comment]
While this issue was pending, the content of the docs was reorganized, and we need to update the link again to point to this instead: https://learn.canceridc.dev/portal/data-exploration-and-cohorts/exploring-imaging-data#understanding-counts-in-the-search-results. The original page was getting exceedingly long, and so I broke it into sub-pages, per one of the discussions.

**Comment by s-paquette** [comment]
@G-White-ISB per @fedorov 's comment this needs to be updated. Moved it into Sprint 23.

**Comment by pgundluru** [comment]
Clicking on the tool tip navigates to correct URL and section https://learn.canceridc.dev/portal/data-exploration-and-cohorts/exploring-imaging-data#understanding-counts-in-the-search-results
