### ISSUE TITLE
Support cohort filter application granularity at case/study/series levels

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#602]
Currently, the counts reported in the portal are the counts of cases that match the cohort filter, while for the export of the cohort, the filter is applied at the study level.

It might be a useful feature to support application of cohort filter at series or study level, based on user selection. I am not sure filter-based selection at case level is as useful as study- and series-level.

@s-paquette per discussion on Tue this week.

**Comment by s-paquette** [comment]
- Need to make and add a case-level index
- Need to add the granularity concept to the cohort backend and the UI

**Comment by fedorov** [comment]
Superseded by #973
