### ISSUE TITLE
unable to export cohort to BigQuery 

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#605]
**General description**
When attempting to export a cohort you are returned the error message, "Unable to export cohort file manifest to table canceridc-user-data.user_manifests.manifest_cohort_181_20210426_144515--please contact the administrator."

**Steps to reproduce the behavior**
I believe the the issue has to due with the filter selections, filters used are listed below. 

COLLECTION IN (tcga_gbm) AND BODY PART EXAMINED IN (Brain) AND MODALITY IN (Magnetic Resonance) AND OBJECT CLASS IN (MR Image) AND PRIMARY SITE LOCATION IN (Brain

**Screenshot**
<img width="1302" alt="Screen Shot 2021-04-26 at 10 51 40 AM" src="https://user-images.githubusercontent.com/16824894/116103257-6b860480-a67d-11eb-94a4-1bfd83d11b58.png">

**Your System**
 - OS: Mac iOS
 - Browser: Chrome
 - Version: Pilot Application Version: canceridc.202104141103.7a803bf

**Comment by madelyngreyes** [comment]
Clicking the failed button will display screenshots and videos of bugs in the test report.

**Comment by s-paquette** [comment]
Issue seems to be related to SOPClassUID being detected as a numeric type and not a string--oddly I could swear we dealt with this for the API already, so I'm poking at how this is a problem again.

**Comment by s-paquette** [comment]
Okay, bug identified. I guess we never tested SOPClassUID as one of the 'strings which has a lot of numbers in it' because it wasn't added to the BQ type schema which defines the types for any possible weirdness. Going to adjust this for hopefully some better guidance here in the BQ filter builder.

**Comment by s-paquette** [comment]
Right, it turns out there's no easy way to tell that '1.4.6.3.2' is a string while '1.4' might be a number, due to how it's possible to send in numeric values AS strings in BigQuery. (The parameter type is used by BQ's API to cast the parameter, so you can send whatever you want.) 

So, added SOPClassUID to the type schema list of 'looks like a number, actually is a string' alongside all the other period/integer UIDs and sample_type.

**Comment by s-paquette** [comment]
@fedorov Did you want me to drop this in as a hotfix? I can put it on test alongside the current one for @madelyngreyes to look at it, and if both are all clear I'll put them onto production.

**Comment by fedorov** [comment]
I don't have objections dropping this in as a hotfix.

**Comment by s-paquette** [comment]
@madelyngreyes Now available on test.

**Comment by madelyngreyes** [comment]
Able to export cohort on the test tier with filters used in the original screenshot. 
<img width="1316" alt="Screen Shot 2021-04-27 at 9 55 25 PM" src="https://user-images.githubusercontent.com/16824894/116334558-6c18bb00-a7a3-11eb-8b5a-00cf6890285e.png">

**Comment by madelyngreyes** [comment]
Cohort was successfully exported on the production tier.
<img width="1300" alt="Screen Shot 2021-04-29 at 1 41 51 PM" src="https://user-images.githubusercontent.com/16824894/116624992-e3229080-a916-11eb-89b7-4fe49f933645.png">
