### ISSUE TITLE
Program assignment for TCIA collection

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#608]
The work is ongoing to assign program to individual collections, see current status here, in coordination with TCIA and @kirbyju:
 https://docs.google.com/spreadsheets/d/1-sk8CMTDDj-deKv7sXglLvHUhDSNS1cRqUg5Oy5UpRY/edit#gid=0.

Issue in TCIA: https://help.cancerimagingarchive.net/servicedesk/customer/portal/1/TH-47350.

**Comment by fedorov** [comment]
Note that program assignments have been established pretty much, see spreadsheet above. This will need to be updated in the webapp sometime before the Fall.

**Comment by fedorov** [comment]
@s-paquette APOLLO-1-VA should be under the APOLLO program. It is not on dev.

@bcli4d we should maintain program assignment in some BQ table. Do you agree?

**Comment by s-paquette** [comment]
@fedorov It is in that program, however all Collections which are solo in their Programs only list as a Collection under Search Scope. @G-White-ISB can change that if you'd prefer.

**Comment by fedorov** [comment]
> all Collections which are solo in their Programs only list as a Collection under Search Scope

@s-paquette I didn't realize this is the expected behavior. Let's leave it as is for now.

> @bcli4d we should maintain program assignment in some BQ table. Do you agree?

From a discussion on this topic, decided to put program information into a dedicated table, and join into the collections table.
