### ISSUE TITLE
BodyPartExamined capitalization should not be altered

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#610]
Currently, there is some transformation applied, while original values are most often all caps (per DICOM definition of this attribute).

**Comment by s-paquette** [comment]
Switched BodyPartExamined to preformatted_values: 1

**Comment by s-paquette** [comment]
@fedorov Can you have a look and make sure this is now listing what it should?

**Comment by fedorov** [comment]
Looks more like it should be now, but I don't know how I would be able to check against the actual value of BodyPartExamined. I think as a general rule, there should be no transformations applied to any of the attributes shown to the user in the portal, since otherwise it will lead to difficulties re-constructing the filter against BigQuery.

**Comment by madelyngreyes** [comment]
Format present on the test tier can be viewed below, 

https://user-images.githubusercontent.com/16824894/121017948-db52d900-c76b-11eb-8298-c70ac012e077.mov
