### ISSUE TITLE
When dev-portal logs me out, I am brought to idc-dev

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#612]
when dev-portal logs me out, I am brought to idc-dev

![image](https://user-images.githubusercontent.com/313942/117189921-bfdf6180-adac-11eb-9de5-f9ce66e08c11.png)

**Comment by s-paquette** [comment]
Problem in the .env file's base URL setting, should be fixed on dev and test.

**Comment by madelyngreyes** [comment]
I have still been seeing a 400 error.

**Comment by s-paquette** [comment]
@madelyngreyes Can you confirm which tier you're getting the 400 on? I can't reproduce this on dev.

**Comment by s-paquette** [comment]
@madelyngreyes Can I get a screenshot? (Including the browser bar.) @fedorov Will do, I'll drop it from the Sprint.

**Comment by s-paquette** [comment]
@pgundluru @madelyngreyes I can't reproduce this bug anymore, but if you can and could send me a screenshot that would be appreciated. it needs to be tested on each tier individually due to how logouts and redirects function.
