### ISSUE TITLE
Select All enabled for cohort details when should be disabled

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#629]
After the end user goes to save a cohort. If they try to select one filter the checkbox becomes disabled for the filter selection. But, if the end user chooses select all, the filters are added to the saved cohort when I believe it should be disabled. 

https://user-images.githubusercontent.com/16824894/118570027-37b47100-b749-11eb-948d-ccac28efb51c.mov

**Comment by s-paquette** [comment]
All checkboxes need to be disabled when the page is open in cohort mode.

**Comment by madelyngreyes** [comment]
Still able to select All cohorts, then export to BigQuery manifest and return the error, "There was an error exporting your cohort to BigQuery. Please contact the administrator."


https://user-images.githubusercontent.com/16824894/120818528-b4549700-c520-11eb-8c31-1f08b3b408f1.mov

**Comment by madelyngreyes** [comment]
You are right. This is the wrong ticket thank you for the clarification.
