### ISSUE TITLE
Dynamic update of the search facets shown based on content

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#63]
Currently, the facets available on the left are static, and are displayed even if there are 0 items that fit individual criteria.

So, for example, if I select tcga-gbm, I still see "Mammography" as modality.

Note that GDC interface does not show facets that have 0 items matching.

I suggest we do not show 0-size facets to simplify and de-clutter the interface, and they add no value to the interface.

![image](https://user-images.githubusercontent.com/313942/77173490-f7e6f080-6a95-11ea-90d9-3663e38c9422.png)

**Comment by G-White-ISB** [comment]
We can do this if there are no second thoughts.

**Comment by G-White-ISB** [comment]
In my latest PR

**Comment by fedorov** [comment]
Is it possible to sort the items based on the number of hits (similar to how it is done in GDC)?

Currently, they are not sorted:

![image](https://user-images.githubusercontent.com/313942/79894282-37756500-83d3-11ea-9fb2-689f001a09b7.png)

**Comment by madelyngreyes** [comment]
Something else related to this issue I noticed there is a None option available to the option Modality in the left filter panel. It has zero cases and therefore, should not be displayed as an option by default. 

![IDC - none an option on the modality filter page](https://user-images.githubusercontent.com/16824894/80728070-82c6fc00-8ad4-11ea-95ed-961a855b70fb.PNG)

![IDC - none filter selected dev tier for modality filter](https://user-images.githubusercontent.com/16824894/80728082-86f31980-8ad4-11ea-9222-a0cd7abfc94d.PNG)

**Comment by wlongabaugh** [comment]
We now show zero counts, but I believe we agreed it should be a user preference?

**Comment by G-White-ISB** [comment]
User has an option to hide or show 0 counts
