### ISSUE TITLE
Manifest export to BigQuery returns an error, "invalid table ID "idc-testing.test_user_dataset.manifest_cohort_86_20210521_020536"."

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#630]
On the test tier from the exploration page, if the user goes to export the cohort via BigQuery the export is successful. But, when the user then selects the export cohort manifest link, they returned an error in the BigQuery console. 

https://user-images.githubusercontent.com/16824894/119073981-3474eb80-b9bc-11eb-8a6d-399f0cd76ddd.mov

**Comment by s-paquette** [comment]
Does this happen on dev, BTW? @madelyngreyes

**Comment by madelyngreyes** [comment]
I have been testing only on the test tier.

**Comment by s-paquette** [comment]
@madelyngreyes All good, this is one both tiers now.
