### ISSUE TITLE
Homepage lists data volume as 0.0TB

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#631]
<img width="1315" alt="Screen Shot 2021-05-20 at 10 59 37 PM" src="https://user-images.githubusercontent.com/16824894/119075694-37bda680-b9bf-11eb-86e7-1549c95ec435.png">

**Comment by s-paquette** [comment]
@bcli4d Do we have a count for our total volume yet?

**Comment by bcli4d** [comment]
6227264481922B


<br class="Apple-interchange-newline">

**Comment by s-paquette** [comment]
@madelyngreyes Updated on dev and test.
