### ISSUE TITLE
Triggered 500 errors with random filter selections

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#632]
Trying to see which exact filters are triggering the 500 error but, seems to be different filters every time so far. 

<img width="1319" alt="Screen Shot 2021-05-20 at 11 02 56 PM" src="https://user-images.githubusercontent.com/16824894/119076515-b535e680-b9c0-11eb-948b-48f788f6e066.png">
<img width="1317" alt="Screen Shot 2021-05-20 at 11 07 36 PM" src="https://user-images.githubusercontent.com/16824894/119076517-b5ce7d00-b9c0-11eb-8724-1c68b72c7a9e.png">

**Comment by s-paquette** [comment]
I *think* I found the source of these. I'm going to mark it as testing needed, feel free to flag as failed and we'll drop it into Sprint 22 again if it comes up.
