### ISSUE TITLE
Pie charts instead of bar plots for the front page?

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#64]
I think pie charts with the legend shown in mouse-over is a more concise and visually appealing way to present the summaries than bar charts. Both GDC and TCIA interfaces are using pie charts.

**Comment by G-White-ISB** [comment]
We're going to add a toggle to go between pie and bar charts. I think Bill L. also favors pie charts. When an attribute has just a few categories (say gender) I find it irritating to have to 'mouse-over' the graph to get the numbers. When there are may categories its hard to display the labels all meaningfully.

**Comment by G-White-ISB** [comment]
Currently set with pie charts as in gdc

**Comment by G-White-ISB** [comment]
Sorry I should say the pie charts are in my pull request which is currently under review to be deployed

**Comment by fedorov** [comment]
I see this has been integrated. Thanks!
