### ISSUE TITLE
Export of cohorts as files should not be allowed when it is not feasible

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#641]
I selected all collections, and could still see export as files in the manifest export dialog.

When I clicked "Export JSON", I got the below.

![image](https://user-images.githubusercontent.com/313942/121214352-095c1a00-c84d-11eb-80c4-50a2820b9b99.png)

**Comment by madelyngreyes** [comment]
You also get this error when exporting a cohort with all collections for the download as CSV and download as TSV as well.

**Comment by s-paquette** [comment]
I'm a little confused by the title of the ticket--we continue to allow it, we just don't let the user get the entire set of files. We warn them that this is the case. This is an actual breakage in the download itself, I think. @fedorov Do you mean you would prefer downloading the files not be listed as available if the entire thing can't be downloaded in a single file? I'm not clear on what the request is.

**Comment by G-White-ISB** [comment]
Download as csv is currently failing on the test portal for even small cohorts. Currently investigating

**Comment by G-White-ISB** [comment]
Locally I'm seeing the same error I mentioned in my last comment on https://github.com/ImagingDataCommons/IDC-WebApp/issues/541 when  trying to export via file download regardless of the cohort size. I expect the same thing is happening on the dev and test tiers.

<img width="1500" alt="Screen Shot 2021-06-08 at 2 21 41 PM" src="https://user-images.githubusercontent.com/58443591/121259412-ef2e3600-c864-11eb-9eee-57e32a20de2b.png">

File "/home/vagrant/www/IDC-Common/idc_collections/collex_metadata_utils.py", line 509, in get_collex_metadata
    search_child_records_by=search_child_records_by)
  File "/home/vagrant/www/IDC-Common/idc_collections/collex_metadata_utils.py", line 613, in get_metadata_solr
    if attr_name in all_ui_attrs['sources'][source.id]['list']:
KeyError: 11
[ERROR] @2021-06-08 14:10:35,862 in utils/1956/140553542170368 - local variable 'results' referenced before assignment
Traceback (most recent call last):
  File "/home/vagrant/www/IDC-Common/cohorts/utils.py", line 225, in cohort_manifest
    collapse_on='SOPInstanceUID', records_only=True, sort="PatientID asc, StudyInstanceUID asc, SeriesInstanceUID asc, SOPInstanceUID asc")
  File "/home/vagrant/www/IDC-Common/idc_collections/collex_metadata_utils.py", line 536, in get_collex_metadata
    return results
UnboundLocalError: local variable 'results' referenced before assignment
[ERROR] @2021-06-08 14:14:32,413 in views/1956/140553542170368 - [ERROR] While downloading the cohort manifest(s) for user 3:
[ERROR] @2021-06-08 14:14:32,414 in views/1956/140553542170368 - argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/home/vagrant/www/IDC-Common/cohorts/views/views.py", line 1140, in download_cohort_manifest
    response = create_file_manifest(request, Cohort.objects.get(id=cohort_id))
  File "/home/vagrant/www/IDC-Common/cohorts/views/views.py", line 1026, in create_file_manifest
    if 'docs' in items:

**Comment by fedorov** [comment]
> I'm a little confused by the title of the ticket--we continue to allow it, we just don't let the user get the entire set of files. We warn them that this is the case. This is an actual breakage in the download itself, I think. @fedorov Do you mean you would prefer downloading the files not be listed as available if the entire thing can't be downloaded in a single file? I'm not clear on what the request is.

@s-paquette, per our [documentation here](https://learn.canceridc.dev/portal/data-exploration-and-cohorts#accessing-the-cohort-manifest): "You can download cohorts of up to 650,000 rows as a multipart file, with each file having a limit of 65,000 rows. Access cohorts larger that 650,000 rows by exporting to BigQuery."

Can you please clarify what is the expected behavior when a cohort results in a manifest that exceeds 650,000 rows?

**Comment by s-paquette** [comment]
@fedorov In checking on production, the expected behavior is that it not be allowed; anything larger than 65k disables the download option.

I don't think it's the size that's the issue here--since we've swapped to series-level Solr cores, all downloaded cohorts will be series level aka bundles, so they're seldom likely to exceed 65k. When they do, it should disable. If that's not happening, that's definitely a bug, but the error shown above is something else, as opposed to an undisabled selector.

What I'm trying to say is, this ticket looks like 2 different bugs. The first bug is, manifests which presumably are too big can still be downloaded. The second bug is the error listed above.

**Comment by fedorov** [comment]
Suzanne, yes, there may be two issues, but they are intertwined and not easily separable. The second error was identify trying to check/test the original issue. Feel free to break into two issues if you like.

> all downloaded cohorts will be series level aka bundles, so they're seldom likely to exceed 65k

I did not realize this has already happened. When I export into BQ, I see instance-level manifests. Are you saying file manifests are not the same as BQ manifests now?

Also, will someone provide instructions how to deal with series-level bundles? We do not have this in the docs, and we must have those in the docs if we switch to series level.

cc: @wlongabaugh @bcli4d

**Comment by s-paquette** [comment]
@fedorov BigQuery exports are performed via the BigQuery pivot, as a result they're instance level. Downloaded exports are done via the Solr collections, which are series (or study) aggregated. For working with the bundles, we do need to put in documentation, which @bcli4d and I can discuss. 

This is largely a function of the fact that we have a 30s timeout from the load balancer, so using BigQuery for these kinds of queries isn't doable in realtime. We haven't yet implemented the ability to provide the user with a limited time file download link into GCS (we have an item for it); once we do, a user will be able to get an instance-level download. Until then, we need to use Solr and those will be the bundles.

**Comment by fedorov** [comment]
Ok, thanks for clarifying. I did not realize we are pushing bundles into v2. If I have no clue how to work with those, then there is no way to even test this capability, forget about making it accessible to the users.

**Comment by wlongabaugh** [comment]
The line of reasoning is that BQ exported manifests are the best way to do this, and that route gives you everything you need. Manifests provided as downloaded files are always going to be constrained by size limits, and we are under the impression they are considered a less-essential feature of the WebApp. So providing them as series bundles is a way to make them much smaller. Yes, we need to document how to use BQ and IndexD to resolve the UUIDs to paths.

**Comment by madelyngreyes** [comment]
@s-paquette how should this ticket be tested?

**Comment by s-paquette** [comment]
@madelyngreyes We're still working out what's wrong with it; nothing to update on that front.

**Comment by s-paquette** [comment]
@fedorov @madelyngreyes Fix is now in test. Changes made:

- Cohorts with v1 data can only be exported to BigQuery
- Cohorts with v2 data can be downloaded as series-level manifests, or exported as instance-level manifests to BigQuery
- The dialog will inform the user (via tooltip for now, we can make a ticket to improve it) why they can only download via BQ when this is the case
- When exporting to BigQuery, the 'name' box will now be replaced by text explaining that BQ table names are auto-generated.
- All 3 file formats for download should work again

We can definitely improve the overall informativeness of the dialog, but for the moment, I want to focus on its functionality.

**Comment by G-White-ISB** [comment]
If I try to export a v1 cohort via file download I just get an error message.  I can edit the export dialog to handle this

**Comment by s-paquette** [comment]
@G-White-ISB Can you screenshot the error/indicate what it is?

**Comment by s-paquette** [comment]
@madelyngreyes We're still fixing this; George found a new bug. The dialog shouldn't be letting you download v1 at all, only export.

**Comment by madelyngreyes** [comment]
Unable to select which columns to export for v1 cohort since the column selection is only visible from the files button selection.

**Comment by s-paquette** [comment]
@madelyngreyes this is as expected, because BQ exports do not currently support column selection. There's a ticket for this feature which is outstanding.
