### ISSUE TITLE
Export of cohort into BQ fails

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#642]
Cohort: https://testing-portal.canceridc.dev/cohorts/103/

Attempting to export it results in this error:

![image](https://user-images.githubusercontent.com/313942/121214657-517b3c80-c84d-11eb-8be8-2a8c7d28d620.png)

**Comment by G-White-ISB** [comment]
@fedorov could you report or show a screenshot of the cohort definition? Thanks

**Comment by fedorov** [comment]
Can you access the cohort by the ID (103)? It's a very long definition (I was basically clicking everything to make the filter very long. But I've just been able to reproduce both issues above by simply selecting all collections.

**Comment by madelyngreyes** [comment]
I selected multiple derived filters and was able to trigger the same error, 
<img width="1326" alt="Screen Shot 2021-06-08 at 11 52 03 AM" src="https://user-images.githubusercontent.com/16824894/121217584-fe56b900-c84f-11eb-9d0f-f74ce574192e.png">

**Comment by fedorov** [comment]
![image](https://user-images.githubusercontent.com/313942/121221274-678bfb80-c853-11eb-85c0-ce881c3b2036.png)

**Comment by s-paquette** [comment]
@G-White-ISB I'm noticing that one of the problems is, program_name is once again being passed in as a filter when it shouldn't be. We don't offer program as a filter explicitly because it's not an entity in TCIA. Those checkboxes purely exist to allow the user to easily select a grouping of collections, but the program_name itself shouldn't be sent to the backend as a filter.

**Comment by s-paquette** [comment]
Ah ha, just found it. Problem with checking on job status.

**Comment by s-paquette** [comment]
@madelyngreyes @fedorov Note this fix does NOT cover derived data, only 'large cohorts' eg. all collections, etc.

**Comment by s-paquette** [comment]
@madelyngreyes This one is now ready for testing; it was actually the same problem as in 641, so really this is a duplicate and they can be tested together.
