### ISSUE TITLE
Alert the user when the filter length is exceeded/approaching the threshold

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#644]
follow up on #622

**Comment by s-paquette** [comment]
Near as I can tell, the purpose of this ticket was to talk about alerting a user if they've made a filter value selection set which is longer than the database can handle for a given attribute.

Right now we don't have a value set which meets this criteria, though the Manufacturer attributes have a possibility of coming close. To implement this we need:

- To define the max size and add it to the ENV file, settings.py, and context processor
- Check that a given concatenated string of values doesn't exceed this value
- Open a warning if it does, disable the Save Cohort button until they've back under the threshhold.

**Comment by s-paquette** [comment]
This functionality is already supported; to test it, select 'check all' for any of the attributes with a large number of values and a yellow warning box should show.

**Comment by pgundluru** [comment]
This is tested by selecting a large collection or filters in the exploration page and the following message is seen 

Your query's URL exceeds the maximum length allowed (2048 characters). You will need to select fewer filters or the URL will not properly load when used.
