### ISSUE TITLE
Possible inconsistencies in the cohort selection result

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#65]
I cannot understand the result of selection here.

I selected "Computed tomography" on the upper left, which says "3 cases", but on the right I see a lot more of 3 studies. 

What is the meaning of "case"?

![image](https://user-images.githubusercontent.com/313942/77174990-4ac1a780-6a98-11ea-8182-d5838230aa81.png)

**Comment by G-White-ISB** [comment]
I will look into it. Its on my agenda to confirm consistency of the filtered data as part of testing.

**Comment by G-White-ISB** [comment]
Yes this does appear to be a bug. We are tracking down. In this context a 'case' would be a patient. So we are reporting 3 patients in gbm were examined by CT, although we should report 13 cases.

**Comment by s-paquette** [comment]
So the issue here is it's possible for a case to have more than one Modality entry, but it's still a unique case, and thus the numbers look odd.

BQ query to see this:

```SELECT PatientID, COUNT(*) as scans, String_Agg(Modality)
FROM (
SELECT PatientID, Modality 
FROM `idc-dev-etl.tcia.dicom_metadata`
WHERE collection_id = 'tcga_gbm'
GROUP BY PatientID, Modality
) gbm
GROUP BY PatientID
ORDER BY scans desc;```

**Comment by s-paquette** [comment]
Looks like we need to using grouping and not collapsing in any case where the 'counted' field might appear more than once. So we can collapse in clinical/biospecimen faceting (which only ever has one entry per PatientID), but we'll need to use grouping in TCIA Images (which will have many). I'll merge in this change later today, after I've tested it some. Note this means on the 'ORIGINAL' tab, the case counts will NOT add up to the total, due to case entry overlap (i.e., you'll see 259 MR, 13 CT, and 1 DX for GBM).

**Comment by fedorov** [comment]
It will not be uncommon for a subject to have multiple modalities, either within the same or across different studies.

Maybe we should have different modes to choose between showing counts of patients vs counts of studies that meet the criteria. I think both modes might be useful. I need to think more about this.

**Comment by s-paquette** [comment]
Right--this comes up in ISB-CGC a lot, since for example a given PatientID might be linked to numerous kinds of file, or have several entries in mutation data.

A toggle wouldn't be a half-bad idea; we can pre-compute the facets, and flip what displays based on the user's preference.

**Comment by s-paquette** [comment]
Okay, I've deployed a new version of the WebApp which will now count the unique Patient IDs in a given facet value - so you'll see '13 cases' for CT under GBM, for example. We can think about what this means, long term.

Note, the case count next to the collection selector is still wrong; I need to sort out the easiest way to make that happen without a separate call, if possible. Still looking into it.

**Comment by s-paquette** [comment]
The total cases will now also appear accurate. We'll be mimicking how TCIA does it.

Them:
![image](https://user-images.githubusercontent.com/8442808/77797402-3ba99f00-702e-11ea-8a06-208be54d576c.png)

Us:
![image](https://user-images.githubusercontent.com/8442808/77797572-89bea280-702e-11ea-97c3-02152a2f7e3e.png)
