### ISSUE TITLE
Long filter name will display text going off the page on test tier cohort filter dropdown

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#653]
On the cohort details page for the test tier, with very long cohort filter list present the end user will see long text appear. 

<img width="1306" alt="Screen Shot 2021-06-10 at 12 49 16 PM" src="https://user-images.githubusercontent.com/16824894/121582517-1c155100-c9fd-11eb-99db-4c53818b01cc.png">

**Comment by G-White-ISB** [comment]
This was because the filter was being displayed with no spaces (just commas) between filter attributes. Spaces have been added allowing text to break and line wrap at words

**Comment by pgundluru** [comment]
This issue is back in the cohort details page 
![image](https://user-images.githubusercontent.com/85526819/130669117-5e3f9817-2853-43be-ba92-cbfa140d5059.png)

**Comment by G-White-ISB** [comment]
Thought this was fixed. I wonder if there was a code reversion. Its still fixed in my local branch

**Comment by G-White-ISB** [comment]
Just submitted a pull request that should resolve the issue
