### ISSUE TITLE
Check all should be de-selected when user navigates to antoher page on cohort list page

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#654]
On the testing tier, for the cohort list page after the user checks the select all button then navigates to the last page. The checkbox should be de-selected. 

<img width="1334" alt="Screen Shot 2021-06-10 at 3 10 46 PM" src="https://user-images.githubusercontent.com/16824894/121583432-3bf94480-c9fe-11eb-9d53-03b760e24233.png">

**Comment by s-paquette** [comment]
Selection of multiple cohorts for actions was removed, so this ticket is moot.
