### ISSUE TITLE
Exporting a manifest with BMI 'None' causes an error

### ISSUE THREAD

**Issue by s-paquette** [ImagingDataCommons/IDC-WebApp#656]
Traceback (most recent call last):
  File "/app/IDC-Common/cohorts/views/views.py", line 926, in create_manifest_bq_table
    base_filters['bmi_btw'].append(BMI_MAPPING[val])
KeyError: 'None'

**Comment by pgundluru** [comment]
Test 1 : 
Select all collections and select all BMI filters in related tab 
Result - Fails to upload to BQ 

Test 2 : 
Select TCGA collections and select all BMI filters in related tab 
Result - Fails 

Test 3 :
Select TCGA collections and select one BMI filter in related tab (I selected overweight BMI )
Result - Success 

Test 4 : 
Select TCGA collections and select one BMI filter in related tab (I selected normal BMI )
Result - Success 

Test 5 : 
Select TCGA collections and select one BMI filter in related tab (I selected underweight BMI )
Result - Success 

Test 6 :
Select TCGA collections and select one BMI filter in related tab (I selected obese BMI )
Result - Success 

Test 7 :
Select TCGA collections and select one BMI filter in related tab (I selected None BMI )
Result - Success 

Note - i have tried selecting TCGA collections and filtering by each option in BMI tab to isolate the issue where the filters with BMI selected are failing.

**Comment by s-paquette** [comment]
@pgundluru Okay, this was being confounded by an error in the new data version. So, now that I've fixed THAT, can you run these tests again.

**Comment by pgundluru** [comment]
Testing results:

Test 1 :
Select all collections and select all BMI filters in related tab
Result - Fails to upload to BQ

Test 2 :
Select TCGA collections and select all BMI filters in related tab
Result - Fails

Test 3 :
Select TCGA collections and select one BMI filter in related tab (I selected overweight BMI )
Result - Success

Test 4 :
Select TCGA collections and select one BMI filter in related tab (I selected normal BMI )
Result - Success

Test 5 :
Select one TCGA collection BLCA and select one BMI filter in related tab (I selected normal BMI )
Result - Success

Test 6 :
Testing results:
Select TCGA collections and select one BMI filter in related tab (I selected underweight BMI )
Result - Success

Test 7 :
Select TCGA collections and select one BMI filter in related tab (I selected obese BMI )
Result - Success

Test 8 :
Select TCGA collections and select one BMI filter in related tab (I selected None BMI )
Result - Success

Test 9 : 
Select multiple TCGA and BMI cohorts and try to upload to BQ 
Result - Success

**Comment by pgundluru** [comment]
Testing results in new build test tier and v7 data version. 

Test 1 :
Select all collections and select all BMI filters in related tab
Result - Success 

Test 2 :
Select TCGA collections and select all BMI filters in related tab
Result - success

Test 3 :
Select TCGA collections and select one BMI filter in related tab (I selected overweight BMI )
Result - Success

Test 4 :
Select TCGA collections and select one BMI filter in related tab (I selected normal BMI )
Result - Success

Test 5 :
Select one TCGA collection BLCA and select one BMI filter in related tab (I selected normal BMI )
Result - Success

Test 6 :
Testing results:
Select TCGA collections and select one BMI filter in related tab (I selected underweight BMI )
Result - Success

Test 7 :
Select TCGA collections and select one BMI filter in related tab (I selected obese BMI )
Result - Success

Test 8 :
Select TCGA collections and select one BMI filter in related tab (I selected None BMI )
Result - Success

Test 9 :
Select multiple TCGA and BMI cohorts and try to upload to BQ
Result - Success
