### ISSUE TITLE
Page selection buttons are jumping around (again)

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#663]
This is what I see in the test tier:

![2021-06-10_23-48-20](https://user-images.githubusercontent.com/313942/121628154-b3eb5d00-ca46-11eb-8d45-69bafe702099.gif)

**Comment by G-White-ISB** [comment]
The  'page number' buttons in between 'previous' and 'next' can change. They can also change size in going say from 1 digit to 3 digit numbers. So unless the 'previous' and 'next' buttons are initially placed far apart, 'next' may be compelled to move out of the way. I've adjusted the formatting of these buttons to reduce the times this might occur, assuming the user has a reasonably wide browser screen

**Comment by fedorov** [comment]
I tested this with a wide browser window, I do not think that issue was because of narrow size. As you can see in the screenshot, there is a huge empty space added after "Previous" at one point. 

Can we learn something from the GDC Portal?

![2021-06-18_16-12-07](https://user-images.githubusercontent.com/313942/122612012-5d86ab80-d050-11eb-8cee-5b5ca542583c.gif)

**Comment by pgundluru** [comment]
This was tested successfully on 8-17 on chrome, edge and firefox

**Comment by s-paquette** [comment]
@pgundluru Is this one still not working? I see the label was added and removed.

**Comment by pgundluru** [comment]
This is resolved in release 23
