### ISSUE TITLE
Test Report for sprint 21 code freeze generated 

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#665]
Results can be found here, https://app.qase.io/public/report/60fd88cedfdbb28eba23104e8f3f4821762cd362

Click the failed button to see comment related to issue. Most tickets that are marked as failed are known issues, test cases that are blocked either the test query or the test suite needs to be created during the next sprint.

**Comment by G-White-ISB** [comment]
Hi Madelyn,

Is there a way to see a description of the test or a related movie.
George

**Comment by madelyngreyes** [comment]
Hello,

I have begun to add test steps to cases that need more detail. Any test scenarios that don't make sense to you please point it out to me and I can update it as needed.

Thank you
Madelyn
________________________________

**Comment by madelyngreyes** [comment]
Will also add descriptions to test cases for further clarification.
