### ISSUE TITLE
SeriesNumber is always 'None'

### ISSUE THREAD

**Issue by G-White-ISB** [ImagingDataCommons/IDC-WebApp#671]
In the Series table, the SeriesNumber is always reported as 'None'.

**Comment by G-White-ISB** [comment]
Debugging this locally the server seems to make  the right request of the Solr core but the 'SeriesNumber' field is missing from the returned docs. Checking the Solr core itself it seems the SeriesNumber field is missing

**Comment by s-paquette** [comment]
Hmmm wonder how that got dropped. As long as it's otherwise in the schema it's a quick fix, I'll have a look.

**Comment by s-paquette** [comment]
This was indeed just an error in making the indicies. Fixed now on dev and production, will do test eventually.
