### ISSUE TITLE
UID tooltip is 'interactive' ie will remain open for selection and copying of text

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#674]
We currently show portions of UIDs in the lists, and full UIDs in tooltips but they are really not usable, given the length and obscurity. If we had a button to copy those to clipboard, it would be possible to use them, for example for selecting UIDs that correspond to interesting studies/series.

![image](https://user-images.githubusercontent.com/313942/122770500-81760700-d273-11eb-86e5-a4c0b08b23f8.png)

**Comment by G-White-ISB** [comment]
Rather than adding a button, if the tooltip stays open when you hover into the tooltip (like the pie chart tooltip) the users can copy it directly

**Comment by fedorov** [comment]
>  if the tooltip stays open when you hover into the tooltip (like the pie chart tooltip) the users can copy it directly

This would be fine. How difficult is it to implement?

**Comment by pgundluru** [comment]
UID Tooltip remains after I move the mouse enabling copy paste for both studies and series level
