### ISSUE TITLE
"Sc" should be "Secondary Capture"

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#675]
I have no idea where this is mapped, but it should be.

![image](https://user-images.githubusercontent.com/313942/122778832-52639380-d27b-11eb-8d4d-992eb309d1d5.png)

**Comment by s-paquette** [comment]
@fedorov @bcli4d 

This is what I'm getting from the BQ table--where does the change need to be made? We can either add a display value for this (so it's still SC in DICOM/BQ but is 'Secondary Capture' in display) or we need to adjust the BQ tables.

**Comment by bcli4d** [comment]
The Modality values in dicom_metadata/dicom_all are all uppercase abbreviations:
1 | CR |  
2 | CT |  
3 | CTPT |  
4 | DX |  
5 | FUSION |  
6 | KO |  
7 | MG |  
8 | MR |  
9 | NM |  
10 | OT |  
11 | PR |  
12 | PT |  
13 | REG |  
14 | RF |  
15 | RTDOSE |  
16 | RTPLAN |  
17 | RTSTRUCT |  
18 | RWV |  
19 | SC |  
20 | SEG |  
21 | SR |  
22 | US |  
23 | XA

**Comment by s-paquette** [comment]
Ah, I see what it is--we did in fact put in Display Values for these. Adding in SC -> Secondary Capture, should show up on Production in the next release.

**Comment by fedorov** [comment]
As it turns out, SC is not an allowed defined value for Modality attribute, I believe the complete list is here: http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.7.3.html#sect_C.7.3.1.1.1. We may want not to dis-ambiguate it, as we don't dis-ambiguate CTPT. @dclunie what do you recommend?

**Comment by dclunie** [comment]
It may not be defined by the standard, but if it occurs it should display something sensible.

**Comment by fedorov** [comment]
I do not think we should get into dis-ambiguating defined values that are not defined by the standard, because it will set wrong expectations for our users. This gets into the area of data harmonization, which we are not doing right now. Note that we do show "Object class" tab, and SC is mentioned and disambiguated there. 

![image](https://user-images.githubusercontent.com/313942/126811578-611ff259-2691-4d50-924e-07bf45029425.png)
