### ISSUE TITLE
Revisions to the portal as requested by NCI Communications

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#678]
The below was communicated via @ulrikew. We should be using PDC as a template for the below changes.

The linkback bar is blue now - this banner is created and pushed at the NCI level, so the design is set beyond our control. We should revert that change so that the banner looks more similar to the creme banner on the PDC. 

![image](https://user-images.githubusercontent.com/313942/124270868-c0754980-db0a-11eb-90f0-131ea7684576.png)

the footer isn't configured to NCI standards - NCI has been moving to a standardized footer for NCI web apps and informational websites. Currently, the PDC has the most up-to-date footer for web apps with the information that we should limit the content to. That does cut down on the information in the footer currently, but if there's a place in the gitbook to share about information that is probably the best place to do it. At the very least, we should remove the social icons as they just link back to the homepage (for example the youtube link just reloads the page). 

![image](https://user-images.githubusercontent.com/313942/124270964-daaf2780-db0a-11eb-8a39-3b11ce115aaf.png)

**Comment by fedorov** [comment]
Should also remove the linkout icon for the NCI Data Commons banner on top of the IDC screen.

**Comment by s-paquette** [comment]
@fedorov @ulrikew These changes are now live on the dev server, and will be built on test shortly. (As they're all visible from the dev server home page you can have a look there, if you want.)

**Comment by fedorov** [comment]
@s-paquette @G-White-ISB note that the NCI link on the top banner is not bolded neither in CRDC nor in PDC:

![image](https://user-images.githubusercontent.com/313942/129959127-4d51c8e9-5b85-472e-ad05-e2377adcdb0f.png)

![image](https://user-images.githubusercontent.com/313942/129959190-c289fc6b-7848-4d85-bf81-9f04f61f954f.png)

No urgency, but I think we should make it look similar to those other components.

Mind you - I most definitely preferred the appearance of the banner the way it used to be on IDC, but it's not my preference that matters here ...

**Comment by pgundluru** [comment]
Link out button removed, social icons removed

**Comment by pgundluru** [comment]
Bottom Footer has 0 TB data instead of 5.66 TB like production

**Comment by s-paquette** [comment]
@pgundluru The volume size isn't part of this ticket (it's a separate issue) so if this ticket has otherwise passed you can mark it as such and close it. This ticket is only about changes requested by NCI Comm.
