### ISSUE TITLE
The collective size of all instances in a cohort should be listed on exports

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#679]
**Enhancement description**

Once the cohort is defined, the next step is downloading of the cohort on a VM. In order to do this, while controlling VM costs, it is important to know how much disk space is needed to replicate the files corresponding to the cohort. We already have the size of each file in BQ, but this functionality is not available to the user in the portal. I suggest adding the size in MB or GB as a column to the list of cohorts under user space in the IDC portal.

**Comment by fedorov** [comment]
In the meantime, I added the size of the selection to the DataStudio cohort dashboard template here: https://datastudio.google.com/reporting/ab96379c-e134-414f-8996-188e678f1b70/page/KHtxB/preview

![image](https://user-images.githubusercontent.com/313942/124991241-63e4c380-e00f-11eb-9b6f-9c776de29e5e.png)

**Comment by fedorov** [comment]
@s-paquette @G-White-ISB @wlongabaugh any comments on this issue? Do you agree it is important? What is the effort to prioritize it?

**Comment by s-paquette** [comment]
@fedorov We discussed this today and a large issue is what to base the calculation on. We have another request to allow cohorts to be series or study or instance level in terms of filtering. While study and series sizes could be calculated and stored into the Solr cores, instance sizes can't as we have no instance-level search. So if a cohort is instance-level filtered, it won't have accurate size information unless we want to send out a request to the BQ tables, and that operation will take several seconds to half a minute.

Given this, how would we handle the eventual allowance for instance-level cohorts?

**Comment by fedorov** [comment]
I would separate the topic of the need for this functionality, and what it should provide from the topic of how it should be implemented.

On the topic of the functionality, it seems pretty clear to me. If the cohort is defined at the level of series or studies, then we assume that everything below the series or study level in the hierarchy is included while estimating the disk size. If the cohort is instance-level, we sum selected instances.

> eventual allowance for instance-level cohorts

Last time I checked, we already support instance level cohorts in BQ export. I am not sure what you mean.

**Comment by s-paquette** [comment]
@fedorov The reason implementation comes into it is we don't have instance-level information in Solr, only in BQ. We would be unable to obtain the sum of the instances without a call to BQ, and right now the WebApp doesn't use BQ due to lack of responsiveness. This means, for instance-level cohorts, we can't provide those numbers in the WebApp, only at export time.

**Comment by fedorov** [comment]
Numbers at export time would be a reasonable compromise.

**Comment by s-paquette** [comment]
@fedorov Got it--I'm going to retitle the ticket so it reflects that.

**Comment by s-paquette** [comment]
We can potentially offer this on Study/Series manifests as well as Instance manifests if we add in a 'size_on_disk' column to the Solr indicies which tallies the instance numbers from BQ.

**Comment by s-paquette** [comment]
This will require adding `instance_size` to the WebApp as an attribute. We won't expose it on the UI, but that will make it possible to request in general for information. Solr cores will have summed values for studies and series.

**Comment by fedorov** [comment]
Now that we can download the cohort, we should prioritize this feature @s-paquette!

**Comment by s-paquette** [comment]
Will want to make a query to run during index source table generation which calculates series and study instance_size aggregates for easier JOINing into the main aggregator, rather than aggregating at index build time (because that slows down index creation enormously).

**Comment by s-paquette** [comment]
Round to Gigabytes, or Terabytes if applicable

**Comment by fedorov** [comment]
Per discussion today, there was a misunderstanding of the feature, and we will initially add the cohort size into the exported manifest header.

**Comment by pgundluru** [comment]
![image](https://github.com/ImagingDataCommons/IDC-WebApp/assets/85526819/937b2748-3d48-4f2b-8689-786f37348c1d)

**Comment by s-paquette** [comment]
@pgundluru 
>Disk size is not visible in the cohorts page as expected
I see it on the cohorts page you have there in your screenshot--by 'cohorts' do you mean the details page? If so that's still to be done.

**Comment by pgundluru** [comment]
> @pgundluru
> 
> > Disk size is not visible in the cohorts page as expected
> 
> I see it on the cohorts page you have there in your screenshot--by 'cohorts' do you mean the details page? If so that's still to be done.

Yes i meant to comment that i see it, I will mark this ticket as testing passed Thank You,

**Comment by pgundluru** [comment]
Able to see the disk size of cohort in explore page when a cohort is created
