### ISSUE TITLE
In the exploration page - search scope - collections list can be ordered to match the other filters in search configuration 

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#680]
![image](https://user-images.githubusercontent.com/85526819/125095491-3a28ac80-e0a2-11eb-8618-7f65d94403ad.png)

**Comment by s-paquette** [comment]
@pgundluru Just to clarify, you mean the 'Sort by Alpha/Num' option on the other facets should be available here as well.

**Comment by pgundluru** [comment]
This issue came up in a meeting with Bill and Andrey and I will check with them to confirm.

**Comment by s-paquette** [comment]
@pgundluru Pretty sure this has been addressed. Can we close it?

**Comment by pgundluru** [comment]
Yes this can be closed
