### ISSUE TITLE
Patient counts for analysis results collections are incorrect

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#682]
As reported by @ulrikew, all analysis results collections show 31 as the number of patients, which is incorrect. As an example, LIDC-IDRI analysis collection with DOI 10.7937/TCIA.2018.h7umfurq has 875 patients.

![image](https://user-images.githubusercontent.com/313942/126672634-b555b710-a9e9-4c04-9102-3f331f2746fa.png)

**Comment by s-paquette** [comment]
This is truly odd and I have to admit I'm not even sure how it happened, as these numbers come straight out of BQ. Fortunately, an easy fix, and done.

**Comment by s-paquette** [comment]
@fedorov @pgundluru This needs to be tested still.

**Comment by s-paquette** [comment]
@pgundluru @fedorov Can this be confirmed and closed? The query at the top is how to confirm the counts expected in this table.

**Comment by s-paquette** [comment]
@pgundluru @fedorov I'm going to remove this one from any Release Milestones until we can work out how this should be handled.

**Comment by pgundluru** [comment]
Thank you, I will reach out to Andrey to validate this ticket as I am not seeing consistent results to mark this issue as passed.

**Comment by s-paquette** [comment]
Now that we have analysis result ID filtering, can we test this one formally? Clicking on the analysis result name in the collections table now actually selects those specific items--though, note, we select and count at the *study* level, which may produce slightly discordant numbers.

**Comment by pgundluru** [comment]
Test for checking Analysis results collections on a study level on test tier. Query with results for each analysis collection below

Glioma SEG - 167 Cases, 168 Studies, and 3535 Series in this cohort
![image](https://user-images.githubusercontent.com/85526819/168665956-3ad058a3-03a9-4977-9f24-0a0247328e55.png)

DICOM-LIDC-IDRI-Nodules - 875 Cases, 883 Studies, and 14691 Series in this cohort
![image](https://user-images.githubusercontent.com/85526819/168666171-a29ed23b-df2f-40d5-8548-72dee727383e.png)

DICOM-SR-Breast-Clinical - 474 Cases, 1286 Studies, and 15046 Series in this cohort
![image](https://user-images.githubusercontent.com/85526819/168666418-4ffad7a5-38fa-4699-871a-65e896b097a0.png)

PROSTATEx-Seg-HiRes - 66 Cases, 66 Studies, and 3617 Series in this cohort 
![image](https://user-images.githubusercontent.com/85526819/168666636-d6560888-ef30-405f-aceb-42fffb87dab3.png)

PROSTATEx-Seg-Zones - 98 Cases, 98 Studies, and 5308 Series in this cohort
![image](https://user-images.githubusercontent.com/85526819/168666838-ad9839a8-c601-44ad-aa4e-d6fb5cf62181.png)


QIN-LungCT-Seg - 31 Cases, 31 Studies, and 533 Series in this cohort
![image](https://user-images.githubusercontent.com/85526819/168667000-541798d3-0b00-45d5-aae5-efcf2fdb92a7.png)


RIDER-LungCT-Seg - 31 Cases, 43 Studies, and 268 Series in this cohort
![image](https://user-images.githubusercontent.com/85526819/168667175-1d86e77b-deec-405b-940f-8077d30371c0.png)
