### ISSUE TITLE
Link to Proxy Policy on Quota Page

### ISSUE THREAD

**Issue by wlongabaugh** [ImagingDataCommons/IDC-WebApp#686]
We now have a proxy policy page in the docs at https://learn.canceridc.dev/portal/proxy-policy. We need to add a link to this on the quota page that is displayed when users hit the quota.

**Comment by G-White-ISB** [comment]
How can 'consistently downloading to a level just under the quota for an extended stretch of time' be a violation of the proxy policy? ' That's too slippery. Why not have a yearly or monthly limit on top of the daily limit?

**Comment by s-paquette** [comment]
@wlongabaugh This is ready for testing.

**Comment by s-paquette** [comment]
@wlongabaugh Was this done?

**Comment by wlongabaugh** [comment]
Yes, this is done.

**Comment by wlongabaugh** [comment]
It is already in production. You can go directly to https://portal.imaging.datacommons.cancer.gov/quota/index.html
