### ISSUE TITLE
Formatting text in the front page tabs

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#705]
I am getting this issue on mac:

![image](https://user-images.githubusercontent.com/313942/129768573-6327c5f9-20ca-45c3-b72f-5e322fe20ff4.png)

![image](https://user-images.githubusercontent.com/313942/129768487-261e17fa-f1b8-4b8f-b862-ca6100e02b15.png)

**Comment by s-paquette** [comment]
Per discussion with Andrey and Bill's suggestion, reverted to the former style:

![image](https://user-images.githubusercontent.com/8442808/129785567-1451e391-1e32-4b82-8927-dad3552f3ca9.png)

This will be easier to maintain, long-term.

**Comment by pgundluru** [comment]
Tested view on Mac, Windows
