### ISSUE TITLE
Chart formatting issues

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#71]
There is no spacing between the text, "Body Part Examined". 

![Screen Shot 2020-03-30 at 3 32 07 PM](https://user-images.githubusercontent.com/16824894/77953846-baefda80-729b-11ea-97e1-02990b25ebd9.png)

- [x] Spacing added 

Underscores present in the title of the bar graph e.g., disease_code and title name are lowercase.

![Screen Shot 2020-03-30 at 3 38 01 PM](https://user-images.githubusercontent.com/16824894/77955799-d4465600-729e-11ea-9f66-1a0ed512892f.png)

- [x]  Remove underscores
- [x] Capitalize title 

The x-axis values titles overlap for the Body Parts Examined chart.

![Screen Shot 2020-03-30 at 3 47 35 PM](https://user-images.githubusercontent.com/16824894/77955252-db209900-729d-11ea-8724-ac6f3bec489c.png)

- [x]  Spacing added

Text cut off under the Related for the BMI chart and BMI is displayed in lowercase format. 

![Screen Shot 2020-03-30 at 3 50 24 PM](https://user-images.githubusercontent.com/16824894/77955650-8df0f700-729e-11ea-83d2-a200f48fa626.png)

- [ ] Full text displayed
- [x] Title changed to BMI

**Comment by s-paquette** [comment]
Note that the the proper capitalization/spacing/etc. is all available from the back-end, and we should use the methods provided by the Attribute_Display_Values ORM to handle this.

**Comment by fedorov** [comment]
"ORM" = ?

IMHO, we should use the mapping from keyword to name as defined in this table: 	
`idc-sandbox-000:DICOM_2019e.attributes`.

**Comment by s-paquette** [comment]
Object Role Model, i.e. the Django class that describes the Attribute_Display_Values table, which is where we store the various display values for anything that has special considerations beyond '_ becomes a space and Title Case it'.  There's a lot of this in the related clinical data, like tobacco smoking history or sample type. The idea is we don't want to store a complete list of possible attribute values and display settings--that can get unwieldy and ugly--but we do want to store any attributes whose recorded values don't match their display value. We can definitely source anything that doesn't confirm to '_ becomes a space and Title Case' from that table.

**Comment by madelyngreyes** [comment]
There seems to still be some text-cut off when hovering over certain project name filter options in the search results panel related tab. 

![Screen Shot 2020-05-20 at 12 58 16 PM](https://user-images.githubusercontent.com/16824894/82475582-b6c18b80-9a9a-11ea-9c6a-82277d1b5607.png)

**Comment by madelyngreyes** [comment]
Also when using the Add Labels? functionality, it's very difficult to read the text and there is text overlap for the filter, "Computed Tomography". 

![Screen Shot 2020-05-20 at 2 21 12 PM](https://user-images.githubusercontent.com/16824894/82483021-b1b60980-9aa5-11ea-8dae-4fa9e335a409.png)

**Comment by madelyngreyes** [comment]
Also, all text should be facing the same direction inside the chart e.g., Kidney and Headneck in the Body Part Examined chart, the text appears to have two different placement formats that were implemented. 

![Screen Shot 2020-05-20 at 2 29 29 PM](https://user-images.githubusercontent.com/16824894/82483432-63553a80-9aa6-11ea-941f-ba337cc1dcec.png)

**Comment by madelyngreyes** [comment]
The bar chart type text format has improved since the last test iteration but, there is still some text cut off for certain variables in the x-axis e.g., project short name TCGA-BLCA the CA is cut off. 

![Screen Shot 2020-05-20 at 2 32 10 PM](https://user-images.githubusercontent.com/16824894/82483806-05752280-9aa7-11ea-97c9-ac4c87537a24.png)

**Comment by madelyngreyes** [comment]
@G-White-ISB Hello, I noticed a ton of improvements to the display of the text in the Search Results panel. 

There is still some text cut off in the project name pie chart.
![Screen Shot 2020-05-28 at 11 39 20 AM](https://user-images.githubusercontent.com/16824894/83163570-2fe36300-a0d9-11ea-8b7b-c38ba076d40b.png)

Also, with the Modality pie chart.

![Screen Shot 2020-05-28 at 11 38 39 AM](https://user-images.githubusercontent.com/16824894/83163654-47225080-a0d9-11ea-8c41-6e68844efe3e.png)

**Comment by fedorov** [comment]
In the current idc-testing, labels do not show up at all

![image](https://user-images.githubusercontent.com/313942/87701305-c4775280-c765-11ea-8caa-7fff3799a450.png)

**Comment by madelyngreyes** [comment]
For the Derived tab, under the Quantitative Analysis tab there is text cut-off for the pie chart/bar chart title.

<img width="647" alt="text cut off - quantitative analysis" src="https://user-images.githubusercontent.com/16824894/90263775-1e7b3e80-de1e-11ea-8575-b19ce51c9436.PNG">

**Comment by G-White-ISB** [comment]
testing needed. Build: dev.010920201029.e06ce4

**Comment by madelyngreyes** [comment]
Looks so much better! 

But, unfortunately I seem to be running into a zoom setting issue again. For the browsers Google Chrome and Firefox at 80-100% zoom there is some text overlap for the filter options, Standardized Added Metabolic Activity (Gram) and Standardized Added Metabolic Activity Background (Standardized Uptake Value body weight). 

<img width="960" alt="2020-09-01 (3)" src="https://user-images.githubusercontent.com/16824894/91907227-72d44a00-ec77-11ea-8611-129ccb7b7f5f.png">


Another small detail is the pie charts don't seem to be aligned vertically for the Derived tab, Qualitative Analysis filter selection in the Search Results panel. 
<img width="960" alt="2020-09-01 (4)" src="https://user-images.githubusercontent.com/16824894/91907429-d8283b00-ec77-11ea-9f86-d69ad3de9ec5.png">

**Comment by madelyngreyes** [comment]
Also, now when no data is available the pie charts appear as blank. 

<img width="960" alt="2020-09-02 (6)" src="https://user-images.githubusercontent.com/16824894/92026340-de2d2300-ed2e-11ea-9795-bf7292189cd7.png">

**Comment by G-White-ISB** [comment]
Charts are now centered in the containing div. 'No data available' added.

**Comment by madelyngreyes** [comment]
Formatting looks much better. 

<img width="960" alt="2020-09-14 (17)" src="https://user-images.githubusercontent.com/16824894/93125221-ccd20800-f698-11ea-9dc8-47982b1afcd6.png">
