### ISSUE TITLE
Unable to export a cohort from an earlier data version

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#711]
![image](https://user-images.githubusercontent.com/313942/130139306-01549f2d-91c6-4fa9-b9b2-9a11359cb57d.png)

![image](https://user-images.githubusercontent.com/313942/130139337-bd5b741d-451f-4407-bdf4-1148f96b1ad1.png)

@pgundluru can you please add checking export of earlier version cohort to your

**Comment by s-paquette** [comment]
Ah ha. So, this is the problem renaming the columns--now we need to track TWO different column names. Or, I can remake the old pivot to use the new names, though the underlying tables won't have them, so it'll be a re-structuring.

Alternative is I make brand new attributes with the new names, and associate those to the new Solr cores/BQ tables. Thoughts?

**Comment by fedorov** [comment]
How about reverting back to the old names? I don't see any major issue with that. What do you think @bcli4d?

**Comment by bcli4d** [comment]
I can make such changes fairly easily, but I think @s-paquette needs to tell us whether doing so will slow down the release.

**Comment by fedorov** [comment]
I can reproduce this issue in the test tier.

![2021-09-16_22-10-51](https://user-images.githubusercontent.com/313942/133713109-ca81a3d8-e4a2-4d46-a0c1-4417fb5009ee.gif)

**Comment by s-paquette** [comment]
@pgundluru Ready for re-testing. Please be sure to indicate the filters of the cohort you can't export if you get another failure. @fedorov If you could try it again as well that would help.

**Comment by fedorov** [comment]
I tested this earlier today, both for v1 and v2 cohorts export, and did not see any issues!

**Comment by pgundluru** [comment]
Thank You Suzanne and Andrey. I was able to test this issue successfully for v1,v2,v3 data versions with no issues.

**Comment by pgundluru** [comment]
In prod i am able to export earlier versions of data. Tried it with V2 and V3
