### ISSUE TITLE
Explore image data selected series panel returns no results

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#72]
On the Explore image data page after selecting a collection, then a selected study no options appear for the selected series panel. 

If you open the DEV console you are returned a, "500 (Internal Server Error)" error when a selecting a studies option. 

![selected series panel broken](https://user-images.githubusercontent.com/16824894/78054306-db796c80-734f-11ea-874a-c464a2eb3c91.PNG)

**Comment by madelyngreyes** [comment]
From @G-White-ISB,  related to query_solr_and_format_result is no longer returning the SeriesNumber in the 'docs' even when SeriesNumber is included in fields and counts_only is false. This leads to an error when trying to populate the Series table.

**Comment by G-White-ISB** [comment]
SeriesNumber is not part of the tcia_fields list sourced from DataSource.objects.get(name="tcia_images")

**Comment by s-paquette** [comment]
@madelyngreyes @G-White-ISB Give it another shot? This should be sorted.

**Comment by G-White-ISB** [comment]
Yup, its working again at least in my quick tests. Thanks

**Comment by madelyngreyes** [comment]
Yes, it's also working for me as well.

**Comment by s-paquette** [comment]
@madelyngreyes Feel free to mark this as testing passed and close it on out.
