### ISSUE TITLE
New Attributes: Manufacturer, ManufacturerModelName, SliceThickness

### ISSUE THREAD

**Issue by s-paquette** [ImagingDataCommons/IDC-WebApp#723]
Add the following attributes:

**Original**
Manufacturer
manufacturer model name
Slice thickness
Study date

**To be added**
License

**Comment by s-paquette** [comment]
Some items about this:
- We need the units for SliceThickness. @bcli4d ? It's also being ETL'd as a string/text which is a problem since it contains both integers and floats. It should be set to NUMERIC in BQ, preferably, though this is a cast potentially which might make things ugly. @fedorov Did you want us to do this?
- Set Manufacturer and Model Name to 'preformatted' which means we will do nothing with the values, they just display as-is

**Comment by fedorov** [comment]
> We need the units for SliceThickness. @bcli4d ? It's also being ETL'd as a string/text which is a problem since it contains both integers and floats. It should be set to NUMERIC in BQ, preferably, though this is a cast potentially which might make things ugly. @fedorov Did you want us to do this?

I think we should leave SliceThickness as is, and maybe later provide a separate view where we may cast certain fields to make them more usable. But casting in the UI to float, but having string in the actual data will be misleading.

> Set Manufacturer and Model Name to 'preformatted' which means we will do nothing with the values, they just display as-is

Yes.

**Comment by fedorov** [comment]
I had a chance to discuss this with @dclunie today, and we agreed on the following approach. We keep the original values in BQ, but introduce a "harmonized" version of SliceThickness (in this case, safe cast to float64) into a separate view (not unlike we do for the segmentations and measurements views), so it is clearly marked to the users as the different from the original data. Then Solr/webapp would ingest the harmonized value.

I understand if this is too much to do for the production release this month. We can postpone until after. Let me know.

If we go ahead, need to establish a convention for how to mark things. For example, we could have a view called `dicom_curated`, and inside that view either mark attributes that were cast to numeric type with the suffix `_FLOAT64`, or keep the attribute name unchanged, and the cast would be implied by "curated".

Thoughts?

**Comment by pieper** [comment]
There are several other derived properties that could be helpful so if we are running a script over all the data we may want to consider also recording if all the orientations are the same in a series, if there is variable spacing, etc.  We can't handle all cases but there are some common things that would be good to be able to access quickly.

**Comment by G-White-ISB** [comment]
I assume in the web app we would filter on slide thickness using a slider, as per other quantitative attributes?

**Comment by s-paquette** [comment]
@G-White-ISB If we put it in as a string we can't do that. Hence the idea of making a view which casts. @fedorov What should we do for production?

The rest of these attributes are all available on dev now.

**Comment by fedorov** [comment]
>  @fedorov What should we do for production?

@s-paquette I discussed [above](https://github.com/ImagingDataCommons/IDC-WebApp/issues/723#issuecomment-917039637) what we should do, in my opinion, and based on discussions with David C, but I do not have a good idea about the effort needed to do it. Please let me know if you think this can or should be done for production or not.

> The rest of these attributes are all available on dev now.

I do not see yet the StudyDate. Is it supposed to be there?

**Comment by s-paquette** [comment]
@fedorov For StudyDate we need to implement some sort of widget to work with it, I think George is still looking into that. For the harmonized view, who will be producing this, and when can I expect it?

**Comment by fedorov** [comment]
@s-paquette the harmonized view at the moment will have just one column. I expect that @bcli4d would need to fold this into the ETL and include into the public dataset. In the subsequent releases we would be adding more columns. Unless I am missing something, there should not be too much effort to add this harmonized view to the public dataset. We can discuss tomorrow.

```sql
SELECT
  SOPInstanceUID,
  SAFE_CAST(SliceThickness AS FLOAT64) AS SliceThickness_FLOAT64
FROM
  `canceridc-data.idc_current.dicom_all`
```

**Comment by bcli4d** [comment]
@fedorov what do you me to name this new view?

**Comment by fedorov** [comment]
@bcli4d following the discussion today, let's use `dicom_curated` as the name for this view. 

I believe @wlongabaugh suggested to add suffix `_curated` to the individual attributes, but maybe this is redundant, since all attributes in this view will be curated. I suggest we keep individual attribute names "as is". If we have more than one approach to curate a given attribute, we can revisit this decision at that time.

**Comment by s-paquette** [comment]
That works best for my purposes.

**Comment by bcli4d** [comment]
Provisionally naming the view `dicom_metadata_curated`.

**Comment by bcli4d** [comment]
The new view is in idc_v4.

**Comment by bcli4d** [comment]
I missed that you suggested dicom_curated. Will regen after next meeting.

**Comment by fedorov** [comment]
`dicom_metadata_curated` is fine with me!

**Comment by bcli4d** [comment]
OK. I'll leave it at dicom_metadata_curated.

**Comment by fedorov** [comment]
StudyDate will need to be postponed.

**Comment by pgundluru** [comment]
Manufacture and Model name are included in available filters on prod.
