### ISSUE TITLE
Refinement of the filter category search/configuration appearance

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#725]
Can we use the appearance of the MIDRC search portal as inspiration for refining IDC UI? What I see there is a lot more compact and appealing than what we have.

![image](https://user-images.githubusercontent.com/313942/131870105-6f078b36-2187-4115-bd90-4c4dc64a1bd4.png)

clicking search lens gives this

![image](https://user-images.githubusercontent.com/313942/131870146-9cff2b5d-accb-4912-8d9d-8d6111e68c81.png)

gear icon gives this

![image](https://user-images.githubusercontent.com/313942/131870182-24b719bc-03b4-4f63-9f6e-78fbe99a10cb.png)

this is from https://data.midrc.org/explorer

**Comment by fedorov** [comment]
Can we please insert space between the gear and magnifying glass icons?

![image](https://user-images.githubusercontent.com/313942/142967268-4aaa735b-400a-43dd-a8a0-7598f4010f28.png)

**Comment by s-paquette** [comment]
@fedorov I did a bit of this earlier today; if you have a look at dev (it's not on test yet) you can see it, along with a couple of other small adjustments (hover text on the icons, no size jump on the search box/sort button flip).

**Comment by fedorov** [comment]
Thanks, this is much better! I will comment on search boxes in #800.

This can be resolved once testing is successful.
