### ISSUE TITLE
Missing tcia collections

### ISSUE THREAD

**Issue by G-White-ISB** [ImagingDataCommons/IDC-WebApp#74]
There are now only 11 of the 21 tcia collections listed under the search scope. They were all there in previous commits. The 21 disease codes are still listed in the disease code tab. I've traced this back to a problem in a python dictionary in the explore_data_page function in views.py. attr_by_source['origin_set']['attributes']['collection_id']['vals'] only has these 11 members not the 21 expected.

**Comment by s-paquette** [comment]
A misuse of the display value table was causing some of these values to drop out, in addition to 10 of them missing from the display value table. The bug in the code has been corrected, and the missing values were added into the display value table.

**Comment by s-paquette** [comment]
@madelyngreyes @G-White-ISB ready for testing.

**Comment by madelyngreyes** [comment]
After manual testing, all collections appear to be present. Currently working on a Selenium IDE script to automate the verification of all collections available.
