### ISSUE TITLE
content jitters at certain sizes

### ISSUE THREAD

**Issue by pieper** [ImagingDataCommons/IDC-WebApp#747]
At certain screensizes it looks like there's a feedback loop that causes the content to jitter.  Resizing a bit can fix it, but then if you pick just the right size it returns.

Probably this is some responsive rules conflicting.

**Screenshots**

https://user-images.githubusercontent.com/126077/134224106-d8230556-a463-4531-a212-281ce26da89c.mov

**Your System**
 - OS: macOS
 - Browser Chrome

**Comment by G-White-ISB** [comment]
Unable to reproduce. Poojitha maybe you could take a brief look?

**Comment by s-paquette** [comment]
@pgundluru Can you see if this is still happening?

**Comment by pgundluru** [comment]
I am not able to reproduce this  issue on Mac chrome or a windows machine.

**Comment by wlongabaugh** [comment]
Can't say I have ever seen that, with Chrome on Mac...

**Comment by s-paquette** [comment]
The UI has changed several times since this was filed; closing but feel free to re-open or resubmit if it happens again.
