### ISSUE TITLE
BMI normal weight missing

### ISSUE THREAD

**Issue by G-White-ISB** [ImagingDataCommons/IDC-WebApp#75]
The BMI 'normal weight' is always 0. It looks like a Mysql/Solr mismatch. query_solr_and_format_result has the category 'normal' but in attr_by_source['related_set']['attributes']['bmi']['vals'] its 'normal weight'. I think we should go with 'normal weight'. Also why are counts so low? Was bmi just not recorded for most collections?

**Comment by s-paquette** [comment]
Small bug when generating the attribute range entries for BMI - database has been fixed.
