### ISSUE TITLE
On test tier, When SM is selected it sends a error on the dev console

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#753]
SM viewer in Mac workstations has the error "An error occurred : Image metadata cannot be retrieved" 
On Windows Chrome, It shows the following error. 

![image](https://user-images.githubusercontent.com/85526819/134417862-e3927210-59f3-41f9-acc3-b902eb671c2e.png)

**Comment by fedorov** [comment]
@pgundluru can you please paste the URL?

**Comment by fedorov** [comment]
Link from @pgundluru - works for me with Chrome on mac: https://viewer.imaging.datacommons.cancer.gov/slim/studies/1.3.6.1.4.1.5962.99.1.2463087261.2121647220.1625960757917.3.0/series/1.3.6.1.4.1.5962.99.1.2463087261.2121647220.1625960757917.2.0

**Comment by pieper** [comment]
Yes, the production version works, but not the testing: https://testing-viewer.canceridc.dev/slim/studies/1.3.6.1.4.1.5962.99.1.2463087261.2121647220.1625960757917.3.0/series/1.3.6.1.4.1.5962.99.1.2463087261.2121647220.1625960757917.2.0

I get a 403 (forbidden) so probably the user agent token is not configured?  I did not set up my chrome but did you follow Bill's instructions @fedorov or @pgundluru and can you check it?

**Comment by fedorov** [comment]
Ah right - I missed that! The test URL works fine for me as well (perhaps somewhat slower than the prod one). There is also this error in the console, but it does not seem to affect the functionality.

![image](https://user-images.githubusercontent.com/313942/134420264-e615ed15-84ab-4fad-9343-cc36b85ed852.png)

**Comment by G-White-ISB** [comment]
Seems to be fixed.
