### ISSUE TITLE
Double Filter Entry in Prod

### ISSUE THREAD

**Issue by wlongabaugh** [ImagingDataCommons/IDC-WebApp#760]
Saw this show up during Andrey's demo. Is the double entry for (Prostate, Prostate) expected?
<img width="776" alt="DoubleEntry" src="https://user-images.githubusercontent.com/8441547/134985660-ccbc7f5f-066a-41ba-80e1-b6635d34eadb.png">

**Comment by fedorov** [comment]
That was because we had "Prostate" code meaning corresponding to codes from two different schemes. I see it has now been fixed but appending coding scheme designator.

![image](https://user-images.githubusercontent.com/313942/142966972-2306eb0a-1366-4a4b-88b3-a27557bdffe9.png)

**Comment by fedorov** [comment]
also a duplicate of #754
