### ISSUE TITLE
On prod tier, exploration page, when a user (signed out) selects Apollo collections and scrolls down. The spinner (loader) keeps spinning with no further action 

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#763]
Summary:

On prod tier, exploration page, when a user (signed out) selects Apollo collections and scrolls down. The spinner (loader) keeps spinning with no further action. 

Note : Only happens when a user is trying to select collections while signed out. 
Note : This seems to be happening to any selected collections while signed out. 

System : W10 chrome and edge browser

**Comment by G-White-ISB** [comment]
We have a fix but we cannot deploy it yet. We are held up by an unexpected error in the build process that is being investigated.
