### ISSUE TITLE
Cannot close popup warning

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#77]
Nothing happens when I click OK after logging in.

![image](https://user-images.githubusercontent.com/313942/79893735-7951db80-83d2-11ea-976d-c1e81ddb4e5e.png)

There are errors in the console:

![image](https://user-images.githubusercontent.com/313942/79893763-85d63400-83d2-11ea-84b1-2f33030d58d2.png)

Do we really need to have this popup after log in? Can't we have it shown once when the portal page is shown before logging in?

**Comment by fedorov** [comment]
After reloading the page, popup disappears.

**Comment by s-paquette** [comment]
@fedorov Can you confirm if this is still an issue? I made some changes to how the click is recorded which should prevent this.

**Comment by madelyngreyes** [comment]
I just tried and it still appears to be an issue on the dev tier. 

![Screen Shot 2020-05-05 at 11 23 53 AM](https://user-images.githubusercontent.com/16824894/81083724-ed0be200-8ec2-11ea-9268-18f8a9d9208e.png)

**Comment by s-paquette** [comment]
I notice you somehow got that on the data explorer page. Can you explain the steps for that?

**Comment by madelyngreyes** [comment]
Yes, I can the steps to reproduce are below.

1. Go to homepage
2. Select near the login link to make pop-up go away
3. Log in to IDC
4. Pop-up appears again 
5. Try to select Okay to get the pop-up to disappear 
6. Pop-up is stuck on page

**Comment by s-paquette** [comment]
Hm, I can't seem to get the popup to show up a second time. Are you logging in locally or via Google?

**Comment by s-paquette** [comment]
I *do* see what's causing the error, though, so I'll fix that for the moment.

**Comment by madelyngreyes** [comment]
I'm logging in via Google on Google Chrome.

**Comment by s-paquette** [comment]
Go ahead and give this another shot, though I find it odd you're being prompted twice; this hasn't been happening to me. Andrey, have you also been seeing the warning twice?

**Comment by madelyngreyes** [comment]
I deleted my cookies for IDC, then tried again on Google Chrome and still seem to be running into the same issue. 

![Screen Shot 2020-05-05 at 4 09 28 PM](https://user-images.githubusercontent.com/16824894/81111397-032d9880-8eeb-11ea-83d0-812e4c80a3aa.png)

**Comment by s-paquette** [comment]
Hokay, figured that error out as well--rebuilding a fix now.

**Comment by s-paquette** [comment]
(So try in about 15m.)

**Comment by madelyngreyes** [comment]
This appears to be fixed on the dev tier.

**Comment by madelyngreyes** [comment]
If you go to the Dashboard from the Data Explorer without closing the pop-up by selecting the Ok button, the pop-up will appear again, and once Ok button is selected the pop-up doesn't close. 

![Screen Shot 2020-05-20 at 1 16 21 PM](https://user-images.githubusercontent.com/16824894/82476817-9397db80-9a9c-11ea-9efd-a0832b050a38.png)

**Comment by s-paquette** [comment]
@madelyngreyes Are you seeing an error in your JavaScript console? I've never been able to reproduce this one so I'm not really sure what might be causing it.

**Comment by madelyngreyes** [comment]
Yes, that is correct.

**Comment by s-paquette** [comment]
So, unfortunately, I still can't get this to happen. I'll keep trying, but in the mean time I recommend maybe clearing the cache on that browser, or trying another browser.

**Comment by s-paquette** [comment]
(Note, I mean a full cache clear, as in empty cache and hard reload, as opposed to just the cookies.)

**Comment by madelyngreyes** [comment]
Hmm, this is so strange. I was able to reproduce the error. This time I cleared my cookies and site data, did a hard reload, and I also used an incognito window. Followed the same steps and returned the error. 

![Screen Shot 2020-05-21 at 2 18 48 PM](https://user-images.githubusercontent.com/16824894/82591908-0b820680-9b6e-11ea-8d8a-ffab9346c4cd.png)

**Comment by s-paquette** [comment]
Was there an error in the console?

**Comment by madelyngreyes** [comment]
Yes, the dev console returned this error.  I should have included it earlier.

![Screen Shot 2020-05-21 at 3 18 12 PM](https://user-images.githubusercontent.com/16824894/82597035-599b0800-9b76-11ea-93d9-90213fa033ca.png)

**Comment by s-paquette** [comment]
Got it! Thanks, I'll have a look.

**Comment by s-paquette** [comment]
@madelyngreyes Okay, give it another shot.
