### ISSUE TITLE
Unable to select study/series in the portal for any collection

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#776]
1. Select NLST
2. select any case
3. select any study
4. observe endless spinner

JS console:

![image](https://user-images.githubusercontent.com/313942/137918653-527d040b-59a8-42dd-a5a7-d8b9271c10b4.png)

Reported by @denbonte

**Comment by s-paquette** [comment]
@fedorov Unfortunately due to the nature of the fix this is related to (it's a security fix so see IDC-Project-Management for that ticket) nothing short of a full regression was likely to catch all of the explorer methods effected by the change.

**Comment by s-paquette** [comment]
@fedorov Testing appears to pass on dev and test, merging into production.

![image](https://user-images.githubusercontent.com/8442808/137971535-847e6ba1-104b-49f8-a847-4ca7626e745b.png)

**Comment by G-White-ISB** [comment]
@fedorov we don't have automated testing to ensure that the web app doesn't break with a new deployment. I have done some work on automated testing but its not complete, nor is it baked into the 'build and deploy' process
