### ISSUE TITLE
Add clear all function for filter definition panel

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#78]
On the Explore Image Data page, there is no simple way to clear all filters selected in the filter definition panel. 

![Screen Shot 2020-04-21 at 3 13 07 PM](https://user-images.githubusercontent.com/16824894/79904690-14eb4800-83e3-11ea-99e9-8d3419b32802.png)

**Comment by fedorov** [comment]
For the reference, in GDC there is a button to clear the complete query:

![image](https://user-images.githubusercontent.com/313942/80024063-7fb48600-84ac-11ea-816f-cc993c9c842e.png)

and there is also a button to clear selection for the individual facet groups:

![image](https://user-images.githubusercontent.com/313942/80024124-93f88300-84ac-11ea-8105-a4fcbcfdf142.png)

I think it would be great to be consistent in this regard, if possible.
