### ISSUE TITLE
Selection of items in the table should be possible by clicking the row

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#780]
Feedback from @swederik, which I share:

> I’ve been using IDC to find some cases and I have a feature request - you should be able to click on a whole row to select/unselect something. I shouldn’t have to click exactly on the checkbox to select it

**Comment by fedorov** [comment]
We used to support selection by clicking the entire row, which was revised due to the discussion in this issue: https://github.com/ImagingDataCommons/IDC-WebApp/issues/522.

**Comment by G-White-ISB** [comment]
I think the real  508 concern was not clicking the row per se but holding down shift to select multiple rows. Revising so that one can just click into the row to select/deselect it. The plus/minus icons to select or deselect a whole page will stay

**Comment by pgundluru** [comment]
I am able to click and select a row anywhere in Collections/Cases/Studies/Series tables on the exploration page successfully except for view case (expected)
