### ISSUE TITLE
Checkboxes that are checked should be sorted to the top in the left panel

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#781]
Feedback from @swederik that I share:

> in the filter panel on the left, checkboxes that are checked should be sorted to the top

**Comment by fedorov** [comment]
@wlongabaugh agrees that items that are checked should not be hidden when we have the list not shown in its entirety.

We also noted that GDC and PDC have the same behavior as IDC - checked items do not float to the top, and when the list is collapsed, checked items are not visible.

**Comment by fedorov** [comment]
@G-White-ISB did the change and now it behaves the way you wanted it to see @swederik!

**Comment by G-White-ISB** [comment]
Clarification: this working in Search Configuration but not in Collections tab. I'll add it there as well.

**Comment by pgundluru** [comment]
Able to successfully test this in collections for each collection.

**Comment by pgundluru** [comment]
Able to successfully test this in collections for each filter in search configuration area (original, related and derived)

**Comment by pgundluru** [comment]
![image](https://user-images.githubusercontent.com/85526819/151223032-3cba6fac-332a-4f7c-a8e0-6195b0710b8f.png)

**Comment by pgundluru** [comment]
Asked @G-White-ISB for guidance on this.

**Comment by pgundluru** [comment]
BMI filter is expected and confirmed with George.

**Comment by G-White-ISB** [comment]
We are now considering undoing this feature. Please see https://github.com/ImagingDataCommons/IDC-WebApp/issues/1232
