### ISSUE TITLE
Presentation issues

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#79]
typo: "Radiotheraoy"

![image](https://user-images.githubusercontent.com/313942/79909299-c0e46180-83ea-11ea-825c-0c0f3aea792b.png)

messed up table columns:

![image](https://user-images.githubusercontent.com/313942/79909327-c9d53300-83ea-11ea-8a27-af39ba4c8d59.png)

why is collections table showing collections that do not have subjects that match the selection criteria?

![image](https://user-images.githubusercontent.com/313942/79909370-db1e3f80-83ea-11ea-8c6c-d8a73b61c6ec.png)

**Comment by fedorov** [comment]
We should consistently use either "cases", or "patients", or clarify why we need to have both:

![image](https://user-images.githubusercontent.com/313942/79910396-a317fc00-83ec-11ea-82c0-7a4893b8968a.png)

![image](https://user-images.githubusercontent.com/313942/79910410-a90ddd00-83ec-11ea-87c4-653d08b7d3d1.png)

**Comment by fedorov** [comment]
I would also argue that "case(s)" should be remove from the count labels.

**Comment by fedorov** [comment]
For the series level display, I do not think it helps anyone to see the UIDs.

![image](https://user-images.githubusercontent.com/313942/82488878-b206d280-9aae-11ea-9083-65316de1e0dd.png)

I suggest instead we display series number, series description, and modality. Below is what is shown in Slicer.

![image](https://user-images.githubusercontent.com/313942/82488866-addab500-9aae-11ea-9e2a-33e2648ea441.png)

**Comment by G-White-ISB** [comment]
Collections table will now hide collections with 0 patients. I concur with not using both patients and cases but would you prefer cases or patients? At least for a non-MD 'patient' is somewhat clearer. We could remove the annotation to the count labels, but I wonder if that could lead to ambiguity as to whether we are counting by patient or study? Will remove SeriesID in the Series table.

I'll be fixing these items over the next two days.

**Comment by fedorov** [comment]
@rkikinis also had a suggestion that the color set used by the charts should be revised.

**Comment by fedorov** [comment]
The sizing of this table during scroll is messed up and should be fixed:

![2020-06-11_10-42-20 (1)](https://user-images.githubusercontent.com/313942/84401934-d8adba00-abd1-11ea-990b-da2f76c6e01e.gif)

**Comment by fedorov** [comment]
Issues here have either been fixed, or superseded by other open issues.
