### ISSUE TITLE
In Dev Environment, in the exploration page, search box position and appearance are different between collections table and other tables. 

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#800]
Summary - On the exploration page, search box position and appearance are different between collections table and other tables. The search box will need to be consistent with the Collections table. 

![2021-11-17_14-54-47 (3)](https://user-images.githubusercontent.com/313942/142449337-e4753748-c831-455a-a411-4ce884ac10f6.gif)

**Comment by s-paquette** [comment]
@fedorov  This is likely a width issue; there's not enough room due to the width of the rest of the text. What would you prefer to happen in the case of a width constraint?

**Comment by fedorov** [comment]
> This is likely a width issue; there's not enough room in the case header due to the width of the rest of the text, so the Search box wraps to the next line.

That's what I thought too, but no matter how wide is the browser window, the search box remains where it is in the screenshot. 

I will modify the issue as submitted by @pgundluru to include the GIF I included in my report in Slack to demonstrate that.

**Comment by fedorov** [comment]
![image](https://user-images.githubusercontent.com/313942/142964996-575ce318-c9b9-44b5-8489-a0a869a95b8c.png)

**Comment by fedorov** [comment]
Still appears broken to me in test

**Comment by fedorov** [comment]
Now the position of the search box is consistent, but the behavior is not consistent. When one searches in the collections search box, it appears to search of any match of the typed text. In the other search boxes, it is expecting exact match, which is not desirable. I think the behavior should be match of any portion of the identifier, and should be the same for all search boxes.

**Comment by G-White-ISB** [comment]
Note that search in the Cases and Studies tables will be always be somewhat different than search in Collections table because search in those tables requires a call to the back end - hence the 'GO' button.  If a table is longer than 2k rows only a portion of it is loaded in the front end. But I think we could support partial text match - I had to check how that's done in SOLR.   Searching for a match anywhere in the table rather than a specified column is doable but might be a bit of work and would slow down response time.

**Comment by fedorov** [comment]
Searching within a specific column (as defined by the text we currently have along with the search box) is ok!

**Comment by G-White-ISB** [comment]
Suggest close this ticket and create new one re: ' I think the behavior should be match of any portion of the identifier, and should be the same for all search boxes'. Function of the search boxes is a different and more complicated issue. I can create the new ticket

**Comment by fedorov** [comment]
I agree, but we should probably close it after testing is passed, right? I don't see that happened based on the issue history.
