### ISSUE TITLE
In Dev Environment, In the exploration page, when viewing the case-study-series tables, Only the collections table doesn't stretch with resizing browser window. 

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#801]
Summary - case-study-series tables appears to stretch with the resizing of the browser window in the exploration page, and the one for collections tables does not stretch. This can be reproduced in Mac Chrome, W10 Chrome.

**Comment by G-White-ISB** [comment]
Every table should now resize the same
