### ISSUE TITLE
In Test Environment, In collections page when a user selects certain analysis type collections and redirects to the exploration page there is no pre-populated collection in the filter definition. 

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#807]
Summary - When a user is in the collections page and sorts by Collection Type = analysis and then clicks on the collection to open up in the explorer page. Some of the collections do not populate in the explorer page as intended. 

This has been observed for analysis type collections below. I am not seeing it for original collections 

DICOM-Glioma-SEG
DICOM-SR-Breast-Clinical
QIN-LungCT-Seg

**Comment by pgundluru** [comment]
![image](https://user-images.githubusercontent.com/85526819/143057353-65da920a-2a04-4559-b931-3ac92632750f.png)

**Comment by s-paquette** [comment]
Change in the Collections value coming in from BQ (no more ' ' in the separator).
