### ISSUE TITLE
In test environment, version compare button for comparing 2 different versions of cohort data is non functional 

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#808]
Summary - In the test environment, version compare button usually pulls up a window to be able to compare the data versions of the cohorts which is currently non functional.

**Comment by pgundluru** [comment]
Update - I am able to use the compare version button for some cohorts and not for others. I will reach out to Suzanne to show her my results and validate this issue.

**Comment by s-paquette** [comment]
So far we haven't been able to nail down what's causing this. Will have to wait until I can reliably reproduce it in a local environment.

**Comment by pgundluru** [comment]
Thank You Suzanne. I am unable to reproduce this issue on my end at this moment so I think we can close this ticket.
