### ISSUE TITLE
In Production Environment, Version compare button to compare different data versions of saved cohorts is non functional 

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#809]
Summary - This is observed in W10 and Mac OS. The version compare button is non functional for saved cohorts from different data versions.

**Comment by pgundluru** [comment]
Update - I am able to use the compare version button for some cohorts and not for others. I will reach out to Suzanne to show her my results and validate this issue.

**Comment by s-paquette** [comment]
So far we haven't been able to nail down what's causing this. Will have to wait until I can reliably reproduce it in a local environment.

**Comment by s-paquette** [comment]
Closing, duplicate of 808.
