### ISSUE TITLE
Search widget

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#81]
Can we have something like this in GDC?

![image](https://user-images.githubusercontent.com/313942/80050846-ba3a1500-84e4-11ea-924f-32144aaa3abc.png)

**Comment by fedorov** [comment]
Discussed this with the ISB team, and decided to reconsider after MVP.

**Comment by wlongabaugh** [comment]
@ulrikew This is the issue that addresses search per #450. Plan to address in an upcoming sprint, but it is not trivial.

**Comment by s-paquette** [comment]
@fedorov Note that this is already done and on the current release of the portal. @pgundluru If you could test this when you have a chance.
