### ISSUE TITLE
"Select/unselect all" buttons are missing for the collections table

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#810]
They are present in all tables except collections. I know it's been like that all the time, but I do not see the reason why it should be like that, and it is quite inconvenient.

![image](https://user-images.githubusercontent.com/313942/143668329-b748822a-69b4-4e6c-9903-f7e8c3584dfc.png)

**Comment by G-White-ISB** [comment]
We could not support selecting all collections until we enabled batch fetching.

**Comment by fedorov** [comment]
How does the search box work - does it search across all pages, or only the currently shown page?

**Comment by G-White-ISB** [comment]
Search box will search accross all pages

**Comment by pgundluru** [comment]
![image](https://user-images.githubusercontent.com/85526819/196544522-a2a7a3f3-d8ee-4a5b-88f0-3f3ef931a8c1.png)

**Comment by pgundluru** [comment]
Closed as completed
