### ISSUE TITLE
Add Preliminary Support for Private or Limited Collections to the WebApp

### ISSUE THREAD

**Issue by G-White-ISB** [ImagingDataCommons/IDC-WebApp#811]
1. Alert users which collections are not public or restricted in the collections tab. 
2. In the Study and Series tables, show a font-awesome 'minus-circle' icon in the  'View' column for any study or series belonging to a restricted collection. Hovering over the icon will open a tooltip explaining that the image is not available. Clicking on the icon will NOT open the corresponding image file in the viewer

**Comment by G-White-ISB** [comment]
Preliminary design. Locally I have 4d_lung and TCGA-BLCA flagged as limited access.

https://user-images.githubusercontent.com/58443591/144523975-6049fc8b-ef04-47b1-bff6-03fe912c0338.mov


https://user-images.githubusercontent.com/58443591/144523930-7ca8a666-7186-44ba-85ab-11e840a20fab.mov

**Comment by fedorov** [comment]
Looks fine to me.

**Comment by pgundluru** [comment]
https://files.slack.com/files-pri/TER7HBP44-F02QJ6C5YKB/image.png

**Comment by pgundluru** [comment]
![image](https://user-images.githubusercontent.com/85526819/145458012-626ea79c-d74f-402a-b10d-4918b33e3e5a.png)
