### ISSUE TITLE
In prod tier, When a user selects TCGA -READ sub collection and original filter modality - CT, related filter - race (white) Then BQ export fails 

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#817]
This was observed by Bill C. To reproduce the issue, 

1. In production select TCGA -Read as the sub collection, 
2. Select Modality - CT
3. Selected related filter - race - white 
4. Save cohort and export to BQ 
![image](https://user-images.githubusercontent.com/85526819/144922151-16524a52-f659-46cd-813a-b6f59802a8fd.png)

**Comment by s-paquette** [comment]
Per the other ticket @pgundluru can you test this again.

**Comment by pgundluru** [comment]
I have successfully tested this issue with selecting TCGA collections (single and select all) and filters in original, derived and related including BMI.
