### ISSUE TITLE
Runtime issue observed

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#82]
Conditions to reproduce are unclear

![image](https://user-images.githubusercontent.com/313942/80136392-9ec81c00-856f-11ea-93d1-6bb3d78c8605.png)

**Comment by fedorov** [comment]
![image](https://user-images.githubusercontent.com/313942/80136955-75f45680-8570-11ea-851c-9acc40523a9a.png)

**Comment by s-paquette** [comment]
These appear to be page load time outs; we can, if we want, invest some time in seeing about handling timeouts more gracefully, but these don't appear to be code bugs.

**Comment by fedorov** [comment]
No need to invest more time into this, let's close it.
