### ISSUE TITLE
Integrate Crazy Egg

### ISSUE THREAD

**Issue by ulrikew** [ImagingDataCommons/IDC-WebApp#831]
Discussed during the IDC stakeholder call on 12/16/2021

Email from Anna Mencarelli (CBIIT Communications) with information about the Crazy Egg implementation

_The heat map tool we offer, [Crazy Egg](https://www.crazyegg.com/), would be helpful to capture the flow and recordings of active users. It can show a variety of front-end interactions that would require additional configuration in analytics tags. To give you an idea of what data is captured, I’ve shared a recent report we ran on one of our blogs. 
 
NCI has a subscription for the tool, so you wouldn’t need to pay for it out of IDC funds. Crazy Egg is also disclosed under the standardized cancer.gov privacy policy, and given that it does not capture identifiable information from a website user (i.e. username) it shouldn’t change the scope of your privacy policy to implement. 
 
There are two avenues we can take to implement the tool: 
•	Hard code snippet the tag within IDC’s <head> tag: This would use CBIIT’s Crazy Egg account, so we would need to coordinate with the testing team to verify that the tag is live and receiving the data. 
•	Hard code an ADTM tag within IDC’s <head> tag: NCI’s enterprise communications office also has a Crazy Egg account. If you implement their analytics tag manager snippet, they’ll be able to push the crazy egg tag to IDC and manage tests directly. The queue can be quite long for getting the ADTM tag, so it may not be available by the time we implement user research. 

I have implemented the Crazy Egg snippet on datascience.cancer.gov through Google Tag Manager. So, if you have GTM on the site, I can answer questions about what the implementation process looked like and share lessons learned. Though we’re more of a static content site, we saw very little to no impact on our site’s performance from Crazy Egg._

**Comment by s-paquette** [comment]
So as far as I know, we don't have Google Tag Manager on our site. That means there's really two levels to this: getting GTM set up, and getting Crazy Egg set up. That's going to be a fair amount of work given we need to read up on how they function and the admin roles associated with GTM.

https://support.google.com/tagmanager/answer/6103576

@wlongabaugh We'll need to look into this somewhat; it's not like GA itself, which is very fast to install, there's some work involved. Not sure I can get this done and the other priority things in this Sprint, @fedorov Does this take priority?

**Comment by fedorov** [comment]
@ulrikew what is the timing of the IDC UX study, which is the main motivation for this, as I understand?

**Comment by ulrikew** [comment]
@s-paquette When I copied and pasted Anna's email the "smart" GitHub app cut out  `<head>`  before the word tag.  I will forward Anna's email to you. Can you please find out if inserting the snippet in the header is simpler than installing the Google Tag Manager?

**Comment by s-paquette** [comment]
@ulrikew Ah that explains it! Assuming the snippet is straight forward that would definitely be easier. I'm unclear from the email who we need to contact for that, or where to get it; it sounds like CBIIT or NCI Comm needs to give it to us?

**Comment by ulrikew** [comment]
@s-paquette I will put you in contract with Anna Mencarelli from the CBIIT communications team. She should be able to answer your questions.

**Comment by ulrikew** [comment]
@s-paquette  I sent the email to Anna.

**Comment by s-paquette** [comment]
@ulrikew Thank you!

**Comment by s-paquette** [comment]
Met with Anna Mencarellia and we went with the script running under CBIIT's account. This will only load on production, not the other tiers or local development.

**Comment by fedorov** [comment]
This was added, and we can revisit if something doesn't work as needed.
