### ISSUE TITLE
Console errors and failures to load when user compares current data version to a previous data version 

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#834]
General Summary:

There is an issue with loading version compare for different data versions in production tier. Suzanne suspects this may be load order precedence issue in JS. 

Steps to reproduce:

Test 1

1.  In cohort details page, select current data version and select data version 2 
2.  Version compare window doesn't pop up 
![image](https://user-images.githubusercontent.com/85526819/149002112-c7c438e5-18a6-466d-8354-ef9426f6e461.png)

**Comment by pgundluru** [comment]
This seems to be an issue while comparing V6 (current data version) to any version except the most recent inactive one (so v6 and v5 work but not v6 and any other versions)

**Comment by fedorov** [comment]
@s-paquette will update the status

**Comment by pgundluru** [comment]
To test this issue on test environment, 

In windows- Chrome, signed into test tier, I created cohorts and selected current version cohort to v5 which was successful. 
Selecting current version to any of the older versions (v4,v3,v2,v1) does not pop up the window and fails.

**Comment by pgundluru** [comment]
Note: This bug was discovered in production tier

**Comment by s-paquette** [comment]
@pgundluru So that error I can't seem to replicate. Are you seeing anything in the dev console when this happens? And does it happen only when you do v5 and then another, or is it on any second attempt to compare?

**Comment by s-paquette** [comment]
@pgundluru Added note, since this is a popup, can you check to see if it's being suppressed because of that?

**Comment by s-paquette** [comment]
@pgundluru Can you test this one again, I found yet another bug this morning which ought to now be resolved.

**Comment by pgundluru** [comment]
Testing results:

System - Mac OS and Chrome browser (Popups enabled in settings)

Note - After every single test I have to refresh or click on the cohort page and reload otherwise compare doesn't work. 

1. Test with selecting V7 cohort and V6 cohort - success
2. Test with selecting V6 and V5 cohort - success
3. Test with V5 and V4 - unsuccessful 
4. Test with V7 and V4 - unsuccessful 
5. Test with V6 and V4 - unsuccessful 
6. Test with V7 and V3 - unsuccessful
7. Test with V7 and V5 - success

**Comment by s-paquette** [comment]
So, I'm confused--how are you comparing V5 to V4? You can only compare a version to the current version. Are you seeing what appears to be a method to compare two arbitrary versions?

**Comment by s-paquette** [comment]
Okay, finally pinned this down--the event wasn't delegated so subsequent table pages on the cohort list weren't bound to the event. Fixed for both comparison and query fetch.

**Comment by s-paquette** [comment]
@pgundluru Ready for testing.
