### ISSUE TITLE
"Clear all" does not clear all

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#835]
Today's version of the webapp, no errors in the console. I didn't have time to debug.

![2022-01-11_22-30-14](https://user-images.githubusercontent.com/313942/149059068-e50ad770-8eb7-4acf-9791-dc0ded369a53.gif)

**Comment by fedorov** [comment]
@pgundluru fyi

**Comment by G-White-ISB** [comment]
Clicking 'Clear All' in the Filter definition is not supposed to clear selections in the Data Tables

**Comment by fedorov** [comment]
@G-White-ISB that is interesting.

Is it also expected that when I modify the filter definition, those uncleared selections are part of my cohort as a matter of fact, but are not satisfying the filter definition?

That's one weird feature.

**Comment by G-White-ISB** [comment]
If you modify the filter definition then any  cases, studies, series  selected in the data tables that no longer match the new filter definition will be unselected and hidden in the data tables.  Cases, studies, series that still match the filter definition are still shown, and their 'selection state' does not change. 

But recall that right now filtering is done at a 'case' level. If you filter on a certain modality one can still see series with a different modality if the associated case has another series with the selected modality.

**Comment by fedorov** [comment]
I do not see the logic of not resetting all of the tables by "Clear all".

When I encountered this issue, the way I encountered is I did clear all, then proceeded to define a new filter, and then observed that I still have cases selected from the previous filter definition included in the new filter definition, even though they did not match the filter. I do not see how this can be correct or helpful.

**Comment by G-White-ISB** [comment]
The logic is that the Clear All button is in the Filter Definition panel, so it should clear the Filter Definition and nothing else. Perhaps this would be more obvious if the panel had a more visible border. Selections in the Data tables do not change the Filter or Cohort definition, but only change which portions of the Cohort the user is currently viewing. I agree this can be /has been confusing. However this has always been the way the portal has worked.

The behavior you describe in your last comment  would be a bug. One should never have cases selected or even viewable in the Cases table if the current filter definition would exclude those cases. But that is not related to the 'Clear All' button. When the filter definition is cleared nothing is excluded from the data tables. Only when the new filter is created would the cases excluded by the filter be removed from the Cases Table. If you can recall or recreate this bug that would be helpful. I am trying to reproduce this myself

**Comment by fedorov** [comment]
> The logic is that the Clear All button is in the Filter Definition panel, so it should clear the Filter Definition and nothing else.

And the logic for clearing all child tables is that they are defined by the filter. They cannot be separated from the filter. If the filter is gone - they should be cleared. They are orphaned once there is no filter.

**Comment by G-White-ISB** [comment]
Some questions to address if we go down this route:
1. If we clear all filters by deselecting them individually rather than using the button would we still clear the child table selections?
2. Will users still be allowed to make selections in the child table before selecting any filter?
3. Will child tables be cleared every time the filter definition is changed or only when it is empty?

**Comment by fedorov** [comment]
These are good questions. Here are my thoughts for the discussion.

> If we clear all filters by deselecting them individually rather than using the button would we still clear the child table selections?

If the case selected no longer meets the criteria of the filter - yes, I think it should be cleared.

> Will users still be allowed to make selections in the child table before selecting any filter?

This is an interesting observation. I guess de facto when the user opens the portal and there is no filter, it is "browse" mode, and selection is allowed. But indeed I think the logical behavior would be if the user selects a filter while in "browse" mode, the content of the tables should be updated to match the filter definition, not matter what is the current selection.

> Will child tables be cleared every time the filter definition is changed or only when it is empty?

I think child tables should be cleared when their content is no longer matching the filter definition.

**Comment by fedorov** [comment]
It would also be appropriate I think to look at the other portals to see how they handle these situations.

**Comment by G-White-ISB** [comment]
So GDC and PDC clear table selections whenever a filter changes, even if the selections match the new filter. We

**Comment by fedorov** [comment]
> So GDC and PDC clear table selections whenever a filter changes, even if the selections match the new filter.

This behavior is completely fine with me, especially if it is much easier to implement.

**Comment by pgundluru** [comment]
To test this issue on dev tier https://dev-portal.canceridc.dev/explore/ in the exploration page, 

1. No selection in access bar and reset will bring back the public selection - pass
2. Selecting a collection and attributes and reset will bring bac the public selection - pass 
3. If display query URL is selected and then reset is enabled then the display URL still shows up unless closed
