### ISSUE TITLE
It should be possible to filter out limited access collections

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#836]
If I can't access them, I think it is natural that I want to get rid of them in my results. I thought we talked about this, no? @wlongabaugh

**Comment by s-paquette** [comment]
@fedorov We didn't come to a decision on how to approach them. The basic question would be, is this a *collection* level filter, or is it a study level filter, or...

What would be your expected outcomes in terms of the items you would expect to still see; this will determine how we filter it.

**Comment by s-paquette** [comment]
Ah, I remember the other angle of this. The reason we--and none of the other Data Commons--offer filtering on access level is it's based on an individual. Which is to say, whether or not you can access something comes down to your own privileges, which we can't detect right now because we don't have a registration system. (The Resources do have such systems, though CGC and possibly neither Seven Bridges nor Broad allow for filtering on this basis as well; that's determined at the time you go to access the data itself.)

This said, the concept of 'is the access to this limited/controlled' is something we could offer filtering on, though we would need to make it clear to the user this doesn't indicate if *they* can access something, just what the level requirement is. And, as above, we'd need to know how you'd expect it to behave when eg. a collection contains both limited and publicly accessible data.

**Comment by fedorov** [comment]
> What would be your expected outcomes in terms of the items you would expect to still see; this will determine how we filter it.

I would like to be able to see only the items that have `access = "Public"` in the underlying tables.

> This said, the concept of 'is the access to this limited/controlled' is something we could offer filtering on, though we would need to make it clear to the user this doesn't indicate if they can access something, just what the level requirement is. And, as above, we'd need to know how you'd expect it to behave when eg. a collection contains both limited and publicly accessible data.

At the moment at least, it is pretty unambiguous - no one can access those limited items in IDC. So showing them in the webapp is useless and confusing. And we do not have any idea when or if we will provide access to those limited items via any means (even storage buckets), so this is not something that will be resolved in the next 1-2 releases.

**Comment by s-paquette** [comment]
> I would like to be able to see only the items that have `access = "Public"` in the underlying tables.

In this case, what are the items in question--collections, studies, series, or instances?

> At the moment at least, it is pretty unambiguous - no one can access those limited items in IDC. So showing them in the webapp is useless and confusing. And we do not have any idea when or if we will provide access to those limited items via any means (even storage buckets), so this is not something that will be resolved in the next 1-2 releases.

Got it. In that case, the question goes back to, at what level is something limited access.

**Comment by fedorov** [comment]
> In this case, what are the items in question--collections, studies, series, or instances?

For the foreseeable future, access will be defined at the collection level.

**Comment by s-paquette** [comment]
Got it. That I think we can do as we have it right now, because access level in Solr is populated from the collection setting. I'll double-check that first, though, before putting this through.

**Comment by G-White-ISB** [comment]
Agreed to move the access attribute to the collection tab. There may be some back and forth on the design. We plan to have it out v8

**Comment by s-paquette** [comment]
@G-White-ISB The new database seed in GCS will now included the access attribute set to a default 'enabled' state for the UI, so if you download it and rebuild your database (or connect to it in MySQL locally and edit it by hand--you want to set the `default_ui_display` column to 1) you can get this one to show up in facets etc.

**Comment by fedorov** [comment]
Todd and Ulli like the idea of excluding limited access collections by default.

**Comment by fedorov** [comment]
Per discussion today, we agreed that the front page of the portal will be updated to only summarize the available public collections. This will be consistent with only public collections included by default in the explore page.

**Comment by pgundluru** [comment]
The search scope on collection level defaults to show public collections
