### ISSUE TITLE
New image examples needed for MR and PET due to defacing

### ISSUE THREAD

**Issue by s-paquette** [ImagingDataCommons/IDC-WebApp#840]
PDF of new images and links provided.
[Front page images - Google Docs.pdf](https://github.com/ImagingDataCommons/IDC-WebApp/files/7894854/Front.page.images.-.Google.Docs.pdf)

**Comment by s-paquette** [comment]
@fedorov Now available on dev and test.

**Comment by pgundluru** [comment]
New images for MR and PET able to load on test tier

**Comment by fedorov** [comment]
For the sake of completeness and to be precise, the "live" internal google doc with those images is here: https://docs.google.com/document/d/1dy6y_52RII4Y3LTxH_6NyvFTC-EvAgsBNdNS5r9nDaI/edit

**Comment by fedorov** [comment]
This is now working in prod
