### ISSUE TITLE
Formalize regression testing for seg/rtstruct related aspects of IDC viewer

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#843]
Regression testing for IDC viewer needs to be updated since the last update to feature testing protocols for new enhancements and bug fixes. 

Please update here https://docs.google.com/document/d/1l0RP3H6D9OCI3J2YubzFidBszu1NvB9lhUcFflnWNLc/edit

**Comment by fedorov** [comment]
I updated the document
