### ISSUE TITLE
Add access level as a column in the cohort export manifest

### ISSUE THREAD

**Issue by G-White-ISB** [ImagingDataCommons/IDC-WebApp#883]
Add a column in the cohort export manifest that reports the access level of the collection.

**Comment by fedorov** [comment]
Most likely, we will not make the decision to remove those out of our data for v8, and would make sense to add this column to the manifest. Will try to check with SHs today.

**Comment by pgundluru** [comment]
![image](https://user-images.githubusercontent.com/85526819/159288010-af347fc5-663c-42c0-98b5-feb43d63f756.png)

**Comment by pgundluru** [comment]
Access level is available in explore page
