### ISSUE TITLE
Add text for the tooltip popup where it is missing right now

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#886]
Right now, at least some of the CPTAC collections are missing description and popup in the portal. At least for CPTAC collections, when TCIA API does not return description, there should be a pointer to the corresponding TCIA wiki page. Default text can be "Please see the X wiki page to learn more about the images and to obtain any supporting metadata for this collection."

**Comment by s-paquette** [comment]
@bcli4d Where were we on this one--have we come up with a way to handle this yet? I rely on the `Description` field of the collection BQ tables for this data,

**Comment by s-paquette** [comment]
Oh I just realized, these are what you just updated. So my next load should address this.

**Comment by bcli4d** [comment]
I've created descriptions as needed. They include DOIs or URLs depending on availability, and all have citation instructions. So this item should be complete, pending any issues found in testing.

**Comment by s-paquette** [comment]
@fedorov This is now available to be tested on dev and test; note that an example of a collection requiring this fix (to compare to production) is CPTAC-COAD

**Comment by pgundluru** [comment]
All CPTAC collections have associated descriptions.

I have checked the other collections and some of them have DOI and collection name without a description. eg. [DICOM-Glioma-SEG]
