### ISSUE TITLE
Add IDC citation requirement to the front page

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#888]
At the moment, we ask users to cite IDC paper in the documentation, but this appears nowhere in our portal or in the metadata accompanying our content.

I think we should add to the front page the requirement to cite IDC.

Related to https://github.com/ImagingDataCommons/IDC-ProjectManagement/issues/1121#issuecomment-1036715976

**Comment by G-White-ISB** [comment]
Would like to discuss. I don't have a good idea of how to do this with our current layout. I have not found an example from the other nodes either.

**Comment by fedorov** [comment]
I will need to discuss this with SHs as well...

@ulrikew do you have any thoughts on this topic?

**Comment by fedorov** [comment]
Definitely let's add the citation to the "About" page:

The overview of IDC is available in this open access publication. If you use IDC, please acknowledge us by citing it!

Fedorov, A., Longabaugh, W. J. R., Pot, D., Clunie, D. A., Pieper, S., Aerts, H. J. W. L., Homeyer, A., Lewis, R., Akbarzadeh, A., Bontempi, D., Clifford, W., Herrmann, M. D., Höfener, H., Octaviano, I., Osborne, C., Paquette, S., Petts, J., Punzo, D., Reyes, M., Schacherer, D. P., Tian, M., White, G., Ziegler, E., Shmulevich, I., Pihl, T., Wagner, U., Farahani, K. & Kikinis, R. NCI Imaging Data Commons. Cancer Res. 81, 4188–4193 (2021). http://dx.doi.org/10.1158/0008-5472.CAN-21-0950

You can also review the accompanying [demonstration videos](https://www.youtube.com/playlist?list=PLhawVWNiPvwb2H0D9UTOIL23bc5DuDJRu) for a quick summary of some of the key features of the platform.

**Comment by fedorov** [comment]
Also discussed adding a new section/top level link "Data use", like it is done in PDC: https://proteomic.datacommons.cancer.gov/pdc/data-use-guidelines

**Comment by pgundluru** [comment]
![image](https://user-images.githubusercontent.com/85526819/159282956-ba34b3fc-0a2a-4eb0-8729-58d004b0db22.png)
