### ISSUE TITLE
In the production tier, In exploration page when you select a collection and filter and navigate to collections. the selected filters and collections are still selected in the exploration page

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#894]
To see this issue. When a user in exploration page selects collections and filters and then navigates away and comes back the selected filters are stuck and show up in the exploration page. This issue was identified while testing https://github.com/ImagingDataCommons/IDC-WebApp/issues/583 (the behavior is different while similar)

Steps to reproduce:

1. In production exploration page, select collection Apollo and CPTAC in search scope. 
2. Navigate away from exploration by going to collections
3. Navigate back to the exploration and the filter definition area will be blank but the collections in search scope are selected (Apollo and CPTAC)

**Comment by s-paquette** [comment]
@pgundluru `Navigate back to the exploration` In what was are you navigating back--the back button?

**Comment by pgundluru** [comment]
Hi Suzanne, I seemed to have missed replying to this After the release I am no longer able to reproduce this issue and will close the ticket.
