### ISSUE TITLE
Add SeriesInstanceUID to Series panel

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#910]
Based on feedback from @dclunie, with which I agree completely, it is strongly suggested to add SeriesInstanceUID column to the series table and also add "Find by SeriesInstanceUID" search box. This is important to help users identify the UID of the series they found in the explorer to subsequently download the corresponding files. Lacking such feature, the only way to do this now is to open the series in the viewer, and then get SeriesInstanceUID from the URL (or find it in the viewer). Not every user will figure this out.

**Comment by G-White-ISB** [comment]
Will we still keep Series Number?

**Comment by dclunie** [comment]
Yes please (I know I find it useful).

David
