### ISSUE TITLE
Testing instructions request to query GCS URLs and Buckets 

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#918]
This is a ticket to request Bill C to provide instructions to test GCS_URLS and buckets in test tier moving forward. Please provide query to find the bucket names and verify if the correct buckets are available for use. Thank You!

**Comment by bcli4d** [comment]
The following query should return no results if gcs_urls correctly  refer to public buckets. dicom_pivot_v8. For completeness, you should also apply to auxiliary_metadata, original_collections_metadata, dicom_all and dicom_derived_all BQ tables. We create a IDC version-specific dataset, idc_v<version>, for each IDC version. So, in the next release you'll need to change 'idc_v8' to 'idc_v9. Also the pivot table name is version specific, dicom_pivot_v8 --> dicom_pivot_v9.

WITH
  found AS (
  SELECT
    DISTINCT SPLIT(gcs_url,'/')[
  OFFSET
    (2)] bucket
  FROM
    `idc-pdp-staging.idc_v8.dicom_pivot_v8`),
  expected AS (
  SELECT
    *
  FROM
    UNNEST(ARRAY[ 'idc-open-idc', 'idc-open-cr', 'idc-open-idc1', 'public-datasets-idc']) AS bucket)
SELECT
  *
FROM
  found
FULL OUTER JOIN
  expected
ON
  found.bucket = expected.bucket
WHERE
  found.bucket IS NULL
  OR expected.bucket IS NULL

**Comment by bcli4d** [comment]
The following query should return no results if set of license_short_names the PDP staging BQ tables is correct. This can be applied to the same set of tables as described above.
WITH
  found AS (
  SELECT
    DISTINCT license_short_name
  FROM
    `idc-pdp-staging.idc_v8.dicom_pivot_v8`),
  expected AS (
  SELECT
    *
  FROM
    UNNEST(ARRAY[ 'CC BY 3.0', 'CC BY 4.0', 'CC BY-NC 3.0', 'CC BY-NC 4.0', 'TCIA ', 'TCIA NC']) AS license_short_name)
SELECT
  *
FROM
  found
FULL OUTER JOIN
  expected
ON
  found.license_short_name = expected.license_short_name
WHERE
  found.license_short_name IS NULL
  OR expected.license_short_name IS NULL
