### ISSUE TITLE
SliceThickness slider does not appear to function as expected

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#922]
![image](https://user-images.githubusercontent.com/313942/161363615-b3829828-837f-47ba-8ce3-8f547710cd65.png)

equivalent query and result in BQ console:

![image](https://user-images.githubusercontent.com/313942/161363610-c6429704-e1dd-4800-9b00-035794baeef3.png)

**Comment by G-White-ISB** [comment]
It's particular to  this collection. Spot checking other collections with other slice thickness ranges check out.
Also there is a discrepancy even without filtering on slice thickness. We have 26408 distinct caseIDs or PatientIDs  for nlst in the WebApp, the big query table has 26254.

**Comment by s-paquette** [comment]
dicom_all has 26408 for cases in nlst:

```WITH cases AS (
SELECT PatientID, collection_id
FROM idc-dev-etl.idc_v8_pub.dicom_all
GROUP BY PatientID,collection_id)
SELECT collection_id,COUNT(*) AS case_count
FROM cases
WHERE collection_id LIKE 'nlst%'
GROUP BY collection_id
;
```

@G-White-ISB What table has 26254?

**Comment by G-White-ISB** [comment]
bigquery-public-data.idc_v7.dicom_all has 26524 patientIDs. This was the table Andrey checked above, which was current at the time of his check

**Comment by s-paquette** [comment]
@bcli4d @fedorov We appear to be short numerous cases between v7 and v8 for NLST - is this expected?

**Comment by fedorov** [comment]
What is expected is that there are some patients that will have only Slide Microscopy modality, which were added in v8. 

`count(distinct(PatientID)) from `bigquery-public-data.idc_v7.dicom_all` where collection_id = "nlst"`

Result = 26254

`select count(distinct(PatientID)) from `bigquery-public-data.idc_v8.dicom_all` where collection_id = "nlst"`

Result = 26408

I can't confirm if the exact delta is accurate, but the larger number for v8 is expected.

Can you clarify what you mean exactly by "We appear to be short numerous cases between v7 and v8 for NLST"?

**Comment by s-paquette** [comment]
@fedorov Sorry, I mean we had added cases from v7 to v8, not that we were short.

That being said, the issue may have been a comparison of dev/test to prod; prod was on v7 at the time, but dev and test were on v8. In general, production can't be compared to dev and test once the version has been updated on those tiers.

So, right now, on production, is this still an issue, and if so, can we have it re-characterized?

**Comment by fedorov** [comment]
Can Poojitha or George take the description of the issue in the original post, and test it in prod? I am not sure what needs to be re-characterized.

**Comment by bcli4d** [comment]
SELECT count(*) FROM `bigquery-public-data.idc_v7.dicom_all` where
collection_id  = 'nlst'
Result=21080927
SELECT count(*) FROM `bigquery-public-data.idc_v8.dicom_all` where
collection_id  = 'nlst'
Result =21087946
SELECT count(*) FROM `bigquery-public-data.idc_v8.dicom_all` where
collection_id  = 'nlst' and Modality = 'SM'
Result=7019

**Comment by s-paquette** [comment]
Okay I think I now see the comment--the BQ result (for v7 or v8) is finding 10936 but the WebApp is showing 902. I can reproduce this one prod right now. 

My instinct is this has to do with how SliceThickness is being treated by Solr, so I need to dig into it a little more.

**Comment by s-paquette** [comment]
Found it. @G-White-ISB The front end is sending `sliceThickness_ebtw` rather than `_ebtwe`. In order for this value to be inclusive on both ends of the range, it needs to be `_ebtwe`.

**Comment by G-White-ISB** [comment]
So I realized afterwards there was a reason for using ebtw in place of ebtwe. The range designation not only affects the range of all results returned but also the ranges used in constructing the pie slices. So if one used the ebtwe range for say age of diagnosis, a 50 year old gets counted in both the 40-50 and 50-60 bins. Will look into fixing this so that total range can be inclusive but pie slices do not double count

**Comment by G-White-ISB** [comment]
On inspection I realize my last comment is not correct. Pie slices are inclusive on LHS, exclusive on RHS except for the last (highest value) pie slice, so every case is only matched on one pie slice.

**Comment by G-White-ISB** [comment]
Now I recall there was a  reason for using ebtw (i.e. filtering inclusively on the lower range, exclusively on the higher range). As mentioned the pie charts are inclusive on the RHS, exclusive on the LHS so a matching value is only added to one 'pie slice'. The filter was designed so that a range corresponding to a slice boundary would only match cases belonging to that slice. 

A good example is age of diagnosis in TCGA. Filtering from 40-50 captures patients belonging to the 40-50 'slice' (everyone >=40 and < 50). Now using an inclusive filter will capture patients in the >=40, <50 slice and the 50 year olds in the >=50, <60 slice.  

Moving forward with an inclusive filter range anyhow unless I'm told otherwise.

**Comment by s-paquette** [comment]
@fedorov @pgundluru This one is the implementation of the actual Slice Thickness numeric boxes, and is related to #932.

**Comment by s-paquette** [comment]
@fedorov @pgundluru Is this ticket okay for release?

**Comment by fedorov** [comment]
I will let @pgundluru spot-check the counts vs BQ.

**Comment by pgundluru** [comment]
I have spot checked the counts on portal vs BQ for slice thickness filters like below 

![image](https://user-images.githubusercontent.com/85526819/169344375-937ee702-c4d4-4418-916c-1f1ed925596f.png)

![image](https://user-images.githubusercontent.com/85526819/169344552-58c6903a-8810-4d39-9786-04981ba4c2ab.png)

**Comment by pgundluru** [comment]
![image](https://user-images.githubusercontent.com/85526819/169345691-e261574b-0e95-486e-80af-be93fde56934.png)

![image](https://user-images.githubusercontent.com/85526819/169345755-c572f4ba-ae62-42d9-9407-55ef7ce17122.png)
