### ISSUE TITLE
After filter selection scroll down will cause the entire page to display whitespace 

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#93]
After selecting multiple collections filter options, multiple selected studies, and a selected series filter option, whitespace appears after the selected series panel which will be displayed on the entire screen.  Scrolling down will display the whitespace. 

![Screen Shot 2020-05-06 at 11 28 50 AM](https://user-images.githubusercontent.com/16824894/81308002-499c0800-904f-11ea-9f2d-e13623bdd30f.png)

**Comment by G-White-ISB** [comment]
Can you repeat this? Could you send a screen shot of the filter definition?

**Comment by madelyngreyes** [comment]
Yes, I have listed the steps to reproduce this error below and added screenshots of the Filter Definition panel, the Collections panel, and the Selected Studies panel for reference.  

1. Go to Data Exploration page
2. Select Collections tcga_blca
3. Select Collections tcga_hnsc
4. Select Collections tcga_kich
5. Select a Selected Studies option e.g., 
tcga_kich | TCGA-KM-8439 | 1.3.6.1.4.1....103166379014 | MRI Abdomen
6. Select another Selected Studies option
7. Scroll down past the Selected series panel
8. You should see whitespace

I have the filter options selected in the Selected Collections panel and the Selected Studies panel but, in the Filter Definition panel, there are no options selected.

![Screen Shot 2020-05-07 at 1 25 40 PM](https://user-images.githubusercontent.com/16824894/81325604-9b03c180-9066-11ea-8f60-f1eb8aa50a4a.png)


![Screen Shot 2020-05-07 at 1 26 11 PM](https://user-images.githubusercontent.com/16824894/81325572-8aebe200-9066-11ea-96cf-59578bf73515.png)

**Comment by G-White-ISB** [comment]
As soon as the selected studies or selected series is populated the page is enlarged with whitespace on the bottom.

**Comment by G-White-ISB** [comment]
Should be fixed after current PR is accepted

**Comment by madelyngreyes** [comment]
If you select a collection e.g., tcga_lusc then select a select studies option e.g., 

tcga_lusc | TCGA-34-5239 | 1.3.6.1.4.1....982782939556 | CT THORAX WITHOUT CON
-- | -- | -- | --

then if you scroll past Selected series panel you will still see whitespace. 
![Screen Shot 2020-05-28 at 12 04 32 PM](https://user-images.githubusercontent.com/16824894/83165398-72a63a80-a0db-11ea-9ddc-cc42c72ff61e.png)

**Comment by G-White-ISB** [comment]
Code fixing this has not been deployed. Still waiting for a PR to be
accepted.
George
