### ISSUE TITLE
In prod Tier, When a user selects certain cases by major primary site on home page, Then they should be available in the filter definition page

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#930]
**General description** The expectation when a user selects a body part from the home page is that it would populate in the filter definition but certain body parts are not showing up currently. 

Below are the ones that are not visible nor filtering that body part cases 

Adrenal gland
Esophagus
Kidney
Testis

Note - This is currently also an issue in Dev and Test tiers

**Comment by s-paquette** [comment]
@pgundluru I can't seem to reproduce the issue with Esophagus--if I click on the Esophagus bar or organ I get Esophagus as the selection. Can you confirm that one is an issue?

The rest have been isolated and fixed.

**Comment by pgundluru** [comment]
Hi Suzanne, 

Interestingly Esophagus doesn't seem to be an issue anymore (Tested as a user logged in and logged out) And Bile duct which isn't working for you when you tried to reproduce the issue seems to be working for me fine. 

Currently just seeing the issue with Adrenal gland, Kidney and testis body parts.

**Comment by pgundluru** [comment]
There is a  ticket for this issue in test tier. This ticket can be tested in production after release.

**Comment by pgundluru** [comment]
Currently in prod there seems to be an issue with Results being filtered in exploration page for adrenal gland as mentioned in the ticket for the same issue on test tier.

**Comment by s-paquette** [comment]
Hm, I thought I'd addressed this but I guess not? Will do it in the next release.

**Comment by s-paquette** [comment]
Problem appears to be that space-containing organ names are treated oddly by sapien; did a small workaround to handle it for now, but that section of the code needs a rewrite.

**Comment by pgundluru** [comment]
In test tier, I have tested this by clicking on each organ in the home page which should take me to filter definition in exploration page with the organ filtered - Tested successfully
