### ISSUE TITLE
Use source_url when source_doi is missing for the collections list on the portal

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#931]
collections page should provide links to the URLs for the collections that do not have a DOI, which will be the case for all of the pathology-only new TCGA collections. The URL is in the source_url field in the aux table. Currently, those collections that do not have DOIs in the front page list have no links to the associated pages.

Should also confirm that in the portal explore page collections are linked by URLs when there's no DOI.

**Comment by pgundluru** [comment]
All TCGA collections except TCGA-DLBC have either a associated DOI or a source DOI.

**Comment by pgundluru** [comment]
Leaving this ticket open since TCGA-DLBC have either a associated DOI or a source DOI.

**Comment by s-paquette** [comment]
@pgundluru It will not have either of those for a time; I would like to ask we close it, because it will update in a subsequent data release when the new value is available (if it ever is).

**Comment by pgundluru** [comment]
Thanks Suzanne,
