### ISSUE TITLE
Domain/origin issue with pushState and portal.imaging vs. imaging URIs

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#937]
First, this collection is labeled as "Limited", but when it is selected, it shows CC-BY licenses for all cases in that collecton.

Second, in the tooltip, this collection points to https://wiki.cancerimagingarchive.net/display/Public/RIDER+Collections, while it should point to the collection-specific page https://wiki.cancerimagingarchive.net/display/Public/RIDER+NEURO+MRI.

![image](https://user-images.githubusercontent.com/313942/163457737-a85b7472-1171-42cd-a4d6-f39fb6f069aa.png)

**Comment by fedorov** [comment]
![image](https://user-images.githubusercontent.com/313942/163458548-5a27db19-8e36-4058-96ce-c7ca96447172.png)

**Comment by fedorov** [comment]
This is because I was coming from imaging vs portal.imaging! We have a new configuration to test.

**Comment by s-paquette** [comment]
Note that this fix can only be tested in production, once we do our release.

**Comment by pgundluru** [comment]
The tool tip points to the correct description in prod. 

Coming in from Portal.imaging - RIDER NEURO MRI  has 0 cases 
Coming in from imaging.datacommons - RIDER NEURO MRI  has 0 cases

**Comment by s-paquette** [comment]
@fedorov Are you still seeing these errors, BTW?
