### ISSUE TITLE
Series-level list is populated incorrectly

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#94]
This seems to be broken in general, but here's a very specific example.

Navigate to `tcga_ov` collection, then to case `TCGA-09-2053`. Selected series shows 844 entries (in fact, it always shows 844 series, no matter what case I select). Changing data source to BigQuery does not have any effect.

![image](https://user-images.githubusercontent.com/313942/82489507-c4cdd700-9aaf-11ea-84ee-05e9a632c38a.png)

If I then check that same collection/case against the BQ table, I get two series:

```sql
SELECT
  DISTINCT(SeriesInstanceUID)
FROM
  `idc-dev-etl.tcia.dicom_metadata`
WHERE
  PatientID = "TCGA-09-2044"
```

![image](https://user-images.githubusercontent.com/313942/82489625-f646a280-9aaf-11ea-910f-53089c10729c.png)

**Comment by s-paquette** [comment]
@G-White-ISB Is there anything up with the data you're getting back, or is the table displaying the wrong thing?

**Comment by G-White-ISB** [comment]
It looks like the data coming back is NOT filtered on the StudyInstanceUID so all the series in the collection, not just those in the study are returned. Also I believe this is a new issue - I think it was working correctly before. Sample call below, with StudyInstanceUID =
1.3.6.1.4.1.14519.5.2.1.1357.4011.225661032809163534141992125012 .
https://idc-dev.appspot.com/explore/?counts_only=False&is_json=True&collapse_on=SeriesInstanceUID&with_clinical=False&filters=%7B%22collection_id%22:%5B%22tcga_kich%22%5D,%22StudyInstanceUID%22:%5B%221.3.6.1.4.1.14519.5.2.1.1357.4011.225661032809163534141992125012%22%5D%7D&fields=%5B%22collection_id%22,%22PatientID%22,%22StudyInstanceUID%22,%22SeriesInstanceUID%22,%22Modality%22,%22BodyPartExamined%22,%22SeriesNumber%22,%22SeriesDescription%22%5D&order_docs=%5B%22collection_id%22,%22PatientID%22,%22StudyInstanceUID%22,%22SeriesNumber%22%5D

**Comment by s-paquette** [comment]
Okay, I'll take a look at it.

**Comment by s-paquette** [comment]
Located the bug - the filter attribute list builder was using for_faceting=True, which is a problem because only categorical strings are facet counted.
