### ISSUE TITLE
In Mac - Safari 14.1.2 browser, When a user opens up IDC production page and navigates to exploration tab  there is a error popup 

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#942]
This issue seems to be isolated to Safari browser 14.1.2 

When you open up https://portal.imaging.datacommons.cancer.gov/ then navigate to exploration page, there is a pop up with the below error message 

![image](https://user-images.githubusercontent.com/85526819/163622951-4ad542fe-7ab6-4575-8b0e-3b02ce2fb556.png)

**Comment by s-paquette** [comment]
@pgundluru A couple of questions to make sure we can identify this:

* Does this happen with any other version of Safari?
* Does this happen with imaging.datacommons.cancer.gov (i.e. no 'portal' in front?)
* Does this happen if you copy and paste the explore URL into a fresh Safari window, as opposed to clicking on the 'explore' button or link from the homepage?

**Comment by pgundluru** [comment]
Does this happen with any other version of Safari? 
This seems to be isolated to 14.1. 
Does this happen with imaging.datacommons.cancer.gov (i.e. no 'portal' in front?)
No I am not able to see the same issue while viewing imaging.datacommons.cancer.gov 
Does this happen if you copy and paste the explore URL into a fresh Safari window, as opposed to clicking on the 'explore' button or link from the homepage?
Only happens when I switch between collections and exploration tabs. 

Note - I have tested this in dev and prod (Portal. and imaging.) and there is no longer an issue with the pop up. I believe we can mark this ticket as closed.
