### ISSUE TITLE
KIDNEY and Kidney counts being collated in backend

### ISSUE THREAD

**Issue by s-paquette** [ImagingDataCommons/IDC-WebApp#946]
KIDNEY and Kidney counts were originally collated due to normalization of the BodyPartExamined values on the front end. Later the formatting of BodyPartExamined was reversed, but the count collating continued. This causes a filtering issue due to case sensitivity in Solr and BigQuery. 

Simple fix, this block of code needs to be removed:

https://github.com/ImagingDataCommons/IDC-Common/blob/7cbc886e4b04a4525ce9c68b18e3e1bc98cb2538/idc_collections/collex_metadata_utils.py#L524

**Comment by pgundluru** [comment]
I was able to test this issue by selecting KIDNEY and kidney filters in body part examined and verifying the case count on each and combined. 
![image](https://user-images.githubusercontent.com/85526819/167874818-41ff2329-eab1-4d99-acdb-616df83c9c17.png)
