### ISSUE TITLE
Use SM in place of Pathology on the portal Collections page

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#948]
We do point to the TCIA collections page for CPTAC and TCGA pathology, but the data we are hosting is all in DICOM and are of SM modality. As suggested by @hackermd, we should use SM.

**Comment by bcli4d** [comment]
What should the ImageType column include for those collections, e.g.PROSTATE-MRI, where we do not have pathology data ? Should we continue to include "Pathology"? "SM" (even though we've not converted to WSI)? And/Or some note that we do not yet have pathology data from the collection?

**Comment by bcli4d** [comment]
@Suzanne, Ok to make this change for V9?
@fedorov , Please respond to above questions. Thanks.

**Comment by fedorov** [comment]
> We could populate the ImageType column in original_collections_metadata from the Modality column in dicom_metadata.

I think this is the most logical approach. I suggest we proceed this way.

**Comment by bcli4d** [comment]
I've regenerated original_collections_metadata (idc-dev-etl and idc-pdp-staging). ImageTypes values are taken from dicom_metadata..

**Comment by s-paquette** [comment]
This should now be displaying in dev.

**Comment by pgundluru** [comment]
Image types are now shown as SM on prod tier
