### ISSUE TITLE
Pagination in collections 

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#95]
"Show *" drop-down appears to control the height of the widget with the table, not how many entries that table will contain. Hopefully the screen capture below helps illustrate this.

![May-20-2020 15-49-49](https://user-images.githubusercontent.com/313942/82490767-b97bab00-9ab1-11ea-88d0-32553977de4e.gif)

**Comment by fedorov** [comment]
I see that all tables behave this way, and I find this very un-intuitive. I think the purpose of pagination is to restrict how many items are shown at the time. I think the way table pagination is implemented in the TCIA search portal is how it is implemented in other places, and is more intuitive.

![image](https://user-images.githubusercontent.com/313942/82491108-34dd5c80-9ab2-11ea-950a-37304228ac52.png)

**Comment by G-White-ISB** [comment]
It was by current design that the table contains all entries, not just one page of content, but only a 'page worth' is shown at a time. One can scroll through all entries, not just through one page. One can view the bottom half of one page and the top half of the preceding at the same time. Suppose the first series for a given case occurs in row #49 in the series table, and the rest are are in rows #50-52. With set page sizes of 10, 25, 50 etc. and 'traditional' pagination one could not view all these rows at the same time without changing the table content.

**Comment by fedorov** [comment]
@G-White-ISB can you show me any other example in an existing application where pagination is handled the same way? I can't think of any. 

I do not understand the justification for this design decision.

**Comment by G-White-ISB** [comment]
So these tables use a hybrid of the infinite scroll/pagination patterns. I
have not found other tables that behave quite this way although the 'Load
More' pattern used by FaceBook is also something of a  hybrid approach
(with 'load more' replacing 'next page')
https://www.smashingmagazine.com/2016/03/pagination-infinite-scrolling-load-more-buttons/.
I see a couple of advantages of this approach over traditional pagination:

1. This pattern avoids cumbersome data splitting. For instance in the Study
Table one could have multiple series split between adjacent pages.

2. I personally prefer scrolling through tables than loading new pages, and
usability studies suggest most people feel the same way (see article
above). Obviously for very large tables (>10 thousand) pagination becomes
convenient.

Anyhow it would not be much effort to revert to traditional pagination.

George

**Comment by fedorov** [comment]
Related feedback from @rkikinis below. Again, the user is confused by the slider, and in this specific case pagination is exactly intended to get rid of slider.

![image](https://user-images.githubusercontent.com/313942/86484972-7b66dd80-bd25-11ea-9178-542572974769.png)

**Comment by G-White-ISB** [comment]
The scroll bar is removed in the current Pull Request

**Comment by fedorov** [comment]
Great! I just noticed that idc-testing still had that issue with the table resizing during scrolling (see below). I am assuming this issue will also go away, right?

![2020-07-08_13-23-45](https://user-images.githubusercontent.com/313942/86950616-5bb52800-c11e-11ea-9e1b-0ce43a68d32b.gif)

**Comment by G-White-ISB** [comment]
The table can resize on page change because table rows may be1 OR 2 lines
long and the table is sized to show a set number of rows.
George

**Comment by fedorov** [comment]
@G-White-ISB I did not see any table row that has more than one line in the example above, but I think it does not matter anymore, now that we do not have scrolling in pagination, so I am closing this.
