### ISSUE TITLE
In test tier, When a user selects adrenal gland case from home page, filter definition is not populated with the body part case 

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#962]
This issue was noticed in the previous release and fixed but seems to have cropped up again. The filter definition is not obtaining the cases selected from the home page and instead shows all the available cases 

Related ticket - https://github.com/ImagingDataCommons/IDC-WebApp/issues/930 

Body parts in home page that are currently doing this: Adrenal gland

**Comment by s-paquette** [comment]
Closing this as a duplicate.
