### ISSUE TITLE
For the mixed access collections, consider using "+/-" icon, or partially grayed out icon, or something similar to indicate it contains not just limited access content

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#968]
Suggested by Andrey on 5-16-2022 for future enhancements:
For the mixed access collections, we should consider using "+/-" icon, or partially grayed out icon, or something similar to indicate it contains not just limited access content.

**Comment by G-White-ISB** [comment]
Not currently relevant as we do not display any limited access content in the portal

**Comment by DavidPotCanuck** [comment]
@G-White-ISB is this really meaning licensing (freely available, versus limited available)?
