### ISSUE TITLE
Need to check if response key is present

### ISSUE THREAD

**Issue by wlongabaugh** [ImagingDataCommons/IDC-WebApp#972]
Could we fix this line to check for 'response'? Logs fill up with piles of stack traces:
```
File "/app/IDC-Common/solr_helpers/__init__.py", line 49, in query_solr_and_format_result
    formatted_query_result['numFound'] = result['response']['numFound']
KeyError: 'response'
```
code: https://github.com/ImagingDataCommons/IDC-Common/blob/a1e118579ca469014ba357d94bae96a1063d9cd4/solr_helpers/__init__.py#L49

**Comment by s-paquette** [comment]
@wlongabaugh Can I close this one? This is as previously discussed the result of an error further up the chain being mishandled.
