### ISSUE TITLE
Filter the study table of the explorer UI by the cohort filters

### ISSUE THREAD

**Issue by s-paquette** [ImagingDataCommons/IDC-WebApp#975]
From #973 

Currently the right-hand table set isn't filtered except as cases/studies are checked. We will now apply the search filter to the study table's results.

**Comment by G-White-ISB** [comment]
Ok so it was an easy fix to  apply the filter to all the tables (Case, Study, Series) etc. Studies and Series that do not apply to the filter and are not part of the cohort are no longer displayed in the table. However, do we not want to similarly update the facet counts as displayed alongside the attributes and in the pie charts?

Example: the filter BODYPARTEXAMINED in (ABD PEL) and MODALITY in (SEGMENTATION) matches 4 cases with 4 studies and 4 series with Segmentation Modality. However the studies have 5 addition CT series. Now the pie chart for Manufacturer Model Name has 3 slices. The slice 'NA" is due to the segmentation series in the cohort. The 2 other slices are due to the CT series that are in the matching studies but are not actually part of the cohort.

**Comment by s-paquette** [comment]
@G-White-ISB @fedorov @wlongabaugh Ah ha, this is why we didn't do the filtering of those tables.

> but are not actually part of the cohort.

This is incorrect. They _are_ part of the cohort, because filtering the case/study/series tables does *not* effect the 'study level' nature of a cohort. So, if you apply the filters to the Case/Study/Series tables, they will cease to match the pie charts, because the pie charts use 'study level' counts, i.e. once a given study is identified based on a filter, *all* instances from that study are involved in the faceted counts. 

This is IIRC why we left it the way it is now on production--we need to handle specifying cohort granularity first, _then_ we can approach these other items. Otherwise, we wind up with a confusing situation where the facet counts show one thing and the tables another.

**Comment by s-paquette** [comment]
@G-White-ISB Note, I think this is why this ticket indicates to only filter the study (and arguably case though that will follow from study) tables, and doesn't mention series--until we can go to series granularity in cohort definitions and facet counts, filtering the table at the filter level will be confusing.

**Comment by G-White-ISB** [comment]
@s-paquette - thanks for the clarification

**Comment by pgundluru** [comment]
To test this issue on dev tier, https://dev-portal.canceridc.dev/explore/ I followed the below steps 

Example:

1. Select a collection and a filter eg body part abd pel and the study level should match the number of cohort filter number which is 9 - Pass 
2. Select a collection covid 19 and a filter eg body part abdomen and modality CT and the study level should match the number of cohort filter number (30 Cases, 30 Studies, and 174 Series in this cohort) - Pass (studies are 30)
3. Select a analysis DICOM breast all clinical and license is cc by  and the study level should match the number of cohort filter number (474 Cases, 1286 Studies, and 15046 Series in this cohort)  - Pass (studies are 1286)
4. Select a analysis DICOM breast all clinical and manufacture is confirma and the study level should match the number of cohort filter number (51 Cases, 54 Studies, and 721 Series in this cohort)  - Pass (studies are 54)
5. Select object class is comprehensive SR and the study level should match the number of cohort filter number (475 Cases, 1748 Studies, and 15508 Series in this cohort)  - Pass (studies are 1748)
6.

**Comment by pgundluru** [comment]
Tested this in test tier : 
    Select a collection and a filter eg body part abd pel and the study level should match the number of cohort filter number which is 9 - Pass
    Select a collection covid 19 and a filter eg body part abdomen and modality CT and the study level should match the number of cohort filter number (30 Cases, 30 Studies, and 174 Series in this cohort) - Pass (studies are 30)
    Select a analysis DICOM breast all clinical and license is cc by and the study level should match the number of cohort filter number (474 Cases, 1286 Studies, and 15046 Series in this cohort) - Pass (studies are 1286)
    Select a analysis DICOM breast all clinical and manufacture is confirma and the study level should match the number of cohort filter number (51 Cases, 54 Studies, and 721 Series in this cohort) - Pass (studies are 54)
    Select object class is comprehensive SR and the study level should match the number of cohort filter number (475 Cases, 1748 Studies, and 15508 Series in this cohort) - Pass (studies are 1748)
