### ISSUE TITLE
Change IDC warning text

### ISSUE THREAD

**Issue by s-paquette** [ImagingDataCommons/IDC-WebApp#978]
When logging in to IDC website you get the following splash screen that needs to be acknowledged:

"Warning
You are accessing a US Government web site which may contain information that must be protected under the US Privacy Act or other sensitive information and is intended for Government authorized use only.

Unauthorized attempts to upload information, change information, or use of this web site may result in disciplinary action, civil, and/or criminal penalties. Unauthorized users of this website should have no expectation of privacy regarding any communications or data processed by this website.

Anyone accessing this website expressly consents to monitoring of their actions and all communications or data transiting or stored on related to this website and is advised that if such monitoring reveals possible evidence of criminal activity, NIH may provide that evidence to law enforcement officials".

Please add a paragraph at the bottom that says:

"The IDC system is authorized to be used by the public to view and analyze cancer data based on the NCI Data Use Agreements specific to individual datasets."

This provides the "a description of the authorized uses of the system." that is required in NIST control AC-8.

**Comment by pgundluru** [comment]
This can be tested by clearing cache and browser history or going to a private tab to see the below warning message

![image](https://user-images.githubusercontent.com/85526819/180280004-49d04ee0-1533-46ef-b50a-f18d54078fbb.png)
