### ISSUE TITLE
"IDC Data Version" and "Access" columns should be present in File manifest

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#980]
like in BQ manifest

<img width="414" alt="image" src="https://user-images.githubusercontent.com/313942/171740407-d8105bef-d4ee-475b-b72a-4acb67d6a76b.png">

**Comment by fedorov** [comment]
Overall, I suggest the list of columns (unless not applicable) should be synchronized between File and BQ manifests. Can we just establish this as a rule, so that we don't need to create issues going forward asking to add items from one to another?

**Comment by s-paquette** [comment]
@fedorov I'm assuming we can drop access from this since it's not an issue at this time.

**Comment by fedorov** [comment]
yes

**Comment by pgundluru** [comment]
![image](https://user-images.githubusercontent.com/85526819/197005976-f395e7c4-fa42-4371-b305-145224699d27.png)

**Comment by pgundluru** [comment]
Closed as completed and tested on production.
