### ISSUE TITLE
Add SamplesPerPixel to Original Data attributes

### ISSUE THREAD

**Issue by s-paquette** [ImagingDataCommons/IDC-WebApp#984]
This would allow users to more easily filter for HTAN data (so is part of v10 data release, or after it).

This may be stored as a String in dicom_metadata; if so it will need to be added to the curation table. @bcli4d @fedorov Can you let me know if this needs to be done, and if so when it has been. (If not I can immediately move to add the field name to my various query builders for ETL.)

**Comment by fedorov** [comment]
`SamplesPerPixel` is INTEGER in `dicom_metadata`:

<img width="495" alt="image" src="https://user-images.githubusercontent.com/313942/172954316-0cdaf0f6-bb9f-44b2-8c51-8ea8261b76b9.png">

**Comment by s-paquette** [comment]
ETL queries are prepped to produce this column going forward, ETL script staged for v10.

**Comment by pgundluru** [comment]
SamplesPerPixel is available as a INT in dicom_all, dicom_metadata and dicom_pivot_v10

![image](https://user-images.githubusercontent.com/85526819/181554002-e34bb664-7713-48c8-a4e9-2586199f6f98.png)

**Comment by s-paquette** [comment]
Note this has been fixed in dicom_pivot_v10 and if Google doesn't pick it up in their publishing of the dataset we'll ask them to run it again.

**Comment by pgundluru** [comment]
Thank You Suzanne, I am able to view it now 
![image](https://user-images.githubusercontent.com/85526819/181786005-c9b7eea8-fa3e-451b-a990-16788d8d8e00.png)
