### ISSUE TITLE
Add link to public BQ dataset to main menu

### ISSUE THREAD

**Issue by s-paquette** [ImagingDataCommons/IDC-WebApp#985]
Add a link directly to the BQ public dataset in the cloud console to the main menu bar of the site.

**Comment by pgundluru** [comment]
In test tier there is a link to BQ that takes you to the Bigquery of Google console 

![image](https://user-images.githubusercontent.com/85526819/180253374-6e5c2d1f-d86f-4854-bb6a-dbbade468c98.png)

**Comment by pgundluru** [comment]
@s-paquette Currently the link brings me to Google console and puts me into my recent used project like image below. What is the best way to check if its taking me to public BQ dataset?

![image](https://user-images.githubusercontent.com/85526819/180253774-89fdd58a-beca-47a7-a2d7-35278327abc7.png)

**Comment by s-paquette** [comment]
So on the left there if you were to collapse `idc-dev-etl` (by clicking on the >) it should then show you `bigquery-public-data`. The interface will AFAIK always respect your latest layout, and we can't really override that to my knowledge.
