### ISSUE TITLE
In UAT tier, when you select SM on home page you are taken to a 404 error page

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#988]
This was noticed while running a test for UAT tier on 06-23-2022 and seems to be isolated to UAT 

Error in console :
require.js:141 Uncaught Error: Mismatched anonymous define() module: function($, utils) {

    // Resets forms in modals on hide. Suppressed warning when leaving page with dirty forms
    $('.modal').on('hide.bs.modal', function () {
        if(!$(this).prop("saving")) {
            if($(this).find('form').get().length) {
                $(this).find('form').get(0).reset();
            }
        }
    });

    $.getCookie = utils.getCookie;
    $.setCookie = utils.setCookie;
    $.removeCookie = utils.removeCookie;

    return {
        blacklist: /<script>|<\/script>|!\[\]|!!\[\]|\[\]\[\".*\"\]|<iframe>|<\/iframe>/ig,
        // From http://www.regular-expressions.info/email.html
        email: /^[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$/,
        showJsMessage: utils.showJsMessage,
        // Simple method for standardizing storage of a message into sessionStorage so it can be retrieved and reloaded
        // at document load time
        setReloadMsg: function(type,text) {
            sessionStorage.setItem("reloadMsg",JSON.stringify({type: type, text: text}));
        },
        setCookie: function(name,val,expires_in,path) {
            utils.setCookie(name,val,expires_in,path);
        },
        removeCookie: function(name, path) {
            utils.removeCookie(name, path);
        },
        blockResubmit: utils.blockResubmit
    };
}
http://requirejs.org/docs/errors.html#mismatch
    at makeError (require.js:166:17)
    at intakeDefines (require.js:1236:36)
    at require.js:1423:25
1.3.6.1.4.1.5962.99.1.208792987.352384958.1640886332827.2.0:1          Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by s-paquette** [comment]
Ah ha! A settings error. I'll need to redeploy to fix it, but a pretty easy fix.
