### ISSUE TITLE
IN UAT tier, there is an internal server error while saving a new cohort. 

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#989]
This issue was noticed on UAT tier on 6-23-2022 

Summary : When a user selects any filters and tries to save a cohort there is an internal server error message

![image](https://user-images.githubusercontent.com/85526819/175363813-7cf41fe8-72f0-46bd-bc43-9218644fa5fc.png)

**Comment by s-paquette** [comment]
@pgundluru okay, this should be ready to test again.
