### ISSUE TITLE
Replace Image examples tab with carousel

### ISSUE THREAD

**Issue by s-paquette** [ImagingDataCommons/IDC-WebApp#998]
This is to facilitate the easier addition of new examples like the upcoming HTAN addition.

**Comment by s-paquette** [comment]
@fedorov Current re-do is now on dev if you want to let me know if you'd like any changes to layout, color, behavior, etc.

**Comment by fedorov** [comment]
This is excellent! Testing passed! ;-)

**Comment by fedorov** [comment]
Maybe just a small nitpick - if it is trivial, maybe consider putting play/pause button to the left of the text under the fugure?

**Comment by s-paquette** [comment]
@fedorov The only issue with that is the text and the image are all one slide, we would need to let the text run 2-3 lines to make space for the button. Would that be alright? (It'll require an absolute positioning as well, which might not play well with smaller screens.)

**Comment by fedorov** [comment]
Let's keep as is, no need to add any headaches. Thank you!

**Comment by fedorov** [comment]
Can revisit later based on feedback from others.

**Comment by pgundluru** [comment]
In Test tier, Images tab is now a carousel with default being play and if a user would like to pause the play/pause button is above the images 

![image](https://user-images.githubusercontent.com/85526819/180245017-012a9a11-7395-4350-89f9-76336c0a5a3c.png)

**Comment by s-paquette** [comment]
@pgundluru Ooof, that layout looks ugly though! Can you tell me what your display size was to get that to happen?

**Comment by pgundluru** [comment]
@s-paquette  This was tested in Firefox browser with zoom 100% (Display size full screen)

**Comment by s-paquette** [comment]
@pgundluru Hm, it doesn't look like that for me. Can I get an OS and FF version?

**Comment by pgundluru** [comment]
@s-paquette Yes, Microsoft windows 10 enterprise and Firefox version - 102.0.1 (64-bit)

**Comment by pgundluru** [comment]
Here is a image of the entire page 

![image](https://user-images.githubusercontent.com/85526819/180279200-391028bd-1901-443b-8f92-a7899cd77089.png)

**Comment by s-paquette** [comment]
@pgundluru oh, well now it looks fine. maybe a CSS loading error? Let me know if it looks all a mess like that again.
