### ISSUE TITLE
Add HTAN thumbnail to the front page

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#999]
The image and the link are here: https://docs.google.com/document/d/1dy6y_52RII4Y3LTxH_6NyvFTC-EvAgsBNdNS5r9nDaI/edit#heading=h.v5lfpbdpnmf7

**Comment by pgundluru** [comment]
HTAN SM Fluorescence image is added to test tier, When i click on the image I am taken to https://testing-viewer.canceridc.dev/slim/studies/2.25.93749216439228361118017742627453453196/series/1.3.6.1.4.1.5962.99.1.2344794501.795090168.1655907236229.4.0?state=1.2.826.0.1.3680043.10.511.3.79630386778396943986328353882008803 

![image](https://user-images.githubusercontent.com/85526819/180244067-1fb6fb50-8d56-424a-8e2a-e1986e0aa308.png)
